### ISSUE TITLE
[10.0] [hr_timesheet] migration error when project_issue not installed

### ISSUE THREAD

**Issue by remi-filament** [OCA/OpenUpgrade#1000]
Impacted versions:
10.0

Steps to reproduce:
Run openupgrade on a database in V9 with hr_timesheet installed but with no project_issue module

Current behavior:
The migration script fails with an error stating that table project_issue module does not exist

Expected behavior:
Run the steps to update account_analytic_line by using project_issue entries only if module project_issue is installed

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You're still not putting the error stack trace

**Comment by remi-filament** [comment]
Please find it below:
```
2017-08-02 13:39:42,069 9367 INFO fil-upgrade odoo.sql_db: bad query:
        UPDATE account_analytic_line aal
        SET project_id = pi.project_id
        FROM project_issue pi
        WHERE pi.id = aal.issue_id
        AND pi.project_id IS NOT NULL
        AND aal.project_id IS NULL

2017-08-02 13:39:42,069 9367 ERROR fil-upgrade OpenUpgrade: hr_timesheet: error in migration script /opt/OpenUpgrade/addons/hr_timesheet/migrations/10.0.1.0/post-migration.py: relation "project_issue" does not exist
LINE 4:         FROM project_issue pi
                     ^

2017-08-02 13:39:42,070 9367 ERROR fil-upgrade OpenUpgrade: relation "project_issue" does not exist
LINE 4:         FROM project_issue pi
                     ^
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1194, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/OpenUpgrade/addons/hr_timesheet/migrations/10.0.1.0/post-migration.py", line 75, in migrate
    fill_analytic_line_project(env)
  File "/opt/OpenUpgrade/addons/hr_timesheet/migrations/10.0.1.0/post-migration.py", line 67, in fill_analytic_line_project
    """,
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 700, in logged_query
    cr.execute(query, args)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "project_issue" does not exist
LINE 4:         FROM project_issue pi
                     ^

2017-08-02 13:39:42,071 9367 ERROR fil-upgrade odoo.modules.loading: Error executing post migration script for module hr_timesheet
`-> lefilament_projets
`-> sale_timesheet
: relation "project_issue" does not exist
LINE 4:         FROM project_issue pi
                     ^

2017-08-02 13:39:42,076 9367 ERROR fil-upgrade odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/OpenUpgrade/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 191, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/OpenUpgrade/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1194, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/OpenUpgrade/addons/hr_timesheet/migrations/10.0.1.0/post-migration.py", line 75, in migrate
    fill_analytic_line_project(env)
  File "/opt/OpenUpgrade/addons/hr_timesheet/migrations/10.0.1.0/post-migration.py", line 67, in fill_analytic_line_project
    """,
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 700, in logged_query
    cr.execute(query, args)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "project_issue" does not exist
LINE 4:         FROM project_issue pi
                     ^

2017-08-02 13:39:42,077 9367 CRITICAL fil-upgrade odoo.service.server: Failed to initialize database `fil-upgrade`.
Traceback (most recent call last):
  File "/opt/OpenUpgrade/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/OpenUpgrade/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 191, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/OpenUpgrade/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1194, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/OpenUpgrade/addons/hr_timesheet/migrations/10.0.1.0/post-migration.py", line 75, in migrate
    fill_analytic_line_project(env)
  File "/opt/OpenUpgrade/addons/hr_timesheet/migrations/10.0.1.0/post-migration.py", line 67, in fill_analytic_line_project
    """,
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 700, in logged_query
    cr.execute(query, args)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "project_issue" does not exist
LINE 4:         FROM project_issue pi
                     ^

2017-08-02 13:39:42,078 9367 INFO fil-upgrade odoo.service.server: Initiating shutdown
```

**Comment by remi-filament** [comment]
Thanks
