### ISSUE TITLE
deadlock detected error

### ISSUE THREAD

**Issue by lambone** [OCA/OpenUpgrade#1006]
Impacted versions:
9.0

Steps to reproduce:
/git/wsc/OpenUpgrade-9.0/openerp-server -c /etc/odoo-server-mig.conf -d cbl3 --stop-after-init --update all

Current behavior:

2017-08-09 06:27:28,155 4400 INFO cbl3 openerp.modules.module: module account: creating or updating database tables
2017-08-09 06:27:48,025 4400 WARNING cbl3 openerp.models.schema: Table 'account_move_line': unable to set a NOT NULL constraint on column 'date_maturity' !
If you want to have it, you should update the records and execute manually:
ALTER TABLE account_move_line ALTER COLUMN date_maturity SET NOT NULL
2017-08-09 06:28:32,202 4400 WARNING cbl3 openerp.models.schema: Table 'account_chart_template': unable to set a NOT NULL constraint on column 'currency_id' !
If you want to have it, you should update the records and execute manually:
ALTER TABLE account_chart_template ALTER COLUMN currency_id SET NOT NULL
2017-08-09 06:28:32,210 4400 INFO cbl3 openerp.sql_db: bad query: ALTER TABLE "account_chart_template" ALTER COLUMN "transfer_account_id" SET NOT NULL
2017-08-09 06:28:32,211 4400 WARNING cbl3 openerp.models: WARNING: unable to set column transfer_account_id of table account_chart_template not null !
Try to re-run: openerp-server --update=module
If it doesn't work, update records and execute manually:
ALTER TABLE account_chart_template ALTER COLUMN transfer_account_id SET NOT NULL
Traceback (most recent call last):
  File "/git/wsc/OpenUpgrade-9.0/openerp/models.py", line 2713, in _auto_init
    cr.execute('ALTER TABLE "%s" ALTER COLUMN "%s" SET NOT NULL' % (self._table, k))
  File "/git/wsc/OpenUpgrade-9.0/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/git/wsc/OpenUpgrade-9.0/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "transfer_account_id" contains null values

2017-08-09 06:28:34,004 4400 INFO cbl3 openerp.sql_db: bad query: ALTER TABLE "account_account_tag" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users" ON DELETE set null
2017-08-09 06:28:34,027 4400 ERROR cbl3 openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/loading.py", line 408, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/loading.py", line 160, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/module.py", line 307, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/git/wsc/OpenUpgrade-9.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/git/wsc/OpenUpgrade-9.0/openerp/models.py", line 2761, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/git/wsc/OpenUpgrade-9.0/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/git/wsc/OpenUpgrade-9.0/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: deadlock detected
DETAIL:  Process 4407 waits for AccessExclusiveLock on relation 933224 of database 969060; blocked by process 4392.
Process 4392 waits for AccessShareLock on relation 931130 of database 969060; blocked by process 4407.
HINT:  See server log for query details.

2017-08-09 06:28:34,040 4400 CRITICAL cbl3 openerp.service.server: Failed to initialize database `cbl3`.
Traceback (most recent call last):
  File "/git/wsc/OpenUpgrade-9.0/openerp/service/server.py", line 897, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/loading.py", line 408, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/loading.py", line 160, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/git/wsc/OpenUpgrade-9.0/openerp/modules/module.py", line 307, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/git/wsc/OpenUpgrade-9.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/git/wsc/OpenUpgrade-9.0/openerp/models.py", line 2761, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/git/wsc/OpenUpgrade-9.0/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/git/wsc/OpenUpgrade-9.0/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: deadlock detected
DETAIL:  Process 4407 waits for AccessExclusiveLock on relation 933224 of database 969060; blocked by process 4392.
Process 4392 waits for AccessShareLock on relation 931130 of database 969060; blocked by process 4407.
HINT:  See server log for query details.

2017-08-09 06:28:34,048 4400 INFO cbl3 openerp.service.server: Initiating shutdown
2017-08-09 06:28:34,049 4400 INFO cbl3 openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

Expected behavior:
No error

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because you are updating in a live server or with multiple workers. Don't do that.
