### ISSUE TITLE
[10.0]IM ODOO chat issue, no more present in v10 => delete ?

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#1023]
Hi,

I successfully update all my modules form 8 => 10.0 and guys, your project is  awesome.

yet once trying to log, I have this issue : 
```
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: unbound method get_param() must be called with ir.config_parameter instance as first argument (got Cursor instance instead)
Traceback (most recent call last):
  File "/home/florent/DEV/_EclipseOdoo/MagOdoo10/OCB/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_web_assets_backend_577
TypeError: unbound method get_param() must be called with ir.config_parameter instance as first argument (got Cursor instance instead)

Error to render compiling AST
TypeError: unbound method get_param() must be called with ir.config_parameter instance as first argument (got Cursor instance instead)
Template: web.assets_backend
Path: /templates/t/script[98]/t[2]
Node: <t t-esc="request.registry['ir.config_parameter'].get_param(request.cr, request.uid, 'database.uuid')"/>"
                        );
                    });
2017-08-14 22:57:16,655 20735 INFO mag_prod_migrated werkzeug: 127.0.0.1 - - [14/Aug/2017 22:57:16] "[1m[35mGET /web HTTP/1.1[0m" 500 -
2017-08-14 22:57:16,664 20735 ERROR mag_prod_migrated werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 210, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 198, in execute
    application_iter = app(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/service/server.py", line 249, in app
    return self.app(e, s)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/http.py", line 1308, in __call__
    return self.dispatch(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/http.py", line 1282, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/http.py", line 1481, in dispatch
    result = ir_http._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/OCB/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/OCB/addons/website/models/ir_http.py", line 218, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/OCB/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/OCB/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/home/florent/DEV/Serveurs/odoo/OCB/addons/website/models/ir_http.py", line 270, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/http.py", line 329, in checked_call
    result.flatten()
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/http.py", line 1259, in flatten
    self.response.append(self.render())
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/http.py", line 1252, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_ui_view.py", line 1039, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/florent/DEV/Serveurs/odoo/OCB/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/home/florent/DEV/Serveurs/odoo/OCB/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_ui_view.py", line 1059, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/florent/DEV/Serveurs/odoo/OCB/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: unbound method get_param() must be called with ir.config_parameter instance as first argument (got Cursor instance instead)
```
Any advice would be appreciated, 

regards

**Comment by flotho** [comment]
Already referenced issue : https://www.odoo.com/forum/help-1/question/help-doing-a-migration-9-10-122066

**Comment by flotho** [comment]
Maybe there's a way to implement a control in the migration script

**Comment by pedrobaeza** [comment]
The module is already merged in its corresponding module that takes its features, so no need to make anything more:

https://github.com/OCA/OpenUpgrade/blob/d27a3adf25f097e3f9a7b3edb9d71f434b283d92/odoo/addons/base/migrations/10.0.1.3/pre-migration.py#L56-L73
