### ISSUE TITLE
ReG:Odoo save error 

### ISSUE THREAD

**Issue by ShrikrishnaPatil** [OCA/OpenUpgrade#1126]
Odoo Server Error
Traceback (most recent call last):
File "/opt/odoo/openerp/http.py", line 650, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/openerp/http.py", line 687, in dispatch
result = self._call_function(**self.params)
File "/opt/odoo/openerp/http.py", line 323, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/odoo/openerp/http.py", line 316, in checked_call
result = self.endpoint(*a, **kw)
File "/opt/odoo/openerp/http.py", line 966, in call
return self.method(*args, **kw)
File "/opt/odoo/openerp/http.py", line 516, in response_wrap
response = f(*args, **kw)
File "/opt/odoo/addons/web/controllers/main.py", line 895, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/opt/odoo/addons/web/controllers/main.py", line 887, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 354, in old_api
result = method(recs, *args, **kwargs)
File "/opt/odoo/addons/account/models/account_invoice.py", line 361, in create
invoice = super(AccountInvoice, self.with_context(mail_create_nolog=True)).create(vals)
File "/opt/odoo/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 490, in new_api
result = method(self._model, cr, uid, *args, **old_kwargs)
File "/opt/odoo/addons/product/product.py", line 1184, in create
product_id = super(product_product, self).create(cr, uid, vals, context=ctx)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 354, in old_api
result = method(recs, *args, **kwargs)
File "/opt/odoo/addons/mail/models/mail_thread.py", line 235, in create
thread = super(MailThread, self).create(values)
File "/opt/odoo/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/odoo/openerp/models.py", line 4174, in create
record = self.browse(self._create(old_vals))
File "/opt/odoo/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 490, in new_api
result = method(self._model, cr, uid, *args, **old_kwargs)
File "/opt/odoo/openerp/models.py", line 4236, in _create
record_id = self.pool[table].create(cr, user, tocreate[table], context=context)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/addons/stock_account/product.py", line 76, in create
return super(product_template, self).create(cr, uid, vals, context=context)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/addons/product/product.py", line 675, in create
product_template_id = super(product_template, self).create(cr, uid, vals, context=context)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 354, in old_api
result = method(recs, *args, **kwargs)
File "/opt/odoo/addons/mail/models/mail_thread.py", line 235, in create
thread = super(MailThread, self).create(values)
File "/opt/odoo/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/odoo/openerp/models.py", line 4174, in create
record = self.browse(self._create(old_vals))
File "/opt/odoo/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 490, in new_api
result = method(self._model, cr, uid, *args, **old_kwargs)
File "/opt/odoo/openerp/models.py", line 4300, in _create
self._check_selection_field_value(cr, user, field, vals[field], context=context)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 354, in old_api
result = method(recs, *args, **kwargs)
File "/opt/odoo/openerp/models.py", line 2254, in _check_selection_field_value
field.convert_to_cache(value, self)
File "/opt/odoo/openerp/fields.py", line 1545, in convert_to_cache
raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for product.template.type: u'out_invoice'

Helpme

**Comment by pedrobaeza** [comment]
Sorry, but this is not related with OpenUpgrade.
