### ISSUE TITLE
[10.0] crm: post-migration script called with version 9.0.1.0

### ISSUE THREAD

**Issue by martintorresvm** [OCA/OpenUpgrade#1133]
Impacted versions:
9.0, 10.0

Steps to reproduce:
Run manual migration from DB with version 9.0 to 10.0 with OpenUpgrade.

Current behavior:
2017-10-19 07:57:07,501 18 INFO  v10 odoo.modules.migration: module crm: Running migration [10.0.1.0>] post-migration
2017-10-19 07:57:07,502 18 INFO  v10 odoo.modules.migration: module crm: Running migration [10.0.1.0>] post-migration
2017-10-19 07:57:07,503 18 INFO  v10 OpenUpgrade: crm: post-migration script called with version 9.0.1.0
2017-10-19 07:57:07,503 18 ERROR  v10 OpenUpgrade: crm: error in migration script /opt/odoo/sources/odoo/addons/crm/migrations/10.0.1.0/post-migration.py: 'crm.activity' object has no attribute '_columns'
2017-10-19 07:57:07,504 18 ERROR  v10 OpenUpgrade: 'crm.activity' object has no attribute '_columns'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.0-py2.7.egg/openupgradelib/openupgrade.py", line 1182, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/sources/odoo/addons/crm/migrations/10.0.1.0/post-migration.py", line 39, in migrate
    _convert_next_activities(env)
  File "/opt/odoo/sources/odoo/addons/crm/migrations/10.0.1.0/post-migration.py", line 17, in _convert_next_activities
    'recommended_activity_ids', openupgrade.get_legacy_name(column),
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.0-py2.7.egg/openupgradelib/openupgrade.py", line 807, in m2o_to_x2m
    if not model._columns.get(field):
AttributeError: 'crm.activity' object has no attribute '_columns'
2017-10-19 07:57:07,504 18 ERROR  v10 odoo.modules.loading: Error executing post migration script for module crm
`-> sale_crm
: 'crm.activity' object has no attribute '_columns'

Expected behavior:
Finish migration with no issue.

Video/Screenshot link (optional):

**Comment by martintorresvm** [comment]
@pedrobaeza @jbeficent  Could you verify this issue?

cc @elicoidal

**Comment by pedrobaeza** [comment]
Use latest GIT version of openupgradelib, not pip one.
