### ISSUE TITLE
Error in migration 8.0 to 10.0

### ISSUE THREAD

**Issue by esturao** [OCA/OpenUpgrade#1235]
Impacted versions:10.0

Steps to reproduce:
2017-12-15 20:31:16,099 18443 INFO odoo8_migrated OpenUpgrade: mail: post-migration script called with version 8.0.1.0
2017-12-15 20:31:16,100 18443 INFO odoo8_migrated odoo.sql_db: bad query: alter table mail_message_res_partner_needaction_rel add column id serial not null primary key
2017-12-15 20:31:16,101 18443 ERROR odoo8_migrated OpenUpgrade: mail: error in migration script mail/migrations/10.0.1.0/post-migration.py: ProgrammingError('ya existe la columna \xc2\xabid\xc2\xbb en la relaci\xc3\xb3n \xc2\xabmail_message_res_partner_needaction_rel\xc2\xbb\n',)
2017-12-15 20:31:16,101 18443 ERROR odoo8_migrated OpenUpgrade: ya existe la columna «id» en la relación «mail_message_res_partner_needaction_rel»
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1391, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/mail/migrations/10.0.1.0/post-migration.py", line 11, in migrate
    'alter table mail_message_res_partner_needaction_rel '
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ya existe la columna «id» en la relación «mail_message_res_partner_needaction_rel»

2017-12-15 20:31:16,113 18443 ERROR odoo8_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 191, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1391, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/mail/migrations/10.0.1.0/post-migration.py", line 11, in migrate
    'alter table mail_message_res_partner_needaction_rel '
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ya existe la columna «id» en la relación «mail_message_res_partner_needaction_rel»

2017-12-15 20:31:16,113 18443 CRITICAL odoo8_migrated odoo.service.server: Failed to initialize database `odoo8_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 191, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1391, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/mail/migrations/10.0.1.0/post-migration.py", line 11, in migrate
    'alter table mail_message_res_partner_needaction_rel '
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ya existe la columna «id» en la relación «mail_message_res_partner_needaction_rel»

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Are you trying to migrate directly from 8 to 10? You have to migrate previously to v9, and then to v10.
