### ISSUE TITLE
AttributeError:  'module' object has no attribute 'rename_fields'

### ISSUE THREAD

**Issue by psugne** [OCA/OpenUpgrade#1238]
I am trying to migrate fro v9 to v10.
run script: sudo python migrate.py --config=/opt/odoo-server-new.conf --database=odoo_new --run-migrations=10.0
script runs without errors but I checked my /var/tmp/openupgrade/migration.log and found some errors:

```
[2017-12-19 17:28:20,534 24770 ERROR odoo_new_migrated OpenUpgrade: stock: error in migration script /var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py: 'module' object has no attribute 'rename_fields'
2017-12-19 17:28:20,534 24770 ERROR odoo_new_migrated OpenUpgrade: 'module' object has no attribute 'rename_fields'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1200, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py", line 74, in migrate
    openupgrade.rename_fields(env, field_renames)
AttributeError: 'module' object has no attribute 'rename_fields'
2017-12-19 17:28:20,535 24770 ERROR odoo_new_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1200, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py", line 74, in migrate
    openupgrade.rename_fields(env, field_renames)
AttributeError: 'module' object has no attribute 'rename_fields'
2017-12-19 17:28:20,535 24770 CRITICAL odoo_new_migrated odoo.service.server: Failed to initialize database `odoo_new_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1200, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py", line 74, in migrate
    openupgrade.rename_fields(env, field_renames)
AttributeError: 'module' object has no attribute 'rename_fields']
```
And

```
2017-12-19 17:27:38,538 24770 DEBUG odoo_new_migrated odoo.tools.convert: Context value ({                             'default_composition_mode': 'mass_mail',                             'default_partner_to': '${object.id or \'\'}',                             'default_active_domain': [['id', 'in', context.get('active_ids', [])]],                         }) for element with id "action_partner_mass_mail" or its data node does not parse at server-side, keeping original string, in case it's meant for client side only
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/tools/convert.py", line 223, in get_context
    ctx_res = safe_eval(ctx, eval_dict)
  File "/var/tmp/openupgrade/10.0/server/odoo/tools/convert.py", line 30, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/var/tmp/openupgrade/10.0/server/odoo/tools/safe_eval.py", line 301, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ValueError: <type 'exceptions.NameError'>: "name 'context' is not defined" while evaluating
"{                             'default_composition_mode': 'mass_mail',                             'default_partner_to': '${object.id or \\'\\'}',                             'default_active_domain': [['id', 'in', context.get('active_ids', [])]],                         }"

```

**Comment by pedrobaeza** [comment]
You have to use directly latest sources. You can install it with:
```bash
pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
```
