### ISSUE TITLE
Problem with table account_statement_operation_template in migration 9.0

### ISSUE THREAD

**Issue by hmartinet** [OCA/OpenUpgrade#1240]
Impact migration 8.0 to 9.0, module account.

This migration try to rename table account_statement_operation_template into account_operation_template. I have an INFO in log and no other logs about this table. There is no ERROR in the migration process.

In the result database the table account_statement_operation_template already exists but not the table account_operation_template. Then the next migration to 10.0 will failed because account_operation_template does not exists. I don't understand why this table can be not renamed without error in logs. I try this migration 3 times with the same result. Someone has an idea in which direction I have to investigate ?

```2017-12-20 13:48:34,611 53675 INFO odoo_8_migrated OpenUpgrade: table account_statement_operation_template: renaming to account_operation_template```

**Comment by pedrobaeza** [comment]
Sorry, no idea. I haven't got any problem with that.

**Comment by hmartinet** [comment]
I will try to rename it manually and then running migration 9.0 to 10.0. If an update process specialist has an idea how a query can not be applied without an ERROR in log.

**Comment by StefanRijnhart** [comment]
What is the error from the 10.0 migration?

**Comment by hmartinet** [comment]
The error (table account_operation_template does not exists) appears in 10.0 migration. But the cause is that the table rename in 9.0 migration was not effective (but correctly logged). The the table name is always account_statement_operation_template after the 9.0 migration (like in 8.0).

**Comment by StefanRijnhart** [comment]
The reason I asked is that I don't understand the problem, so I was hoping that a log snipped of a failed migration (or the whole set of logs maybe) could provide more insight. I am currently finishing a migration from 7.0 to 10.0 and I do not have this problem but then again I have no entries in either table which might make a difference.

BTW if the problem is that table account_statement_operation_template remains unchanged after the rename_tables operation it should actually go unnoticed because an upgrade of account 9.0 should create the new table anyway.

**Comment by hmartinet** [comment]
Ok. I have this problem only with one customer database, another customer was in same version of Odoo 7.0 with same version of custom addons and the database was successfully migrated. Then I think the problem is in the database but I have no idea where to investigate.

The error logged in 10.0 migration is:
```
2017-12-20 10:07:28,400 30257 ERROR odoo_9_migrated OpenUpgrade: relation "account_operation_template" does not exist
Traceback (most recent call last):
  File "[...]/workdir/openupgradelib/openupgradelib/openupgrade.py", line 1391, in wrapped_function
    if use_env2 else cr, version)
  File "[...]/workdir/10.0/addons/account/migrations/10.0.1.1/pre-migration.py", line 16, in migrate
    ('account_operation_template', 'account_reconcile_model'),
  File "[...]/workdir/openupgradelib/openupgradelib/openupgrade.py", line 517, in rename_tables
    cr.execute('ALTER TABLE "%s" RENAME TO "%s"' % (old, new,))
  File "[...]/workdir/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "[...]/workdir/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "account_operation_template" does not exist

2017-12-20 10:07:28,401 30257 ERROR odoo_9_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "[...]/workdir/10.0/server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "[...]/workdir/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "[...]/workdir/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "[...]/workdir/10.0/server/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "[...]/workdir/10.0/server/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "[...]/workdir/openupgradelib/openupgradelib/openupgrade.py", line 1391, in wrapped_function
    if use_env2 else cr, version)
  File "[...]/workdir/10.0/addons/account/migrations/10.0.1.1/pre-migration.py", line 16, in migrate
    ('account_operation_template', 'account_reconcile_model'),
  File "[...]/workdir/openupgradelib/openupgradelib/openupgrade.py", line 517, in rename_tables
    cr.execute('ALTER TABLE "%s" RENAME TO "%s"' % (old, new,))
  File "[...]/workdir/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "[...]/workdir/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "account_operation_template" does not exist

2017-12-20 10:07:28,402 30257 CRITICAL odoo_9_migrated odoo.service.server: Failed to initialize database `odoo_9_migrated`.
Traceback (most recent call last):
  File "[...]/workdir/10.0/server/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "[...]/workdir/10.0/server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "[...]/workdir/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "[...]/workdir/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "[...]/workdir/10.0/server/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "[...]/workdir/10.0/server/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "[...]/workdir/openupgradelib/openupgradelib/openupgrade.py", line 1391, in wrapped_function
    if use_env2 else cr, version)
  File "[...]/workdir/10.0/addons/account/migrations/10.0.1.1/pre-migration.py", line 16, in migrate
    ('account_operation_template', 'account_reconcile_model'),
  File "[...]/workdir/openupgradelib/openupgradelib/openupgrade.py", line 517, in rename_tables
    cr.execute('ALTER TABLE "%s" RENAME TO "%s"' % (old, new,))
  File "[...]/workdir/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "[...]/workdir/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "account_operation_template" does not exist
```

**Comment by hmartinet** [comment]
I try to apply the 10.0 migration with manually rename the concerned table after 9.0 migration.

No error at this time but the current operation has been running for 17 hours and is not finished. But there is 273995 account.move, possibly a long process.

```
2017-12-20 17:24:22,838 58849 INFO openerp_9_migrated odoo.models: Storing computed values of account.move fields amount, currency_id, matched_percentage
```

**Comment by StefanRijnhart** [comment]
About performance: you will find regularly that migration scripts are not optimized for large record sets simply because there are no test sets for that. When storing computed values is a bottleneck, the solution is often to precreate the columns and fill them in the pre-script in a more efficient way than Odoo does (if you can figure out such a way).

**Comment by StefanRijnhart** [comment]
I'm thinking that the upgrade of the account module was somehow rolled back on the database level, because the missing table implies that the regular database provisioning by the Odoo ORM has not taken place either for the account.operation.template model. We do use savepoints and rollbacks in Openupgrade, so there may be a bug in that. Can you make all of the 9.0 migration logs available on some pastebin or mail them to me privately?

**Comment by hmartinet** [comment]
@StefanRijnhart Thanks for your explanations.

### Performances
Seems to be legit. It's easy to read the functional field algorithm and write a query to update columns in SQL if it's need for some larges datasets. Is it a dedicated way to share such scripts or everybody do it for his own use ?
### Bug table rename
Ok. I will send you the complete log tomorrow (I have no access to the VM on which I test migrations at this time). If I can I will try to understand the OpenUpgrade code about that to try to search the cause (over time it would be more effective if I have a better knowledge of the system).

I will be on holiday for 2 weeks after tomorrow then I will not try to install a test instance on Odoo 10 for this customer in 2017, I will see that in January.

**Comment by StefanRijnhart** [comment]
We would greatly appreciate performance improvements on any script as a PR here!

**Comment by hmartinet** [comment]
Sorry I forgot that before my holidays...

Then I have another error in migration 9.0 now.

```
2017-12-22 18:50:07,274 58849 ERROR my_database OpenUpgrade: account: error in migration script account/migrations/10.0.1.1/post-migration.py: ProgrammingError('column am.rate_diff_partial_rec_id does not exist\nLINE 11:             ON apr.id = am.rate_diff_partial_rec_id\n              
```

I will do the performance proposal first and after I will start a ne migration from 0 because I think I have a problem with the database.

**Comment by hmartinet** [comment]
The fields amount, currency_id, matched_percentage in account_move_line already exists. How can I know why the software recalculate these values to avoid that ? This recalculation takes more than 2 days and I can't stop the production instance as long to do the migration. If I add a post script to recalculate these fields in SQL it will not bypass the python recalculation.

```
2017-12-20 17:24:22,838 58849 INFO my_database odoo.models: Storing computed values of account.move fields amount, currency_id, matched_percentage
2017-12-22 18:49:36,444 58849 INFO my_database odoo.modules.loading: loading account/security/account_security.xml
```

**Comment by StefanRijnhart** [comment]
>  amount, currency_id, matched_percentage in account_move_line

Oh, but the logs mentions account_move, not account_move_line.

**Comment by hmartinet** [comment]
Oh sorry, my bad, yes it's on account_move, but fields already exists in Odoo 9.0.

Then I will retry all process from zero to be sure at which level appears which problem.

But it can takes 3 days to run ;)

**Comment by StefanRijnhart** [comment]
Oh, I see, this is from 9 to 10

**Comment by hmartinet** [comment]
Yes.

**Comment by StefanRijnhart** [comment]
I only have that log message when migrating from 8.0 to 9.0. Again, it comes down to your 'ineffective' migration from 8.0 to 9.0 probably caused by a rolled back database transaction.

**Comment by hmartinet** [comment]
Yes ok. It seems that I had to mix things between all my databases at each migration steps. Sorry I will start a new process and come back with more precise informations.

**Comment by hmartinet** [comment]
I found the source of all the problems !

It's at the v7 to v8 migration. The migrate.py process was killed by debian because there is no available memory. Then there is no log for that in the migration.log, but the last line is the calculation of field reconcile_ref on account_move_line. This will explain why some tables are missing in following migration.

I have to write some SQL script for every new fields on account_move_line in 8.0, 9.0 and 10.0 migration because my table is too big. I will make PR for that and I consider this issue is closed.

**Comment by StefanRijnhart** [comment]
Thanks for the update! Looking forward to your PR.
