### ISSUE TITLE
[9.0] project_timesheet : running script on uninstalled.

### ISSUE THREAD

**Issue by rousseldenis** [OCA/OpenUpgrade#1266]
It seems that the migration script for 8->9 is run and project_timesheet module is uninstalled in original db.

So, the column hr_analytic_timesheet_id does not exist in project.task.work model.

Is there a previous script that install this module? Did I miss something?

**Comment by StefanRijnhart** [comment]
Not entirely clear what is the matter here. Do you have the module installed in 8.0 and is the module uninstalled during the migration?

**Comment by geluboros** [comment]
Hi @StefanRijnhart,

I faced an issue that i think is related to this one.

I will try to explain it:
* Some modules from version 8 (not installed) are getting installed during the migration process, due to dependency changes. The problem is that during the installation, the migration scripts are executed and generate errors that stop the migration process.

For example:
* project_timesheet - this module becomes a dependency of project_issue_sheet in v9, so if it's not installed in v8, the migration scripts will fail and stop the migration process. It fails because the script tries to copy data from old columns (v8) that don't exist.
* portal - portal module becomes a dependency of project in v9, so if it's not installed in v8, migration script will fail. It tries to delete an external ID that is not created.

I am not sure if there are other modules that can cause this type of issue.

**Comment by pedrobaeza** [comment]
This is weird, as the decorator `@openupgrade.migrate()` on the script prevents migration scripts to be run when modules are being installed instead of being updated. Can you show us a migration log where the problem happens?

**Comment by geluboros** [comment]
Hi Pedro,

I don't have the entire log, but i did save the error part when i was doing the migration. I don't know if it will help, but here it is:

```
2018-03-19 09:17:35,119 15853 WARNING test-8_migrated openerp.models.schema: Table `project_config_settings`: column `group_tasks_work_on_tasks` has changed type (DB=bool, def=selection), data moved to column `group_tasks_work_on_tasks_moved0`
2018-03-19 09:17:35,693 15853 INFO test-8_migrated OpenUpgrade: project_timesheet: post-migration script called with version 7.0.1.0
2018-03-19 09:17:35,693 15853 INFO test-8_migrated openerp.sql_db: Programming error: column w.hr_analytic_timesheet_id does not exist
LINE 1: ...oject_task_work w join hr_analytic_timesheet t on w.hr_analy...
                                                             ^
, in query update account_analytic_line set task_id=work.task_id from (select w.task_id, t.line_id from project_task_work w join hr_analytic_timesheet t on w.hr_analytic_timesheet_id=t.id) work where work.line_id=account_analytic_line.id
2018-03-19 09:17:35,694 15853 ERROR test-8_migrated OpenUpgrade: project_timesheet: error in migration script project_timesheet/migrations/9.0.1.0/post-migration.py: ProgrammingError('column w.hr_analytic_timesheet_id does not exist\nLINE 1: ...oject_task_work w join hr_analytic_timesheet t on w.hr_analy...\n                                                             ^\n',)
2018-03-19 09:17:35,694 15853 ERROR test-8_migrated OpenUpgrade: column w.hr_analytic_timesheet_id does not exist
LINE 1: ...oject_task_work w join hr_analytic_timesheet t on w.hr_analy...
                                                             ^
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1391, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/project_timesheet/migrations/9.0.1.0/post-migration.py", line 10, in migrate
    'update account_analytic_line '
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column w.hr_analytic_timesheet_id does not exist
LINE 1: ...oject_task_work w join hr_analytic_timesheet t on w.hr_analy...
                                                             ^
```

**Comment by pedrobaeza** [comment]
You are not migrating correctly, as the script is called with `7.0...` version. There's something incorrect in your end.

**Comment by pedrobaeza** [comment]
Triaging this.

**Comment by twe-t** [comment]
@StefanRijnhart  I have same issue like this. No, Module is not unintalled at the time of migration. It is already uninstalled on my production database by client. I am trying to migrate the db v8 -> v9 with the help pf openupgrade. But because of this module openupgrade stoped the migration and I cant get the migrated data. Traceback is  same mention by @gboros-rgbconsulting above. But this module is uninstalled on production database itself before migration. Please provide me guidance ASAP.

**Comment by StefanRijnhart** [comment]
@twe-t do you have this line as well in your logs: `post-migration script called with version 7.0.1.0` ?

**Comment by twe-t** [comment]
@StefanRijnhart no not that one... Rather I have like this....
**post-migration script called with version 8.0.1.0**

**Comment by StefanRijnhart** [comment]
So the traceback is not the same. Can you post it?

**Comment by twe-t** [comment]
My last few lines from migration.log file are like this:
```
`2018-08-23 11:15:28,649 14975 INFO prod_database_v8_migrated openerp.modules.loading: loading project_timesheet/report/project_report_view.xml
2018-08-23 11:15:28,711 14975 INFO prod_database_v8_migrated openerp.modules.loading: loading project_timesheet/project_timesheet_view.xml
2018-08-23 11:15:29,165 14975 INFO prod_database_v8_migrated openerp.modules.loading: loading project_timesheet/res_config_view.xml
2018-08-23 11:15:29,225 14975 INFO prod_database_v8_migrated openerp.modules.migration: module project_timesheet: Running migration [9.0.1.0>] post-migration
2018-08-23 11:15:29,225 14975 INFO prod_database_v8_migrated openerp.modules.migration: module project_timesheet: Running migration [9.0.1.0>] post-migration
2018-08-23 11:15:29,233 14975 INFO prod_database_v8_migrated OpenUpgrade: project_timesheet: post-migration script called with version 8.0.1.0
2018-08-23 11:15:29,236 14975 INFO prod_database_v8_migrated openerp.sql_db: Programming error: column w.hr_analytic_timesheet_id does not exist
LINE 1: ...oject_task_work w join hr_analytic_timesheet t on w.hr_analy...
                                                             ^
, in query update account_analytic_line set task_id=work.task_id from (select w.task_id, t.line_id from project_task_work w join hr_analytic_timesheet t on w.hr_analytic_timesheet_id=t.id) work where work.line_id=account_analytic_line.id
2018-08-23 11:15:29,236 14975 ERROR prod_database_v8_migrated OpenUpgrade: project_timesheet: error in migration script project_timesheet/migrations/9.0.1.0/post-migration.py: ProgrammingError('column w.hr_analytic_timesheet_id does not exist\nLINE 1: ...oject_task_work w join hr_analytic_timesheet t on w.hr_analy...\n                                                             ^\n',)
2018-08-23 11:15:29,236 14975 ERROR prod_database_v8_migrated OpenUpgrade: column w.hr_analytic_timesheet_id does not exist
LINE 1: ...oject_task_work w join hr_analytic_timesheet t on w.hr_analy...
                                                             ^
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1439, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/project_timesheet/migrations/9.0.1.0/post-migration.py", line 10, in migrate
    'update account_analytic_line '
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column w.hr_analytic_timesheet_id does not exist
LINE 1: ...oject_task_work w join hr_analytic_timesheet t on w.hr_analy...
                                                             ^

2018-08-23 11:15:29,237 14975 ERROR prod_database_v8_migrated openerp.modules.loading: Error executing post migration script for module project_timesheet
`-> sale_service
: column w.hr_analytic_timesheet_id does not exist
LINE 1: ...oject_task_work w join hr_analytic_timesheet t on w.hr_analy...`
```
