### ISSUE TITLE
Error migrating from 7.0 to 8.0

### ISSUE THREAD

**Issue by thagaba** [OCA/OpenUpgrade#1271]
I am using the migrate.py script to upgrade from v7.0 to v8.0. I run into the following error: 
"""
2018-01-24 21:22:32,629 12436 ERROR TO_migrated openerp.addons.base.ir.ir_ui_view: Element '\<group name="status" version="7.0"\>' cannot be located in parent view

Error context:
View `product.product.form`
[view_id: 221, xml_id: product.product_normal_form_view, model: product.product, parent_id: 239]
2018-01-24 21:22:32,649 12436 CRITICAL TO_migrated openerp.service.server: Failed to initialize database `TO_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 509, in load_modules
    if not Views._validate_custom_views(cr, SUPERUSER_ID, model):
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 1133, in _validate_custom_views
    return self._check_xml(cr, uid, ids, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 197, in _check_xml
    view_def = self.read_combined(cr, uid, view.id, ['arch'], context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 561, in read_combined
    cr, uid, arch_tree, view_arch, parent_view['id'], context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 498, in apply_inheritance_specs
    self.raise_view_error(cr, uid, _("Element '%s' cannot be located in parent view") % tag, inherit_id, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 383, in raise_view_error
    raise AttributeError(message)
AttributeError: Element '\<group name="status" version="7.0"\>' cannot be located in parent view

Error context:
View `product.product.form`
[view_id: 221, xml_id: product.product_normal_form_view, model: product.product, parent_id: 239]

"""

My customizations to v7.0 have not touched the <group name="status"> element or anything inside the <page name="Information"> in which it occurs, neither in product.product_normal_form_view nor its parent, product.product_template_form_view.

I have tried inserting the version="7.0" attribute in the relevant ir_ui_view record of my original v7.0 database, but without success. I cannot find the reference to <group name="status" version="7.0"> in the v8.0 code. I am at a loss as to how to proceed, and, more generally, I do not understand why upgrades to ui objects are critical. I mean, once other objects are upgraded, can't 8.0 menus and views be installed from scratch in the new environment?

Thanks in advance

**Comment by StefanRijnhart** [comment]
Such errors are expected and should not be fatal in OpenUpgrade. Does the error halt the migration process?

**Comment by thagaba** [comment]
Thanks for your reply. 

Yes, the error does halt the migration process. 
The relevant line from ps during execution:

sysadmin  6364  0.0  1.2  94760 12452 pts/0    S+   22:58   0:00 python migrate.py --config=/etc/openerp-server.conf --database=TO --run-migrations=8.0

But PID 6364 no longer appears after the log entry cited in my OP.

Sorry for the late response: I recreated everything after you expressed your doubt, and have reproduced the fatal error. I remain committed to the upgrade. Please advise.

**Comment by StefanRijnhart** [comment]
The fatal error might be another one. Can you post the full logs of your migration somewhere or forward them to me privately (email in my profile).

**Comment by StefanRijnhart** [comment]
Thanks for sending the logs. I could have seen from what you already submitted that this concerns a custom view. We did not think of catching errors for custom views. I'm submitting a tentative PR here: https://github.com/OCA/OpenUpgrade/pull/1287. ~~I have not tested this yet~~. It would be great if you could try the migration with this patch in your setup. It should continue the migration, setting the invalid custom views to inactive.

**Comment by thagaba** [comment]
Wow thanks! I will have a try tonight (of Montreal).
I'm looking forward to moving forward. 
Till tomorrow, 
Guru

**Comment by pedrobaeza** [comment]
Closing as fixed.

**Comment by thagaba** [comment]
I can now confirm that the patched migration script worked: the script produces a migrated database which can be accessed in an odoo 8 environment. Sorry for the late response.
Many thanks!

**Comment by StefanRijnhart** [comment]
Alright, thanks for confirming ;-)
