### ISSUE TITLE
El campo `notify_email` no existe

### ISSUE THREAD

**Issue by carlosecv** [OCA/OpenUpgrade#1274]
Impacted versions: migration 10 to 11

Steps to reproduce: 
use a database Odoo v10 CE  
Modules:

- CRM
- WebSite
- Purchases
- Wharehouse
- Sales
No customizations

1.- Execute OpenUpgrade over this version 10 database with  –update all –stop-after-init
2.- Execute -u all on  standar 11 version over the same database

Current behavior:

```
2018-02-15 18:21:27,921 8774 INFO hitra11 odoo.modules.loading: loading mail/views/res_partner_views.xml
2018-02-15 18:21:27,967 8774 INFO hitra11 odoo.addons.base.ir.ir_ui_view: Field `notify_email` does not exist

Error context:
View `res.partner.view.form.inherit.mail`
[view_id: 1088, xml_id: mail.res_partner_view_form_inherit_mail, model: res.partner, parent_id: 124]
2018-02-15 18:21:27,968 8774 ERROR hitra11 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/carlos/odoo11/odoo/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/home/carlos/odoo11/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/home/carlos/odoo11/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/carlos/odoo11/odoo/odoo/models.py", line 971, in _validate_fields
    check(self)
  File "/home/carlos/odoo11/odoo/odoo/addons/base/ir/ir_ui_view.py", line 321, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/home/carlos/odoo11/odoo/odoo/addons/base/ir/ir_ui_view.py", line 919, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/home/carlos/odoo11/odoo/odoo/addons/base/ir/ir_ui_view.py", line 489, in raise_view_error
    raise ValueError(message)
ValueError: Field `notify_email` does not exist

```

Expected behavior:

Migrated database without errors.

**Comment by pedrobaeza** [comment]
Have you check current migration coverage? For sure your DB is not yet possible to be migrated because there are a lot of uncovered modules.

Any way, the error indicates that you are not using OpenUpgrade server for performing the upgrade.
