### ISSUE TITLE
[9.0] Migration from 8.0 to 9.0 -> AttributeError: 'module' object has no attribute 'rename_fields' 

### ISSUE THREAD

**Issue by xavierjimenez** [OCA/OpenUpgrade#1290]
Hello,

I just started a migration from 8.0 to 9.0 but I'm founding this error at the start.
**AttributeError: 'module' object has no attribute 'rename_fields'**

I have the last version from Github and also upgraded the Openupgrade Python library since my last migration was a few months ago.

I assume this is because the changes done recently. Am I missing something or has the way to do migrations changed because of those changes?

Thanks,

**Impacted versions:**
8.0/9.0
**Steps to reproduce:**
Run an 8.0 database with the OpenUpgrade 9.0 Odoo and --update=all command
**Current behavior:**
It halts the process almost at the start
**Expected behavior:**
It should keep going

**Logs:**

2018-03-15 09:38:13,867 3583 ERROR databasev8 openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/modules/loading.py", line 342, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/modules/migration.py", line 169, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/Users/xavierjimenez/odoo-env/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 1200, in wrapped_function
    if use_env2 else cr, version)
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/addons/base/migrations/9.0.1.3/pre-migration.py", line 171, in migrate
    openupgrade.rename_fields(env, field_renames, no_deep=True)
AttributeError: 'module' object has no attribute 'rename_fields'

2018-03-15 09:38:13,868 3583 CRITICAL databasev8 openerp.service.server: Failed to initialize database `databasev8`.
Traceback (most recent call last):
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/service/server.py", line 897, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/modules/loading.py", line 342, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/modules/migration.py", line 169, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/Users/xavierjimenez/odoo-env/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 1200, in wrapped_function
    if use_env2 else cr, version)
  File "/Users/xavierjimenez/odoo-env/openupgrade-9.0/openerp/addons/base/migrations/9.0.1.3/pre-migration.py", line 171, in migrate
    openupgrade.rename_fields(env, field_renames, no_deep=True)
AttributeError: 'module' object has no attribute 'rename_fields'

**Comment by paolovalier** [comment]
hi @xavierjimenez have you found a solution? I got stuck in the same point

**Comment by xavierjimenez** [comment]
Yes I did @paolovalier 

You just need to upgrade the OpenUpgrade Python library, but you can't do a pip --upgrade because that doesn't work, get the latest version from GitHub: https://github.com/OCA/openupgradelib

**Comment by paolovalier** [comment]
thank @xavierjimenez 
should I git clone it somewhere? I miss how to install from source..

**Comment by xavierjimenez** [comment]
You have to get the latest version on your Python libraries folder

**Comment by pedrobaeza** [comment]
You can use also pip:
```
sudo pip install git+https://github.com/OCA/openupgradelib.git@master --upgrade
```

**Comment by paolovalier** [comment]
I got it from https://github.com/OCA/OpenUpgrade/issues/773 few moments ago
thanks pedrobaeza
