### ISSUE TITLE
Database Migration Problem.

### ISSUE THREAD

**Issue by DonFeraRRi** [OCA/OpenUpgrade#1292]
Impacted versions: Database on Odoo 9.0
**I read it in your document that Each branch migrates to its version from the previous version, so branch 7.0 migrates from 6.1 to 7.0. If you are skipping versions, you still need to run all the branches in between..** link: https://doc.therp.nl/openupgrade/migration_details.html
Steps to reproduce: I just Downloaded the OpenUpgrade10.0 to upgrade my Database that is in odoo9.0 and replaced my odoo folder with openUpgrade10.0. I manually tried to run it, selected my odoo9.0 database, a login screen occurs, but when I enter the login credentials, it shows," Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." 

Current behavior: Error

Expected behavior: To run the Odoo9.0 Database

Video/Screenshot link (optional): Log Details.
2018-03-21 07:32:43,260 11241 INFO ? odoo: Odoo version 10.0
2018-03-21 07:32:43,261 11241 INFO ? odoo: addons paths: ['/opt/dex/.local/share/Odoo/addons/10.0', u'/opt/dex/simple/OpenUpgrade-10.0/addons', '/opt/dex/simple/OpenUpgrade-10.0/odoo/addons']
2018-03-21 07:32:43,261 11241 INFO ? odoo: database: default@default:default
2018-03-21 07:32:43,300 11241 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2018-03-21 07:32:44,881 11241 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2018-03-21 07:32:46,189 11241 INFO ? odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2018-03-21 07:32:46,998 11241 INFO ? odoo.http: HTTP Configuring static files
2018-03-21 07:32:47,020 11241 INFO odoo9 odoo.modules.loading: loading 1 modules...
2018-03-21 07:32:47,076 11241 INFO odoo9 odoo.modules.loading: 1 modules loaded in 0.05s, 0 queries
2018-03-21 07:32:47,108 11241 WARNING odoo9 odoo.modules.graph: module web_tip: not installable, skipped
2018-03-21 07:32:47,112 11241 WARNING odoo9 odoo.modules.graph: module marketing: not installable, skipped
2018-03-21 07:32:47,117 11241 WARNING odoo9 odoo.modules.graph: module web_view_editor: not installable, skipped
2018-03-21 07:32:47,124 11241 WARNING odoo9 odoo.modules.graph: module mail_tip: not installable, skipped
2018-03-21 07:32:47,125 11241 WARNING odoo9 odoo.modules.graph: module im_odoo_support: not installable, skipped
2018-03-21 07:32:47,141 11241 ERROR odoo9 odoo.modules.graph: module fetchmail: Unmet dependencies: mail
2018-03-21 07:32:47,142 11241 ERROR odoo9 odoo.modules.graph: module base_action_rule: Unmet dependencies: mail
2018-03-21 07:32:47,142 11241 ERROR odoo9 odoo.modules.graph: module portal: Unmet dependencies: auth_signup
2018-03-21 07:32:47,142 11241 ERROR odoo9 odoo.modules.graph: module mail: Unmet dependencies: web_tour
2018-03-21 07:32:47,142 11241 ERROR odoo9 odoo.modules.graph: module auth_signup: Unmet dependencies: mail
2018-03-21 07:32:47,142 11241 ERROR odoo9 odoo.modules.graph: module calendar: Unmet dependencies: mail, base_action_rule
2018-03-21 07:32:47,143 11241 ERROR odoo9 odoo.modules.graph: module sales_team: Unmet dependencies: mail
2018-03-21 07:32:47,143 11241 ERROR odoo9 odoo.modules.graph: module crm: Unmet dependencies: base_action_rule, sales_team, mail, calendar, fetchmail, web_tour
2018-03-21 07:32:47,144 11241 INFO odoo9 odoo.modules.loading: loading 16 modules...
2018-03-21 07:32:47,245 11241 INFO odoo9 odoo.modules.loading: 16 modules loaded in 0.10s, 0 queries
2018-03-21 07:32:47,802 11241 INFO odoo9 odoo.modules.loading: Modules loaded.
2018-03-21 07:32:47,814 11241 INFO odoo9 odoo.addons.base.ir.ir_http: Generating routing map
2018-03-21 07:32:51,224 11241 INFO odoo9 werkzeug: 127.0.0.1 - - [21/Mar/2018 07:32:51] "GET /web?db=odoo9 HTTP/1.1" 303 -
2018-03-21 07:32:51,456 11241 INFO odoo9 werkzeug: 127.0.0.1 - - [21/Mar/2018 07:32:51] "GET /web/login HTTP/1.1" 200 -
2018-03-21 07:33:00,544 11241 INFO odoo9 odoo.sql_db: bad query:  SELECT "res_partner"."type" as "type","res_partner"."write_uid" as "write_uid","res_partner"."street" as "street","res_partner"."tz" as "tz","res_partner"."commercial_partner_id" as "commercial_partner_id","res_partner"."display_name" as "display_name","res_partner"."email" as "email","res_partner"."id" as "id","res_partner"."customer" as "customer","res_partner"."company_id" as "company_id","res_partner"."create_date" as "create_date","res_partner"."date" as "date","res_partner"."country_id" as "country_id","res_partner"."vat" as "vat","res_partner"."write_date" as "write_date","res_partner"."employee" as "employee","res_partner"."fax" as "fax","res_partner"."parent_id" as "parent_id","res_partner"."website" as "website","res_partner"."function" as "function","res_partner"."zip" as "zip","res_partner"."state_id" as "state_id","res_partner"."credit_limit" as "credit_limit","res_partner"."title" as "title","res_partner"."barcode" as "barcode","res_partner"."comment" as "comment","res_partner"."is_company" as "is_company","res_partner"."name" as "name","res_partner"."mobile" as "mobile","res_partner"."user_id" as "user_id","res_partner"."city" as "city","res_partner"."active" as "active","res_partner"."lang" as "lang","res_partner"."street2" as "street2","res_partner"."color" as "color","res_partner"."partner_share" as "partner_share","res_partner"."create_uid" as "create_uid","res_partner"."phone" as "phone","res_partner"."company_name" as "company_name","res_partner"."supplier" as "supplier","res_partner"."commercial_company_name" as "commercial_company_name","res_partner"."ref" as "ref" FROM "res_partner"
                        WHERE "res_partner".id IN (3)  ORDER BY "res_partner"."display_name"  
                    
2018-03-21 07:33:01,026 11241 INFO odoo9 werkzeug: 127.0.0.1 - - [21/Mar/2018 07:33:01] "POST /web/login HTTP/1.1" 500 -
2018-03-21 07:33:01,092 11241 ERROR odoo9 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 1308, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 1282, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 1480, in dispatch
    result = ir_http._dispatch()
  File "/opt/dex/simple/OpenUpgrade-10.0/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/dex/simple/OpenUpgrade-10.0/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/dex/simple/OpenUpgrade-10.0/addons/web/controllers/main.py", line 469, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 1047, in authenticate
    if uid: self.get_context()
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/http.py", line 1082, in get_context
    self.context = request.env['res.users'].context_get() or {}
  File "<decorator-gen-30>", line 2, in context_get
    
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/addons/base/res/res_users.py", line 417, in context_get
    res = getattr(user, k) or False
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/fields.py", line 897, in __get__
    self.determine_value(record)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/fields.py", line 1008, in determine_value
    self.compute_value(recs)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/fields.py", line 963, in compute_value
    self._compute_value(records)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/fields.py", line 956, in _compute_value
    self.compute(records)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/fields.py", line 607, in _compute_related
    record[self.name] = other[field.name]
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/models.py", line 5265, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/fields.py", line 897, in __get__
    self.determine_value(record)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/fields.py", line 999, in determine_value
    record._prefetch_field(self)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/models.py", line 3121, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/models.py", line 3061, in read
    self._read_from_database(stored, inherited)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/models.py", line 3189, in _read_from_database
    cr.execute(query_str, params)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/dex/simple/OpenUpgrade-10.0/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_partner.partner_share does not exist
LINE 1: ...t2" as "street2","res_partner"."color" as "color","res_partn...

**Comment by pedrobaeza** [comment]
You are not updating the database with `-u all` parameter.

**Comment by DonFeraRRi** [comment]
Yeah I was trying to run the database and open it. So I need to run -u all.

**Comment by DonFeraRRi** [comment]
I Did that this time and updated the im_odoo_support too and then took the backup from there and uploaded in odoo10.  i entered my credentials on login screen but this error popped out in log screen.
--------
2018-03-21 10:21:51,707 9062 INFO migrationtest4 werkzeug: 192.168.1.50 - - [21/Mar/2018 10:21:51] "GET /web HTTP/1.1" 500 -
2018-03-21 10:21:51,717 9062 ERROR migrationtest4 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/asoral/Simple_10/core/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/home/asoral/Simple_10/core/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/home/asoral/Simple_10/core/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/home/asoral/Simple_10/core/odoo/http.py", line 1314, in __call__
    return self.dispatch(environ, start_response)
  File "/home/asoral/Simple_10/core/odoo/http.py", line 1288, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/asoral/Simple_10/core/odoo/http.py", line 1487, in dispatch
    result = ir_http._dispatch()
  File "/home/asoral/Simple_10/core/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/asoral/Simple_10/core/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/home/asoral/Simple_10/core/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/home/asoral/Simple_10/core/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/home/asoral/Simple_10/core/odoo/http.py", line 774, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/asoral/Simple_10/core/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/home/asoral/Simple_10/core/odoo/http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "/home/asoral/Simple_10/core/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/asoral/Simple_10/core/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/asoral/Simple_10/core/odoo/http.py", line 329, in checked_call
    result.flatten()
  File "/home/asoral/Simple_10/core/odoo/http.py", line 1265, in flatten
    self.response.append(self.render())
  File "/home/asoral/Simple_10/core/odoo/http.py", line 1258, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/home/asoral/Simple_10/core/odoo/addons/base/ir/ir_ui_view.py", line 1043, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/asoral/Simple_10/core/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/asoral/Simple_10/core/odoo/addons/base/ir/ir_ui_view.py", line 1063, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/asoral/Simple_10/core/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/asoral/Simple_10/core/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/asoral/Simple_10/core/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: unbound method get_param() must be called with ir.config_parameter instance as first argument (got Cursor instance instead)
Traceback (most recent call last):
  File "/home/asoral/Simple_10/core/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_web_assets_backend_1203
TypeError: unbound method get_param() must be called with ir.config_parameter instance as first argument (got Cursor instance instead)

Error to render compiling AST
TypeError: unbound method get_param() must be called with ir.config_parameter instance as first argument (got Cursor instance instead)
Template: web.assets_backend
Path: /templates/t/script[66]/t[2]
Node: <t t-esc="request.registry['ir.config_parameter'].get_param(request.cr, request.uid, 'database.uuid')"/>"
                        );
                    });

**Comment by pedrobaeza** [comment]
Migration log?

**Comment by DonFeraRRi** [comment]
I did it....  I just removed the im_odoo_support as it is not present in 10. I uninstalled it and then -u all with OpenUpgrade and then taking the backup, running it on 10 It was successful without any errors. Now will try my live database. and if something will there I will again call you for help. You are a savior,

**Comment by DonFeraRRi** [comment]
Now this is the error while upgrading. Any Solutions?
```
_9/nmpl/ -d nmpl -u all --xmlrpc-port=1122
2018-03-21 11:10:03,094 14130 INFO ? odoo: Odoo version 10.0
2018-03-21 11:10:03,094 14130 INFO ? odoo: Using configuration file at /home/asoral/.openerp_serverrc
2018-03-21 11:10:03,095 14130 INFO ? odoo: addons paths: ['/home/asoral/.local/share/Odoo/addons/10.0', u'/home/asoral/Simple_10/openupgrade/addons', u'/home/asoral/Simple_10/repo', u'/home/asoral/Simple_9/nmpl', '/home/asoral/Simple_10/openupgrade/odoo/addons']
2018-03-21 11:10:03,095 14130 INFO ? odoo: database: default@default:default
2018-03-21 11:10:03,105 14130 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:1122
2018-03-21 11:10:03,115 14130 INFO nmpl odoo.modules.loading: loading 1 modules...
2018-03-21 11:10:03,117 14130 ERROR nmpl odoo.modules.migration: module base: Unable to load pre-migration file base/migrations/10.0.1.3/pre-migration.py
Traceback (most recent call last):
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/migration.py", line 153, in migrate_module
    mod = imp.load_module(name, fp, pathname, ('.py', 'r', imp.PY_SOURCE))
  File "/home/asoral/Simple_10/openupgrade/odoo/addons/base/migrations/10.0.1.3/pre-migration.py", line 4, in <module>
    from openupgradelib import openupgrade
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 44, in <module>
    from openerp.osv.fields import many2many, one2many
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/module.py", line 109, in load_module
    mod = importlib.import_module(canonical)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named fields
2018-03-21 11:10:03,118 14130 ERROR nmpl odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/migration.py", line 153, in migrate_module
    mod = imp.load_module(name, fp, pathname, ('.py', 'r', imp.PY_SOURCE))
  File "/home/asoral/Simple_10/openupgrade/odoo/addons/base/migrations/10.0.1.3/pre-migration.py", line 4, in <module>
    from openupgradelib import openupgrade
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 44, in <module>
    from openerp.osv.fields import many2many, one2many
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/module.py", line 109, in load_module
    mod = importlib.import_module(canonical)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named fields
2018-03-21 11:10:03,118 14130 CRITICAL nmpl odoo.service.server: Failed to initialize database `nmpl`.
Traceback (most recent call last):
  File "/home/asoral/Simple_10/openupgrade/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/migration.py", line 153, in migrate_module
    mod = imp.load_module(name, fp, pathname, ('.py', 'r', imp.PY_SOURCE))
  File "/home/asoral/Simple_10/openupgrade/odoo/addons/base/migrations/10.0.1.3/pre-migration.py", line 4, in <module>
    from openupgradelib import openupgrade
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 44, in <module>
    from openerp.osv.fields import many2many, one2many
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/module.py", line 109, in load_module
    mod = importlib.import_module(canonical)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named fields

```

**Comment by pedrobaeza** [comment]
Sorry, but you should be doing something bad, as this error is basically a bad deployment derived issue. We can't help you in that case, as it's not something about OpenUpgrade itself.

**Comment by DonFeraRRi** [comment]
After reading this line 2018-03-21 11:10:03,117 14130 ERROR nmpl odoo.modules.migration: module base: Unable to load pre-migration file base/migrations/10.0.1.3/pre-migration.py
I doubt something wrong with openupgrade and moreover, i was running this remotely. So I guess there is some issue with that openupgrade on remote computer.
Prior i tested it on my pc.

**Comment by DonFeraRRi** [comment]
Any Idea about this log?I am unable to trace this error.
---------------
2018-03-21 13:56:56,210 20537 INFO ? odoo: Odoo version 10.0
2018-03-21 13:56:56,210 20537 INFO ? odoo: Using configuration file at /home/asoral/.openerp_serverrc
2018-03-21 13:56:56,211 20537 INFO ? odoo: addons paths: ['/home/asoral/.local/share/Odoo/addons/10.0', u'/home/asoral/Simple_10/openupgrade/addons', u'/home/asoral/Simple_10/repo', u'/home/asoral/Simple_9/nmpl', '/home/asoral/Simple_10/openupgrade/odoo/addons']
2018-03-21 13:56:56,211 20537 INFO ? odoo: database: default@default:default
2018-03-21 13:56:56,221 20537 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:5698
2018-03-21 13:56:56,237 20537 INFO nmpl odoo.modules.loading: loading 1 modules...
2018-03-21 13:56:56,240 20537 ERROR nmpl odoo.modules.migration: module base: Unable to load pre-migration file base/migrations/10.0.1.3/pre-migration.py
Traceback (most recent call last):
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/migration.py", line 153, in migrate_module
    mod = imp.load_module(name, fp, pathname, ('.py', 'r', imp.PY_SOURCE))
  File "/home/asoral/Simple_10/openupgrade/odoo/addons/base/migrations/10.0.1.3/pre-migration.py", line 4, in <module>
    from openupgradelib import openupgrade
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 44, in <module>
    from openerp.osv.fields import many2many, one2many
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/module.py", line 109, in load_module
    mod = importlib.import_module(canonical)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named fields
2018-03-21 13:56:56,241 20537 ERROR nmpl odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/migration.py", line 153, in migrate_module
    mod = imp.load_module(name, fp, pathname, ('.py', 'r', imp.PY_SOURCE))
  File "/home/asoral/Simple_10/openupgrade/odoo/addons/base/migrations/10.0.1.3/pre-migration.py", line 4, in <module>
    from openupgradelib import openupgrade
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 44, in <module>
    from openerp.osv.fields import many2many, one2many
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/module.py", line 109, in load_module
    mod = importlib.import_module(canonical)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named fields
2018-03-21 13:56:56,242 20537 CRITICAL nmpl odoo.service.server: Failed to initialize database `nmpl`.
Traceback (most recent call last):
  File "/home/asoral/Simple_10/openupgrade/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/migration.py", line 153, in migrate_module
    mod = imp.load_module(name, fp, pathname, ('.py', 'r', imp.PY_SOURCE))
  File "/home/asoral/Simple_10/openupgrade/odoo/addons/base/migrations/10.0.1.3/pre-migration.py", line 4, in <module>
    from openupgradelib import openupgrade
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 44, in <module>
    from openerp.osv.fields import many2many, one2many
  File "/home/asoral/Simple_10/openupgrade/odoo/modules/module.py", line 109, in load_module
    mod = importlib.import_module(canonical)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named fields

**Comment by StefanRijnhart** [comment]
Again, this is a matter of installing Odoo (openupgrade) from source properly.
