### ISSUE TITLE
v9 -> v10 stock migration has no attribute 'rename_fields'

### ISSUE THREAD

**Issue by travish2** [OCA/OpenUpgrade#1328]
Impacted versions: v10

Steps to reproduce:
Git clone the 10.0 branch and run as same user as v9 instance. Update .conf file to point to OpenUpgrade addons and v10 addons. Run ./odoo-bin

Current behavior:
Gets to stock upgrade and quits with error

Expected behavior:
Continue upgrade

Error

> 2018-05-08 04:22:36,136 9660 ERROR DB_upgrade_tov10 OpenUpgrade: stock: error in migration script /odoo-community/OpenUpgrade/addons/stock/migrations/10.0.1.1/pre-migration.py: 'module' object has no attribute 'rename_fields'
2018-05-08 04:22:36,136 9660 ERROR DB_upgrade_tov10 OpenUpgrade: 'module' object has no attribute 'rename_fields'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1200, in wrapped_function
    if use_env2 else cr, version)
  File "/odoo-community/OpenUpgrade/addons/stock/migrations/10.0.1.1/pre-migration.py", line 74, in migrate
    openupgrade.rename_fields(env, field_renames)
AttributeError: 'module' object has no attribute 'rename_fields'
2018-05-08 04:22:36,138 9660 ERROR DB_upgrade_tov10 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo-community/OpenUpgrade/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo-community/OpenUpgrade/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/odoo-community/OpenUpgrade/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/odoo-community/OpenUpgrade/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/odoo-community/OpenUpgrade/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1200, in wrapped_function
    if use_env2 else cr, version)
  File "/odoo-community/OpenUpgrade/addons/stock/migrations/10.0.1.1/pre-migration.py", line 74, in migrate
    openupgrade.rename_fields(env, field_renames)
AttributeError: 'module' object has no attribute 'rename_fields'
2018-05-08 04:22:36,139 9660 CRITICAL DB_upgrade_tov10 odoo.service.server: Failed to initialize database `DB_upgrade_tov10`.
Traceback (most recent call last):
  File "/odoo-community/OpenUpgrade/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo-community/OpenUpgrade/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo-community/OpenUpgrade/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/odoo-community/OpenUpgrade/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/odoo-community/OpenUpgrade/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/odoo-community/OpenUpgrade/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1200, in wrapped_function
    if use_env2 else cr, version)
  File "/odoo-community/OpenUpgrade/addons/stock/migrations/10.0.1.1/pre-migration.py", line 74, in migrate
    openupgrade.rename_fields(env, field_renames)
AttributeError: 'module' object has no attribute 'rename_fields'
2018-05-08 04:22:36,141 9660 INFO DB_upgrade_tov10 odoo.service.server: Stopping gracefully

**Comment by pedrobaeza** [comment]
Please use latest openupgradelib code using:
```
pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
```
