### ISSUE TITLE
Access refused (database) for user "openerp"

### ISSUE THREAD

**Issue by buxx** [OCA/OpenUpgrade#133]
I've got this error when execute:

```
root@deb:~/openupgrade# python migrate.py --config="/etc/openerp/openerp-server.conf" --database="cs" --run-migrations="8.0"
linking server/addons to /var/tmp/openupgrade/8.0/addons
getting git://github.com/OpenUpgrade/OpenUpgrade.git
sh: 1: git: not found
copying database cs to cs_migrated...
Traceback (most recent call last):
  File "migrate.py", line 300, in <module>
    db_name = copy_database(conn_parms)
  File "migrate.py", line 26, in copy_database
    conn = psycopg2.connect(**conn_parms)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  authentification peer ?chou?e pour l'utilisateur << openerp >>
```

Migration script need additional credentials for databse ?

**Comment by pedrobaeza** [comment]
No, the problem is that you don't have configured correctly postgresql: put your user as postgres user if you are using peer identification, or provide a correct user and password for othe authentication.

**Comment by buxx** [comment]
On this machine i've simply installed openerp (with apt-get), load prod database et tested it (logins working). I will search with postgres user ok.

**Comment by buxx** [comment]
Ok i got it thank's !
