### ISSUE TITLE
Upgrade worked ?

### ISSUE THREAD

**Issue by buxx** [OCA/OpenUpgrade#134]
I've use migrate.py to upgrade my database:

```
bux@deb:~/openupgrade$ python migrate.py --config="/etc/openerp/openerp-server.conf" --database="cs" --run-migrations="8.0"
From git://github.com/OpenUpgrade/OpenUpgrade
 * branch            8.0        -> FETCH_HEAD
Already up-to-date.
copying database cs to cs_migrated...
Copying the database using 'with template'
running migration for 8.0
/usr/lib/python2.7/dist-packages/babel/__init__.py:33: UserWarning: Module openerp was already imported from /var/tmp/openupgrade/8.0/server/openerp/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import get_distribution, ResolutionError
```

A simple warning appear, so i consider as success. So i restaure my migrated database "cs_migrated" in fresh and working install of Odoo. But, after the restauration, when i go to the home page of odoo, i've got an `Internal Server Error 
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

The odoo log say:

```
2014-11-18 21:51:39,950 2093 INFO cs werkzeug: 192.168.1.11 - - [18/Nov/2014 21:51:39] "GET /web/login HTTP/1.1" 500 -
2014-11-18 21:51:40,016 2093 ERROR cs werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 280, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1215, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1189, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/share/pyshared/werkzeug/wsgi.py", line 411, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1361, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1296, in get_response
    result = request.registry['ir.http']._handle_exception(e)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 596, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1293, in get_response
    result.flatten()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1166, in flatten
    self.response.append(self.render())
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1160, in render
    context=request.context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 1007, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_qweb.py", line 184, in get_template
    raise_qweb_exception(QWebTemplateNotFound, message="Loader could not find template %r" % name, template=origin_template)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_qweb.py", line 182, in get_template
    xml_doc = qwebcontext.loader(name)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 1005, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in read_template

  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 119, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 849, in read_template
    view_id = self.pool['ir.model.data'].xmlid_to_res_id(cr, uid, xml_id, raise_if_not_found=True)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 934, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(cr, uid, xmlid, raise_if_not_found)[1]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 926, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup

  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 916, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
QWebTemplateNotFound: External ID not found in the system: web.login
```

The database has not been migrated or i have an other problem with odoo ? Can i found in my "supposed" migrated database an information who can say if it's migrated or not ?

**Comment by buxx** [comment]
After debug migration.py i found os.system() with start of "tmp" openerp-server. I will debug his migrate.log.

**Comment by fred0716** [comment]
I have the same error message after executing migrate.py
How to fix this issue? 

running migration for 8.0
/usr/lib/python2.7/dist-packages/babel/**init**.py:33: UserWarning: Module openerp was already imported from /var/tmp/openupgrade/8.0/server/openerp/**init**.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import get_distribution, ResolutionError

**Comment by StefanRijnhart** [comment]
You could try a virtualenv with --no-site-packages
