### ISSUE TITLE
Migration 7 to 8 : Unable to load Base Module's models 

### ISSUE THREAD

**Issue by TobinFrost** [OCA/OpenUpgrade#1340]
Impacted versions: 8

Steps to reproduce:  python /var/tmp/openupgrade/8.0/server/openerp-server -c /var/tmp/openupgrade/8.0/server.cfg -u all

Current behavior: 7

Expected behavior: 

Video/Screenshot link (optional):

Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/service/model.py", line 120, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/var/tmp/openupgrade/8.0/addons/web/controllers/main.py", line 1247, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 910, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_actions.py", line 326, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3186, in read
    result = BaseModel.read(records, fields, load=load)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3221, in read
    self._read_from_database(stored, inherited)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3408, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/fields.py", line 1460, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_actions.py", line 266, in _search_view
    field_get = self.pool[act.res_model].fields_view_get(cr, uid,
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
KeyError: u'product.category'

**Comment by pedrobaeza** [comment]
This seems an incorrect deployment, as the error is not something normal, but without full log, we can't say much about this.

**Comment by TobinFrost** [comment]
There is the migration file log  : [https://ufile.io/asqqw](url)

**Comment by StefanRijnhart** [comment]
Looks like you accessed the web interface to trigger the migration. That can cause multiple workers to run the migration simultaneously amongst other problems. Can you run on a fresh copy of your version 7 database using 
`python /var/tmp/openupgrade/8.0/server/openerp-server -c /var/tmp/openupgrade/8.0/server.cfg -u all -d $DBNAME --stop-after-init` and post the logs of that if the results are similar?

**Comment by TobinFrost** [comment]
I tried the command, so there's the log file [https://ufile.io/xqs4l](url) 
I have the same error

**Comment by pedrobaeza** [comment]
Your addons path doesn't contain the OpenUpgrade modules, so that's your problem. Nothing to do with OpenUpgrade itself.

**Comment by StefanRijnhart** [comment]
That's the same log file ;-) But indeed, maybe best to check your addons directory first.
