### ISSUE TITLE
Upgrading from v8.0 to v9.0 

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#1355]
I got this error in my `migration.log`

```
2018-05-30 09:43:01,007 10163 INFO coma_iso_migrated openerp.modules.migration: module portal_stock: Running migration [>9.0.0.1] pre-migration
2018-05-30 09:43:01,007 10163 INFO coma_iso_migrated openerp.modules.migration: module portal_stock: Running migration [>9.0.0.1] pre-migration
2018-05-30 09:43:01,013 10163 INFO coma_iso_migrated OpenUpgrade: portal_stock: pre-migration script called with version 8.0.0.1
2018-05-30 09:43:01,018 10163 ERROR coma_iso_migrated OpenUpgrade: portal_stock: error in migration script portal_stock/migrations/9.0.0.1/pre-migration.py: ValueError('External ID not found in the system: portal_stock.portal_stock_picking_user_rule',)
2018-05-30 09:43:01,018 10163 ERROR coma_iso_migrated OpenUpgrade: External ID not found in the system: portal_stock.portal_stock_picking_user_rule
Traceback (most recent call last):
  File "/opt/odoo/tmp/openupgradelib/openupgradelib/openupgrade.py", line 1427, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/tmp/9.0/addons/portal_stock/migrations/9.0.0.1/pre-migration.py", line 10, in migrate
    env.ref('portal_stock.portal_stock_picking_user_rule').unlink()
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 792, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/addons/base/ir/ir_model.py", line 1028, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(cr, uid, xmlid, raise_if_not_found)
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/addons/base/ir/ir_model.py", line 1014, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<decorator-gen-3>", line 2, in xmlid_lookup
  File "/opt/odoo/tmp/9.0/server/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/addons/base/ir/ir_model.py", line 1004, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: portal_stock.portal_stock_picking_user_rule
2018-05-30 09:43:01,086 10163 ERROR coma_iso_migrated openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/tmp/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/tmp/9.0/server/openerp/modules/loading.py", line 412, in load_modules
    loaded_modules, update_module, upg_registry)
  File "/opt/odoo/tmp/9.0/server/openerp/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/opt/odoo/tmp/9.0/server/openerp/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/tmp/9.0/server/openerp/modules/migration.py", line 169, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/opt/odoo/tmp/openupgradelib/openupgradelib/openupgrade.py", line 1427, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/tmp/9.0/addons/portal_stock/migrations/9.0.0.1/pre-migration.py", line 10, in migrate
    env.ref('portal_stock.portal_stock_picking_user_rule').unlink()
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 792, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/addons/base/ir/ir_model.py", line 1028, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(cr, uid, xmlid, raise_if_not_found)
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/addons/base/ir/ir_model.py", line 1014, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<decorator-gen-3>", line 2, in xmlid_lookup
  File "/opt/odoo/tmp/9.0/server/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/addons/base/ir/ir_model.py", line 1004, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: portal_stock.portal_stock_picking_user_rule
2018-05-30 09:43:01,087 10163 CRITICAL coma_iso_migrated openerp.service.server: Failed to initialize database `coma_iso_migrated`.
Traceback (most recent call last):
  File "/opt/odoo/tmp/9.0/server/openerp/service/server.py", line 897, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/odoo/tmp/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/tmp/9.0/server/openerp/modules/loading.py", line 412, in load_modules
    loaded_modules, update_module, upg_registry)
  File "/opt/odoo/tmp/9.0/server/openerp/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/opt/odoo/tmp/9.0/server/openerp/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/tmp/9.0/server/openerp/modules/migration.py", line 169, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/opt/odoo/tmp/openupgradelib/openupgradelib/openupgrade.py", line 1427, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/tmp/9.0/addons/portal_stock/migrations/9.0.0.1/pre-migration.py", line 10, in migrate
    env.ref('portal_stock.portal_stock_picking_user_rule').unlink()
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 792, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/addons/base/ir/ir_model.py", line 1028, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(cr, uid, xmlid, raise_if_not_found)
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/addons/base/ir/ir_model.py", line 1014, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/tmp/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<decorator-gen-3>", line 2, in xmlid_lookup
  File "/opt/odoo/tmp/9.0/server/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/tmp/9.0/server/openerp/addons/base/ir/ir_model.py", line 1004, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: portal_stock.portal_stock_picking_user_rule
2018-05-30 09:43:01,089 10163 INFO coma_iso_migrated openerp.service.server: Initiating shutdown
```
knowing that the portal_stock module is not installed !

**Comment by pedrobaeza** [comment]
This is because you removed in v8 instance that record rule. There are 2 solutions:

- Update portal_stock module in v8 for restoring that record rule and the migrate.
- Make a PR on OpenUpgrade for enclosing that unlink in a savepoint + try for avoiding the problem in case the record is not found.
