### ISSUE TITLE
Upgrade from Openerp 5 to Openerp 7

### ISSUE THREAD

**Issue by afridiwaqar** [OCA/OpenUpgrade#136]
Hello Geeks

I am trying to migrate from Openerp 5.0.10 to Openerp 7.0. I read some blogs and tutorial regarding how to do it using OpenUpgrade. 

First I Migrated the Database named "cms" using the migrate.py script provided in OpenUpgrade. The Process was successful and I got a database named cms_migrated with all of the data intact. (I thought it will migrate the custom NEWLY MADE modules also but it didnt)

Next I wanted to migrate the custom modules that we wrote TO Openerp 7 using the command below

$ ./openerp-server --config=/home/waqar/.openerp_serverrc --update=base,migration,audittrail,base_setup,cms,cms_attendance,cms_attendance_makeup_class,cms_attendance_schedule_changes,cms_examination,cms_hostel,cms_hr_holiday,cms_qec_evaluation,cms_transport,crm,hr,hr_contract,ims_financial_reporting,multi_company,process,product --stop-after-init --database=cms -u all -r waqar --addons-path=/home/waqar/erptmp/7.0/addons

cms and cms_\* are the modules we wrote and we also made changes to modules like HR and accounts and inherited the rest. /home/waqar/erptmp/7.0/addons contains the modules that were downloaded during migrate.py script was running. all the modules of Openerp 5 and custom modules are on path /usr/local/lib/python2.7/dist-packages/openerp-server/addons. While doing so, I got the following errors
# 

2014-11-21 06:46:48,972 14870 INFO ? openerp: OpenERP version 7.0
2014-11-21 06:46:48,972 14870 INFO ? openerp: addons paths: /home/waqar/erptmp/7.0/addons
2014-11-21 06:46:48,973 14870 INFO ? openerp: database hostname: localhost
2014-11-21 06:46:48,973 14870 INFO ? openerp: database port: 5432
2014-11-21 06:46:48,973 14870 INFO ? openerp: database user: waqar
2014-11-21 06:46:49,240 14870 INFO cms openerp.modules.loading: loading 1 modules...
2014-11-21 06:46:49,303 14870 INFO cms openerp.modules.migration: module base: Running migration [>7.0.1.3] pre-migration
2014-11-21 06:46:49,303 14870 INFO cms openerp.modules.migration: module base: Running migration [>7.0.1.3] pre-migration
2014-11-21 06:46:49,330 14870 INFO cms OpenUpgrade: base: pre-migration script called with version 5.0.1.1
2014-11-21 06:46:49,440 14870 DEBUG cms OpenUpgrade: Running UPDATE ir_module_module SET demo = false
2014-11-21 06:46:49,440 14870 DEBUG cms OpenUpgrade: 531 rows affected
2014-11-21 06:46:49,754 14870 ERROR cms openerp.sql_db: Programming error: relation "public.ir_act_client" does not exist
LINE 3:         WHERE inhrelid = 'public.ir_act_client'::regclass::o...
                                 ^
, in query 
        SELECT count(*) from pg_catalog.pg_inherits
        WHERE inhrelid = 'public.ir_act_client'::regclass::oid
        AND inhparent = 'public.ir_actions'::regclass::oid

2014-11-21 06:46:49,754 14870 ERROR cms OpenUpgrade: base: error in migration script /home/waqar/openupgrade/openupgrade-server/openerp/addons/base/migrations/7.0.1.3/pre-migration.py: relation "public.ir_act_client" does not exist
LINE 3:         WHERE inhrelid = 'public.ir_act_client'::regclass::o...
                                 ^

2014-11-21 06:46:49,755 14870 ERROR cms OpenUpgrade: relation "public.ir_act_client" does not exist
LINE 3:         WHERE inhrelid = 'public.ir_act_client'::regclass::o...
                                 ^
Traceback (most recent call last):
  File "/home/waqar/openupgrade/openupgrade-server/openerp/openupgrade/openupgrade.py", line 473, in wrapped_function
    func(cr, version)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/addons/base/migrations/7.0.1.3/pre-migration.py", line 228, in migrate
    update_base_sql(cr)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/addons/base/migrations/7.0.1.3/pre-migration.py", line 143, in update_base_sql
    """)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "public.ir_act_client" does not exist
LINE 3:         WHERE inhrelid = 'public.ir_act_client'::regclass::o...
                                 ^

2014-11-21 06:46:49,756 14870 ERROR cms openerp: Failed to initialize database `cms`.
Traceback (most recent call last):
  File "/home/waqar/openupgrade/openupgrade-server/openerp/cli/server.py", line 98, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname,update_module=update_module)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/modules/registry.py", line 192, in get
    update_module)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/modules/registry.py", line 218, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/modules/loading.py", line 331, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, registry=registry)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/modules/loading.py", line 172, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/waqar/openupgrade/openupgrade-server/openerp/modules/migration.py", line 191, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/openupgrade/openupgrade.py", line 473, in wrapped_function
    func(cr, version)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/addons/base/migrations/7.0.1.3/pre-migration.py", line 228, in migrate
    update_base_sql(cr)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/addons/base/migrations/7.0.1.3/pre-migration.py", line 143, in update_base_sql
    """)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/waqar/openupgrade/openupgrade-server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "public.ir_act_client" does not exist
LINE 3:         WHERE inhrelid = 'public.ir_act_client'::regclass::o...
                                 ^
# 

I dont know what mistake am I making, Kindly put me in the right direction.

Regards

**Comment by hbrunn** [comment]
What migrate.py hides from you is that for every version, you have to call openupgrade separately. That's why you should see also folders for 6 and 6.1 in your temp directory. What you currently do is to run the migration for 7.0 on a 5.0 database, that's not going to work.

But on the other hand, I'm not sure what you expect the migration process to do with your custom modules. If you didn't write any migration scripts for them yourself, nothing will happen. Probably it will be enough to use your migrated database from the first step and install your new modules there?

**Comment by Elchrif** [comment]
Hi,
plz i want to migrate the database from 6.1 to 8, using the file migrate.py, but i don't know the steps to execute the migrate.py, ple help me
