### ISSUE TITLE
[11.0] invalid syntax when I check Menu Items

### ISSUE THREAD

**Issue by AMhadhbi** [OCA/OpenUpgrade#1362]
Impacted versions:
11.0
Steps to reproduce:
Setting --> General Settings
Technical --> user interface --> **menu items**
Current behavior:
after migration to odoo 11, I check the view menu items but I found this issue 
```
2018-06-01 08:48:47,574 25194 INFO yarab odoo.modules.loading: Modules loaded.
2018-06-01 08:49:12,310 25194 INFO ? odoo.http: HTTP Configuring static files
2018-06-01 08:49:12,381 25194 INFO yarab odoo.addons.base.ir.ir_http: Generating routing map
2018-06-01 08:49:12,523 25194 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2018-06-01 08:49:44,701 25194 INFO yarab werkzeug: 10.0.0.1 - - [01/Jun/2018 08:49:44] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-06-01 08:49:47,590 25194 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database yarab because of modules to install/upgrade/remove.
2018-06-01 08:49:48,645 25194 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database yarab because of modules to install/upgrade/remove.
2018-06-01 08:49:52,417 25194 ERROR yarab odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/var/www/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/var/www/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/var/www/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.actions.actions', <function IrActions.get_bindings at 0x7fd424192510>, frozenset({1, 2, 3, 4, 6, 7, 8, 9, 10, 12, 17, 21, 22, 24, 25, 26, 27, 28, 33, 34, 35, 36, 38, 39, 40, 41, 43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 55, 58, 76, 77, 79, 84, 89}), 'ir.ui.menu')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/var/www/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fd40f74ba90>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/www/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/var/www/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/var/www/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/var/www/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/www/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/www/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/var/www/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/var/www/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/var/www/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/var/www/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/var/www/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/var/www/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/var/www/odoo/models.py", line 1282, in load_views
    for [v_id, v_type] in views
  File "/var/www/odoo/models.py", line 1282, in <dictcomp>
    for [v_id, v_type] in views
  File "/var/www/odoo/models.py", line 1374, in fields_view_get
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
  File "<decorator-gen-27>", line 2, in get_bindings
  File "/var/www/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/var/www/odoo/addons/base/ir/ir_actions.py", line 110, in get_bindings
    result[binding_type].append(action.read()[0])
  File "/var/www/odoo/models.py", line 2576, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/var/www/odoo/models.py", line 4729, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/var/www/odoo/fields.py", line 967, in __get__
    self.determine_value(record)
  File "/var/www/odoo/fields.py", line 1078, in determine_value
    self.compute_value(recs)
  File "/var/www/odoo/fields.py", line 1034, in compute_value
    self._compute_value(records)
  File "/var/www/odoo/fields.py", line 1025, in _compute_value
    getattr(records, self.compute)()
  File "/var/www/odoo/addons/base/ir/ir_actions.py", line 716, in _compute_params
    record.params = record_bin.params_store and safe_eval(record_bin.params_store, {'uid': self._uid})
  File "/var/www/odoo/tools/safe_eval.py", line 346, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/var/www/odoo/tools/safe_eval.py", line 205, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    {'header_description': u'General announces for all employees.', 'context': {'default_model': 'mail.group', 'search_default_message_unread': True, 'default_res_id': 1L}, 'res_model': 'mail.message', 'thread_level': 1, 'search_view_id': 202, 'domain': [('model', '=', 'mail.group'), ('res_id', '=', 1L)]}
                                                                                                                                                                         ^
SyntaxError: invalid syntax
2018-06-01 08:49:52,468 25194 INFO yarab werkzeug: 10.0.0.1 - - [01/Jun/2018 08:49:52] "POST /web/dataset/call_kw/ir.ui.menu/load_views HTTP/1.1" 200 -
```
I want to delete view or action related to old view not migrated to fix this issue. please need your feedback about this issue. Thanks

**Comment by pedrobaeza** [comment]
Have you made another update all with Odoo v11 loaded?

**Comment by AMhadhbi** [comment]
I use now the latest version in OpenUpgrade v11 also latest version openupgradelib.  so it is up to date. everything is ok on the migration just I have this issue when I check the menu items
 I use ./odoo-bin -u all -d yarab --stop-after-init to run the migration
after I run the database ./odoo-bin -d yarab with OpenUpgradev11.

**Comment by pedrobaeza** [comment]
You have to switch to Odoo/OCB once you have finished the migration and start service with it.

**Comment by AMhadhbi** [comment]
Alright, I will run the database with Odoo v11. I will let you know if the issue still exist.

**Comment by AMhadhbi** [comment]
I run the database with Odoov11 latest version with ./odoo-bin -u all but I receive the same issue when I check menu items.

**Comment by pedrobaeza** [comment]
Can you specify what "when I check menu items" means?

**Comment by AMhadhbi** [comment]
Steps to reproduce:
Setting --> General Settings Technical --> user interface --> menu items

**Comment by pedrobaeza** [comment]
But it's the rest working fine?

**Comment by AMhadhbi** [comment]
Yes the rest working fine just I have this issue

**Comment by pedrobaeza** [comment]
OK, although not critical, I will check when doing first full migration by my side.

**Comment by AMhadhbi** [comment]
when I check the log file  {'header_description': u'**General announces for all employees.'**, and this one related  to OpenERP v7. I search General announces for all employees and I found in addons mail version 7, take a look
![screen shot 2018-06-01 at 14 05 52](https://user-images.githubusercontent.com/10393083/40840121-aa875a74-65a5-11e8-82e5-0c3a51a69156.png)

**Comment by AMhadhbi** [comment]
and the origin of this database is database is version7, I migrate this database to v8 to v9 and v10 and then to v11.

**Comment by pedrobaeza** [comment]
Then it seems that is a renmant of these upgrades. I'm pretty sure I'm not going to be able to reproduce the problem. Can you simply remove that item?

**Comment by AMhadhbi** [comment]
which item ? I cant found it, sure I need to remove the view or action link to this record

**Comment by pedrobaeza** [comment]
Look for an action with that name.

**Comment by pedrobaeza** [comment]
Closing as no further action.

**Comment by luistriana28** [comment]
Same error from a DB updated from V7

File "/Users/Odoo/12.0/odoo/odoo/tools/safe_eval.py", line 205, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    {'header_description': u'General announces for all employees.', 'compose_placeholder': 'Send a message to the group', 'search_view_id': 198, 'context': {'default_model': 'mail.group', 'default_res_id': }, 'res_model': 'mail.message', 'thread_level': 1, 'domain': [('model', '=', 'mail.group'), ('res_id', '=', )], 'view_mailbox': True}
                                                                                                                                                                                                              ^
SyntaxError: invalid syntax

Looking for any actions and it doesn't show up.

Thanks for your help.
