### ISSUE TITLE
[9.0]  8 to 9 account.voucher can't use 

### ISSUE THREAD

**Issue by jaronemo** [OCA/OpenUpgrade#1366]
IntegrityError: update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
 Key (id)=(540) is still referenced from table "ir_ui_view".

8.0 view id=540 ---> Account.Voucher
why?
2018-06-06 01:04:31,762 20957 INFO TEST_migrated openerp.tools.translate: loading /var/tmp/openupgrade/9.0/addons/account_full_reconcile/i18n/zh_TW.po
2018-06-06 01:04:31,891 20957 INFO TEST_migrated openerp.modules.migration: module account_voucher: Running migration [>9.0.1.0] pre-migration
2018-06-06 01:04:31,891 20957 INFO TEST_migrated openerp.modules.migration: module account_voucher: Running migration [>9.0.1.0] pre-migration
2018-06-06 01:04:31,893 20957 INFO TEST_migrated OpenUpgrade: account_voucher: pre-migration script called with version 8.0.1.0
2018-06-06 01:04:32,055 20957 DEBUG TEST_migrated OpenUpgrade: Running 
                ALTER TABLE account_voucher
                ADD COLUMN openupgrade_legacy_9_0_type character varying;
                UPDATE account_voucher SET openupgrade_legacy_9_0_type=type;
                
2018-06-06 01:04:32,055 20957 DEBUG TEST_migrated OpenUpgrade: 7194 rows affected
2018-06-06 01:04:32,056 20957 INFO TEST_migrated OpenUpgrade: table account_voucher, column type: renaming to voucher_type
2018-06-06 01:04:32,061 20957 INFO TEST_migrated OpenUpgrade: table account_voucher_line, column amount: renaming to price_unit
2018-06-06 01:04:32,070 20957 INFO TEST_migrated openerp.sql_db: bad query:         DELETE FROM ir_ui_view
        WHERE name like '%account.voucher.payment%'
        
2018-06-06 01:04:32,070 20957 ERROR TEST_migrated OpenUpgrade: account_voucher: error in migration script account_voucher/migrations/9.0.1.0/pre-migration.py: IntegrityError('update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"\n\xe8\xa9\xb3\xe7\xb4\xb0\xe8\xb3\x87\xe6\x96\x99: Key (id)=(540) is still referenced from table "ir_ui_view".\n',)
2018-06-06 01:04:32,071 20957 ERROR TEST_migrated OpenUpgrade: update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
詳細資料: Key (id)=(540) is still referenced from table "ir_ui_view".
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1427, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/account_voucher/migrations/9.0.1.0/pre-migration.py", line 43, in migrate
    delete_payment_views(cr)
  File "/var/tmp/openupgrade/9.0/addons/account_voucher/migrations/9.0.1.0/pre-migration.py", line 32, in delete_payment_views
    """
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
詳細資料: Key (id)=(540) is still referenced from table "ir_ui_view".

**Comment by pedrobaeza** [comment]
That's because you have modules that extend the voucher on previous version. You should check that (and remove them on v8) or remove manually the views.

**Comment by StefanRijnhart** [comment]
That would be the case if this error occurred when the ORM tries to delete the views in the migration end stage, but in this case it is the migration script itself that causes the problem. It's not unreasonable for the migration script to remove depending views as well.

**Comment by StefanRijnhart** [comment]
https://github.com/OCA/OpenUpgrade/blob/9.0/addons/account_voucher/migrations/9.0.1.0/pre-migration.py#L30

**Comment by StefanRijnhart** [comment]
But yeah, it's still a valid workaround for @jaronemo to get his migration going.

**Comment by jaronemo** [comment]
I got it....Thank you!!
Currently trying again..
If want upgrade to v11 ....

need to 9.0 --> 10.0 --> 11.0 ? 
or can 8.0 ---> 11.0?

**Comment by pedrobaeza** [comment]
You have to pass by each step.

**Comment by pedrobaeza** [comment]
@NL66278 you made this script. Maybe you can fix the view removal part with what Stefan suggested.

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by NL66278** [comment]
@pedrobaeza and @StefanRijnhart It might not be impossible to write a script that builds a tree of all views that have certain views as a parent, or grandparent etc. and then delete them in the right order, but is is certainly a lot of work. I fear people with have to do with the workaround of de-installing modules that created the extra views.

**Comment by pedrobaeza** [comment]
Well, you can try to delete cascade those conflicting views.

**Comment by StefanRijnhart** [comment]
@pedrobaeza does that not leave lingering XML ids?

**Comment by StefanRijnhart** [comment]
Is it that much work to refactor the view deletion to also delete it's dependencies in one go? I don't think you have to delete them one by one.

**Comment by pedrobaeza** [comment]
@StefanRijnhart dangling XML-IDs can be later cleaned through database_cleanup. It's not the most important thing IMO.

**Comment by StefanRijnhart** [comment]
You are right. I see in the code that if an XML ID is left with an invalid res_id it is overwritten with a new record if it is encountered in a module that is upgraded later on.

**Comment by pedrobaeza** [comment]
Any news with this?

**Comment by StefanRijnhart** [comment]
Closing because apparently this is not a very common situation and the original poster solved this some other way.
