### ISSUE TITLE
[11.0] error migration database odoo v10 to v11  related to migration stock module

### ISSUE THREAD

**Issue by AMhadhbi** [OCA/OpenUpgrade#1377]
Impacted versions:
11.0
Steps to reproduce:
./odoo-bin --load=web --update=all  --stop-after-init -d yarab
Current behavior:
2018-06-19 11:51:48,089 3169 INFO yarab odoo.modules.migration: module stock: Running migration [$11.0.1.1] end-migration
2018-06-19 11:51:48,105 3169 INFO yarab OpenUpgrade: stock: end-migration script called with version 10.0.1.1
2018-06-19 11:51:48,917 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:48,936 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '35' of model 'stock.quant'
2018-06-19 11:51:49,010 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [1265, 3993, 28337]
2018-06-19 11:51:49,010 3169 DEBUG yarab OpenUpgrade: Deleted 3 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,024 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,049 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '36' of model 'stock.quant'
2018-06-19 11:51:49,081 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [4643, 5304, 6541]
2018-06-19 11:51:49,081 3169 DEBUG yarab OpenUpgrade: Deleted 3 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,092 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,122 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '37' of model 'stock.quant'
2018-06-19 11:51:49,153 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [83, 178, 29327]
2018-06-19 11:51:49,153 3169 DEBUG yarab OpenUpgrade: Deleted 3 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,167 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,200 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '38' of model 'stock.quant'
2018-06-19 11:51:49,252 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [89, 102, 163, 200, 390, 409, 1185, 1262]
2018-06-19 11:51:49,252 3169 DEBUG yarab OpenUpgrade: Deleted 8 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,266 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,294 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '39' of model 'stock.quant'
2018-06-19 11:51:49,325 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [158]
2018-06-19 11:51:49,325 3169 DEBUG yarab OpenUpgrade: Deleted 1 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,342 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,382 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '41' of model 'stock.quant'
2018-06-19 11:51:49,418 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [389, 408]
2018-06-19 11:51:49,418 3169 DEBUG yarab OpenUpgrade: Deleted 2 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,435 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,468 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '40' of model 'stock.quant'
2018-06-19 11:51:49,512 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [244, 381, 382, 384, 551, 554, 1959, 1961]
2018-06-19 11:51:49,512 3169 DEBUG yarab OpenUpgrade: Deleted 8 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,526 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,589 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '1846' of model 'stock.quant'
2018-06-19 11:51:49,658 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [2332, 2435, 2796, 2850, 3298, 3301, 3834, 3839, 3850, 5203, 5557, 5563, 6300, 6565, 6610, 6981, 6983, 6985, 6988, 7016, 7198]
2018-06-19 11:51:49,658 3169 DEBUG yarab OpenUpgrade: Deleted 21 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,670 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,696 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '1957' of model 'stock.quant'
2018-06-19 11:51:49,729 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [2832, 4720, 5586, 6760]
2018-06-19 11:51:49,729 3169 DEBUG yarab OpenUpgrade: Deleted 4 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,742 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,772 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '4109' of model 'stock.quant'
2018-06-19 11:51:49,807 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [4718, 6015, 6306, 6464, 6980, 8960]
2018-06-19 11:51:49,807 3169 DEBUG yarab OpenUpgrade: Deleted 6 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,820 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,854 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '1789' of model 'stock.quant'
2018-06-19 11:51:49,900 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [1888, 4719, 4722, 5204, 5222, 6307, 6310, 7257]
2018-06-19 11:51:49,900 3169 DEBUG yarab OpenUpgrade: Deleted 8 source record(s) of model 'stock.quant'
2018-06-19 11:51:49,915 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:49,950 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '4644' of model 'stock.quant'
2018-06-19 11:51:49,988 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [4755, 6296, 7611, 8959, 31431]
2018-06-19 11:51:49,988 3169 DEBUG yarab OpenUpgrade: Deleted 5 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,003 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:50,031 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '3285' of model 'stock.quant'
2018-06-19 11:51:50,060 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [3433, 4756]
2018-06-19 11:51:50,060 3169 DEBUG yarab OpenUpgrade: Deleted 2 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,078 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:50,117 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '1922' of model 'stock.quant'
2018-06-19 11:51:50,183 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [4757, 5736, 6542, 8087, 8131, 10888, 12890, 13429, 14060, 17935]
2018-06-19 11:51:50,183 3169 DEBUG yarab OpenUpgrade: Deleted 10 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,201 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:50,238 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '4160' of model 'stock.quant'
2018-06-19 11:51:50,286 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [4758, 7258, 8362, 8976, 9861, 29328, 32305]
2018-06-19 11:51:50,287 3169 DEBUG yarab OpenUpgrade: Deleted 7 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,306 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:50,348 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '1847' of model 'stock.quant'
2018-06-19 11:51:50,399 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [2266, 3299, 3304, 3851, 4759, 5050, 5735, 6122]
2018-06-19 11:51:50,399 3169 DEBUG yarab OpenUpgrade: Deleted 8 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,414 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:50,443 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '10889' of model 'stock.quant'
2018-06-19 11:51:50,481 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [11594, 12329, 12333, 17592, 22758]
2018-06-19 11:51:50,481 3169 DEBUG yarab OpenUpgrade: Deleted 5 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,499 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:50,533 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '12889' of model 'stock.quant'
2018-06-19 11:51:50,579 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [15508, 16712, 17803, 19012, 19899, 20225, 20935]
2018-06-19 11:51:50,580 3169 DEBUG yarab OpenUpgrade: Deleted 7 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,596 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:50,641 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '11062' of model 'stock.quant'
2018-06-19 11:51:50,698 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [11064, 11282, 15784, 17313, 17452, 29329]
2018-06-19 11:51:50,699 3169 DEBUG yarab OpenUpgrade: Deleted 6 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,823 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:50,858 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '12311' of model 'stock.quant'
2018-06-19 11:51:50,900 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [14061, 14932, 15785, 16427]
2018-06-19 11:51:50,900 3169 DEBUG yarab OpenUpgrade: Deleted 4 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,917 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:50,951 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '13016' of model 'stock.quant'
2018-06-19 11:51:50,981 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [13036]
2018-06-19 11:51:50,982 3169 DEBUG yarab OpenUpgrade: Deleted 1 source record(s) of model 'stock.quant'
2018-06-19 11:51:50,996 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:51,038 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '10744' of model 'stock.quant'
2018-06-19 11:51:51,114 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [10890, 11529, 11593, 12330, 12334, 12338, 13817, 13840, 14057, 14114, 14796, 15507, 15557, 16424, 16426, 16570, 17218, 18471]
2018-06-19 11:51:51,116 3169 DEBUG yarab OpenUpgrade: Deleted 18 source record(s) of model 'stock.quant'
2018-06-19 11:51:51,129 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:51,156 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '17591' of model 'stock.quant'
2018-06-19 11:51:51,187 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [18143, 19010]
2018-06-19 11:51:51,187 3169 DEBUG yarab OpenUpgrade: Deleted 2 source record(s) of model 'stock.quant'
2018-06-19 11:51:51,200 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:51,236 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '12328' of model 'stock.quant'
2018-06-19 11:51:51,277 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [12639, 12668, 14115, 14213, 16135, 17012, 17219]
2018-06-19 11:51:51,277 3169 DEBUG yarab OpenUpgrade: Deleted 7 source record(s) of model 'stock.quant'
2018-06-19 11:51:51,293 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:51,321 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '11063' of model 'stock.quant'
2018-06-19 11:51:51,358 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [12309, 16136, 16429, 17220]
2018-06-19 11:51:51,358 3169 DEBUG yarab OpenUpgrade: Deleted 4 source record(s) of model 'stock.quant'
2018-06-19 11:51:51,372 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:51,406 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '12120' of model 'stock.quant'
2018-06-19 11:51:51,462 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [12314, 14931, 14980, 15786, 15911, 15915, 15921, 16432, 16662, 17590, 18895]
2018-06-19 11:51:51,462 3169 DEBUG yarab OpenUpgrade: Deleted 11 source record(s) of model 'stock.quant'
2018-06-19 11:51:51,483 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:51,523 3169 DEBUG yarab OpenUpgrade: Write 2 value(s) in target record '11330' of model 'stock.quant'
2018-06-19 11:51:51,583 3169 INFO yarab odoo.models.unlink: User #1 deleted stock.quant records with IDs: [11919, 14243, 14704, 14925, 14930]
2018-06-19 11:51:51,583 3169 DEBUG yarab OpenUpgrade: Deleted 5 source record(s) of model 'stock.quant'
2018-06-19 11:51:51,604 3169 ERROR yarab odoo.osv.expression: Non-stored field stock.warn.insufficient.qty.scrap.quant_ids cannot be searched.
2018-06-19 11:51:51,640 3169 **ERROR** yarab **OpenUpgrade: stock: error in migration script stock/migrations/11.0.1.1/end-migration.py: ('An incoming date cannot be set to an untracked product.', None)**
2018-06-19 11:51:51,640 3169 ERROR yarab OpenUpgrade: ('An incoming date cannot be set to an untracked product.', None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/var/www/addons/stock/migrations/11.0.1.1/end-migration.py", line 31, in migrate
    merge_quants(env)
  File "/var/www/addons/stock/migrations/11.0.1.1/end-migration.py", line 25, in merge_quants
    env, 'stock.quant', quants[1:].ids, quants[0].id, QUANT_MERGE_OPS,
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade_merge_records.py", line 347, in merge_records
    _adjust_merged_values_orm(*args2)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade_merge_records.py", line 294, in _adjust_merged_values_orm
    target_record.write(new_vals)
  File "/var/www/odoo/models.py", line 3065, in write
    self._write(old_vals)
  File "/var/www/odoo/models.py", line 3231, in _write
    self._validate_fields(vals)
  File "/var/www/odoo/models.py", line 1023, in _validate_fields
    check(self)
  File "/var/www/addons/stock/models/stock_quant.py", line 86, in check_in_date
    raise ValidationError(_('An incoming date cannot be set to an untracked product.'))
odoo.exceptions.ValidationError: ('An incoming date cannot be set to an untracked product.', None)
2018-06-19 11:51:51,663 3169 WARNING yarab odoo.modules.loading: Transient module states were reset
2018-06-19 11:51:51,665 3169 ERROR yarab odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/www/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/www/odoo/modules/loading.py", line 428, in load_modules
    migrations.migrate_module(package, 'end')
  File "/var/www/odoo/modules/migration.py", line 174, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/var/www/addons/stock/migrations/11.0.1.1/end-migration.py", line 31, in migrate
    merge_quants(env)
  File "/var/www/addons/stock/migrations/11.0.1.1/end-migration.py", line 25, in merge_quants
    env, 'stock.quant', quants[1:].ids, quants[0].id, QUANT_MERGE_OPS,
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade_merge_records.py", line 347, in merge_records
    _adjust_merged_values_orm(*args2)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade_merge_records.py", line 294, in _adjust_merged_values_orm
    target_record.write(new_vals)
  File "/var/www/odoo/models.py", line 3065, in write
    self._write(old_vals)
  File "/var/www/odoo/models.py", line 3231, in _write
    self._validate_fields(vals)
  File "/var/www/odoo/models.py", line 1023, in _validate_fields
    check(self)
  File "/var/www/addons/stock/models/stock_quant.py", line 86, in check_in_date
    raise ValidationError(_('An incoming date cannot be set to an untracked product.'))
odoo.exceptions.ValidationError: ('An incoming date cannot be set to an untracked product.', None)
2018-06-19 11:51:51,667 3169 CRITICAL yarab odoo.service.server: Failed to initialize database `yarab`.
Traceback (most recent call last):
  File "/var/www/odoo/service/server.py", line 925, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/www/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/www/odoo/modules/loading.py", line 428, in load_modules
    migrations.migrate_module(package, 'end')
  File "/var/www/odoo/modules/migration.py", line 174, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/var/www/addons/stock/migrations/11.0.1.1/end-migration.py", line 31, in migrate
    merge_quants(env)
  File "/var/www/addons/stock/migrations/11.0.1.1/end-migration.py", line 25, in merge_quants
    env, 'stock.quant', quants[1:].ids, quants[0].id, QUANT_MERGE_OPS,
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade_merge_records.py", line 347, in merge_records
    _adjust_merged_values_orm(*args2)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade_merge_records.py", line 294, in _adjust_merged_values_orm
    target_record.write(new_vals)
  File "/var/www/odoo/models.py", line 3065, in write
    self._write(old_vals)
  File "/var/www/odoo/models.py", line 3231, in _write
    self._validate_fields(vals)
  File "/var/www/odoo/models.py", line 1023, in _validate_fields
    check(self)
  File "/var/www/addons/stock/models/stock_quant.py", line 86, in check_in_date
    raise ValidationError(_('An incoming date cannot be set to an untracked product.'))
odoo.exceptions.ValidationError: ('An incoming date cannot be set to an untracked product.', None)
2018-06-19 11:51:51,671 3169 INFO yarab odoo.service.server: Initiating shutdown
2018-06-19 11:51:51,671 3169 INFO yarab odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by pedrobaeza** [comment]
This is because there's a constraint about that in the old code of OpenUpgrade. @mreficent did you try to update with upstream code?

**Comment by MiquelRForgeFlow** [comment]
Not yet

**Comment by AMhadhbi** [comment]
@mreficent could you please update OpenUpgrade. thanks.

**Comment by AMhadhbi** [comment]
@pedrobaeza, Fixed after Update OpenUpgrade.

**Comment by pedrobaeza** [comment]
Fixed in #1398

**Comment by Rathnakreeswaran** [comment]
@pedrobaeza,@mreficent or any others kindly see this issue  #1506 and give possible solution
