### ISSUE TITLE
[11.0] KeyError: 'qty'

### ISSUE THREAD

**Issue by travish2** [OCA/OpenUpgrade#1433]
Impacted versions: 11

Steps to reproduce: Upgrading v10 -> v11
./odoo-bin -d database_v11 -u all --config=/odoo-10/OpenUpgrade.conf --stop-after-init

Current behavior: Errors out on a module with KeyError: 'qty' 
I am not sure which module it is, any ideas to track it down?

> 2018-07-06 07:03:59,681 449 INFO database_v11 odoo.models: Actual recompute of field ir.module.module.menus_by_module for 1 recs.
2018-07-06 07:03:59,969 449 WARNING database_v11 odoo.modules.loading: Transient module states were reset
2018-07-06 07:03:59,973 449 ERROR database_v11 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo-10/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo-10/OpenUpgrade/odoo/modules/loading.py", line 442, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/odoo-10/OpenUpgrade/odoo/modules/loading.py", line 328, in load_marked_modules
    upg_registry=upg_registry,
  File "/odoo-10/OpenUpgrade/odoo/modules/loading.py", line 159, in load_module_graph
    registry.setup_models(cr)
  File "/odoo-10/OpenUpgrade/odoo/modules/registry.py", line 277, in setup_models
    model._setup_fields()
  File "/odoo-10/OpenUpgrade/odoo/models.py", line 2429, in _setup_fields
    field.setup_full(self)
  File "/odoo-10/OpenUpgrade/odoo/fields.py", line 498, in setup_full
    self._setup_related_full(model)
  File "/odoo-10/OpenUpgrade/odoo/fields.py", line 535, in _setup_related_full
    field = target._fields[name]
KeyError: 'qty'
2018-07-06 07:03:59,977 449 CRITICAL database_v11 odoo.service.server: Failed to initialize database `database_v11`.
Traceback (most recent call last):
  File "/odoo-10/OpenUpgrade/odoo/service/server.py", line 925, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo-10/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo-10/OpenUpgrade/odoo/modules/loading.py", line 442, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/odoo-10/OpenUpgrade/odoo/modules/loading.py", line 328, in load_marked_modules
    upg_registry=upg_registry,
  File "/odoo-10/OpenUpgrade/odoo/modules/loading.py", line 159, in load_module_graph
    registry.setup_models(cr)
  File "/odoo-10/OpenUpgrade/odoo/modules/registry.py", line 277, in setup_models
    model._setup_fields()
  File "/odoo-10/OpenUpgrade/odoo/models.py", line 2429, in _setup_fields
    field.setup_full(self)
  File "/odoo-10/OpenUpgrade/odoo/fields.py", line 498, in setup_full
    self._setup_related_full(model)
  File "/odoo-10/OpenUpgrade/odoo/fields.py", line 535, in _setup_related_full
    field = target._fields[name]
KeyError: 'qty'
2018-07-06 07:03:59,980 449 INFO database_v11 odoo.service.server: Stopping gracefully

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This seems a custom module. Put a print statement in that line for seeing the model it belongs to before the error.

**Comment by travish2** [comment]
Hi Pedro thank you for the reply. Custom module makes sense but can you shed a little more light on where the print statement would go? I did not come across it in documentation.

**Comment by pedrobaeza** [comment]
I mean before this line so that you can figure out which model is trying to be accessed:

> File "/odoo-10/OpenUpgrade/odoo/fields.py", line 535, in _setup_related_full
> field = target._fields[name]
