### ISSUE TITLE
[11.0] TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by patel1008b** [OCA/OpenUpgrade#1450]
Impacted versions: OpenUpgrade from V10 to V11

try with solutions mention #716 

but still mention below error comes : 

Traceback (most recent call last):
  File "/var/tmp/openupgrade/11.0/server/odoo/service/server.py", line 925, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 442, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 328, in load_marked_modules
    upg_registry=upg_registry,
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 208, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/migration.py", line 174, in migrate_module
    migrate(self.cr, installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/11.0/addons/account/migrations/11.0.1.1/post-migration.py", line 182, in migrate
    fill_account_invoice_line_total(env)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1367, in wrapped_function
    return func(*args, **kwargs)
  File "/var/tmp/openupgrade/11.0/addons/account/migrations/11.0.1.1/post-migration.py", line 99, in fill_account_invoice_line_total
    partner=line.invoice_id.partner_id,
  File "/var/tmp/openupgrade/11.0/addons/account/models/account.py", line 973, in compute_all
    tax_amount = currency.round(tax_amount)
  File "/var/tmp/openupgrade/11.0/server/odoo/addons/base/res/res_currency.py", line 135, in round
    return tools.float_round(amount, precision_rounding=self.rounding)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/float_utils.py", line 73, in float_round
    normalized_value = value / rounding_factor # normalize
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by patel1008b** [comment]
with the lots of issues and no help get on proper time so dropped the migration plan.

**Comment by pedrobaeza** [comment]
OK, you should find the source of them, as this is working perfectly for me for a lot of migrations. Data consistency is important and that you have previously update your DB with latest version of code from N-1 version.
