### ISSUE TITLE
[11.0] odoo.exceptions.ValidationError: ("Invalid model name 'procurement.order' in action definition.", None)

### ISSUE THREAD

**Issue by patel1008b** [OCA/OpenUpgrade#1451]
Impacted versions: v10->v11

Error::

Traceback (most recent call last):
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/convert.py", line 748, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/convert.py", line 658, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/var/tmp/openupgrade/11.0/server/odoo/addons/base/ir/ir_model.py", line 1498, in _update
    record.write(values)
  File "/var/tmp/openupgrade/11.0/server/odoo/addons/base/ir/ir_actions.py", line 55, in write
    res = super(IrActions, self).write(vals)
  File "/var/tmp/openupgrade/11.0/server/odoo/models.py", line 3094, in write
    self._write(old_vals)
  File "/var/tmp/openupgrade/11.0/server/odoo/models.py", line 3260, in _write
    self._validate_fields(vals)
  File "/var/tmp/openupgrade/11.0/server/odoo/models.py", line 1040, in _validate_fields
    check(self)
  File "/var/tmp/openupgrade/11.0/server/odoo/addons/base/ir/ir_actions.py", line 131, in _check_model
    raise ValidationError(_('Invalid model name %r in action definition.') % action.src_model)
odoo.exceptions.ValidationError: ("Invalid model name 'procurement.order' in action definition.", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 442, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 328, in load_marked_modules
    upg_registry=upg_registry,
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 198, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/convert.py", line 795, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/convert.py", line 856, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/convert.py", line 755, in parse
    exc_info[2]
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/convert.py", line 748, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/convert.py", line 658, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/var/tmp/openupgrade/11.0/server/odoo/addons/base/ir/ir_model.py", line 1498, in _update
    record.write(values)
  File "/var/tmp/openupgrade/11.0/server/odoo/addons/base/ir/ir_actions.py", line 55, in write
    res = super(IrActions, self).write(vals)
  File "/var/tmp/openupgrade/11.0/server/odoo/models.py", line 3094, in write
    self._write(old_vals)
  File "/var/tmp/openupgrade/11.0/server/odoo/models.py", line 3260, in _write
    self._validate_fields(vals)
  File "/var/tmp/openupgrade/11.0/server/odoo/models.py", line 1040, in _validate_fields
    check(self)
  File "/var/tmp/openupgrade/11.0/server/odoo/addons/base/ir/ir_actions.py", line 131, in _check_model
    raise ValidationError(_('Invalid model name %r in action definition.') % action.src_model)
odoo.tools.convert.ParseError: "Invalid model name 'procurement.order' in action definition.
None" while parsing /var/tmp/openupgrade/11.0/addons/stock/wizard/stock_scheduler_compute_views.xml:20, near
<record id="action_procurement_compute" model="ir.actions.act_window">
        <field name="name">Run Scheduler</field>
        <field name="res_model">stock.scheduler.compute</field>
        <field name="view_type">form</field>
        <field name="view_mode">form</field>
        <field name="target">new</field>
    </record>

**Comment by pedrobaeza** [comment]
This has been already fixed.
