### ISSUE TITLE
[11.0] psycopg2.ProgrammingError: column l.amt_to_invoice does not exist

### ISSUE THREAD

**Issue by patel1008b** [OCA/OpenUpgrade#1452]
Impacted versions: v10 -> v11 : most migrations

Traceback (most recent call last):
  File "/mnt/hgfs/ws/odoo/odoo_v11/odoo/service/server.py", line 925, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/mnt/hgfs/ws/odoo/odoo_v11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/mnt/hgfs/ws/odoo/odoo_v11/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/mnt/hgfs/ws/odoo/odoo_v11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/mnt/hgfs/ws/odoo/odoo_v11/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/mnt/hgfs/ws/odoo/odoo_v11/odoo/modules/registry.py", line 317, in init_models
    self.check_tables_exist(cr)
  File "/mnt/hgfs/ws/odoo/odoo_v11/odoo/modules/registry.py", line 335, in check_tables_exist
    env[name].init()
  File "/mnt/hgfs/ws/odoo/odoo_v11/addons/sale/report/sale_report.py", line 131, in init
    )""" % (self._table, self._select(), self._from(), self._group_by()))
  File "/mnt/hgfs/ws/odoo/odoo_v11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/hgfs/ws/odoo/odoo_v11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column l.amt_to_invoice does not exist
LINE 27:                     sum(l.amt_to_invoice / COALESCE(cr.rate,...
                                 ^
HINT:  Perhaps you meant to reference the column "l.qty_to_invoice".

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by patel1008b** [comment]
with the lots of issues and no help get on proper time so droped the migration plan.

**Comment by hhgabelgaard** [comment]
I'm getting the same error on a v10->v11 migration

But I think the cause is an earlier error:

2018-12-29 17:15:52,474 1 INFO test odoo.modules.migration: module account_payment_mode: Running migration [>11.0.1.0.1] pre-migration
2018-12-29 17:15:52,474 1 ERROR test odoo.sql_db: bad query: b'ALTER TABLE res_partner_bank DROP COLUMN acc_type'
ERROR: column "acc_type" of relation "res_partner_bank" does not exist

res.partner.bank acc_type is a computed field in my v10 database - See https://github.com/OCA/bank-payment/pull/535 for a suggested fix
