### ISSUE TITLE
IntegrityError: update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"

### ISSUE THREAD

**Issue by pilyt** [OCA/OpenUpgrade#1472]
Hello,

I'm trying to migrate our base odoo 8 to 9. We are a small company and we do not have the means to call a specialist so I try to use openupgrade alone. I am hopeful because we use the basic features. The only OCA external module is account_auto_fy_sequence which is apparently supported and is no longer needed in version 9.
Unfortunately I encounter an error during the execution of the script.I'm pretty sure it's not a bug but probably a manipulation error or a misunderstanding on my part. I hope someone can help me a little.

**Impacted versions:**
9.0

**Steps to reproduce:**
Under ubuntu 12.04.
I had some problems with the git version and the lack of some python modules but it seems to be fixed. So I run:
```
wget https://raw.githubusercontent.com/OCA/OpenUpgrade/HEAD/scripts/migrate.py
service odoo stop
python ./migrate.py --database=MyCompanyBase --config=/etc/odoo/openerp-server.conf --run-migrations=9.0
```

**Current behavior:**

I get :
```
Depuis git://github.com/OpenUpgrade/OpenUpgrade
 * branch              9.0        -> FETCH_HEAD
Déjà à jour.
Depuis https://github.com/OCA/openupgradelib
 * branch            master     -> FETCH_HEAD
Déjà à jour.
copying database MyCompanyBase to MyCompanyBase_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
running migration for 9.0
Running as user 'root' is a security risk.
/usr/lib/python2.7/dist-packages/jinja2/loaders.py:214: UserWarning: Module openupgradelib was already imported from /var/tmp/openupgrade/openupgradelib/openupgradelib/__init__.pyc, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import DefaultProvider, ResourceManager, \
/usr/lib/python2.7/dist-packages/jinja2/loaders.py:214: UserWarning: Module openerp was already imported from /var/tmp/openupgrade/9.0/server/openerp/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import DefaultProvider, ResourceManager, \
Warn: Can't find .pfb for face 'Times-Roman'
Could not upgrade to version 9.0
```

In migration.log, the significant part seems to me to be at the end :
```
2018-08-08 12:43:54,697 12299 ERROR MyCompanyBase_migrated openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 214, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1439, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1219, in migrate
    move_view_accounts(env)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 289, in move_view_accounts
    WHERE %s = 'view'""", (AsIs(openupgrade.get_legacy_name('type')),)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 926, in logged_query
    cr.execute(query, args)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"
DETAIL:  Key (id)=(451) is still referenced from table "account_tax".

2018-08-08 12:43:54,697 12299 CRITICAL MyCompanyBase_migrated openerp.service.server: Failed to initialize database `MyCompanyBase_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 214, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1439, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1219, in migrate
    move_view_accounts(env)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 289, in move_view_accounts
    WHERE %s = 'view'""", (AsIs(openupgrade.get_legacy_name('type')),)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 926, in logged_query
    cr.execute(query, args)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"
DETAIL:  Key (id)=(451) is still referenced from table "account_tax".
```

**Expected behavior:**
An upgraded base ?

Thank you for reading to the end !
Pierre

**Comment by StefanRijnhart** [comment]
Hi Pierre, thank you for the detailed issue report. In the relevant code from the traceback, ledger accounts of type 'view' are removed as they serve no more purpose in the accounting after 8.0 (https://github.com/OCA/OpenUpgrade/blob/9.0/addons/account/migrations/9.0.1.1/post-migration.py#L288). The error that you submit above seems to imply that you have a tax that is configured to post move lines on a view account. That is obviously a configuration error but if the tax is unused it could have gone unnoticed easily. Can you check your tax configuration for this?

**Comment by pedrobaeza** [comment]
Closing as answered.

**Comment by pilyt** [comment]
Hi, thank you a lot @StefanRijnhart ! There were actually two taxes configured to use a view account. It was not used and I could change that easily. The migration of the base went well. I just have to test this new base.

**Comment by StefanRijnhart** [comment]
Thanks @piotrlyonnevitch for the follow up!

**Comment by daudakhtar** [comment]
verts@verts-Daud:/var/tmp/openupgrade/8.0/scripts$ python migrate.py –config=/opt/odoo/odoo_v8/odoo.conf –database=v7_migrate  –run-migrations=7.0,8.0 -help
Traceback (most recent call last):
  File "migrate.py", line 3, in <module>
    from future.utils import iteritems
ImportError: No module named future.utils

**Comment by daudakhtar** [comment]
Hello Sir

while i am trying to migrate my database from 7 to 8

#############ERROR############################
verts@verts-Daud:/var/tmp/openupgrade/8.0/scripts$ python migrate.py –-config=/etc/openerp-server.conf –-database=v7_migrate  --run-migrations=MIGRATIONS
Usage: migrate.py [options]

Migrate script for the impatient or lazy. Makes a copy of your database,
downloads the files necessary to migrate it as requested and runs the
migration on the copy (so your original database will not be touched). While
the migration is running only errors are shown, for a detailed log see
${branch-dir}/migration.log

Options:
  -h, --help            show this help message and exit
  -C CONFIG, --config=CONFIG
                        current openerp config (required)
  -D DATABASE, --database=DATABASE
                        current openerp database (required if not given in
                        config)
  -B BRANCH_DIR, --branch-dir=BRANCH_DIR
                        the directory to download openupgrade-server code to
                        [/var/tmp/openupgrade]
  -R MIGRATIONS, --run-migrations=MIGRATIONS
                        comma separated list of migrations to run, ie.
                        "10.0,11.0,6.0,6.1,7.0,8.0,9.0" (required)
  -A ADD, --add=ADD     load a python module that declares a dict 'migrations'
                        which is merged with the one of this script (see the
                        source for details). You also can pass a string that
                        evaluates to a dict. For the banking addons, pass
                        "{'6.1': {'addons': {'banking': 'lp:banking-
                        addons/6.1'}}}"
  -I, --inplace         don't copy database before attempting upgrade
                        (dangerous)
  -F FORCE_DEPS, --force-deps=FORCE_DEPS
                        force dependencies from a dict of the form
                        "{'module_name': ['new_dependency1',
                        'new_dependency2']}"
verts@verts-Daud:/var/tmp/openupgrade/8.0/scripts$ 


##########ERROR################################

actually i wanna migrate my erp7 database into odoo11, for this my first step was 7 to 8
