### ISSUE TITLE
8 to 9 "Cannot create unbalanced journal entry."

### ISSUE THREAD

**Issue by chiragbiz** [OCA/OpenUpgrade#1473]
When i try to migrating my odoo 8 database to odoo 9 i found below error: 
Can anybody help me please ???  

Steps to reproduce:  When migrate from 8 to 9

2018-08-09 11:11:07,214 29516 ERROR db_live1_migrated OpenUpgrade: account: error in migration script account/migrations/9.0.1.1/post-migration.py: UserError(u'Cannot create unbalanced journal entry.', None)
2018-08-09 11:11:07,215 29516 ERROR db_live1_migrated OpenUpgrade: (u'Cannot create unbalanced journal entry.', None)
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1439, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1225, in migrate
    fill_move_taxes(env)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 561, in fill_move_taxes
    _fill_aml_tax_line_ids(env, amls, row_base[1], tax_amounts)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 452, in _fill_aml_tax_line_ids
    lines_to_write.write({'tax_ids': [(4, tax_id)]})
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 1205, in write
    self.env['account.move'].browse(list(move_ids))._post_validate()
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 181, in _post_validate
    self.assert_balanced()
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 212, in assert_balanced
    raise UserError(_("Cannot create unbalanced journal entry."))
UserError: (u'Cannot create unbalanced journal entry.', None)
2018-08-09 11:11:07,219 29516 ERROR db_live1_migrated openerp.modules.loading: Error executing post migration script for module account
`-> account_accountant
`-> account_bank_statement_import
`-> account_cancel
`-> account_full_reconcile
`-> account_voucher
`-> payment
   `-> payment_transfer
   `-> portal_sale
: (u'Cannot create unbalanced journal entry.', None)
2018-08-09 11:11:07,254 29516 ERROR db_live1_migrated openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 214, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1439, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1225, in migrate
    fill_move_taxes(env)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 561, in fill_move_taxes
    _fill_aml_tax_line_ids(env, amls, row_base[1], tax_amounts)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 452, in _fill_aml_tax_line_ids
    lines_to_write.write({'tax_ids': [(4, tax_id)]})
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 1205, in write
    self.env['account.move'].browse(list(move_ids))._post_validate()
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 181, in _post_validate
    self.assert_balanced()
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 212, in assert_balanced
    raise UserError(_("Cannot create unbalanced journal entry."))
UserError: (u'Cannot create unbalanced journal entry.', None)
2018-08-09 11:11:07,255 29516 CRITICAL db_live1_migrated openerp.service.server: Failed to initialize database `db_live1_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 214, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1439, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1225, in migrate
    fill_move_taxes(env)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 561, in fill_move_taxes
    _fill_aml_tax_line_ids(env, amls, row_base[1], tax_amounts)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 452, in _fill_aml_tax_line_ids
    lines_to_write.write({'tax_ids': [(4, tax_id)]})
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 1205, in write
    self.env['account.move'].browse(list(move_ids))._post_validate()
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 181, in _post_validate
    self.assert_balanced()
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 212, in assert_balanced
    raise UserError(_("Cannot create unbalanced journal entry."))
UserError: (u'Cannot create unbalanced journal entry.', None)

**Comment by pedrobaeza** [comment]
OpenUpgrade is writing taxes on a journal entry that is unbalanced, and thus the error. Check this on your old v8 system.
