### ISSUE TITLE
7.0 to 8.0: Key (meeting_id)=(15) is not present in table "calendar_event"

### ISSUE THREAD

**Issue by mgielissen** [OCA/OpenUpgrade#150]
I've got this error with OpenUpgrade when upgrading from 7.0 to 8.0:

2014-12-04 12:19:03,586 8327 INFO xxxx openerp.modules.module: module hr_holidays: creating or updating database tables
2014-12-04 12:19:03,930 8327 ERROR xxxx openerp.sql_db: bad query: ALTER TABLE "hr_holidays" ADD FOREIGN KEY ("meeting_id") REFERENCES "calendar_event" ON DELETE set null
Traceback (most recent call last):
  File "/home/mario/z/8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "hr_holidays" violates foreign key constraint "hr_holidays_meeting_id_fkey"
DETAIL:  Key (meeting_id)=(15) is not present in table "calendar_event".

2014-12-04 12:19:03,931 8327 CRITICAL xxxx openerp.service.server: Failed to initialize database `xxxx`.
Traceback (most recent call last):
  File "/home/mario/z/8/openerp/service/server.py", line 906, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/mario/z/8/openerp/modules/registry.py", line 341, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/mario/z/8/openerp/modules/loading.py", line 354, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/mario/z/8/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/mario/z/8/openerp/modules/loading.py", line 163, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/mario/z/8/openerp/modules/module.py", line 290, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/home/mario/z/8/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/mario/z/8/openerp/models.py", line 2694, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/home/mario/z/8/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/mario/z/8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "hr_holidays" violates foreign key constraint "hr_holidays_meeting_id_fkey"
DETAIL:  Key (meeting_id)=(15) is not present in table "calendar_event".

**Comment by pedrobaeza** [comment]
Check this PR to see if that helps: #112

**Comment by hbrunn** [comment]
this error message was the exact reason for me to begin working on the calendar migration, so yes, I think that should fix the problem. Probably you want to merge in #130 too

**Comment by hbrunn** [comment]
as #112 is merged, this issue should be solved
