### ISSUE TITLE
[10.0] SQL error in hr_timesheet/migrations/10.0.1.0/pre-migration.py

### ISSUE THREAD

**Issue by hmartinet** [OCA/OpenUpgrade#1501]
A SQL Query try to use the column effective_hours, but this column is defined in Odoo 8.0 but not in 9.0 and 10.0. If the project module is installed by dependency from 9.0 this query will fail.

```
2018-08-28 16:59:23,852 27657 ERROR database OpenUpgrade: hr_timesheet: error in migration script hr_timesheet/migrations/10.0.1.0/pre-migration.py: ProgrammingError('column "effective_hours" does not exist\nLINE 2: ...ject_task SET children_hours=0, total_hours_spent=effective_...\n                                                             ^\n',)
2018-08-28 16:59:23,852 27657 ERROR database OpenUpgrade: column "effective_hours" does not exist
LINE 2: ...ject_task SET children_hours=0, total_hours_spent=effective_...
                                                             ^
Traceback (most recent call last):
  File "/.../openupgrade-migrate/workdir/openupgradelib/openupgradelib/openupgrade.py", line 1439, in wrapped_function
    if use_env2 else cr, version)
  File ".../openupgrade-migrate/workdir/10.0/addons/hr_timesheet/migrations/10.0.1.0/pre-migration.py", line 53, in migrate
    create_and_populate_children(env)
  File "/.../openupgrade-migrate/workdir/10.0/addons/hr_timesheet/migrations/10.0.1.0/pre-migration.py", line 46, in create_and_populate_children
    ''')
  File "/.../openupgrade-migrate/workdir/openupgradelib/openupgradelib/openupgrade.py", line 926, in logged_query
    cr.execute(query, args)
  File "/.../openupgrade-migrate/workdir/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/.../openupgrade-migrate/workdir/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "effective_hours" does not exist
LINE 2: ...ject_task SET children_hours=0, total_hours_spent=effective_...
```

**Comment by pedrobaeza** [comment]
OK, got it the problem: you haven't got installed `project` module. This commit fixes this situation:

https://github.com/OCA/OpenUpgrade/commit/e6928a68f605a537fe300af84d06c7542b73c2ac

**Comment by hmartinet** [comment]
@pedrobaeza Ok. Yes a workaround was to pre install manually project module before upgrade, Thanks for the fix.
