### ISSUE TITLE
 stock: error in migration script stock/migrations/11.0.1.1/post-migration.py: null value in column "responsible_id" violates not-null constraint

### ISSUE THREAD

**Issue by LeaderMalang** [OCA/OpenUpgrade#1503]
Impacted versions:11.0

Steps to reproduce:Simply trying to migrate from Odoo 10 to Odoo 11

Current behavior:
```
2018-08-30 17:56:26,511 9858 ERROR final_test_migrated_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 217, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1439, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/11.0/addons/stock/migrations/11.0.1.1/post-migration.py", line 215, in migrate
    product_assign_responsible(env)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1376, in wrapped_function
    return func(*args, **kwargs)
  File "/var/tmp/openupgrade/11.0/addons/stock/migrations/11.0.1.1/post-migration.py", line 55, in product_assign_responsible
    """
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 926, in logged_query
    cr.execute(query, args)
  File "/var/tmp/openupgrade/11.0/server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/11.0/server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "responsible_id" violates not-null constraint
DETAIL:  Failing row contains (12169, 0, 1.00, 0.00, 1, null, 1, 1, null, 2017-04-28 23:36:19.713065, null, t, 1, null, null, 1, null, 1, testing quotations not to be synced with opencart, null, 0, 2018-08-30 17:52:36.168802, t, f, test product sync, consu, null, 7, none, 1, t, receive, manual, order, f, cost, null, 10, null, null, null, f, 1, 1, null, t, f, null, f, null, null, null, null, null, order, no-message, null, null, null, null, no-message, null, empty, 0, null, null, null, null, null)
```

Expected behavior:it have to complete migration from odoo 10 to Odoo 11

**Comment by pedrobaeza** [comment]
That can only happen because you have a bad manipulated DB. Look at the code:

https://github.com/OCA/OpenUpgrade/blob/69e5edd7edbb6fd13dd686da225c6871bf67d093/addons/stock/migrations/11.0.1.1/post-migration.py#L54

The error arises if there are records without `create_uid` column set, which is not possible in a normal DB. Did you import products by SQL without filling that column?

Any way, closing as it's not a direct OpenUpgrade problem.
