### ISSUE TITLE
[11.0] SOLVED: KeyError: ('ir.actions.actions', <function IrActions.get_bindings at 0x7fefa83a08c8>, frozenset({}), 'account.move')

### ISSUE THREAD

**Issue by miquelalzanillas** [OCA/OpenUpgrade#1507]
**Impacted versions:**
11.0

**Steps to reproduce:**
Migration 8.0 -> 9.0 -> 10.0 -> 11.0

**Current behavior:**
Everything is working, except if you try to access to 'Accounting -> Account Moves' or you try to access to any account move from anywhere.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
**KeyError: ('ir.actions.actions', <function IrActions.get_bindings at 0x7fefa83a08c8>, frozenset({1, 2, 3, 131, 130, 6, 7, 8, 137, 10, 9, 13, 142, 15, 20, 21, 22, 23, 152, 155, 156, 29, 30, 157, 32, 28, 166, 39, 38, 170, 43, 44, 45, 53, 62, 63, 64, 67, 68, 78, 82, 87, 115, 116, 118, 119, 122}), 'account.move')**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fef86cbac88>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1295, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1295, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 119, in fields_view_get
    view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1387, in fields_view_get
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
  File "<decorator-gen-27>", line 2, in get_bindings
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions.py", line 120, in get_bindings
    result[binding_type].append(action.read()[0])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions.py", line 207, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2601, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4759, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions.py", line 167, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 760, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'import_wizard'
```

The account move ids indicated in the error doesn't exist in the database from v8 db, but this error only appears in v11

I opened this ticket in [Odoo](https://github.com/odoo/odoo/issues/26715) and was closed by @pedrobaeza as is not an Odoo error, but a migration.

Thanks a lot for your help Pedro, but I did the migration with Openupgrade and at this moment I not able to find a solution.

Maybe here I can get a bit light on it?

**Comment by pedrobaeza** [comment]
@zclick I'm afraid this is also not an OpenUpgrade thing, but a remaining of a custom module one. You had one module that adds a model called `import_wizard`, and now you don't have it, so the error is because of that. Clean the DB out of any trace of that model, or migrate the custom module to the target version.

**Comment by miquelalzanillas** [comment]
Hello Pedro,

Thanks a lot for you help.

This what I mean from the first, but there is not any model registered with this name in the DB.

Maybe there is some record pointing to this model but this model doesn't exist to in the DB. Do you know if there is any way to debug which record is pointing to it?

Thanks.

**Comment by pedrobaeza** [comment]
Look for the code in the old version to see which module declares that model.

**Comment by miquelalzanillas** [comment]
I just found the problem.

There were a custom action pointing to this model.

Thanks a lot for your help!

**Comment by mgielissen** [comment]
I've got the same error after migration to v12 (from v8 in the past). Deleting action windows 'account.move.line.reconcile' seems to solve the problem.

**Comment by pedrobaeza** [comment]
Can you point to the XML-ID of the record. Maybe it's one marked on noupdate and then the removal is not auto-performed. Other possibility is a reused XML record with a field that is not overwritten in new definition.

**Comment by mgielissen** [comment]
![afbeelding](https://user-images.githubusercontent.com/7700396/54497674-e0fb4480-48fd-11e9-9c63-0f3b2cdd91d4.png)

**Comment by pedrobaeza** [comment]
There's no XML-ID there... Can you see which one was in v8?

**Comment by mgielissen** [comment]
Extern ID | account.action_view_account_move_line_reconcile

**Comment by pedrobaeza** [comment]
I have searched and `action_view_account_move_line_reconcile` action window record has stayed unaltered during all the mentioned versions, only adding the field binding_model_id in 11.0, so on standard there's no possible error. Maybe a third party module that modified it?

**Comment by rubelhosen79** [comment]
Impacted vesion: 11.0

Getting below error when, try to upgrade the capacity analysis.




Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\cache.py", line 84, in lookup
    r = d[key]
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x02F7C978>, 'capacity_management.model_igw_automate')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 642, in _tag_record
    f_val = self.id_get(f_ref)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 727, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 733, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1334, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1323, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: capacity_management.model_igw_automate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-51>", line 2, in button_immediate_upgrade
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 603, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 751, in parse
    exc_info[2]
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 642, in _tag_record
    f_val = self.id_get(f_ref)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 727, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 733, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1334, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1323, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: capacity_management.model_igw_automate" while parsing file:/c:/program%20files%20(x86)/odoo%2011.0/server/addons/capacity_management/views/igw.xml:4, near
<record id="scheduler_igw_tps" model="ir.cron">
                <field name="name">IGW TPS</field>
                <field name="active" eval="True"/>
                <field name="user_id" ref="base.user_root"/>
                <field name="interval_number">5</field>
                <field name="interval_type">hours</field>
                <field name="numbercall">-1</field>
                <field name="doal">1</field>
                <field name="nextcall">2018-09-20 12:55:00</field>
                <field name="model_id" ref="model_igw_automate"/>
        	<field name="state">code</field>
        	<field name="code">model.process()</field>
        
                    
    </record>


Hello pedro, 
getting the above error 
Could you Please help me on this issue? @pedrobaeza 


Thanks.

**Comment by OthmaneGhandi** [comment]
> `action_view_account_move_line_reconcile`

@mgielissen I got the same issue, I couldn't open Journal Items I got an error related to account.move.line.reconcile and when removing the action, it seems now working. Even if it's weird as the Journal Items has its own action **action_account_moves_all_a**  

@pedrobaeza in V12 **action_view_account_move_line_reconcile** is used in **ir.actions.client** not **ir.actions.act_window**
