### ISSUE TITLE
Migrate 7.0 to 8.0 event_sale addon

### ISSUE THREAD

**Issue by ludogre** [OCA/OpenUpgrade#1511]
When migrating database 7.0 to 8.0, I have this error message in migration.log file:
```
[…]
2018-09-05 08:02:14,130 12037 INFO heureuxcyclage openerp.modules.module: module event_sale: creating or updating database tables
2018-09-05 08:02:14,583 12037 INFO heureuxcyclage openerp.modules.loading: loading event_sale/event_sale_view.xml
2018-09-05 08:02:14,897 12037 INFO heureuxcyclage openerp.modules.loading: loading event_sale/event_sale_data.xml
2018-09-05 08:02:15,101 12037 ERROR heureuxcyclage openerp.sql_db: bad query:  INSERT INTO product_supplier_taxes_rel (prod_id, tax_id)
                        (SELECT 114, unnest(ARRAY[5])) EXCEPT (SELECT prod_id, tax_id FROM product_supplier_taxes_rel WHERE prod_id=114)
                    
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  une instruction insert ou update sur la table « product_supplier_taxes_rel » viole la contrainte de clé
étrangère « product_supplier_taxes_rel_tax_id_fkey »
DÉTAIL : La clé (tax_id)=(5) n'est pas présente dans la table « account_tax ».

2018-09-05 08:02:15,102 12037 CRITICAL heureuxcyclage openerp.service.server: Failed to initialize database `heureuxcyclage`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 941, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 420, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 312, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 198, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 120, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 986, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 762, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_model.py", line 1086, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/addons/product/product.py", line 1200, in create
    return super(product_product, self).create(cr, uid, vals, context=ctx)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4143, in create
    record = self.browse(self._create(old_vals))
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4205, in _create
    record_id = self.pool[table].create(cr, user, tocreate[table], context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/addons/product/product.py", line 742, in create
    product_template_id = super(product_template, self).create(cr, uid, vals, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4143, in create
    record = self.browse(self._create(old_vals))
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4334, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/fields.py", line 1046, in set
    link(act[2])
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/fields.py", line 1016, in link
    cr.execute(query, (id, list(sub_ids), id))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ParseError: "ERREUR:  une instruction insert ou update sur la table \xab product_supplier_taxes_rel \xbb viole la contrainte de cl\xe9
\xe9trang\xe8re \xab product_supplier_taxes_rel_tax_id_fkey \xbb
D\xc9TAIL : La cl\xe9 (tax_id)=(5) n'est pas pr\xe9sente dans la table \xab account_tax \xbb.
" while parsing /var/tmp/openupgrade/8.0/addons/event_sale/event_sale_data.xml:9, near
<record id="product_product_event" model="product.product">
            <field name="list_price">10.0</field>
            <field name="event_ok" eval="True"/>
            <field name="standard_price">30.0</field>
            <field name="uom_id" ref="product.product_uom_unit"/>
            <field name="uom_po_id" ref="product.product_uom_unit"/>
            <field name="name">Event Subscription</field>
            <field name="categ_id" ref="product.product_category_all"/>
            <field name="type">service</field>
            <field name="event_type_id" ref="event_sale.event_type"/>
        </record>
2018-09-05 08:02:15,114 12037 INFO heureuxcyclage openerp.service.server: Initiating shutdown
2018-09-05 08:02:15,115 12037 INFO heureuxcyclage openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown
```
I know that event_sale addon is not already covered by OpenUpgrade. Maybe I can work about that with some help.

Thanks.

**Comment by pedrobaeza** [comment]
As said, the module is not covered, so it's normal that it fails. You need to follow DB changes for making the migration scripts. Look other migration scripts for the used techniques.
