### ISSUE TITLE
crm_meeting key error when migrate 7.0 to 8.0 hr_holidays addon

### ISSUE THREAD

**Issue by ludogre** [OCA/OpenUpgrade#1512]
When migrating 7.0 to 8.0 database, I've got this error:
```
[…]
2017-10-20 09:29:45,872 21732 INFO heureuxcyclage openerp.modules.migration: module hr_holidays: Running migration [>8.0.1.5] pre-migration
2017-10-20 09:29:45,872 21732 INFO heureuxcyclage openerp.modules.migration: module hr_holidays: Running migration [>8.0.1.5] pre-migration
2017-10-20 09:29:45,875 21732 INFO heureuxcyclage OpenUpgrade: hr_holidays: pre-migration script called with version 7.0.1.5
2017-10-20 09:29:45,907 21732 ERROR heureuxcyclage openerp.sql_db: bad query: update hr_holidays
        set meeting_id=calendar_event.id
        from calendar_event where meeting_id=openupgrade_legacy_8_0_crm_meeting_id
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  une instruction insert ou update sur la table « hr_holidays » viole la contrainte de clé
étrangère « hr_holidays_case_id_fkey »
DÉTAIL : La clé (meeting_id)=(33) n'est pas présente dans la table « crm_meeting ».

2017-10-20 09:29:45,907 21732 ERROR heureuxcyclage OpenUpgrade: hr_holidays: error in migration script hr_holidays/migrations/8.0.1.5/pre-migration.py: ERREUR:  une instruction insert ou update sur la table « hr_holidays » viole la contrainte de clé
étrangère « hr_holidays_case_id_fkey »
DÉTAIL : La clé (meeting_id)=(33) n'est pas présente dans la table « crm_meeting ».

2017-10-20 09:29:45,908 21732 ERROR heureuxcyclage OpenUpgrade: ERREUR:  une instruction insert ou update sur la table « hr_holidays » viole la contrainte de clé
étrangère « hr_holidays_case_id_fkey »
DÉTAIL : La clé (meeting_id)=(33) n'est pas présente dans la table « crm_meeting ».
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1250, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/8.0/addons/hr_holidays/migrations/8.0.1.5/pre-migration.py", line 34, in migrate
    openupgrade.get_legacy_name('crm_meeting_id'),
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  une instruction insert ou update sur la table « hr_holidays » viole la contrainte de clé
étrangère « hr_holidays_case_id_fkey »
DÉTAIL : La clé (meeting_id)=(33) n'est pas présente dans la table « crm_meeting ».

2017-10-20 09:29:45,909 21732 CRITICAL heureuxcyclage openerp.service.server: Failed to initialize database `heureuxcyclage`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 420, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 312, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 156, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1250, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/8.0/addons/hr_holidays/migrations/8.0.1.5/pre-migration.py", line 34, in migrate
    openupgrade.get_legacy_name('crm_meeting_id'),
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  une instruction insert ou update sur la table « hr_holidays » viole la contrainte de clé
étrangère « hr_holidays_case_id_fkey »
DÉTAIL : La clé (meeting_id)=(33) n'est pas présente dans la table « crm_meeting ».
```
To bypass this error, I execute this sql script before starting migration script:
```
DO
$do$
DECLARE
    i RECORD;
BEGIN
    FOR i IN SELECT id FROM calendar_event WHERE id NOT IN (SELECT id FROM crm_meeting) LOOP
        INSERT INTO crm_meeting (id, date, date_deadline, name) VALUES (i.id, '2000-01-01', '2000-01-01', 'Mig 8.0');
    END LOOP;
END
$do$;
```
It's just a trick to see the incidence in the migrate database.

Is someone knows a better way to fix this?

**Comment by pedrobaeza** [comment]
Closing as stalled.
