### ISSUE TITLE
KeyError: u'payment.mode' after migration from 8 to 9

### ISSUE THREAD

**Issue by FranciscoBigWings** [OCA/OpenUpgrade#1513]
Impacted versions: 8.0 to 9.0
Steps to reproduce: Try to open any contact company already imported within the migration. If I create a new contact and try to open it everything is fine

I did checked many times all the modules installed within 8.0 version and I didnt find any incompatibility

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade9/openerp/http.py", line 659, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/OpenUpgrade9/openerp/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/OpenUpgrade9/openerp/http.py", line 332, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/service/model.py", line 120, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/http.py", line 325, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/OpenUpgrade9/openerp/http.py", line 975, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/OpenUpgrade9/openerp/http.py", line 525, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/OpenUpgrade9/addons/web/controllers/main.py", line 897, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/OpenUpgrade9/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/partner-contact/partner_contact_in_several_companies/models/res_partner.py", line 82, in read
    return super(ResPartner, modified_self).read(fields=fields, load=load)
  File "/opt/odoo/OpenUpgrade9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/models.py", line 3287, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/OpenUpgrade9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/models.py", line 3465, in _read_from_database
    res2 = self._columns[fs[0]].get(cr, self._model, ids, fs, user, context=context, values=result)
  File "/opt/odoo/OpenUpgrade9/openerp/osv/fields.py", line 1541, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/OpenUpgrade9/openerp/osv/fields.py", line 1809, in _property_read
    values = ir_property.get_multi(cr, uid, prop_name, obj._name, ids, context=context)
  File "/opt/odoo/OpenUpgrade9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/addons/base/res/ir_property.py", line 182, in get_multi
    result[id] = self.get_by_record(prop)
  File "/opt/odoo/OpenUpgrade9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/OpenUpgrade9/openerp/addons/base/res/ir_property.py", line 122, in get_by_record
    value = self.pool[model].browse(cr, uid, int(resource_id), context=context)
  File "/opt/odoo/OpenUpgrade9/openerp/modules/registry.py", line 88, in __getitem__
    return self.models[model_name]
KeyError: u'payment.mode'

**Comment by StefanRijnhart** [comment]
Did you have account_payment installed? If you want to keep the functionality, have a look at https://github.com/OCA/bank-payment/tree/9.0. Including that in your addons path during and after the migration should provide a clean upgrade path, solving this problem.

Otherwise, go to settings -> technical -> company properties and remove the entries that have a value for  `resource` starting with 'payment.mode'.
