### ISSUE TITLE
[11] Point_of_sale Error after migration from V10C

### ISSUE THREAD

**Issue by E-HO** [OCA/OpenUpgrade#1626]
Hello,

Impacted versions: 11

Steps to reproduce: A database was running fine in V10C, small project with only basic features (sales, inventory, ...). Upgraded under a system up to date.

Current behavior:

Error when launching the point_of_sale : the modules are loaded normally but at the place of the POS interface the screen remains completely black.

First error : while trying to upgrade the point_of_sale module : 
> ...
File "/usr/local/src/Software-source/Software/tools/convert.py", line 832, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading point_of_sale failed: file point_of_sale/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'product.model_product_pricelist' in field 'Object'
Missing required value for the field 'Object' (model_id)
No matching record found for external id 'product.model_product_pricelist' in field 'Object'
Missing required value for the field 'Object' (model_id)

Second error : in the logs :
> `2018-... 2685 ERROR TEST odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/local/src/odoo-source/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/src/odoo-source/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/local/src/odoo-source/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/local/src/odoo-source/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/src/odoo-source/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/src/odoo-source/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/src/odoo-source/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/src/odoo-source/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/local/src/odoo-source/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/src/odoo-source/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable`

**Note :** a second migration from 10 to 11 made with another database gave the same results when trying to install the point of sale for the first time. But on the same system, making a fresh database from scratch give absolutely no error with the point of sale who is running fine.

**Comment by pedrobaeza** [comment]
Sorry, but these errors are something in your deployment, not OpenUpgrade's fault.
For 1, there are missing dependencies for sure.
For 2, check how you deploy your workers and proxy configuration.
