### ISSUE TITLE
Migration v10 to v11.

### ISSUE THREAD

**Issue by GoDjango** [OCA/OpenUpgrade#1627]
```Traceback (most recent call last):
  File "/home/openupgrade/ou-11.0/openupgrade/odoo/service/server.py", line 932, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/openupgrade/ou-11.0/openupgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openupgrade/ou-11.0/openupgrade/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/openupgrade/ou-11.0/openupgrade/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/openupgrade/ou-11.0/openupgrade/odoo/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/openupgrade/ou-11.0/openupgrade/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/openupgrade/ou-11.0/venv/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/home/openupgrade/ou-11.0/openupgrade/addons/project/migrations/11.0.1.1/pre-migration.py", line 34, in migrate
    openupgrade.delete_records_safely_by_xml_id(env, [
AttributeError: module 'openupgradelib.openupgrade' has no attribute 'delete_records_safely_by_xml_id'```

**Comment by pedrobaeza** [comment]
You should upgrade your openupgradelib library to latest one with pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master.

**Comment by GoDjango** [comment]
Thanks

**Comment by MRVov** [comment]
Thanks
