### ISSUE TITLE
[9.0] account_account_parent_id_fkey contraint not delete

### ISSUE THREAD

**Issue by stephanesalah** [OCA/OpenUpgrade#1641]
Impacted versions:
Migration fro 8.0 to 9.0

Steps to reproduce:
Launch a migration of a 8.0 database.

Current behavior:
migration log:
```
2018-12-01 14:46:24,916 15390 DEBUG prescom_mig_migrated OpenUpgrade: Running 
        ALTER TABLE account_account
        DROP CONSTRAINT account_account_parent_id_fkey
2018-12-01 14:46:24,917 15390 DEBUG prescom_mig_migrated OpenUpgrade: -1 rows affected
postgres log:
2018-12-01 15:24:51 CET [14704-19] stsal@prescom_mig_migrated ERROR:  constraint "account_account_parent_id_fkey" of relation "account_account" does not exist
2018-12-01 15:24:51 CET [14704-20] stsal@prescom_mig_migrated STATEMENT:  
                ALTER TABLE account_account
                DROP CONSTRAINT account_account_parent_id_fkey
control on postgresql console:
TABLE "account_account" CONSTRAINT "account_account_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES account_account(id) ON DELETE CASCADE
```
Expected behavior:
this constraint should be delete to permit 'view' type account unlink.
If i'm go on postgres console with the same user and execute 'ALTER TABLE ....' the request is ok.

I can not explain chat the matter

thanks for your help.

Stéphane

**Comment by pedrobaeza** [comment]
Please put full stack trace to see where this is originated. Any way, it seems some data inconsistency, like using a view account where is not valid (account.move.line, fiscal position account mapping...).

**Comment by stephanesalah** [comment]
hi ,
here the full migration log.

**and my test process on the migrated process**

prescom_mig_migrated=# delete from account_account where type = 'view';
ERROR:  update or delete on table "account_account" violates foreign key constraint "account_analytic_line_general_account_id_fkey" on table "account_analytic_line"
DETAIL:  Key (id)=(618) is still referenced from table "account_analytic_line".
prescom_mig_migrated=# ALTER TABLE account_account  DROP CONSTRAINT account_account_parent_id_fkey;
ALTER TABLE
prescom_mig_migrated=# delete from account_account where type = 'view';
DELETE 263

**full log error :** 

2018-12-03 08:32:46,389 8050 DEBUG prescom_mig_migrated OpenUpgrade: Running 
        ALTER TABLE account_account
        DROP CONSTRAINT account_account_parent_id_fkey
**2018-12-03 08:32:46,389 8050 DEBUG prescom_mig_migrated OpenUpgrade: -1 rows affected**
2018-12-03 08:32:48,305 8050 INFO prescom_mig_migrated openerp.sql_db: bad query: 
        DELETE FROM account_account
        WHERE openupgrade_legacy_9_0_type = 'view'
2018-12-03 08:32:48,305 8050 ERROR prescom_mig_migrated OpenUpgrade: Error running 
        DELETE FROM account_account
        WHERE openupgrade_legacy_9_0_type = 'view'
2018-12-03 08:32:48,305 8050 ERROR prescom_mig_migrated OpenUpgrade: account: error in migration script account/migrations/9.0.1.1/post-migration.py: IntegrityError('update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"\nDETAIL:  Key (id)=(451) is still referenced from table "account_tax".\n',)
2018-12-03 08:32:48,305 8050 ERROR prescom_mig_migrated OpenUpgrade: update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"
DETAIL:  Key (id)=(451) is still referenced from table "account_tax".
Traceback (most recent call last):
  File "/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1445, in wrapped_function
    if use_env2 else cr, version)
  File "/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1219, in migrate
    move_view_accounts(env)
  File "/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 289, in move_view_accounts
    WHERE %s = 'view'""", (AsIs(openupgrade.get_legacy_name('type')),)
  File "/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 929, in logged_query
    cr.execute(query, args)
  File "/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"
DETAIL:  Key (id)=(451) is still referenced from table "account_tax".

2018-12-03 08:32:48,305 8050 ERROR prescom_mig_migrated openerp.modules.loading: Error executing post migration script for module account
`-> account_bank_statement_import
`-> account_full_reconcile
`-> account_voucher
`-> base_iban
`-> base_vat
   `-> l10n_fr
`-> payment
   `-> payment_transfer
   `-> portal_sale
: update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"
DETAIL:  Key (id)=(451) is still referenced from table "account_tax".

2018-12-03 08:32:48,323 8050 ERROR prescom_mig_migrated openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 214, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1445, in wrapped_function
    if use_env2 else cr, version)
  File "/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1219, in migrate
    move_view_accounts(env)
  File "/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 289, in move_view_accounts
    WHERE %s = 'view'""", (AsIs(openupgrade.get_legacy_name('type')),)
  File "/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 929, in logged_query
    cr.execute(query, args)
  File "/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"
DETAIL:  Key (id)=(451) is still referenced from table "account_tax".

2018-12-03 08:32:48,323 8050 CRITICAL prescom_mig_migrated openerp.service.server: Failed to initialize database `prescom_mig_migrated`.
Traceback (most recent call last):
  File "/tmp/openupgrade/9.0/server/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 214, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1445, in wrapped_function
    if use_env2 else cr, version)
  File "/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1219, in migrate
    move_view_accounts(env)
  File "/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 289, in move_view_accounts
    WHERE %s = 'view'""", (AsIs(openupgrade.get_legacy_name('type')),)
  File "/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 929, in logged_query
    cr.execute(query, args)
  File "/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
**IntegrityError: update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"
DETAIL:  Key (id)=(451) is still referenced from table "account_tax".**

2018-12-03 08:32:48,324 8050 INFO prescom_mig_migrated openerp.service.server: Initiating shutdown
2018-12-03 08:32:48,324 8050 INFO prescom_mig_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by pedrobaeza** [comment]
Then it's the said problem: you have at least one account of type view assigned in one tax, so you should solve this in your v8 DB.

**Comment by stephanesalah** [comment]
ohhhh fine, thank you !!

i will correct it directlly
is there a good method to add pre migration script on openupgrade ?

thanks for all
stéphane

**Comment by pedrobaeza** [comment]
I don't get your question.

**Comment by stephanesalah** [comment]
in my upgrade project my 1st step will be to correct all the data bug present.
 with your experience is there a good method to implement this type of script

for the moment, i will create an sql script to update database.
thanks for all

**Comment by pedrobaeza** [comment]
As said, this is something incorrect even for v8, so you should fix it directly there, not on a pre-phase, and no, it doesn't exist anything apart for pre-, post- migration scripts.

**Comment by stephanesalah** [comment]
ok thanks for your help.
