### ISSUE TITLE
9.0 to 10.0 Database Upgrade Bad Query Error

### ISSUE THREAD

**Issue by glrangel** [OCA/OpenUpgrade#1653]
Hello,

This isn't a bug, I just need some help. I am using the migrate.py script updating my v9 database to v10. Does a bad query imply that I am missing a column in my db? If so how would I go about fixing it. I am new to the odoo community and any help would be appreciated, thank you!

Current behavior:
```
INFO db-9.0_migrated odoo.sql_db: bad query: DELETE FROM ir_model WHERE model = 'mrp.workorder'
2018-12-07 19:15:46,040 20356 ERROR db-9.0_migrated OpenUpgrade: mrp: error in migration script mrp/migrations/10.0.2.0/pre-migration.py: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n',)
2018-12-07 19:15:46,040 20356 ERROR db-9.0_migrated OpenUpgrade: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1445, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/mrp/migrations/10.0.2.0/pre-migration.py", line 162, in migrate
    rename_mrp_workorder(cr)
  File "/var/tmp/openupgrade/10.0/addons/mrp/migrations/10.0.2.0/pre-migration.py", line 129, in rename_mrp_workorder
    delete_old_workorder_model(cr)
  File "/var/tmp/openupgrade/10.0/addons/mrp/migrations/10.0.2.0/pre-migration.py", line 78, in delete_old_workorder_model
    ('mrp.workorder',)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 929, in logged_query
    cr.execute(query, args)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

>2018-12-07 19:15:46,079 20356 INFO db-9.0_migrated odoo.sql_db: bad query: DELETE FROM ir_model WHERE model = 'mrp.workorder'
2018-12-07 19:15:46,084 20356 INFO db-9.0_migrated odoo.sql_db: Connection to the database failed
2018-12-07 19:15:46,085 20356 ERROR db-9.0_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/private/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.reset_modules_state(db_name)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 581, in reset_modules_state
    with db.cursor() as cr:
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 635, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 177, in __init__
    self._cnx = pool.borrow(dsn)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 518, in _locked
    return fun(self, *args, **kwargs)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 586, in borrow
    **connection_info)
  File "/Users/TheShire/anaconda/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL:  the database system is in recovery mode

>2018-12-07 19:15:46,158 20356 CRITICAL db-9.0_migrated odoo.service.server: Failed to initialize database `db-9.0_migrated`.
Traceback (most recent call last):
  File "/private/var/tmp/openupgrade/10.0/server/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.reset_modules_state(db_name)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 581, in reset_modules_state
    with db.cursor() as cr:
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 635, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 177, in __init__
    self._cnx = pool.borrow(dsn)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 518, in _locked
    return fun(self, *args, **kwargs)
  File "/private/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 586, in borrow
    **connection_info)
  File "/Users/TheShire/anaconda/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL:  the database system is in recovery mode
2018-12-07 19:15:46,159 20356 INFO db-9.0_migrated odoo.service.server: Initiating shutdown
```
Expected behavior: 
Successful upgrade from v9 to v10.

**Comment by pedrobaeza** [comment]
Sorry, but that trace has nothing to do with OpenUpgrade, but with Postgres being incorrect. If there are no previous error that can lead to this, you should check your deployment processes.

Closing as no issue and not possible to help in unrelated things.
