### ISSUE TITLE
[12.0] could not create unique index "ir_translation_unique"

### ISSUE THREAD

**Issue by mgielissen** [OCA/OpenUpgrade#1672]
I tried to migrate a production database (11.0, migrated in the past from 8.0) to 12.0 and got this error (the key is randomly):

2019-01-02 22:35:38,462 11540 INFO prod_migrated odoo.modules.registry: module base: creating or updating database tables
2019-01-02 22:35:39,328 11540 ERROR prod_migrated odoo.sql_db: bad query: b'CREATE UNIQUE INDEX "ir_translation_unique" ON "ir_translation" (type, name, lang, res_id, md5(src))'
ERROR: could not create unique index "ir_translation_unique"
DETAIL:  Key (type, name, lang, res_id, md5(src))=(field, sale.order.line,product_tmpl_id, nl_NL, 0, 9a1d6522e61266f6da2f9754109b8c46) is duplicated.

2019-01-02 22:35:39,331 11540 WARNING prod_migrated odoo.modules.loading: Transient module states were reset
2019-01-02 22:35:39,332 11540 ERROR prod_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 414, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 224, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 296, in init_models
    model._auto_init()
  File "/var/tmp/openupgrade/12.0/server/odoo/addons/base/models/ir_translation.py", line 278, in _auto_init
    ['type', 'name', 'lang', 'res_id', 'md5(src)'])
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/sql.py", line 205, in create_unique_index
    cr.execute('CREATE UNIQUE INDEX "{}" ON "{}" ({})'.format(indexname, tablename, args))
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: could not create unique index "ir_translation_unique"
DETAIL:  Key (type, name, lang, res_id, md5(src))=(field, sale.order.line,product_tmpl_id, nl_NL, 0, 9a1d6522e61266f6da2f9754109b8c46) is duplicated.

2019-01-02 22:35:39,334 11540 CRITICAL prod_migrated odoo.service.server: Failed to initialize database `prod_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/service/server.py", line 1042, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 414, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 224, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 296, in init_models
    model._auto_init()
  File "/var/tmp/openupgrade/12.0/server/odoo/addons/base/models/ir_translation.py", line 278, in _auto_init
    ['type', 'name', 'lang', 'res_id', 'md5(src)'])
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/sql.py", line 205, in create_unique_index
    cr.execute('CREATE UNIQUE INDEX "{}" ON "{}" ({})'.format(indexname, tablename, args))
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: could not create unique index "ir_translation_unique"
DETAIL:  Key (type, name, lang, res_id, md5(src))=(field, sale.order.line,product_tmpl_id, nl_NL, 0, 9a1d6522e61266f6da2f9754109b8c46) is duplicated.

**Comment by mgielissen** [comment]
I've tried the nuclear option: **drop table ir_translation** and DB upgrade -all (ir_translation is recreated). Now OpenUpgrades seems to move on.

**Comment by pedrobaeza** [comment]
@mgielissen you have this specific code:

https://github.com/OCA/OpenUpgrade/blob/a858e8657caab9d924e925e2a00ac285c47d2207/odoo/addons/base/migrations/12.0.1.3/pre-migration.py#L48

for that purpose

Is it being executed?

**Comment by mgielissen** [comment]
It's being executed but still get dupliced errors when running the migration script. I did manually run the sql queries and there are no duplicates.

**Comment by pedrobaeza** [comment]
So you are saying that the duplicates happen between the execution of this and the error?

Full migration log would be very helpful.

**Comment by mgielissen** [comment]
Before the migration I run the sql queries manually, several records where deletes.
```
2019-01-03 12:55:52,317 29069 DEBUG prod_migrated OpenUpgrade: 1 rows affected
2019-01-03 12:55:52,317 29069 DEBUG prod_migrated OpenUpgrade: Running UPDATE ir_model_data SET module = uom, name = product_uom_gal WHERE module = product and name = product_uom_gal
2019-01-03 12:55:52,317 29069 DEBUG prod_migrated OpenUpgrade: 1 rows affected
2019-01-03 12:55:52,396 29069 DEBUG prod_migrated OpenUpgrade: Running  DELETE FROM ir_translation WHERE id IN (
        SELECT it2.id FROM ir_translation it1
        JOIN ir_translation it2 ON it1.type = 'code'
            AND it1.type = it2.type
            AND it1.src = it2.src
            AND it1.lang = it2.lang
            AND it1.id < it2.id);
2019-01-03 12:55:52,397 29069 DEBUG prod_migrated OpenUpgrade: 0 rows affected
2019-01-03 12:55:52,886 29069 DEBUG prod_migrated OpenUpgrade: Running  DELETE FROM ir_translation WHERE id IN (
        SELECT it2.id FROM ir_translation it1
        JOIN ir_translation it2 ON it1.type = 'model'
            AND it1.type = it2.type
            AND it1.name = it2.name
            AND it1.res_id = it2.res_id
            AND it1.lang = it2.lang
            AND it1.id < it2.id);
2019-01-03 12:55:52,887 29069 DEBUG prod_migrated OpenUpgrade: 0 rows affected
2019-01-03 12:55:52,965 29069 DEBUG prod_migrated OpenUpgrade: Running  DELETE FROM ir_translation WHERE id IN (
        SELECT it2.id FROM ir_translation it1
        JOIN ir_translation it2 ON it1.type IN
                ('selection', 'constraint', 'sql_constraint')
            AND it1.type = it2.type
            AND it1.name = it2.name
            AND it1.src = it2.src
            AND it1.lang = it2.lang
            AND it1.id < it2.id);
2019-01-03 12:55:52,965 29069 DEBUG prod_migrated OpenUpgrade: 0 rows affected
2019-01-03 12:55:52,969 29069 DEBUG prod_migrated OpenUpgrade: Running ALTER TABLE ir_translation
        DROP CONSTRAINT ir_translation_lang_fkey_res_lang

2019-01-03 12:55:52,970 29069 DEBUG prod_migrated OpenUpgrade: -1 rows affected
2019-01-03 12:55:52,970 29069 INFO prod_migrated OpenUpgrade: table res_company, column external_report_layout: renaming to openupgrade_legacy_12_0_external_report_layout
2019-01-03 12:55:53,297 29069 INFO prod_migrated odoo.modules.registry: module base: creating or updating database tables
2019-01-03 12:55:54,297 29069 ERROR prod_migrated odoo.sql_db: bad query: b'CREATE UNIQUE INDEX "ir_translation_unique" ON "ir_translation" (type, name, lang, res_id, md5(src))'
ERROR: could not create unique index "ir_translation_unique"
DETAIL:  Key (type, name, lang, res_id, md5(src))=(view, stock.warehouse.orderpoint, nl_NL, 0, 6416e8cb5fc0a208d94fa7f5a300dbc4) is duplicated.

2019-01-03 12:55:54,300 29069 WARNING prod_migrated odoo.modules.loading: Transient module states were reset
2019-01-03 12:55:54,301 29069 ERROR prod_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 414, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 224, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 296, in init_models
    model._auto_init()
  File "/var/tmp/openupgrade/12.0/server/odoo/addons/base/models/ir_translation.py", line 278, in _auto_init
    ['type', 'name', 'lang', 'res_id', 'md5(src)'])
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/sql.py", line 205, in create_unique_index
    cr.execute('CREATE UNIQUE INDEX "{}" ON "{}" ({})'.format(indexname, tablename, args))
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: could not create unique index "ir_translation_unique"
DETAIL:  Key (type, name, lang, res_id, md5(src))=(view, stock.warehouse.orderpoint, nl_NL, 0, 6416e8cb5fc0a208d94fa7f5a300dbc4) is duplicated.

2019-01-03 12:55:54,303 29069 CRITICAL prod_migrated odoo.service.server: Failed to initialize database `prod_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/service/server.py", line 1042, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 414, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 224, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 296, in init_models
    model._auto_init()
  File "/var/tmp/openupgrade/12.0/server/odoo/addons/base/models/ir_translation.py", line 278, in _auto_init
    ['type', 'name', 'lang', 'res_id', 'md5(src)'])
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/sql.py", line 205, in create_unique_index
    cr.execute('CREATE UNIQUE INDEX "{}" ON "{}" ({})'.format(indexname, tablename, args))
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: could not create unique index "ir_translation_unique"
DETAIL:  Key (type, name, lang, res_id, md5(src))=(view, stock.warehouse.orderpoint, nl_NL, 0, 6416e8cb5fc0a208d94fa7f5a300dbc4) is duplicated.
```

**Comment by pedrobaeza** [comment]
@StefanRijnhart maybe your code leaves any possible duplicate translation?

**Comment by mgielissen** [comment]
This PR fixes the problem https://github.com/OCA/OpenUpgrade/pull/1767
