### ISSUE TITLE
After migrate from 7.0 to 8.0: ValueError: Wrong value for res.users.notify_email: u'email'

### ISSUE THREAD

**Issue by Arcaudas** [OCA/OpenUpgrade#169]
After a migration all almost seems to be right, but when I go to view the profile of any user (included the Admin) Odoo shows the next error:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 539, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 292, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 755, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 388, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 932, in _call_kw
    records = getattr(request.session.model(model), method)(_args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 859, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/res/res_users.py", line 869, in read
    res = super(users_view, self).read(cr, uid, ids, other_fields, context=context, load=load)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/res/res_users.py", line 295, in read
    result = super(res_users, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3083, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3126, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/opt/odoo/odoo-server/openerp/models.py", line 5492, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo-server/openerp/fields.py", line 774, in **get**
    self.determine_value(record)
  File "/opt/odoo/odoo-server/openerp/fields.py", line 876, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/odoo-server/openerp/fields.py", line 832, in compute_value
    self._compute_value(records)
  File "/opt/odoo/odoo-server/openerp/fields.py", line 824, in _compute_value
    self.compute(records)
  File "/opt/odoo/odoo-server/openerp/fields.py", line 497, in _compute_related
    record[self.name] = other[self.related[-1]]
  File "/opt/odoo/odoo-server/openerp/models.py", line 5501, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/opt/odoo/odoo-server/openerp/fields.py", line 790, in **set**
    value = self.convert_to_cache(value, record)
  File "/opt/odoo/odoo-server/openerp/fields.py", line 1320, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.users.notify_email: u'email'

**Comment by pedrobaeza** [comment]
That it's because mail migration is not yet completed. Current work is being discused here: https://github.com/OpenUpgrade/OpenUpgrade/pull/116

**Comment by Arcaudas** [comment]
Thanks
I'll wait.

**Comment by pedrobaeza** [comment]
Or review current PR...

**Comment by Arcaudas** [comment]
Sorry, I don't understand what can I do.

**Comment by pedrobaeza** [comment]
You can propose a fix according the discussion.

**Comment by Arcaudas** [comment]
Ah, ok.
But is necessary knowledge about programming with Odoo, I presume. 
Isn't it?

**Comment by pedrobaeza** [comment]
Yeah, that's it

**Comment by StefanRijnhart** [comment]
Fixed in #116, which is now merged.

**Comment by ShrikrishnaPatil** [comment]
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/account/models/account_invoice.py", line 361, in create
    invoice = super(AccountInvoice, self.with_context(mail_create_nolog=True)).create(vals)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/addons/product/product.py", line 1184, in create
    product_id = super(product_product, self).create(cr, uid, vals, context=ctx)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 235, in create
    thread = super(MailThread, self).create(values)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4174, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4236, in _create
    record_id = self.pool[table].create(cr, user, tocreate[table], context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/stock_account/product.py", line 76, in create
    return super(product_template, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/product/product.py", line 675, in create
    product_template_id = super(product_template, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 235, in create
    thread = super(MailThread, self).create(values)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4174, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4300, in _create
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 2254, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/opt/odoo/openerp/fields.py", line 1545, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for product.template.type: u'out_invoice'




helme

**Comment by StefanRijnhart** [comment]
ShrikrishnaPatil if you think this is related to OpenUpgrade (rather than just Odoo), please create a new issue. However, it looks like insufficient context sanitation, so that the default_type value is passed to the product creation, containing a value that is only valid for the invoice.
