### ISSUE TITLE
[11.0] stock: Error  Error executing post migration script for module stock `-> mrp : column t.route_sequence_moved0 does not exist

### ISSUE THREAD

**Issue by fordonez-zabyca** [OCA/OpenUpgrade#1709]
Impacted versions:
11.0

Steps to reproduce:
python3 migrate.py --config="/home/eclipse-workspace/odoo9-fm/odoo9ee-fm.conf" --database=macroquil_20190129_10_migrated --run-migrations=11.0

Current behavior:
2019-01-30 12:45:58,951 18365 DEBUG macroquil_20190129_10_migrated OpenUpgrade: Running 
        UPDATE stock_move
        SET reference = name
        WHERE picking_id IS NULL
2019-01-30 12:45:58,951 18365 DEBUG macroquil_20190129_10_migrated OpenUpgrade: 195 rows affected
2019-01-30 12:46:01,563 18365 DEBUG macroquil_20190129_10_migrated OpenUpgrade: Running 
        UPDATE stock_move sm
        SET reference = sp.name
        FROM stock_picking sp
        WHERE sm.picking_id = sp.id
2019-01-30 12:46:01,563 18365 DEBUG macroquil_20190129_10_migrated OpenUpgrade: 9719 rows affected
2019-01-30 12:46:01,563 18365 INFO macroquil_20190129_10_migrated OpenUpgrade: Executing method compute_picking_scheduled_date
2019-01-30 12:46:01,769 18365 DEBUG macroquil_20190129_10_migrated OpenUpgrade: Running 
        UPDATE stock_picking sp
        SET scheduled_date = sub.date_expected
        FROM (
            SELECT sm.picking_id,
                CASE WHEN sp.move_type = 'direct'
                THEN MIN(sm.date_expected)
                ELSE MAX(sm.date_expected)
                END AS date_expected
            FROM stock_move sm, stock_picking sp
            WHERE sm.picking_id = sp.id
            GROUP BY sm.picking_id, sp.move_type
        ) AS sub
        WHERE sub.picking_id = sp.id
2019-01-30 12:46:01,770 18365 DEBUG macroquil_20190129_10_migrated OpenUpgrade: 978 rows affected
2019-01-30 12:46:01,770 18365 INFO macroquil_20190129_10_migrated OpenUpgrade: Executing method product_assign_responsible
2019-01-30 12:46:01,845 18365 DEBUG macroquil_20190129_10_migrated OpenUpgrade: Running 
        UPDATE product_template
        SET responsible_id = create_uid
        
2019-01-30 12:46:01,845 18365 DEBUG macroquil_20190129_10_migrated OpenUpgrade: 2854 rows affected
2019-01-30 12:46:01,845 18365 INFO macroquil_20190129_10_migrated OpenUpgrade: **Executing method create_specific_procurement_rules_from_globals**
2019-01-30 12:46:01,851 18365 ERROR macroquil_20190129_10_migrated odoo.sql_db: bad query: b'\n            INSERT INTO procurement_rule\n            (create_uid, create_date, name, sequence, company_id, write_uid, action, write_date, active, group_id, group_propagation_option, partner_address_id, procure_method, location_id, location_src_id, picking_type_id, delay, warehouse_id, propagate, route_sequence_moved0, route_id, propagate_warehouse_id, route_sequence)\n            SELECT t.create_uid, t.create_date, t.name, t.sequence, t.company_id, t.write_uid, t.action, t.write_date, t.active, t.group_id, t.group_propagation_option, t.partner_address_id, t.procure_method, t.location_id, t.location_src_id, t.picking_type_id, t.delay, t.warehouse_id, t.propagate, t.route_sequence_moved0, slr.id, t.propagate_warehouse_id, t.route_sequence\n            FROM openupgrade_legacy_11_0_procurement_rule t, stock_location_route slr'
ERROR: column t.route_sequence_moved0 does not exist
LINE 4: ...ng_type_id, t.delay, t.warehouse_id, t.propagate, t.route_se...
                                                             ^

2019-01-30 12:46:01,851 18365 ERROR macroquil_20190129_10_migrated OpenUpgrade: Error running b'\n            INSERT INTO procurement_rule\n            (create_uid, create_date, name, sequence, company_id, write_uid, action, write_date, active, group_id, group_propagation_option, partner_address_id, procure_method, location_id, location_src_id, picking_type_id, delay, warehouse_id, propagate, route_sequence_moved0, route_id, propagate_warehouse_id, route_sequence)\n            SELECT t.create_uid, t.create_date, t.name, t.sequence, t.company_id, t.write_uid, t.action, t.write_date, t.active, t.group_id, t.group_propagation_option, t.partner_address_id, t.procure_method, t.location_id, t.location_src_id, t.picking_type_id, t.delay, t.warehouse_id, t.propagate, t.route_sequence_moved0, slr.id, t.propagate_warehouse_id, t.route_sequence\n            FROM openupgrade_legacy_11_0_procurement_rule t, stock_location_route slr'
2019-01-30 12:46:01,851 18365 ERROR macroquil_20190129_10_migrated OpenUpgrade: stock: error in migration script stock/migrations/11.0.1.1/post-migration.py: column t.route_sequence_moved0 does not exist
LINE 4: ...ng_type_id, t.delay, t.warehouse_id, t.propagate, t.route_se...
                                                             ^

2019-01-30 12:46:01,851 18365 ERROR macroquil_20190129_10_migrated OpenUpgrade: column t.route_sequence_moved0 does not exist
LINE 4: ...ng_type_id, t.delay, t.warehouse_id, t.propagate, t.route_se...
                                                             ^
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1445, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/11.0/addons/stock/migrations/11.0.1.1/post-migration.py", line 405, in migrate
    create_specific_procurement_rules_from_globals(env)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1382, in wrapped_function
    return func(*args, **kwargs)
  File "/var/tmp/openupgrade/11.0/addons/stock/migrations/11.0.1.1/post-migration.py", line 87, in create_specific_procurement_rules_from_globals
    AsIs(openupgrade.get_legacy_name(table)),
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 929, in logged_query
    cr.execute(query, args)
  File "/var/tmp/openupgrade/11.0/server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/11.0/server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column t.route_sequence_moved0 does not exist
LINE 4: ...ng_type_id, t.delay, t.warehouse_id, t.propagate, t.route_se...
                                                             ^

2019-01-30 12:46:01,856 18365 ERROR macroquil_20190129_10_migrated odoo.modules.loading: Error executing post migration script for module stock
`-> mrp
: column t.route_sequence_moved0 does not exist
LINE 4: ...ng_type_id, t.delay, t.warehouse_id, t.propagate, t.route_se...
                                                             ^

2019-01-30 12:46:01,870 18365 WARNING macroquil_20190129_10_migrated odoo.modules.loading: Transient module states were reset

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because you have that weird column (`route_sequence_moved0`) in the original table. What is the source of it? Remove it and everything will go OK.

**Comment by fordonez-zabyca** [comment]
HI Pedro no i dont have, I already checked in all tables , there is one but not in another table

![image](https://user-images.githubusercontent.com/16288758/51983919-f7416400-2467-11e9-89d6-b52e215ef0bf.png)




@pedrobaeza , what else do you think it could cause the problem ?

**Comment by pedrobaeza** [comment]
You can see here that the column is got the same way:

https://github.com/OCA/OpenUpgrade/blob/be961df9f08bd990b0665480324b7a5b37916ed6/addons/stock/migrations/11.0.1.1/post-migration.py#L67

So somehow, that column exists.

**Comment by fordonez-zabyca** [comment]
I have commented thar part in the script in migration folder, and migration continued and fiinshed but now i see a column with that name. So i think odoo is creating that column in the migration process , I mean when is updating the module or something.
because i see ther alter column with move in models.py

Maybe some parameter is not correct ?
