### ISSUE TITLE
[6.1->7.0] Migration failed due to changes in openupgradelib

### ISSUE THREAD

**Issue by ypapouin** [OCA/OpenUpgrade#1759]
Changes made in https://github.com/OCA/openupgradelib/commit/22a6409a5dc5946bea5e71e5124b3f7152f4106b broke the migration.
Are this changes a wanted behaviour ? Do I need to stay on an older openupgradelib version to make a 6.1 to 7.0 migration ?

Stacktrace:
```
2019-02-22 11:08:49,316 18993 INFO erp_database openerp.modules.migration: module base: Running migration [7.0.1.3>] post-migration
2019-02-22 11:08:49,316 18993 INFO erp_database openerp.modules.migration: module base: Running migration [7.0.1.3>] post-migration
2019-02-22 11:08:49,317 18993 INFO erp_database OpenUpgrade: base: post-migration script called with version 6.1.1.3
2019-02-22 11:08:49,318 18993 ERROR erp_database OpenUpgrade: base: error in migration script base/migrations/7.0.1.3/post-migration.py: TypeError('get() takes exactly 2 arguments (3 given)',)
2019-02-22 11:08:49,318 18993 ERROR erp_database OpenUpgrade: get() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "/media/data/ypa/projects/odoo-community/openupgradelib/openupgradelib/openupgrade.py", line 1446, in wrapped_function
    if use_env2 else cr, version)
  File "/media/data/ypa/projects/odoo-community/OpenUpgrade/openerp/addons/base/migrations/7.0.1.3/post-migration.py", line 514, in migrate
    openupgrade.set_defaults(cr, pool, force_defaults, force=True)
  File "/media/data/ypa/projects/odoo-community/openupgradelib/openupgradelib/openupgrade.py", line 851, in set_defaults
    obj = pool.get(model, False)
TypeError: get() takes exactly 2 arguments (3 given)
2019-02-22 11:08:49,318 18993 ERROR erp_database openerp.modules.loading: Error executing post migration script for module base
: get() takes exactly 2 arguments (3 given)
2019-02-22 11:08:49,328 18993 ERROR erp_database openerp: Failed to initialize database `erp_database`.
Traceback (most recent call last):
  File "/media/data/ypa/projects/odoo-community/OpenUpgrade/openerp/cli/server.py", line 97, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname,update_module=update_module)
  File "/media/data/ypa/projects/odoo-community/OpenUpgrade/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/media/data/ypa/projects/odoo-community/OpenUpgrade/openerp/modules/registry.py", line 203, in get
    update_module)
  File "/media/data/ypa/projects/odoo-community/OpenUpgrade/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/media/data/ypa/projects/odoo-community/OpenUpgrade/openerp/modules/loading.py", line 329, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, registry=registry)
  File "/media/data/ypa/projects/odoo-community/OpenUpgrade/openerp/modules/loading.py", line 231, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/media/data/ypa/projects/odoo-community/OpenUpgrade/openerp/modules/migration.py", line 191, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/media/data/ypa/projects/odoo-community/openupgradelib/openupgradelib/openupgrade.py", line 1446, in wrapped_function
    if use_env2 else cr, version)
  File "/media/data/ypa/projects/odoo-community/OpenUpgrade/openerp/addons/base/migrations/7.0.1.3/post-migration.py", line 514, in migrate
    openupgrade.set_defaults(cr, pool, force_defaults, force=True)
  File "/media/data/ypa/projects/odoo-community/openupgradelib/openupgradelib/openupgrade.py", line 851, in set_defaults
    obj = pool.get(model, False)
TypeError: get() takes exactly 2 arguments (3 given)

```

**Comment by pedrobaeza** [comment]
Wow, there still 6.1 left in the world, hehe. Total compatibility shouldn't be broken, but for now the only solution is indeed to stay on previous version. At the end, new features are not needed for migrating that version. Any way, I'll try to keep the compatibility later.

**Comment by MiquelRForgeFlow** [comment]
😱🙈

**Comment by ypapouin** [comment]
Yes, our 6.1 instance is running perfectly even after 7 years of daily usages :) and I'm currently upgrading to 8.0.
So I will stay on an older openupgradelib version to continue the upgrade process.

**Comment by pedrobaeza** [comment]
For me it's an error to stay on v8 having a far technical + functional v11/v12, but that's only my opinion of course.

**Comment by ypapouin** [comment]
Thank your for your advice. I was thinking about staying on the latest fully OSS version since I read some time ago that, started from odoo 9, a lot of built-in modules were dropped or rewritten to reduce functionalities in the CE version. I will spend more time on testing the latest release.

**Comment by pedrobaeza** [comment]
There's a lot of FUD around all of this. Open Source is the same for v8 or v12. The difference is the OSS license used: LGPL instead of AGPL. LGPL allows flexibility on third party modules, although opens a door for closing that parts. Well, I only work with OSS in all the chain. About modules were dropped, sincerely we don't miss them, as we have better OSS replacements in OCA ecosystem.

**Comment by pedrobaeza** [comment]
Fixed in openupgradelib.
