### ISSUE TITLE
Migration 12.0

### ISSUE THREAD

**Issue by Danoolo** [OCA/OpenUpgrade#1761]
Impacted versions: 12.0

Steps to reproduce:
 when i run the server with openupgrade branch 12.0

Current behavior:
             - It launch the following errors, suggesting that yaml_import.py doesn't exist..but in version 12.0 of Odoo that file was removed.

2019-02-28 19:31:09,910 15107 INFO ? odoo: Odoo version 12.0 
2019-02-28 19:31:09,910 15107 INFO ? odoo: Using configuration file at /home/gloobal/PycharmProjects/Developments/odoo_confs/odoo11_dev_migration.conf 
2019-02-28 19:31:09,910 15107 INFO ? odoo: addons paths: ['/home/gloobal/.local/share/Odoo/addons/12.0', '/home/gloobal/PycharmProjects/Developments/migration/openupgrade/addons', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/product-variant', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/partner-contact', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/web', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/website', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/website-cms', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/crm', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/manufacture', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/purchase-workflow', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/stock-logistics-warehouse', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/mis-builder', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/connector-telephony', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/server-ux', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/server-tools', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/arg/account-financial-tools', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/arg/account-invoicing', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/arg/account-payment', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/arg/miscellaneous', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/arg/aeroo_reports', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/arg/odoo-argentina', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/arg/product', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/sale_gl', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/stock_gl', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/product_gl', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/product_gl/configurator_gl', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/crm_gl', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/manufacture_gl', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/partner_gl', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/local_gl', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/theme_gl', '/home/gloobal/PycharmProjects/Developments/gloobal-addons/cliente_ap', '/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/addons', '/home/gloobal/PycharmProjects/Developments/odoo11/odoo/addons'] 
2019-02-28 19:31:09,910 15107 INFO ? odoo: database: gloobal@default:default 
2019-02-28 19:31:09,949 15107 CRITICAL ? odoo.modules.module: Couldn't load module base 
2019-02-28 19:31:09,949 15107 CRITICAL ? odoo.modules.module: module 'odoo.tools' has no attribute 'yaml_import' 
2019-02-28 19:31:09,949 15107 ERROR ? odoo.service.server: Failed to load server-wide module `base`. 
Traceback (most recent call last):
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/service/server.py", line 1002, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 5, in <module>
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/addons/base/models/__init__.py", line 7, in <module>
    from . import ir_model
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/addons/base/models/ir_model.py", line 17, in <module>
    from openupgradelib import openupgrade
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 84, in <module>
    yaml_import = tools.yaml_import
AttributeError: module 'odoo.tools' has no attribute 'yaml_import'
2019-02-28 19:31:09,958 15107 INFO AP_1_copy odoo.modules.loading: loading 1 modules... 
2019-02-28 19:31:09,964 15107 ERROR AP_1_copy odoo.modules.migration: module base: Each pre-migration file must have a "migrate(cr, installed_version)" function 
2019-02-28 19:31:09,966 15107 INFO AP_1_copy odoo.modules.registry: module base: creating or updating database tables 
2019-02-28 19:31:09,966 15107 ERROR AP_1_copy odoo.sql_db: bad query: b"\n        SELECT c.relname\n          FROM pg_class c\n          JOIN pg_namespace n ON (n.oid = c.relnamespace)\n         WHERE c.relname IN ()\n           AND c.relkind IN ('r', 'v', 'm')\n           AND n.nspname = 'public'\n    "
ERROR: syntax error at or near ")"
LINE 5:          WHERE c.relname IN ()
                                     ^
 
2019-02-28 19:31:09,967 15107 WARNING AP_1_copy odoo.modules.loading: Transient module states were reset 
2019-02-28 19:31:09,967 15107 ERROR AP_1_copy odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 410, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/registry.py", line 313, in init_models
    self.check_tables_exist(cr)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/registry.py", line 321, in check_tables_exist
    missing_tables = set(table2model).difference(existing_tables(cr, table2model))
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/tools/sql.py", line 34, in existing_tables
    cr.execute(query, [tuple(tablenames)])
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near ")"
LINE 5:          WHERE c.relname IN ()
                                     ^

2019-02-28 19:31:09,967 15107 CRITICAL AP_1_copy odoo.service.server: Failed to initialize database `AP_1_copy`. 
Traceback (most recent call last):
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/service/server.py", line 1055, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 410, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/registry.py", line 313, in init_models
    self.check_tables_exist(cr)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/registry.py", line 321, in check_tables_exist
    missing_tables = set(table2model).difference(existing_tables(cr, table2model))
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/tools/sql.py", line 34, in existing_tables
    cr.execute(query, [tuple(tablenames)])
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near ")"
LINE 5:          WHERE c.relname IN ()
                                     ^

2019-02-28 19:31:09,968 15107 INFO AP_1_copy odoo.service.server: Initiating shutdown 
2019-02-28 19:31:09,968 15107 INFO AP_1_copy odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 

Expected behavior:
              - Run server and launch errors related with my db pointed!

Video/Screenshot link (optional):
Image of configuration parameters:
![captura de pantalla de 2019-02-28 16-42-30](https://user-images.githubusercontent.com/30710193/53593628-ea538580-3b77-11e9-8152-a083d4102d9b.png)

I'm starting with the subject of migration and i have to migrate a v11 db, I have already read the doc here but i dont understand the issue! Thanks in advance!

**Comment by pedrobaeza** [comment]
You are clearly not running correct OpenUpgrade server, as that code line doesn't exist in current branch.

**Comment by Danoolo** [comment]
Yeah!! That was because of openupgradelib..i had installed an old version!! ..thanks so much Pedro!

**Comment by mdemaison** [comment]
Hi just for information i got the same problem because in requirements.txt i got openupgradelib>=2.0.0

**Comment by pedrobaeza** [comment]
Yeah, let's fix it this way:

https://github.com/OCA/OpenUpgrade/commit/389c78d0383e6ee1605c5cde92931eba85a15baf
