### ISSUE TITLE
Upgrade from v10 t v11

### ISSUE THREAD

**Issue by fohnbit** [OCA/OpenUpgrade#1782]
Hello,

I tried to upgrade from v10 to v11 .. we have several own modules written for v10.

I get this error:
  2019-03-19 10:38:59,198 4268 WARNING company_migrated py.warnings: /var/tmp/openupgrade/11.0/server/odoo/tools/yaml_import.py:794: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for node in yaml.load(yaml_string):

2019-03-19 10:38:59,235 4268 WARNING company_migrated odoo.modules.loading: Transient module states were reset
2019-03-19 10:39:04,471 4268 ERROR company_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 207, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/convert.py", line 793, in convert_file
    convert_yaml_import(cr, module, fp, kind, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/yaml_import.py", line 854, in yaml_import
    yaml_interpreter.process(yaml_string)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/yaml_import.py", line 794, in process
    for node in yaml.load(yaml_string):
  File "/usr/local/lib/python3.5/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 131, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!python'
  in "<byte string>", line 2, column 3:
      !python {model: ir.model.data, i ...
      ^
2019-03-19 10:39:04,474 4268 CRITICAL company_migrated odoo.service.server: Failed to initialize database `company_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/11.0/server/odoo/service/server.py", line 945, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 207, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/convert.py", line 793, in convert_file
    convert_yaml_import(cr, module, fp, kind, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/yaml_import.py", line 854, in yaml_import
    yaml_interpreter.process(yaml_string)
  File "/var/tmp/openupgrade/11.0/server/odoo/tools/yaml_import.py", line 794, in process
    for node in yaml.load(yaml_string):
  File "/usr/local/lib/python3.5/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 131, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!python'
  in "<byte string>", line 2, column 3:
      !python {model: ir.model.data, i ...
      ^
2019-03-19 10:39:04,478 4268 INFO company_migrated odoo.service.server: Stopping gracefully

**Comment by fohnbit** [comment]
sorry: 
my command line:
python migrate.py --config="/etc/odoo/odoo.conf" --database=company --run-migrations=11.0

**Comment by fohnbit** [comment]
update 2:
I deinstalled all customs modules in odoo10 ... but same error.

**Comment by pedrobaeza** [comment]
The problem is to use that script. It's not working in v11. Please use manual method.

**Comment by fohnbit** [comment]
Hello,

ok I unterstand. But is there a docu how I made this manual? The link https://doc.therp.nl/openupgrade/migration_details.html I know ... but did not really unterstand what I have to do.

Thank you!

**Comment by pedrobaeza** [comment]
That are the steps, so you must learn first how to update your modules via command line, which is not something of OpenUpgrade, but Odoo itself.

**Comment by jnbruguer** [comment]
Hola Pedro, estoy intentantando migrar la base de datos de Odoo 10 CE a 11 CE, no tengo modulos propios, pero no acabo de entender como hacer el openupgrade, no encuentro en ningún sitio ni en el manual como ejecutarlo. Por favor me podrías ayudar?

Mil gracias de antemano.
JOan
