### ISSUE TITLE
Mig 10.0 -> 11.0 KeyError: 'toclose'

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#1786]
```
2019-03-29 15:44:53,235 11096 CRITICAL db_migrated odoo.service.server: Failed to initialize database db_migrated.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/11.0/server/odoo/service/server.py", line 945, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/loading.py", line 217, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1443, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/11.0/addons/fleet/migrations/11.0.0.1/post-migration.py", line 14, in migrate
    env['fleet.vehicle.log.contract'].scheduler_manage_contract_expiration()
  File "/var/tmp/openupgrade/11.0/addons/fleet/models/fleet_vehicle_cost.py", line 278, in scheduler_manage_contract_expiration
    expired_contracts.write({'state': 'expired'})
  File "/var/tmp/openupgrade/11.0/addons/mail/models/mail_thread.py", line 291, in write
    track_self.message_track(tracked_fields, initial_values)
  File "/var/tmp/openupgrade/11.0/addons/mail/models/mail_thread.py", line 494, in message_track
    tracking = self._message_track_get_changes(tracked_fields, initial_values)
  File "/var/tmp/openupgrade/11.0/addons/mail/models/mail_thread.py", line 444, in _message_track_get_changes
    result[record.id] = record._message_track(tracked_fields, initial_values[record.id])
  File "/var/tmp/openupgrade/11.0/addons/mail/models/mail_thread.py", line 467, in _message_track
    tracking = self.env['mail.tracking.value'].create_tracking_values(initial_value, new_value, col_name, col_info)
  File "/var/tmp/openupgrade/11.0/addons/mail/models/mail_tracking_value.py", line 57, in create_tracking_values
    'old_value_char': initial_value and dict(col_info['selection'])[initial_value] or '',
KeyError: 'toclose'

```

**Comment by pedrobaeza** [comment]
How are you executing the migration? `migrate.py` script is not valid for 10>11

**Comment by m3asmi** [comment]
we cannot migrate from 10.0 to 11.0 with migrate.py ?

**Comment by pedrobaeza** [comment]
No, use manual method.

**Comment by m3asmi** [comment]
any documentation ?

**Comment by pedrobaeza** [comment]
https://doc.therp.nl/openupgrade/migration_details.html
