### ISSUE TITLE
10->11: openupgrade  has no attribute delete_records_safely_by_xml_id

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#1788]
```
2019-04-01 11:55:34,911 29517 DEBUG db_migrated OpenUpgrade: 1 rows affected
2019-04-01 11:55:34,911 29517 ERROR db_migrated OpenUpgrade: project: error in migration script project/migrations/11.0.1.1/pre-migration.py: module 'openupgradelib.openupgrade' has no attribute 'delete_records_safely_by_xml_id'
2019-04-01 11:55:34,911 29517 ERROR db_migrated OpenUpgrade: module 'openupgradelib.openupgrade' has no attribute 'delete_records_safely_by_xml_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/OpenUpgrade/addons/project/migrations/11.0.1.1/pre-migration.py", line 34, in migrate
    openupgrade.delete_records_safely_by_xml_id(env, [
AttributeError: module 'openupgradelib.openupgrade' has no attribute 'delete_records_safely_by_xml_id'
2019-04-01 11:55:34,915 29517 WARNING db_migrated odoo.modules.loading: Transient module states were reset
2019-04-01 11:55:34,916 29517 ERROR db_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/OpenUpgrade/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/OpenUpgrade/addons/project/migrations/11.0.1.1/pre-migration.py", line 34, in migrate
    openupgrade.delete_records_safely_by_xml_id(env, [
AttributeError: module 'openupgradelib.openupgrade' has no attribute 'delete_records_safely_by_xml_id'```

**Comment by pedrobaeza** [comment]
You are using an outdated library. Install latest code version always with
`pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master`
