### ISSUE TITLE
10->11: Error while validating constraint

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#1789]
```

2019-04-01 16:31:18,907 19216 ERROR db_migrated OpenUpgrade: project: error in migration script project/migrations/11.0.1.1/post-migration.py: ("Error while validating constraint\n\nYou can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project\n", None)
2019-04-01 16:31:18,907 19216 ERROR db_migrated OpenUpgrade: ("Error while validating constraint\n\nYou can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project\n", None)
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 1041, in _validate_fields
    check(self)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 568, in _check_subtask_project
    raise UserError(_("You can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project"))
odoo.exceptions.UserError: ("You can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project", '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1443, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/OpenUpgrade/addons/project/migrations/11.0.1.1/post-migration.py", line 226, in migrate
    convert_issues(env)
  File "/opt/odoo/OpenUpgrade/addons/project/migrations/11.0.1.1/post-migration.py", line 78, in convert_issues
    'label_tasks': row['label_issues'],
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 252, in copy
    self.map_tasks(project.id)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 237, in map_tasks
    tasks += task.copy(defaults)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 549, in copy
    return super(Task, self).copy(default)
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 3972, in copy
    new = self.with_context(lang=None).create(vals)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 663, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/opt/odoo/OpenUpgrade/addons/mail/models/mail_thread.py", line 238, in create
    thread = super(MailThread, self).create(values)
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 3398, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 3551, in _create
    self._validate_fields(vals)
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 1045, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ("Error while validating constraint\n\nYou can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project\n", None)
2019-04-01 16:31:18,909 19216 ERROR db_migrated odoo.modules.loading: Error executing post migration script for module project
`-> hr_timesheet
   `-> hr_timesheet_attendance
   `-> project_native
   `-> project_timesheet_holidays
   `-> project_timesheet_synchro
   `-> tecnibo_hr
   `-> timesheet_grid
`-> project_forecast
: ("Error while validating constraint\n\nYou can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project\n", None)
2019-04-01 16:31:18,930 19216 WARNING db_migrated odoo.modules.loading: Transient module states were reset
2019-04-01 16:31:18,933 19216 ERROR db_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 1041, in _validate_fields
    check(self)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 568, in _check_subtask_project
    raise UserError(_("You can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project"))
odoo.exceptions.UserError: ("You can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project", '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 217, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/odoo/OpenUpgrade/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1443, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/OpenUpgrade/addons/project/migrations/11.0.1.1/post-migration.py", line 226, in migrate
    convert_issues(env)
  File "/opt/odoo/OpenUpgrade/addons/project/migrations/11.0.1.1/post-migration.py", line 78, in convert_issues
    'label_tasks': row['label_issues'],
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 252, in copy
    self.map_tasks(project.id)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 237, in map_tasks
    tasks += task.copy(defaults)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 549, in copy
    return super(Task, self).copy(default)
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 3972, in copy
    new = self.with_context(lang=None).create(vals)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 663, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/opt/odoo/OpenUpgrade/addons/mail/models/mail_thread.py", line 238, in create
    thread = super(MailThread, self).create(values)
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 3398, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 3551, in _create
    self._validate_fields(vals)
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 1045, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ("Error while validating constraint\n\nYou can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project\n", None)
2019-04-01 16:31:18,934 19216 CRITICAL db_migrated odoo.service.server: Failed to initialize database `db_migrated`.
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 1041, in _validate_fields
    check(self)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 568, in _check_subtask_project
    raise UserError(_("You can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project"))
odoo.exceptions.UserError: ("You can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project", '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/service/server.py", line 945, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 217, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/odoo/OpenUpgrade/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1443, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/OpenUpgrade/addons/project/migrations/11.0.1.1/post-migration.py", line 226, in migrate
    convert_issues(env)
  File "/opt/odoo/OpenUpgrade/addons/project/migrations/11.0.1.1/post-migration.py", line 78, in convert_issues
    'label_tasks': row['label_issues'],
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 252, in copy
    self.map_tasks(project.id)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 237, in map_tasks
    tasks += task.copy(defaults)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 549, in copy
    return super(Task, self).copy(default)
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 3972, in copy
    new = self.with_context(lang=None).create(vals)
  File "/opt/odoo/OpenUpgrade/addons/project/models/project.py", line 663, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/opt/odoo/OpenUpgrade/addons/mail/models/mail_thread.py", line 238, in create
    thread = super(MailThread, self).create(values)
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 3398, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 3551, in _create
    self._validate_fields(vals)
  File "/opt/odoo/OpenUpgrade/odoo/models.py", line 1045, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ("Error while validating constraint\n\nYou can't define a parent task if its project is not correctly configured. The sub-task's project of the parent task's project should be this task's project\n", None)
2019-04-01 16:31:18,934 19216 INFO db_migrated odoo.service.server: Initiating shutdown
2019-04-01 16:31:18,934 19216 INFO db_migrated odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2019-04-01 16:31:18,934 19216 DEBUG db_migrated odoo.service.server: current thread: <_MainThread(MainThread, started 140076535674688)>
2019-04-01 16:31:18,934 19216 DEBUG db_migrated odoo.service.server: process <_MainThread(MainThread, started 140076535674688)> (False)
2019-04-01 16:31:18,934 19216 DEBUG db_migrated odoo.service.server: --

```

**Comment by m3asmi** [comment]
suggestion 
```
UPDATE project_task t
SET parent_id = NULL
FROM project_task p
WHERE t.parent_id = p.id
	AND t.project_id != p.project_id
```

**Comment by pedrobaeza** [comment]
Please check if #1790 solves your problem.
