### ISSUE TITLE
10->11: No module named 'models'

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#1791]
after migration with openupgrad I lanched odoo with --update all I get this error!
stock_calendar is not existing in odoo 11.0 
```2019-04-04 09:04:36,659 10217 CRITICAL db_migrated odoo.modules.module: Couldn't load module stock_calendar
2019-04-04 09:04:36,659 10217 CRITICAL db_migrated odoo.modules.module: No module named 'models'
2019-04-04 09:04:36,662 10217 WARNING db_migrated odoo.modules.loading: Transient module states were reset
2019-04-04 09:04:36,662 10217 ERROR db_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 137, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo11/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/odoo11/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'models'
2019-04-04 09:04:36,663 10217 CRITICAL db_migrated odoo.service.server: Failed to initialize database `db_migrated`.
Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/service/server.py", line 1006, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 137, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo11/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/odoo11/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'models'
```

**Comment by pedrobaeza** [comment]
That module is not yet covered in the migration, as you can see in:

https://doc.therp.nl/openupgrade/modules100-110.html
