### ISSUE TITLE
10 -> 11: openupgrade_legacy_11_0_state" does not exist

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#1792]
```
2019-04-04 15:05:16,185 10701 INFO db_migrated odoo.modules.migration: module fleet: Running migration [>11.0.0.1] pre-migration
2019-04-04 15:05:16,186 10701 INFO db_migrated OpenUpgrade: fleet: pre-migration script called with version 10.0.0.1
2019-04-04 15:05:16,190 10701 DEBUG db_migrated OpenUpgrade: Running 
                ALTER TABLE fleet_service_type
                ADD COLUMN openupgrade_legacy_11_0_category character varying;
                UPDATE fleet_service_type SET openupgrade_legacy_11_0_category=category;
                
2019-04-04 15:05:16,190 10701 DEBUG db_migrated OpenUpgrade: 81 rows affected
2019-04-04 15:05:16,191 10701 ERROR db_migrated odoo.sql_db: bad query: b"UPDATE fleet_vehicle_log_contract\n                       SET state = 'expired'\n                       WHERE openupgrade_legacy_11_0_state = 'toclose'"
ERROR: column "openupgrade_legacy_11_0_state" does not exist
LINE 3:                        WHERE openupgrade_legacy_11_0_state =...
                                     ^

2019-04-04 15:05:16,191 10701 ERROR db_migrated OpenUpgrade: Error running b"UPDATE fleet_vehicle_log_contract\n                       SET state = 'expired'\n                       WHERE openupgrade_legacy_11_0_state = 'toclose'"
2019-04-04 15:05:16,191 10701 ERROR db_migrated OpenUpgrade: fleet: error in migration script fleet/migrations/11.0.0.1/pre-migration.py: column "openupgrade_legacy_11_0_state" does not exist
LINE 3:                        WHERE openupgrade_legacy_11_0_state =...
                                     ^

2019-04-04 15:05:16,191 10701 ERROR db_migrated OpenUpgrade: column "openupgrade_legacy_11_0_state" does not exist
LINE 3:                        WHERE openupgrade_legacy_11_0_state =...
                                     ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1443, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/OpenUpgrade/addons/fleet/migrations/11.0.0.1/pre-migration.py", line 18, in migrate
    [('toclose', 'expired')], table='fleet_vehicle_log_contract',
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1217, in map_values
    logged_query(cr, query, values)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 927, in logged_query
    cr.execute(query, args)
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "openupgrade_legacy_11_0_state" does not exist
LINE 3:                        WHERE openupgrade_legacy_11_0_state =...
                                     ^

2019-04-04 15:05:16,198 10701 WARNING db_migrated odoo.modules.loading: Transient module states were reset
2019-04-04 15:05:16,200 10701 ERROR db_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/OpenUpgrade/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1443, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/OpenUpgrade/addons/fleet/migrations/11.0.0.1/pre-migration.py", line 18, in migrate
    [('toclose', 'expired')], table='fleet_vehicle_log_contract',
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1217, in map_values
    logged_query(cr, query, values)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 927, in logged_query
    cr.execute(query, args)
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "openupgrade_legacy_11_0_state" does not exist
LINE 3:                        WHERE openupgrade_legacy_11_0_state =...
                                     ^

2019-04-04 15:05:16,200 10701 CRITICAL db_migrated odoo.service.server: Failed to initialize database `db_migrated`.
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/service/server.py", line 945, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/OpenUpgrade/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1443, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/OpenUpgrade/addons/fleet/migrations/11.0.0.1/pre-migration.py", line 18, in migrate
    [('toclose', 'expired')], table='fleet_vehicle_log_contract',
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1217, in map_values
    logged_query(cr, query, values)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 927, in logged_query
    cr.execute(query, args)
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "openupgrade_legacy_11_0_state" does not exist
LINE 3:                        WHERE openupgrade_legacy_11_0_state =...
                                     ^

2019-04-04 15:05:16,200 10701 INFO db_migrated odoo.service.server: Initiating shutdown
```

**Comment by pedrobaeza** [comment]
This is because you own suggested code in https://github.com/OCA/OpenUpgrade/issues/1787#issuecomment-478553130, so please check well before posting an issue.
