### ISSUE TITLE
v10 -> v11: ValueError Element group name="options"

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#1794]
after migration and running with `odoo  -u all `
```
2019-04-11 09:59:35,793 16995 INFO db_migrated odoo.modules.loading: loading project/views/project_views.xml
2019-04-11 09:59:35,893 16995 INFO db_migrated odoo.models.unlink: User #1 deleted ir.translation records with IDs: [379536, 380304, 381335]
2019-04-11 09:59:35,943 16995 INFO db_migrated odoo.models.unlink: User #1 deleted ir.translation records with IDs: [381334]
2019-04-11 09:59:35,993 16995 INFO db_migrated odoo.models.unlink: User #1 deleted ir.translation records with IDs: [381333]
2019-04-11 09:59:36,028 16995 INFO db_migrated odoo.models.unlink: User #1 deleted ir.translation records with IDs: [379604]
2019-04-11 09:59:36,038 16995 INFO db_migrated odoo.addons.base.ir.ir_ui_view: Element '<group name="options">' cannot be located in parent view

Error context:
View `project.project.view.form.simplified.inherit.issue`
[view_id: 1955, xml_id: project.project_project_view_form_simplified_inherit_issue, model: project.project, parent_id: 1918]
2019-04-11 09:59:36,043 16995 WARNING db_migrated odoo.modules.loading: Transient module states were reset
2019-04-11 09:59:36,045 16995 ERROR db_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/models.py", line 1037, in _validate_fields
    check(self)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 337, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 730, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 679, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 657, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 519, in raise_view_error
    raise ValueError(message)
ValueError: Element '<group name="options">' cannot be located in parent view

Error context:
View `project.project.view.form.simplified.inherit.issue`
[view_id: 1955, xml_id: project.project_project_view_form_simplified_inherit_issue, model: project.project, parent_id: 1918]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1457, in _update
    record.write(values)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo11/odoo/models.py", line 3129, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo11/odoo/fields.py", line 1074, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 273, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo11/odoo/models.py", line 3109, in write
    self._write(old_vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 3277, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 1041, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<group name="options">\' cannot be located in parent view\n\nError context:\nView `project.project.view.form.simplified.inherit.issue`\n[view_id: 1955, xml_id: project.project_project_view_form_simplified_inherit_issue, model: project.project, parent_id: 1918]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1457, in _update
    record.write(values)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo11/odoo/models.py", line 3129, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo11/odoo/fields.py", line 1074, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 273, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo11/odoo/models.py", line 3109, in write
    self._write(old_vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 3277, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 1041, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<group name="options">' cannot be located in parent view

Error context:
View `project.project.view.form.simplified.inherit.issue`
[view_id: 1955, xml_id: project.project_project_view_form_simplified_inherit_issue, model: project.project, parent_id: 1918]
None" while parsing /opt/odoo/odoo11/addons/project/views/project_views.xml:232, near
<record id="project_project_view_form_simplified" model="ir.ui.view">
            <field name="name">project.project.view.form.simplified</field>
            <field name="model">project.project</field>
            <field name="arch" type="xml">
                <form string="Project">
                    <sheet>
                        <group>
                            <group>
                                <field name="name" class="o_project_name oe_inline" string="Project Name" placeholder="e.g. Office Party"/>
                                <label for="alias_name" string="Choose a Project Email" attrs="{'invisible': [('alias_domain', '=', False)]}"/>
                                <div name="alias_def" attrs="{'invisible': [('alias_domain', '=', False)]}">
                                    <field name="alias_name" class="oe_inline"/>@<field name="alias_domain" class="oe_inline" readonly="1"/>
                                </div>
                                <field name="user_id" invisible="1"/>
                            </group>
                        </group>
                        <footer>
                            <button string="Create" name="close_dialog" type="object" class="btn-primary"/>
                            <button string="Create &amp; Edit" name="edit_dialog" type="object" class="btn-primary"/>
                            <button string="Discard" class="btn-default" special="cancel"/>
                        </footer>

                    </sheet>
                </form>
            </field>
        </record>
2019-04-11 09:59:36,048 16995 CRITICAL db_migrated odoo.service.server: Failed to initialize database `db_migrated`.
Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/models.py", line 1037, in _validate_fields
    check(self)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 337, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 730, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 679, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 657, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 519, in raise_view_error
    raise ValueError(message)
ValueError: Element '<group name="options">' cannot be located in parent view

Error context:
View `project.project.view.form.simplified.inherit.issue`
[view_id: 1955, xml_id: project.project_project_view_form_simplified_inherit_issue, model: project.project, parent_id: 1918]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1457, in _update
    record.write(values)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo11/odoo/models.py", line 3129, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo11/odoo/fields.py", line 1074, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 273, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo11/odoo/models.py", line 3109, in write
    self._write(old_vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 3277, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 1041, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<group name="options">\' cannot be located in parent view\n\nError context:\nView `project.project.view.form.simplified.inherit.issue`\n[view_id: 1955, xml_id: project.project_project_view_form_simplified_inherit_issue, model: project.project, parent_id: 1918]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/service/server.py", line 1006, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1457, in _update
    record.write(values)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo11/odoo/models.py", line 3129, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo11/odoo/fields.py", line 1074, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 273, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo11/odoo/models.py", line 3109, in write
    self._write(old_vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 3277, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 1041, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<group name="options">' cannot be located in parent view

Error context:
View `project.project.view.form.simplified.inherit.issue`
[view_id: 1955, xml_id: project.project_project_view_form_simplified_inherit_issue, model: project.project, parent_id: 1918]
None" while parsing /opt/odoo/odoo11/addons/project/views/project_views.xml:232, near
<record id="project_project_view_form_simplified" model="ir.ui.view">
            <field name="name">project.project.view.form.simplified</field>
            <field name="model">project.project</field>
            <field name="arch" type="xml">
                <form string="Project">
                    <sheet>
                        <group>
                            <group>
                                <field name="name" class="o_project_name oe_inline" string="Project Name" placeholder="e.g. Office Party"/>
                                <label for="alias_name" string="Choose a Project Email" attrs="{'invisible': [('alias_domain', '=', False)]}"/>
                                <div name="alias_def" attrs="{'invisible': [('alias_domain', '=', False)]}">
                                    <field name="alias_name" class="oe_inline"/>@<field name="alias_domain" class="oe_inline" readonly="1"/>
                                </div>
                                <field name="user_id" invisible="1"/>
                            </group>
                        </group>
                        <footer>
                            <button string="Create" name="close_dialog" type="object" class="btn-primary"/>
                            <button string="Create &amp; Edit" name="edit_dialog" type="object" class="btn-primary"/>
                            <button string="Discard" class="btn-default" special="cancel"/>
                        </footer>

                    </sheet>
                </form>
            </field>
        </record>
2019-04-11 09:59:36,056 16995 DEBUG db_migrated odoo.service.server: cron0 started!
2019-04-11 09:59:36,060 16995 DEBUG db_migrated odoo.service.server: cron1 started!
2019-04-11 10:00:36,125 16995 DEBUG ? odoo.service.server: cron0 polling for jobs
2019-04-11 10:00:37,119 16995 DEBUG ? odoo.service.server: cron1 polling for jobs

```

**Comment by pedrobaeza** [comment]
You have to check that the original view is not one custom one that can't be removed on the migration due to other existing children views. Also check non covered modules in OpenUpgrade.

Any way, this is not an issue related to existing OpenUpgrade code, but something you have to handle on each DB. On the worst case, you can remove the view on the DB.
