### ISSUE TITLE
v10 -> v11: ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#1795]
```2019-04-11 13:27:41,287 30835 DEBUG ? odoo.http: Loading website_crm_score
2019-04-11 13:27:41,289 30835 INFO ? odoo.addons.website_crm_score.models.sales_team: Flanker is not compatible with Python 3, email validation has been disabled
2019-04-11 13:27:41,292 30835 DEBUG ? odoo.http: Loading website_delivery_ups
2019-04-11 13:27:41,294 30835 DEBUG ? odoo.http: Loading website_enterprise
2019-04-11 13:27:41,294 30835 DEBUG ? odoo.http: Loading website_form_editor
2019-04-11 13:27:41,294 30835 DEBUG ? odoo.http: Loading website_helpdesk
2019-04-11 13:27:41,295 30835 DEBUG ? odoo.http: Loading website_sign
2019-04-11 13:27:41,295 30835 DEBUG ? odoo.http: Loading website_studio
2019-04-11 13:27:41,296 30835 DEBUG ? odoo.http: Loading website_version
2019-04-11 13:27:41,296 30835 DEBUG ? odoo.http: Loading auth_oauth
2019-04-11 13:27:41,299 30835 DEBUG ? odoo.http: Loading delivery
2019-04-11 13:27:41,307 30835 DEBUG ? odoo.http: Loading marketing_campaign
2019-04-11 13:27:41,517 30835 INFO ? werkzeug: 127.0.0.1 - - [11/Apr/2019 13:27:41] "GET /web/login HTTP/1.1" 500 -
2019-04-11 13:27:41,519 30835 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo11/odoo/service/server.py", line 319, in app
    return self.app(e, s)
  File "/opt/odoo/odoo11/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo11/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo11/odoo/http.py", line 1318, in __call__
    self.load_addons()
  File "/opt/odoo/odoo11/odoo/http.py", line 1350, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/opt/odoo/odoo11/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>
    
ModuleNotFoundError: No module named 'models'
```

**Comment by pedrobaeza** [comment]
Same answer than #1791
