### ISSUE TITLE
psycopg2.IntegrityError: insert or update on table "stock_move" violates foreign key constraint "stock_move_rule_id_fkey" DETAIL:  Key (rule_id)=(1) is not present in table "stock_rule"

### ISSUE THREAD

**Issue by furicks** [OCA/OpenUpgrade#1800]
Impacted versions:
12.0

Steps to reproduce:
Postgresql 9.5
./odoo-bin -c /etc/odoo12.conf --update all --stop-after-init
no "Reordering Rules" exist in current dataset under Inventory module

```
Current behavior:
2019-04-18 14:51:07,785 32434 INFO fodoo12 odoo.models: Actual recompute of field ir.module.module.reports_by_module for 1 recs.
2019-04-18 14:51:08,511 32434 INFO fodoo12 odoo.fields: Field stock.production.lot.product_uom_id depends on non-stored field product.product.uom_id
2019-04-18 14:51:08,515 32434 INFO fodoo12 odoo.fields: Field stock.picking.move_ids_without_package depends on non-stored field stock.move.picking_type_entire_packs
2019-04-18 14:51:08,517 32434 INFO fodoo12 odoo.fields: Field stock.picking.move_line_ids_without_package depends on non-stored field stock.move.line.picking_type_entire_packs
2019-04-18 14:51:08,598 32434 INFO fodoo12 odoo.modules.registry: module stock: creating or updating database tables
2019-04-18 14:51:10,876 32434 ERROR fodoo12 odoo.sql_db: bad query: b'ALTER TABLE "stock_move" ADD FOREIGN KEY ("rule_id") REFERENCES "stock_rule"("id") ON DELETE restrict'
ERROR: insert or update on table "stock_move" violates foreign key constraint "stock_move_rule_id_fkey"
DETAIL:  Key (rule_id)=(1) is not present in table "stock_rule".

2019-04-18 14:51:10,879 32434 WARNING fodoo12 odoo.modules.loading: Transient module states were reset
2019-04-18 14:51:10,880 32434 ERROR fodoo12 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/modules/registry.py", line 301, in init_models
    func()
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/fields.py", line 2142, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/tools/sql.py", line 185, in fix_foreign_key
    return add_foreign_key(cr, tablename1, columnname1, tablename2, columnname2, ondelete)
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/tools/sql.py", line 158, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/lampstack-5.6.20-0/OpenUpgrade-12.0/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: insert or update on table "stock_move" violates foreign key constraint "stock_move_rule_id_fkey"
DETAIL:  Key (rule_id)=(1) is not present in table "stock_rule".
```

Can I manually fix this in Odoo 11 so it will get past this step? 

Expected behavior:
looks like procurement.rule is now required in the analysis. 
"stock        / procurement.rule         / location_id (many2one)        : now required"

generic stock_move rules are created where needed
database is migrated

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Stock module is still not migrated. Check #1681. Any way, before migrating you have to update all your modules in previous version (11.0).

**Comment by vifonne** [comment]
I am reopening this issue since #1681 is merged and I still have this issue, every module in previous version (11.0) is updated.

Impacted versions:
12.0

PostgreSQL 10

```
2021-05-19 09:18:21,159 7603 ERROR ophelia-sensors-12-15 odoo.sql_db: bad query: ALTER TABLE "stock_move" ADD FOREIGN KEY ("rule_id") REFERENCES "stock_rule"("id") ON DELETE restrict
ERROR: insert or update on table "stock_move" violates foreign key constraint "stock_move_rule_id_fkey"
DETAIL:  Key (rule_id)=(1) is not present in table "stock_rule".

2021-05-19 09:18:21,162 7603 ERROR ophelia-sensors-12-15 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/root/upgrade/12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/root/upgrade/12/odoo/modules/loading.py", line 487, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/root/upgrade/12/odoo/modules/loading.py", line 371, in load_marked_modules
    upg_registry=upg_registry,
  File "/root/upgrade/12/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/root/upgrade/12/odoo/modules/registry.py", line 320, in init_models
    func()
  File "/root/upgrade/12/odoo/fields.py", line 2252, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/root/upgrade/12/odoo/tools/sql.py", line 186, in fix_foreign_key
    return add_foreign_key(cr, tablename1, columnname1, tablename2, columnname2, ondelete)
  File "/root/upgrade/12/odoo/tools/sql.py", line 159, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/root/upgrade/12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/root/upgrade/12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: insert or update on table "stock_move" violates foreign key constraint "stock_move_rule_id_fkey"
DETAIL:  Key (rule_id)=(1) is not present in table "stock_rule".
```

I tried to remove manually the constraint `stock_move_rule_id_fkey` but it did not work.

**Comment by pedrobaeza** [comment]
Yeah, but you have to expose data that leads to this problem. This is mostly a database with "corrupted" data that leads to the problem, not something that should be fixed at OpenUpgrade level.

**Comment by vifonne** [comment]
Ok, I understand, do you have any insights/ideas about where I should look ?

**Comment by pedrobaeza** [comment]
It seems you delete the stock.rule with id 1 in the database, but not removing the appearances of this rule in the stock moves.

**Comment by vifonne** [comment]
Oh, yes, I will look forward on this!

Thanks for your usefull help !

**Comment by vifonne** [comment]
I don't think it's the right place for this but as we discuss about that kind of issues. I've got hundreds of errors about constraint violation (not-null, unique etc...) during the migration. But on the previous version (11.0) everything was working great.

Is there another platform where we can talk about that kind of issue ? (maling list, forum etc...)
Do you have any idea on how I can go through this issue ? Do I really need to delete a lots of row in my database to satisfy the constraints ?

**Comment by pedrobaeza** [comment]
There is a mailing list in https://odoo-community.org/groups. You have to see how you insert such data that violates integrity of the DB and do the queries to restore it.
