### ISSUE TITLE
v10 -> v11: ValueError: Field `model` does not exist

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#1820]
after upgrade I cannot enter to the scheduled actions
I got this error:

```
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/models.py", line 1296, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/odoo11/odoo/models.py", line 1296, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/odoo11/odoo/models.py", line 1382, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 1064, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 519, in raise_view_error
    raise ValueError(message)
ValueError: Field `model` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

```

**Comment by pedrobaeza** [comment]
You have to dig-in a bit more in your original data for discovering which cron is provoking this. At first sight, it doesn't seem something of OpenUpgrade itself, but on your custom code.

**Comment by m3asmi** [comment]
I had to comment this line in the view form of ir.cron

```
    <!--<group string="Action to Trigger">
                            <field name="model"/>
                            <field name="function"/>
                        </group>
                        <label for="args"/>
                        <field name="args"/>-->
```

**Comment by pedrobaeza** [comment]
Is that view standard in v11?

**Comment by m3asmi** [comment]
yes `base.ir_cron_view`

**Comment by pedrobaeza** [comment]
Then there's something weird in your migration as that field should be populated in the DB.
