### ISSUE TITLE
 duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#1829]
Impacted versions:
Migration from 9.0 to 10.0

Steps to reproduce:
Start the automated script as in documentation.
Script run the migration, but fail after few minutes with the following error in log:

```
2019-05-16 07:16:54,217 72 INFO migration_db_migrated openerp.tools.translate: loading /var/tmp/openupgrade/9.0/addons/payment/i18n/de.po
2019-05-16 07:16:55,150 72 INFO migration_db_migrated openerp.modules.module: module project: creating or updating database tables
2019-05-16 07:16:55,331 72 INFO migration_db_migrated openerp.models: Moving XMLID for ir.model.fields record of res.company#project_time_mode_id from sale_timesheet to project
2019-05-16 07:16:55,332 72 INFO migration_db_migrated openerp.sql_db: bad query: UPDATE ir_model_data SET module='project' WHERE id=21157
2019-05-16 07:16:55,333 72 ERROR migration_db_migrated openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 178, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/module.py", line 300, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 2492, in _auto_init
    self._field_create(cr, context=context)
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 427, in _field_create
    dict(rec, module=context['module']))
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_model_data_module_name_uniq"
DETAIL:  Key (name, module)=(project_time_mode_id_duplicate_xmlid, project) already exists.

2019-05-16 07:16:55,335 72 CRITICAL migration_db_migrated openerp.service.server: Failed to initialize database `migration_db_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 178, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/module.py", line 300, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 2492, in _auto_init
    self._field_create(cr, context=context)
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 427, in _field_create
    dict(rec, module=context['module']))
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_model_data_module_name_uniq"
DETAIL:  Key (name, module)=(project_time_mode_id_duplicate_xmlid, project) already exists.
```

**Comment by pedrobaeza** [comment]
Delete your ir_model_data entry in previous version before migrating.

**Comment by thomaspaulb** [comment]
For the next lonely migrater arriving here: before migration it's in `sale_timesheet`, so this will do it:

```
delete from ir_model_data where module = 'sale_timesheet' and name = 'project_time_mode_id_duplicate_xmlid';
```
