### ISSUE TITLE
Installation Error for Branch 12

### ISSUE THREAD

**Issue by FelipeEnriqueGG** [OCA/OpenUpgrade#1876]
**Impacted versions:**
12.0
**Steps to reproduce:**
-Clone the repository OpenUpgrade branch 12.0
-Clone the repository openupgradelib
-run in CMD /opt/odoo/OpenUpgrade/odoo-bin
**Current behavior:**
-show this Error message:
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo-bin", line 5, in <module>
    import odoo
  File "/opt/odoo/OpenUpgrade/odoo/__init__.py", line 106, in <module>
    from . import modules
  File "/opt/odoo/OpenUpgrade/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/opt/odoo/OpenUpgrade/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/opt/odoo/OpenUpgrade/odoo/tools/__init__.py", line 10, in <module>
    from .convert import *
  File "/opt/odoo/OpenUpgrade/odoo/tools/convert.py", line 29, in <module>
    from odoo.openupgrade import openupgrade_log
  File "/opt/odoo/OpenUpgrade/odoo/openupgrade/openupgrade_log.py", line 6, in <module>
    from openupgradelib.openupgrade_tools import table_exists
ModuleNotFoundError: No module named 'openupgradelib'

**Expected behavior:**
-Correct installation

**Comment by pedrobaeza** [comment]
Install `openupgradelib` with the command stated in https://doc.therp.nl/openupgrade/migration_details.html
