### ISSUE TITLE
[12.0] mail: no unique constraint matching given keys for referenced table "mail_message_res_partner_needaction_rel"

### ISSUE THREAD

**Issue by davidtranhp** [OCA/OpenUpgrade#1892]
Impacted versions:
12.0

Steps to reproduce:
Migrate a v11 production database

Current behavior:
Error occured and migration was shutdown with error message as below
```
2019-06-21 10:12:32,139 13553 INFO prod_db_no_filestore odoo.modules.migration: module mail: Running migration [>12.0.1.0] pre-migration 
2019-06-21 10:12:32,318 13553 INFO prod_db_no_filestore OpenUpgrade: mail: pre-migration script called with version 11.0.1.0 
2019-06-21 10:12:32,318 13553 INFO prod_db_no_filestore OpenUpgrade: table res_partner, column opt_out: renaming to openupgrade_legacy_12_0_opt_out 
2019-06-21 10:12:32,318 13553 INFO prod_db_no_filestore OpenUpgrade: table mail_activity_type, column days: renaming to delay_count 
2019-06-21 10:12:32,565 13553 INFO prod_db_no_filestore odoo.modules.registry: module mail: creating or updating database tables 
2019-06-21 10:13:24,617 13553 ERROR prod_db_no_filestore odoo.sql_db: bad query: b'ALTER TABLE "mail_message_res_partner_needaction_rel_mail_resend_message_rel" ADD FOREIGN KEY ("mail_message_res_partner_needaction_rel_id") REFERENCES "mail_message_res_partner_needaction_rel"("id") ON DELETE cascade'
ERROR: there is no unique constraint matching given keys for referenced table "mail_message_res_partner_needaction_rel"
 
2019-06-21 10:13:24,644 13553 WARNING prod_db_no_filestore odoo.modules.loading: Transient module states were reset 
2019-06-21 10:13:24,654 13553 ERROR prod_db_no_filestore odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/user/git/openupgrade12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/user/git/openupgrade12/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/user/git/openupgrade12/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/user/git/openupgrade12/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/user/git/openupgrade12/odoo/modules/registry.py", line 301, in init_models
    func()
  File "/home/user/git/openupgrade12/odoo/fields.py", line 2683, in update_db_foreign_keys
    sql.add_foreign_key(cr, self.relation, self.column2, comodel._table, 'id', 'cascade')
  File "/home/user/git/openupgrade12/odoo/tools/sql.py", line 158, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/home/user/git/openupgrade12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/user/git/openupgrade12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: there is no unique constraint matching given keys for referenced table "mail_message_res_partner_needaction_rel"

**Comment by pedrobaeza** [comment]
This seems something in your end. Remove duplicated records on the indicated table for being able to put the unique. AFAIK, that unique condition was there also on v11.

**Comment by davidtranhp** [comment]
> This seems something in your end. Remove duplicated records on the indicated table for being able to put the unique. AFAIK, that unique condition was there also on v11.

Do you know from  where this comes? 
```
2019-06-21 10:13:24,617 13553 ERROR prod_db_no_filestore odoo.sql_db: bad query: b'ALTER TABLE "mail_message_res_partner_needaction_rel_mail_resend_message_rel" ADD FOREIGN KEY ("mail_message_res_partner_needaction_rel_id") REFERENCES "mail_message_res_partner_needaction_rel"("id") ON DELETE cascade'
```
mail_message_res_partner_needaction_rel_mail_resend_message_rel is not in v11.

**Comment by pedrobaeza** [comment]
The problem is in the table `mail_message_res_partner_needaction_rel`, that is not complying with the uniqueness condition.

**Comment by davidtranhp** [comment]
I have overcome this issue. Thanks @pedrobaeza for pointing out the root cause.
