### ISSUE TITLE
[12.0] account: KeyError: 'parent_id' during taxes search

### ISSUE THREAD

**Issue by davidtranhp** [OCA/OpenUpgrade#1893]
Impacted versions:
12.0

Steps to reproduce:
Migrate a v11 production database

Current behavior:
Error occured due to the following migration code
```python
def recompute_invoice_taxes_add_analytic_tags(env):
    analytic_taxes = env['account.tax'].search([('analytic', '=', True)])
    taxes = env['account.tax'].search([
        ('id', 'parent_of', analytic_taxes.ids),
    ])
    invoice_lines = env['account.invoice.line'].search(
        [('invoice_line_tax_ids', 'in', taxes.ids)])
    invoices = invoice_lines.mapped('invoice_id')
    for invoice in invoices:
        amount_total = invoice.amount_total
        with env.cr.savepoint():
            invoice.compute_taxes()
            if invoice.amount_total != amount_total:
                env.cr.rollback()
```
that generates the message as below
```
2019-06-21 11:33:35,637 25251 ERROR tvtma_v11_no_filestore OpenUpgrade: account: error in migration script account/migrations/12.0.1.1/post-migration.py: 'parent_id' 
2019-06-21 11:33:35,637 25251 ERROR tvtma_v11_no_filestore OpenUpgrade: 'parent_id' 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1495, in wrapped_function
    if use_env2 else cr, version)
  File "/home/tuan/git/openupgrade12/addons/account/migrations/12.0.1.1/post-migration.py", line 236, in migrate
    recompute_invoice_taxes_add_analytic_tags(env)
  File "/home/tuan/git/openupgrade12/addons/account/migrations/12.0.1.1/post-migration.py", line 195, in recompute_invoice_taxes_add_analytic_tags
    ('id', 'parent_of', analytic_taxes.ids),
  File "/home/tuan/git/openupgrade12/odoo/models.py", line 1568, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/tuan/git/openupgrade12/addons/account/models/account.py", line 984, in _search
    return super(AccountTax, self)._search(args, offset, limit, order, count=count, access_rights_uid=access_rights_uid)
  File "/home/tuan/git/openupgrade12/odoo/models.py", line 4111, in _search
    query = self._where_calc(args)
  File "/home/tuan/git/openupgrade12/odoo/models.py", line 3903, in _where_calc
    e = expression.expression(domain, self)
  File "/home/tuan/git/openupgrade12/odoo/osv/expression.py", line 672, in __init__
    self.parse()
  File "/home/tuan/git/openupgrade12/odoo/osv/expression.py", line 866, in parse
    dom = HIERARCHY_FUNCS[operator](left, ids2, model)
  File "/home/tuan/git/openupgrade12/odoo/osv/expression.py", line 789, in parent_of_domain
    record = record[parent_name]
  File "/home/tuan/git/openupgrade12/odoo/models.py", line 5124, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: 'parent_id'
2019-06-21 11:33:35,638 25251 ERROR tvtma_v11_no_filestore odoo.modules.loading: Error executing post migration script for module account
```
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@mreficent Indeed, there's no `parent_id` in taxes.

**Comment by MiquelRForgeFlow** [comment]
Fixed in https://github.com/OCA/OpenUpgrade/pull/1895.
