### ISSUE TITLE
[7.0 to 8.0] IOError: cannot identify image file > Initiating shutdown

### ISSUE THREAD

**Issue by raviprasadmr** [OCA/OpenUpgrade#1903]
Impacted versions: 7.0

Steps to reproduce:
Ran the migrate.py script as:
python OpenUpgrade-8.0/scripts/migrate.py --config=OpenUpgrade-8.0/openerp-server.conf --database=eg --run-migrations=8.0

openerp-server.conf has:
[options]
; This is the password that allows database operations:
; admin_passwd = admin
xmlrpc_port = 8069
db_host = False
db_port = False
db_user = odoo
db_password = xxxxx
addons_path = addons,../odoo-oca-addons,../odoo-eg-addons

Current behavior:
I end up with an error:
IOError: cannot identify image file <cStringIO.StringI object at 0x7fb86eb79e00>
2019-06-27 18:35:49,036 9756 INFO eg_migrated openerp.service.server: Initiating shutdown

Here is the log:

019-06-27 18:34:51,030 9756 DEBUG eg_migrated OpenUpgrade: 10375 rows affected
2019-06-27 18:34:51,035 9756 INFO eg_migrated OpenUpgrade: Moving data from 'product.product'.'image_variant' to 'product.template'.'image'
2019-06-27 18:35:48,937 9756 ERROR eg_migrated OpenUpgrade: product: error in migration script product/migrations/8.0.1.1/post-migration.py: IOError('cannot identify image file <cStringIO.StringI object at 0x7fb86eb79e00>',)
2019-06-27 18:35:48,937 9756 ERROR eg_migrated OpenUpgrade: cannot identify image file <cStringIO.StringI object at 0x7fb86eb79e00>
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1495, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/8.0/addons/product/migrations/8.0.1.1/post-migration.py", line 159, in migrate
    quick_request=False, binary_field=True)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1589, in move_field_m2o
    {field_new_model: res[1][:]})
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/addons/product/product.py", line 772, in write
    res = super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3831, in write
    self._write(old_vals)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4086, in _write
    cr, user, todo, fields_to_recompute, context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4465, in _store_set_values
    result = self._columns[val[0]].get(cr, self, ids, val, SUPERUSER_ID, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/var/tmp/openupgrade/8.0/addons/product/product.py", line 457, in _get_image
    result[obj.id] = tools.image_get_resized_images(obj.image, avoid_resize_medium=True)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/image.py", line 230, in image_get_resized_images
    return_dict[medium_name] = image_resize_image_medium(base64_source, avoid_if_small=avoid_resize_medium)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/image.py", line 168, in image_resize_image_medium
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/image.py", line 75, in image_resize_image
    image = Image.open(image_stream)
  File "/home/raviprasadmr/.local/lib/python2.7/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
IOError: cannot identify image file <cStringIO.StringI object at 0x7fb86eb79e00>
2019-06-27 18:35:48,996 9756 ERROR eg_migrated openerp.modules.loading: Error executing post migration script for module product
`-> procurement
   `-> stock
      `-> product_expiry
: cannot identify image file <cStringIO.StringI object at 0x7fb86eb79e00>
2019-06-27 18:35:49,002 9756 CRITICAL eg_migrated openerp.service.server: Failed to initialize database `eg_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 941, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 420, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 312, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 208, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1495, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/8.0/addons/product/migrations/8.0.1.1/post-migration.py", line 159, in migrate
    quick_request=False, binary_field=True)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1589, in move_field_m2o
    {field_new_model: res[1][:]})
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/addons/product/product.py", line 772, in write
    res = super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3831, in write
    self._write(old_vals)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4086, in _write
    cr, user, todo, fields_to_recompute, context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4465, in _store_set_values
    result = self._columns[val[0]].get(cr, self, ids, val, SUPERUSER_ID, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/var/tmp/openupgrade/8.0/addons/product/product.py", line 457, in _get_image
    result[obj.id] = tools.image_get_resized_images(obj.image, avoid_resize_medium=True)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/image.py", line 230, in image_get_resized_images
    return_dict[medium_name] = image_resize_image_medium(base64_source, avoid_if_small=avoid_resize_medium)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/image.py", line 168, in image_resize_image_medium
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/image.py", line 75, in image_resize_image
    image = Image.open(image_stream)
  File "/home/raviprasadmr/.local/lib/python2.7/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
IOError: cannot identify image file <cStringIO.StringI object at 0x7fb86eb79e00>
2019-06-27 18:35:49,036 9756 INFO eg_migrated openerp.service.server: Initiating shutdown
2019-06-27 18:35:49,037 9756 INFO eg_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

Expected behavior:
Should have not stopped the migration.

Video/Screenshot link (optional):

Please help!!

**Comment by pedrobaeza** [comment]
You have a binary file in one image field that is not an image. You must search inside your DB, but it's not OpenUpgrade fault.
