### ISSUE TITLE
[12] mass_mailing : Error related mail_mass_mailing_contact_list_rel.id

### ISSUE THREAD

**Issue by OthmaneGhandi** [OCA/OpenUpgrade#1992]
Impacted versions:
I got an error related to "mail_mass_mailing_contact_list_rel.id" while trying to migrate to V12

NB: I will try to fix it, I put it here maybe someone has already the solution or will solve it before me

`2019-08-27 15:57:02,485 7433 CRITICAL piavitaV12 odoo.service.server: Failed to initialize database `piavitaV12`. 
Traceback (most recent call last):
  File "/Users/othmaneghandi/OpenUpgrade/odoo/service/server.py", line 1116, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/Users/othmaneghandi/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/othmaneghandi/OpenUpgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/Users/othmaneghandi/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/Users/othmaneghandi/OpenUpgrade/odoo/modules/loading.py", line 194, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/Users/othmaneghandi/OpenUpgrade/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 1505, in wrapped_function
    if use_env2 else cr, version)
  File "/Users/othmaneghandi/OpenUpgrade/addons/mass_mailing/migrations/12.0.2.0/pre-migration.py", line 54, in migrate
    complete_mail_mass_mailing_contact_list_rel_db_layout(cr)
  File "/Users/othmaneghandi/OpenUpgrade/addons/mass_mailing/migrations/12.0.2.0/pre-migration.py", line 47, in complete_mail_mass_mailing_contact_list_rel_db_layout
    OWNED BY mail_mass_mailing_contact_list_rel.id""",
  File "/usr/local/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 986, in logged_query
    cr.execute(query, args)
  File "/Users/othmaneghandi/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/othmaneghandi/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.OperationalError: sequence must have same owner as table it is linked to`

**Comment by OthmaneGhandi** [comment]
I managed to solve this issue, you should verify that the owner of the table **`mail_mass_mailing_contact_list_rel`** is the same as the one who run openupgrade script

NB: 
=> the owner of the database can be different from the owner of the table
=> you can see the owners of tables by running this query 

```
select t.table_name, t.table_type, c.relname, c.relowner, u.usename
from information_schema.tables t
join pg_catalog.pg_class c on (t.table_name = c.relname)
join pg_catalog.pg_user u on (c.relowner = u.usesysid)
where t.table_schema='public';
```

**Comment by pedrobaeza** [comment]
This is not something related to OpenUpgrade itself, but how you run your Odoo and your OpenUpgrade instance. Closing then.

**Comment by OthmaneGhandi** [comment]
@pedrobaeza  Yeah, that's why I closed it. It may be useful for anyone who will face the same issue
