### ISSUE TITLE
Error analytic module "account_analytic_group" does not exist

### ISSUE THREAD

**Issue by esturao** [OCA/OpenUpgrade#1994]
Impacted versions: 11.0 -> 12.0

Steps to reproduce:
```
2019-08-28 17:45:37,387 879 INFO text_db odoo.modules.migration: module analytic: Running migration [>12.0.1.1] pre-migration 
2019-08-28 17:45:37,389 879 INFO text_db OpenUpgrade: analytic: pre-migration script called with version 11.0.1.1 
2019-08-28 17:45:37,392 879 ERROR text_db OpenUpgrade: analytic: error in migration script analytic/migrations/12.0.1.1/pre-migration.py: 'NoneType' object is not subscriptable 
2019-08-28 17:45:37,392 879 ERROR text_db OpenUpgrade: 'NoneType' object is not subscriptable 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib-2.0.0-py3.5.egg/openupgradelib/openupgrade.py", line 1496, in wrapped_function
    if use_env2 else cr, version)
  File "/OpenUpgrade/addons/analytic/migrations/12.0.1.1/pre-migration.py", line 16, in migrate
    openupgrade.copy_columns(cr, column_copies)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib-2.0.0-py3.5.egg/openupgradelib/openupgrade.py", line 366, in copy_columns
    field_type = cr.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
2019-08-28 17:45:37,399 879 WARNING text_db odoo.modules.loading: Transient module states were reset 
2019-08-28 17:45:37,402 879 ERROR text_db odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/OpenUpgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/OpenUpgrade/odoo/modules/loading.py", line 194, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/OpenUpgrade/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib-2.0.0-py3.5.egg/openupgradelib/openupgrade.py", line 1496, in wrapped_function
    if use_env2 else cr, version)
  File "/OpenUpgrade/addons/analytic/migrations/12.0.1.1/pre-migration.py", line 16, in migrate
    openupgrade.copy_columns(cr, column_copies)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib-2.0.0-py3.5.egg/openupgradelib/openupgrade.py", line 366, in copy_columns
    field_type = cr.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
2019-08-28 17:45:37,406 879 CRITICAL text_db odoo.service.server: Failed to initialize database `text_db`. 
Traceback (most recent call last):
  File "/OpenUpgrade/odoo/service/server.py", line 1116, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/OpenUpgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/OpenUpgrade/odoo/modules/loading.py", line 194, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/OpenUpgrade/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib-2.0.0-py3.5.egg/openupgradelib/openupgrade.py", line 1496, in wrapped_function
    if use_env2 else cr, version)
  File "/OpenUpgrade/addons/analytic/migrations/12.0.1.1/pre-migration.py", line 16, in migrate
    openupgrade.copy_columns(cr, column_copies)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib-2.0.0-py3.5.egg/openupgradelib/openupgrade.py", line 366, in copy_columns
    field_type = cr.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pedrobaeza** [comment]
Sorry, but you have something misconfigured, as the operation done there is the copy of the column `company_id` in `account_analytic_line` table. Nothing to do with module `account_analytic_group`.
