### ISSUE TITLE
openerp 7 to odoo 8 upgrade

### ISSUE THREAD

**Issue by maaathieu-x** [OCA/OpenUpgrade#202]
Hello,

The upgrade from openerp 7 to odoo 8 fails. 
In "/var/tmp/openupgrade/migration.log", I find this message: 

ParseError: "project.task" while parsing /var/tmp/openupgrade/8.0/server/openerp/addons/base/base_data.xml:123, near
<record id="public_partner" model="res.partner">
            <field name="name">Public user</field>
            <field name="active" eval="False"/>
        </record>

It seems related to the "public", but I don't have such a public user. 

Should I add this "public user" in order to perform the upgrade, or is this a bug ?

**Comment by legalsylvain** [comment]
Can you provide a more detailled log ?
Regards.

**Comment by maaathieu-x** [comment]
here is the content of /var/tmp/openupgrade/migration.log.
do you need someting else ? 

2015-03-06 15:14:14,486 3343 INFO ? openerp: OpenERP version 8.0
2015-03-06 15:14:14,493 3343 INFO ? openerp: addons paths: ['/var/lib/odoo/.local/share/Odoo/addons/8.0', u'/var/tmp/openupgrade/8.0/server/openerp/addons', u'/var/tmp/openupgrade/8.0/addons']
2015-03-06 15:14:14,493 3343 INFO ? openerp: database hostname: 127.0.0.1
2015-03-06 15:14:14,494 3343 INFO ? openerp: database port: 5432
2015-03-06 15:14:14,494 3343 INFO ? openerp: database user: openerp
2015-03-06 15:14:15,841 3343 INFO xilan_migrated openerp.modules.loading: loading 1 modules...
2015-03-06 15:14:15,931 3343 INFO xilan_migrated openerp.modules.migration: module base: Running migration [>8.0.1.3] pre-migration
2015-03-06 15:14:15,932 3343 INFO xilan_migrated openerp.modules.migration: module base: Running migration [>8.0.1.3] pre-migration
2015-03-06 15:14:16,036 3343 INFO xilan_migrated OpenUpgrade: base: pre-migration script called with version 7.0.1.3
2015-03-06 15:14:16,305 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_module_module SET name = procurement_jit WHERE name = mrp_jit
2015-03-06 15:14:16,306 3343 DEBUG xilan_migrated OpenUpgrade: 1 rows affected
2015-03-06 15:14:16,339 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_model_data SET module = procurement_jit WHERE module = mrp_jit 
2015-03-06 15:14:16,339 3343 DEBUG xilan_migrated OpenUpgrade: 0 rows affected
2015-03-06 15:14:16,402 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_module_module_dependency SET name = procurement_jit WHERE name = mrp_jit
2015-03-06 15:14:16,402 3343 DEBUG xilan_migrated OpenUpgrade: 1 rows affected
2015-03-06 15:14:16,403 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_module_module SET name = calendar WHERE name = base_calendar
2015-03-06 15:14:16,403 3343 DEBUG xilan_migrated OpenUpgrade: 1 rows affected
2015-03-06 15:14:16,689 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_model_data SET module = calendar WHERE module = base_calendar 
2015-03-06 15:14:16,689 3343 DEBUG xilan_migrated OpenUpgrade: 266 rows affected
2015-03-06 15:14:16,690 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_module_module_dependency SET name = calendar WHERE name = base_calendar
2015-03-06 15:14:16,690 3343 DEBUG xilan_migrated OpenUpgrade: 4 rows affected
2015-03-06 15:14:16,690 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_module_module SET name = account_invoice_validation_workflow WHERE name = invoice_validation_wkfl
2015-03-06 15:14:16,690 3343 DEBUG xilan_migrated OpenUpgrade: 0 rows affected
2015-03-06 15:14:16,690 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_model_data SET module = account_invoice_validation_workflow WHERE module = invoice_validation_wkfl 
2015-03-06 15:14:16,690 3343 DEBUG xilan_migrated OpenUpgrade: 0 rows affected
2015-03-06 15:14:16,691 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_module_module_dependency SET name = account_invoice_validation_workflow WHERE name = invoice_validation_wkfl
2015-03-06 15:14:16,691 3343 DEBUG xilan_migrated OpenUpgrade: 0 rows affected
2015-03-06 15:14:16,744 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_model_data SET module = base, name = group_public WHERE module = portal and name = group_anonymous
2015-03-06 15:14:16,744 3343 DEBUG xilan_migrated OpenUpgrade: 1 rows affected
2015-03-06 15:14:16,752 3343 DEBUG xilan_migrated OpenUpgrade: Running UPDATE ir_model_data SET module = base, name = group_portal WHERE module = portal and name = group_portal
2015-03-06 15:14:16,752 3343 DEBUG xilan_migrated OpenUpgrade: 1 rows affected
2015-03-06 15:14:16,965 3343 ERROR xilan_migrated OpenUpgrade: Invalid value 'tree_account_reconciliation' in the table 'ir_ui_view' for the field 'type'. (1 rows).
2015-03-06 15:14:17,132 3343 INFO xilan_migrated openerp.modules.module: module base: creating or updating database tables
2015-03-06 15:14:27,294 3343 INFO xilan_migrated openerp.models: storing computed values of fields.function 'crud_model_name'
2015-03-06 15:14:27,299 3343 INFO xilan_migrated openerp.models: storing computed values of fields.function 'wkf_model_name'
2015-03-06 15:14:27,300 3343 INFO xilan_migrated openerp.models: storing computed values of fields.function 'commercial_partner_id'
2015-03-06 15:14:27,890 3343 INFO xilan_migrated openerp.models: storing computed values of fields.function 'email'
2015-03-06 15:14:28,054 3343 INFO xilan_migrated openerp.models: storing computed values of fields.function 'phone'
2015-03-06 15:14:28,371 3343 INFO xilan_migrated openerp.modules.loading: loading base/base_data.xml
2015-03-06 15:14:28,559 3343 CRITICAL xilan_migrated openerp.service.server: Failed to initialize database `xilan_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 337, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 205, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 120, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 902, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 988, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 854, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 768, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_model.py", line 1064, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/res/res_partner.py", line 560, in create
    partner = super(res_partner, self).create(vals)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3965, in create
    vals = self._add_missing_default_values(vals)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 1839, in _add_missing_default_values
    defaults = self.default_get(cr, uid, list(missing_defaults), context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 1334, in default_get
    value = record[name]
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 5454, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/var/tmp/openupgrade/8.0/server/openerp/fields.py", line 714, in **get**
    record.add_default_value(self)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 1379, in add_default_value
    field.determine_default(self)
  File "/var/tmp/openupgrade/8.0/server/openerp/fields.py", line 826, in determine_default
    record._cache[self] = SpecialValue(self.null(record.env))
  File "/var/tmp/openupgrade/8.0/server/openerp/fields.py", line 1303, in null
    return env[self.comodel_name]
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 720, in __getitem__
    return self.registry[model_name]._browse(self, ())
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 100, in __getitem__
    return self.models[model_name]
ParseError: "project.task" while parsing /var/tmp/openupgrade/8.0/server/openerp/addons/base/base_data.xml:123, near
<record id="public_partner" model="res.partner">
            <field name="name">Public user</field>
            <field name="active" eval="False"/>
        </record>
2015-03-06 15:14:28,616 3343 INFO xilan_migrated openerp.service.server: Initiating shutdown
2015-03-06 15:14:28,616 3343 INFO xilan_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by pedrobaeza** [comment]
Closing due to inactivity
