### ISSUE TITLE
[12.0] constraint "web_planner_create_uid_fkey" of relation "web_planner" does not exist

### ISSUE THREAD

**Issue by GSLabIt** [OCA/OpenUpgrade#2022]
Impacted versions: 12.0

Steps to reproduce:
updating from 11.0

Current behavior:
raise an error:

```
2019-09-16 16:27:58,346 11159 ERROR gslab odoo.sql_db: bad query: b'ALTER TABLE web_planner DROP CONSTRAINT web_planner_create_uid_fkey'
ERROR: constraint "web_planner_create_uid_fkey" of relation "web_planner" does not exist

2019-09-16 16:27:58,346 11159 ERROR gslab OpenUpgrade: Error running ALTER TABLE web_planner DROP CONSTRAINT web_planner_create_uid_fkey
2019-09-16 16:27:58,346 11159 ERROR gslab OpenUpgrade: web: error in migration script web/migrations/12.0.1.0/pre-migration.py: constraint "web_planner_create_uid_fkey" of relation "web_planner" does not exist

2019-09-16 16:27:58,347 11159 ERROR gslab OpenUpgrade: constraint "web_planner_create_uid_fkey" of relation "web_planner" does not exist

Traceback (most recent call last):
  File "/Users/giovanni/dev/odoo-dev/openupgrade/venv-3.7/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 1642, in wrapped_function
    if use_env2 else cr, version)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/addons/web/migrations/12.0.1.0/pre-migration.py", line 27, in migrate
    remove_web_planner_constraints(env)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/addons/web/migrations/12.0.1.0/pre-migration.py", line 21, in remove_web_planner_constraints
    (AsIs(constraint), ),
  File "/Users/giovanni/dev/odoo-dev/openupgrade/venv-3.7/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 1112, in logged_query
    cr.execute(query, args)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: constraint "web_planner_create_uid_fkey" of relation "web_planner" does not exist

2019-09-16 16:27:58,360 11159 WARNING gslab odoo.modules.loading: Transient module states were reset
2019-09-16 16:27:58,362 11159 ERROR gslab odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 194, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/venv-3.7/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 1642, in wrapped_function
    if use_env2 else cr, version)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/addons/web/migrations/12.0.1.0/pre-migration.py", line 27, in migrate
    remove_web_planner_constraints(env)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/addons/web/migrations/12.0.1.0/pre-migration.py", line 21, in remove_web_planner_constraints
    (AsIs(constraint), ),
  File "/Users/giovanni/dev/odoo-dev/openupgrade/venv-3.7/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 1112, in logged_query
    cr.execute(query, args)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: constraint "web_planner_create_uid_fkey" of relation "web_planner" does not exist
```

Expected behavior:
i think it should drop key only if exists 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Did you remove somehow `web_planner` module in v11?

**Comment by GSLabIt** [comment]
seems it is missed in OpenUgrade 12.0, is that correct?

https://github.com/OCA/OpenUpgrade/tree/12.0/addons/web_planner

**Comment by pedrobaeza** [comment]
Yes, that's why we do that, but I'm talking about v11. There's no way that constraint doesn't exist in v11 unless you manually have manipulated that database for not having it (as the module is mandatory there).

**Comment by GSLabIt** [comment]
I honestly never worked on that table, so not sure why they are missing. Btw i could update web_planner on 11.0 and retry. Will let u know. 

In the meanwhile i'm getting another error:
```
2019-09-16 17:14:48,557 12092 ERROR gslab odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 483, in load_modules
    registry.setup_models(cr)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 264, in setup_models
    model._setup_base()
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/models.py", line 2583, in _setup_base
    self._add_field(name, field.new())
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/models.py", line 302, in _add_field
    field.setup_base(self, name)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/fields.py", line 414, in setup_base
    self._setup_regular_base(model)
  File "/Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/fields.py", line 1935, in _setup_regular_base
    assert self.selection is not None, "Field %s without selection" % self
AssertionError: Field res.users.odoobot_state without selection
```

is that related in some way?

**Comment by pedrobaeza** [comment]
Not sure, but a migration ended that way can lead to that.

**Comment by GSLabIt** [comment]
i've solved the web_planner issue, but still getting:

```
2019-09-16 18:39:48,102 13389 ERROR mydb odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/Users/odoo/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/odoo/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/Users/odoo/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/Users/odoo/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 211, in load_module_graph
    registry.setup_models(cr)
  File "/Users/odoo/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 264, in setup_models
    model._setup_base()
  File "/Users/odoo/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/models.py", line 2583, in _setup_base
    self._add_field(name, field.new())
  File "/Users/odoo/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/models.py", line 302, in _add_field
    field.setup_base(self, name)
  File "/Users/odoo/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/fields.py", line 414, in setup_base
    self._setup_regular_base(model)
  File "/Users/odoo/dev/odoo-dev/openupgrade/OpenUpgrade/odoo/fields.py", line 1935, in _setup_regular_base
    assert self.selection is not None, "Field %s without selection" % self
AssertionError: Field res.users.odoobot_state without selection
```

it seems `res.users.odoobot_state` is not getting default field value, any hint?

Thx

**Comment by pedrobaeza** [comment]
But that field is populated by a module (`mail_bot`) that shouldn't be installed, so your environment must be somehow mixed for loading this.

**Comment by pedrobaeza** [comment]
Any way, closing this.

**Comment by GSLabIt** [comment]
@pedrobaeza fyi, the problem was the module mail_bot set as auto_install. So for some reason, it is updated when using -u all; that's end to the error.  I made an workaround ad it seems to solve the issue.
