### ISSUE TITLE
[11.0] AttributeError: 'Composed' object has no attribute 'lower'

### ISSUE THREAD

**Issue by WeeDom** [OCA/OpenUpgrade#2028]
Impacted versions:
11.0
Steps to reproduce:
After fixing previous issue here https://github.com/OCA/OpenUpgrade/issues/2026
I ran
`./odoo-bin --update all --stop-after-init -d miningsearchesuk`

and it did loads of good looking stuff - table renaming, column renaming, etc and then:

Current behavior:
```
2019-09-18 15:41:28,198 12 DEBUG miningsearchesuk odoo.sql_db: query: Composed([SQL('ALTER TABLE '), Identifier('ir_cron'), SQL(' ADD COLUMN '), Identifier('ir_actions_server_id'), SQL(' '), SQL('int4')])
2019-09-18 15:41:28,200 12 ERROR miningsearchesuk OpenUpgrade: base: error in migration script base/migrations/11.0.1.3/pre-migration.py: 'Composed' object has no attribute 'lower'
2019-09-18 15:41:28,200 12 ERROR miningsearchesuk OpenUpgrade: 'Composed' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1642, in wrapped_function
    if use_env2 else cr, version)
  File "/home/openupgrade/odoo/addons/base/migrations/11.0.1.3/pre-migration.py", line 104, in migrate
    fill_cron_action_server_pre(env)
  File "/home/openupgrade/odoo/addons/base/migrations/11.0.1.3/pre-migration.py", line 51, in fill_cron_action_server_pre
    'base'),
  File "/usr/local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 2088, in add_fields
    sql.SQL(sql_type),
  File "/usr/local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1112, in logged_query
    cr.execute(query, args)
  File "/home/openupgrade/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/openupgrade/odoo/sql_db.py", line 245, in execute
    res_from = re_from.match(query.lower())
AttributeError: 'Composed' object has no attribute 'lower'
```
Expected behavior:

finish upgrade successfully

Is there any other information I can supply?

**Comment by pedrobaeza** [comment]
Related to https://github.com/OCA/openupgradelib/commit/004e8983fda0782e4698f5fa8e91728df7ea8215

**Comment by WeeDom** [comment]
I've just run `pip3 install git+git://github.com/OCA/openupgradelib.git` and got the same error... checked out the openupgrade master branch, and `git branch --contains 004e898` says master has it. 

Any ideas?

**Comment by WeeDom** [comment]
```
Step 30/34 : RUN pip3 install git+git://github.com/OCA/openupgradelib.git                               
 ---> Running in 27307ed9e8e9                                                                                
Collecting git+git://github.com/OCA/openupgradelib.git                                                       
  Cloning git://github.com/OCA/openupgradelib.git to /tmp/pip-eipafi8b-build                                  
Requirement already satisfied: lxml in /usr/local/lib/python3.6/site-packages (from openupgradelib==3.0.0)
```

from my `docker build` output

**Comment by yajo** [comment]
Disable sql logging. `logged_query` already logs important queries.

**Comment by pedrobaeza** [comment]
So, where is the problem?

**Comment by yajo** [comment]
This one: https://github.com/odoo/odoo/pull/37267

**Comment by pedrobaeza** [comment]
OK, so it's not a problem of OpenUpgrade itself. @WeeDom just disable sql logging. In fact, that verbose level is insane. OpenUpgrade already provides proper queries debugging.
