### ISSUE TITLE
[12.0]hr_recruitment wrong model interpretation ?

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#2036]
Hi everyone,

I'm migrating from v10 to v12.0. The v11.0 version is migrated and then I'm trying to update to the v12.
during the upgrade process I have this issues :
```
 hr_recruitment/data/hr_recruitment_data.xml 
2019-09-23 21:24:44,481 17674 WARNING mag_10_to_be_migrated odoo.modules.loading: Transient module states were reset 
2019-09-23 21:24:44,491 17674 ERROR mag_10_to_be_migrated odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/tools/convert.py", line 600, in _tag_record
    record = self.env['ir.model.data']._load_xmlid(xid)
  File "/home/florent/DEV/_EclipseOdoo/Mag10Migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 1573, in _load_xmlid
    record = self.xmlid_to_object(xml_id)
  File "/home/florent/DEV/_EclipseOdoo/Mag10Migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 1445, in xmlid_to_object
    record = self.env[res_model].browse(res_id)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/api.py", line 821, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'hr.applicant_category'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/modules/loading.py", line 249, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/tools/convert.py", line 807, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/tools/convert.py", line 870, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/tools/convert.py", line 760, in parse
    self.parse(rec, mode)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/tools/convert.py", line 769, in parse
    exc_info[2]
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/tools/convert.py", line 600, in _tag_record
    record = self.env['ir.model.data']._load_xmlid(xid)
  File "/home/florent/DEV/_EclipseOdoo/Mag10Migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 1573, in _load_xmlid
    record = self.xmlid_to_object(xml_id)
  File "/home/florent/DEV/_EclipseOdoo/Mag10Migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 1445, in xmlid_to_object
    record = self.env[res_model].browse(res_id)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/api.py", line 821, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/home/florent/DEV/Odoo_Server_And_Libs/OpenUpgrade/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
odoo.tools.convert.ParseError: "hr.applicant_category" while parsing /home/florent/DEV/_EclipseOdoo/Mag10Migration/OpenUpgrade/addons/hr_recruitment/data/hr_recruitment_data.xml:346, near
<record id="tag_applicant_reserve" model="hr.applicant.category">
        <field name="name">Reserve</field>
    </record>
```

In the hr module of course there is no hr.applicant_category as model but there is hr.applicant.category
What could be the origin of this misinterpretation of the model name during the upgrade?

Regards

**Comment by pedrobaeza** [comment]
I think this is a leftover you have from an old migration. Does this DB have been in < v11 version before?

**Comment by flotho** [comment]
Hi @pedrobaeza ,
You're right, this db was created in v8.
I suppose that the recommendation is to use the famous https://github.com/OCA/server-tools/tree/12.0/database_cleanup module in v10 before all the migration process.

Regards

**Comment by pedrobaeza** [comment]
Well, in fact the renaming is not being done in the proper version. See #2038 for the fix. Not critical consequences any way for not having that renaming done. For your case, passing `database_cleanup` will remove that model and then you will be able to continue the migration.

**Comment by flotho** [comment]
hum....
I add more info there 
I used database cleanup on a v10 with hr.recruitment and check all the columns, model etc.. 
Then I run successfully a v11 migration, yet I still have the issue on the v12.
The solution is to delete xml ids https://github.com/OCA/OpenUpgrade/pull/2038/files#diff-de508521f8eba7465e12bca9cd52afaeb6b9f4bd7998f24c78a6dff32356da33R15

**Comment by pedrobaeza** [comment]
The problem is if you migrated before the patch. In that case, indeed you have to do other thing, like deleting the XML-IDs.

**Comment by flotho** [comment]
and recreating it, or better, changing the definition to match ,
Thanks for your crystal clear explanations, this part is clearly solved for me
