### ISSUE TITLE
9.0 -> 10.0: website pre-migration: ImportError: cannot import name convert_html_fragment

### ISSUE THREAD

**Issue by treviser** [OCA/OpenUpgrade#2037]
Everything runs smoothly, until it comes to the website migration. I'm running OpenUpgrade manually on an Ubuntu 16.04 LTS server.
Is there any hint how I can troubleshoot this issue?

Here's my traceback:

```
2019-09-24 07:06:50,006 1834 INFO flohmarkt-zug odoo.models: Actual recompute of field ir.ui.view.model_data_id for 1 recs.
2019-09-24 07:06:50,023 1834 INFO flohmarkt-zug odoo.addons.base.ir.ir_translation: module web_settings_dashboard: loading translation file (de) for language de_DE
2019-09-24 07:06:50,023 1834 INFO flohmarkt-zug odoo.tools.translate: loading /openupgrade/10/OpenUpgrade-10.0/addons/web_settings_dashboard/i18n/de.po
2019-09-24 07:06:50,078 1834 INFO flohmarkt-zug odoo.models: Actual recompute of field ir.module.module.views_by_module for 1 recs.
2019-09-24 07:06:50,119 1834 ERROR flohmarkt-zug odoo.modules.migration: module website: Unable to load pre-migration file website/migrations/10.0.1.0/pre-migration.py
Traceback (most recent call last):
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/migration.py", line 166, in migrate_module
    mod = imp.load_module(name, fp, pathname, ('.py', 'r', imp.PY_SOURCE))
  File "/openupgrade/10/OpenUpgrade-10.0/addons/website/migrations/10.0.1.0/pre-migration.py", line 7, in <module>
    from openupgradelib.openupgrade_tools import (
ImportError: cannot import name convert_html_fragment
2019-09-24 07:06:50,122 1834 WARNING flohmarkt-zug odoo.modules.loading: Transient module states were reset
2019-09-24 07:06:50,124 1834 ERROR flohmarkt-zug odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/loading.py", line 441, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/loading.py", line 326, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/loading.py", line 146, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/migration.py", line 166, in migrate_module
    mod = imp.load_module(name, fp, pathname, ('.py', 'r', imp.PY_SOURCE))
  File "/openupgrade/10/OpenUpgrade-10.0/addons/website/migrations/10.0.1.0/pre-migration.py", line 7, in <module>
    from openupgradelib.openupgrade_tools import (
ImportError: cannot import name convert_html_fragment
2019-09-24 07:06:50,125 1834 CRITICAL flohmarkt-zug odoo.service.server: Failed to initialize database `flohmarkt-zug`.
Traceback (most recent call last):
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/service/server.py", line 974, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/loading.py", line 441, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/loading.py", line 326, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/loading.py", line 146, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/openupgrade/10/OpenUpgrade-10.0/odoo/modules/migration.py", line 166, in migrate_module
    mod = imp.load_module(name, fp, pathname, ('.py', 'r', imp.PY_SOURCE))
  File "/openupgrade/10/OpenUpgrade-10.0/addons/website/migrations/10.0.1.0/pre-migration.py", line 7, in <module>
    from openupgradelib.openupgrade_tools import (
ImportError: cannot import name convert_html_fragment
2019-09-24 07:06:50,126 1834 INFO flohmarkt-zug odoo.service.server: Initiating shutdown
2019-09-24 07:06:50,126 1834 INFO flohmarkt-zug odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```

**Comment by pedrobaeza** [comment]
Outdated openupgradelib. Install the newest one with:
```
pip install git+git://github.com/OCA/openupgradelib.git
```

**Comment by treviser** [comment]
@pedrobaeza Thank you for your answer. I did install the newest version of openupgradelib as you have indicated, nevertheless I do face the exact same error.
