### ISSUE TITLE
[11.0] unaffected earnings

### ISSUE THREAD

**Issue by WeeDom** [OCA/OpenUpgrade#2048]
Impacted versions:
11.0
Steps to reproduce:
run `/odoo-bin --update all --stop-after-init --dev=all -d miningsearchesuk` from 11.0 repo

Current behavior:
It does lots and lots of things, then I get this output:
```19-10-01 14:44:20,484 65 INFO miningsearchesuk odoo.models: Actual recompute of field ir.actions.server.model_name for 1 recs.
2019-10-01 14:44:20,736 65 ERROR miningsearchesuk odoo.sql_db: bad query: b'INSERT INTO "account_financial_html_report_line" ("id", "name", "groupby", "special_date_changer", "show_domain", "domain", "formulas", "level", "green_on_positive", "figure_type", "code", "parent_id", "sequence", "hide_if_zero", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval(\'account_financial_html_report_line_id_seq\'), \'Unallocated Earnings\', NULL, \'normal\', \'foldable\', \'[]\', \'balance = CURR_YEAR_EARNINGS.balance + PREV_YEAR_EARNINGS.balance\', 1, true, \'float\', \'UNAFFECTED_EARNINGS\', 25, 1, false, 1, 1, (now() at time zone \'UTC\'), (now() at time zone \'UTC\')) RETURNING id'
ERROR: duplicate key value violates unique constraint "account_financial_html_report_line_code_uniq"
DETAIL:  Key (code)=(UNAFFECTED_EARNINGS) already exists.

2019-10-01 14:44:20,745 65 WARNING miningsearchesuk odoo.modules.loading: Transient module states were reset
2019-10-01 14:44:20,747 65 ERROR miningsearchesuk odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/openupgrade/odoo/tools/convert.py", line 749, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/openupgrade/odoo/tools/convert.py", line 659, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/openupgrade/odoo/addons/base/ir/ir_model.py", line 1570, in _update
    record = record.create(values)
  File "/home/openupgrade/odoo/models.py", line 3419, in create
    record = self.browse(self._create(old_vals))
  File "/home/openupgrade/odoo/models.py", line 3512, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/openupgrade/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/openupgrade/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "account_financial_html_report_line_code_uniq"
DETAIL:  Key (code)=(UNAFFECTED_EARNINGS) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/openupgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openupgrade/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/openupgrade/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/openupgrade/odoo/modules/loading.py", line 207, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/openupgrade/odoo/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/openupgrade/odoo/tools/convert.py", line 796, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/openupgrade/odoo/tools/convert.py", line 857, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/openupgrade/odoo/tools/convert.py", line 746, in parse
    self.parse(rec, mode)
  File "/home/openupgrade/odoo/tools/convert.py", line 756, in parse
    exc_info[2]
  File "/home/openupgrade/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/openupgrade/odoo/tools/convert.py", line 749, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/openupgrade/odoo/tools/convert.py", line 659, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/openupgrade/odoo/addons/base/ir/ir_model.py", line 1570, in _update
    record = record.create(values)
  File "/home/openupgrade/odoo/models.py", line 3419, in create
    record = self.browse(self._create(old_vals))
  File "/home/openupgrade/odoo/models.py", line 3512, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/openupgrade/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/openupgrade/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "account_financial_html_report_line_code_uniq"
DETAIL:  Key (code)=(UNAFFECTED_EARNINGS) already exists.
" while parsing /usr/lib/python3/dist-packages/odoo/addons/account_reports/data/account_financial_report_data.xml:283, near
<record id="account_financial_unaffected_earnings0" model="account.financial.html.report.line">
            <field name="name">Unallocated Earnings</field>
            <field name="code">UNAFFECTED_EARNINGS</field>
            <field name="domain">[]</field>
            <field name="formulas">balance = CURR_YEAR_EARNINGS.balance + PREV_YEAR_EARNINGS.balance</field>
            <field name="sequence" eval="1"/>
            <field name="special_date_changer">normal</field>
            <field name="parent_id" ref="account_financial_report_equity0"/>
            <field name="level" eval="1"/>
        </record>
2019-10-01 14:44:20,754 65 CRITICAL miningsearchesuk odoo.service.server: Failed to initialize database `miningsearchesuk`.
Traceback (most recent call last):
  File "/home/openupgrade/odoo/tools/convert.py", line 749, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/openupgrade/odoo/tools/convert.py", line 659, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/openupgrade/odoo/addons/base/ir/ir_model.py", line 1570, in _update
    record = record.create(values)
  File "/home/openupgrade/odoo/models.py", line 3419, in create
    record = self.browse(self._create(old_vals))
  File "/home/openupgrade/odoo/models.py", line 3512, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/openupgrade/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/openupgrade/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "account_financial_html_report_line_code_uniq"
DETAIL:  Key (code)=(UNAFFECTED_EARNINGS) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/openupgrade/odoo/service/server.py", line 1006, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/openupgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openupgrade/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/openupgrade/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/openupgrade/odoo/modules/loading.py", line 207, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/openupgrade/odoo/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/openupgrade/odoo/tools/convert.py", line 796, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/openupgrade/odoo/tools/convert.py", line 857, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/openupgrade/odoo/tools/convert.py", line 746, in parse
    self.parse(rec, mode)
  File "/home/openupgrade/odoo/tools/convert.py", line 756, in parse
    exc_info[2]
  File "/home/openupgrade/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/openupgrade/odoo/tools/convert.py", line 749, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/openupgrade/odoo/tools/convert.py", line 659, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/openupgrade/odoo/addons/base/ir/ir_model.py", line 1570, in _update
    record = record.create(values)
  File "/home/openupgrade/odoo/models.py", line 3419, in create
    record = self.browse(self._create(old_vals))
  File "/home/openupgrade/odoo/models.py", line 3512, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/openupgrade/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/openupgrade/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "account_financial_html_report_line_code_uniq"
DETAIL:  Key (code)=(UNAFFECTED_EARNINGS) already exists.
" while parsing /usr/lib/python3/dist-packages/odoo/addons/account_reports/data/account_financial_report_data.xml:283, near
<record id="account_financial_unaffected_earnings0" model="account.financial.html.report.line">
            <field name="name">Unallocated Earnings</field>
            <field name="code">UNAFFECTED_EARNINGS</field>
            <field name="domain">[]</field>
            <field name="formulas">balance = CURR_YEAR_EARNINGS.balance + PREV_YEAR_EARNINGS.balance</field>
            <field name="sequence" eval="1"/>
            <field name="special_date_changer">normal</field>
            <field name="parent_id" ref="account_financial_report_equity0"/>
            <field name="level" eval="1"/>
        </record>
2019-10-01 14:44:20,756 65 INFO miningsearchesuk odoo.service.server: Initiating shutdown
2019-10-01 14:44:20,756 65 INFO miningsearchesuk odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
odoo@689ed3476033:/home/openupgrade$
```

There is, indeed, an entry in my db with that code. Can I safely delete it from my db, or comment the xml block out in the xml file?

Expected behavior:

Complete upgrade

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
`account_reports` is not an OpenUpgrade module. You have to add migration scripts for that one.

**Comment by WeeDom** [comment]
thanks for the quick response
