### ISSUE TITLE
Error upgrading v9 to v10, after upgrading v8 to v9

### ISSUE THREAD

**Issue by roberto-barreiro** [OCA/OpenUpgrade#2057]
Impacted versions: v10

Steps to reproduce: upgrade from v8 to v9, and then v9 to v10

```
2019-10-13 15:24:53,167 14641 ERROR dgm OpenUpgrade: base: error in migration script base/migrations/10.0.1.3/post-migration.py: TypeError('merge_records() takes at least 5 arguments (4 given)',)
2019-10-13 15:24:53,167 14641 ERROR dgm OpenUpgrade: merge_records() takes at least 5 arguments (4 given)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/openupgrade/odoo/addons/base/migrations/10.0.1.3/post-migration.py", line 141, in migrate
    merge_country_states(env)
  File "/opt/openupgrade/odoo/addons/base/migrations/10.0.1.3/post-migration.py", line 72, in merge_country_states
    correct_country_states[-1].id,
TypeError: merge_records() takes at least 5 arguments (4 given)
2019-10-13 15:24:53,168 14641 ERROR dgm odoo.modules.loading: Error executing post migration script for module base
: merge_records() takes at least 5 arguments (4 given)
2019-10-13 15:24:53,171 14641 WARNING dgm odoo.modules.loading: Transient module states were reset
2019-10-13 15:24:53,172 14641 ERROR dgm odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/openupgrade/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openupgrade/odoo/modules/loading.py", line 375, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/opt/openupgrade/odoo/modules/loading.py", line 211, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/openupgrade/odoo/modules/migration.py", line 178, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/openupgrade/odoo/addons/base/migrations/10.0.1.3/post-migration.py", line 141, in migrate
    merge_country_states(env)
  File "/opt/openupgrade/odoo/addons/base/migrations/10.0.1.3/post-migration.py", line 72, in merge_country_states
    correct_country_states[-1].id,
TypeError: merge_records() takes at least 5 arguments (4 given)
2019-10-13 15:24:53,175 14641 INFO dgm werkzeug: 192.168.0.3 - - [13/Oct/2019 15:24:53] "GET / HTTP/1.1" 500 -
2019-10-13 15:24:53,180 14641 ERROR dgm werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/openupgrade/odoo/service/server.py", line 307, in app
    return self.app(e, s)
  File "/opt/openupgrade/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/opt/openupgrade/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/openupgrade/odoo/http.py", line 1326, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/openupgrade/odoo/http.py", line 1300, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/openupgrade/odoo/http.py", line 1482, in dispatch
    odoo.registry(db).check_signaling()
  File "/opt/openupgrade/odoo/__init__.py", line 52, in registry
    return modules.registry.Registry(database_name)
  File "/opt/openupgrade/odoo/modules/registry.py", line 59, in __new__
    return cls.new(db_name)
  File "/opt/openupgrade/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openupgrade/odoo/modules/loading.py", line 375, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/opt/openupgrade/odoo/modules/loading.py", line 211, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/openupgrade/odoo/modules/migration.py", line 178, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/openupgrade/odoo/addons/base/migrations/10.0.1.3/post-migration.py", line 141, in migrate
    merge_country_states(env)
  File "/opt/openupgrade/odoo/addons/base/migrations/10.0.1.3/post-migration.py", line 72, in merge_country_states
    correct_country_states[-1].id,
TypeError: merge_records() takes at least 5 arguments (4 given)
```

**Comment by pedrobaeza** [comment]
You must have an incorrect openupgradelib version, as you can see here:

https://github.com/OCA/openupgradelib/blob/5a0a2369e08a141a9a5bc8f091c4fc0522b07fa3/openupgradelib/openupgrade_merge_records.py#L468
