### ISSUE TITLE
Error alter table account_chart_template and update stock_picking_type tables

### ISSUE THREAD

**Issue by ggdnstyle** [OCA/OpenUpgrade#2062]
Impacted versions: 11 to 12 upgrade

Steps to reproduce: When I try to upgrade from 11 to 12 version with openupgrade.
I launch this command : OpenUpgrade/odoo-bin --addons-path OpenUpgrade/addons --database Vimaflore_test --update all --stop-after-init --logfile migration.log

Current behavior: 

ERROR Vimaflore_test odoo.sql_db: bad query: ALTER TABLE "account_chart_template" ALTER COLUMN "transfer_account_code_prefix" SET NOT NULL
ERROR: column "transfer_account_code_prefix" contains null values

2019-10-21 12:59:35,649 95751 WARNING Vimaflore_test odoo.schema: Table 'account_chart_template': unable to set NOT NULL on column 'transfer_account_code_prefix'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "account_chart_template" ALTER COLUMN "transfer_account_code_prefix" SET NOT NULL
Traceback (most recent call last):
  File "/odoo/OpenUpgrade/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: column "transfer_account_code_prefix" contains null values

Other error : 

2019-10-21 13:00:13,181 95751 DEBUG Vimaflore_test OpenUpgrade: Deleting record for XML-ID mrp.sequence_mrp_prod
2019-10-21 13:00:13,187 95751 ERROR Vimaflore_test odoo.sql_db: bad query: DELETE FROM ir_sequence WHERE id IN (13)
ERROR: null value in column "sequence_id" violates not-null constraint
DETAIL:  Failing row contains (21, Fabrication, 0, 15, null, 27, 27, mrp_operation, null, f, 3, t, t, f, f, t, null, 1, 2018-10-28 15:31:54.362968, 1, 2019-10-21 12:59:59.142238, null).
CONTEXT:  SQL statement "UPDATE ONLY "public"."stock_picking_type" SET "sequence_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "sequence_id""

2019-10-21 13:00:13,188 95751 ERROR Vimaflore_test OpenUpgrade: Error deleting XML-ID mrp.sequence_mrp_prod: NotNullViolation('null value in column "sequence_id" violates not-null constraint\nDETAIL:  Failing row contains (21, Fabrication, 0, 15, null, 27, 27, mrp_operation, null, f, 3, t, t, f, f, t, null, 1, 2018-10-28 15:31:54.362968, 1, 2019-10-21 12:59:59.142238, null).\nCONTEXT:  SQL statement "UPDATE ONLY "public"."stock_picking_type" SET "sequence_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "sequence_id""\n',)

I have tried the update process several times, but I still have the same mistakes. I am novice and I am really confused about how to proceed

Expected behavior:

The upgrade failed, but I have some other errors that I put in another issue

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That are not blocking errors. Why are you reporting them?

**Comment by ggdnstyle** [comment]
Because my migration fails and I look for what's wrong. I am novice I am sorry

**Comment by ggdnstyle** [comment]
> That are not blocking errors. Why are you reporting them?

**Comment by pedrobaeza** [comment]
Then please put which is the error that stops the migration process.

**Comment by ggdnstyle** [comment]
> Then please put which is the error that stops the migration process.

In fact, I did have critical error in POS module, but for continue migration I removed POS module. 
The critical error is : 

2019-10-22 09:44:25,969 101912 ERROR Vimaflore_test odoo.sql_db: bad query: INSERT INTO "product_template" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "available_in_pos", "categ_id", "company_id", "list_price", "produce_delay", "purchase_line_warn", "purchase_method", "purchase_ok", "rental", "responsible_id", "sale_delay", "sale_ok", "sequence", "to_weight", "tracking", "type", "uom_id", "uom_po_id") VALUES (nextval('product_template_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), true, true, 12, 1, '1.00', 0.0, 'no-message', 'receive', true, false, 1, 0.0, true, 1, false, 'none', 'consu', 1, 1) RETURNING id
ERROR: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (77, null, 1, null, null, null, consu, f, 12, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2019-10-22 09:44:03.505063, 1, 2019-10-22 09:44:03.505063, 1, 0, none, null, null, null, null, null, 0, null, null, null, null, null, t, f, null, receive, no-message, null, null, null, null).

2019-10-22 09:44:25,969 101912 ERROR Vimaflore_test OpenUpgrade: point_of_sale: error in migration script point_of_sale/migrations/12.0.1.0.1/post-migration.py: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (77, null, 1, null, null, null, consu, f, 12, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2019-10-22 09:44:03.505063, 1, 2019-10-22 09:44:03.505063, 1, 0, none, null, null, null, null, null, 0, null, null, null, null, null, t, f, null, receive, no-message, null, null, null, null).
" while parsing /odoo/OpenUpgrade/addons/point_of_sale/migrations/12.0.1.0.1/noupdate_changes.xml:3, near
<record id="product_product_consumable" model="product.product">
    <field name="categ_id" ref="point_of_sale.product_category_pos"/>
    <field name="available_in_pos">True</field>
  </record>
2019-10-22 09:44:25,970 101912 ERROR Vimaflore_test OpenUpgrade: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (77, null, 1, null, null, null, consu, f, 12, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2019-10-22 09:44:03.505063, 1, 2019-10-22 09:44:03.505063, 1, 0, none, null, null, null, null, null, 0, null, null, null, null, null, t, f, null, receive, no-message, null, null, null, null).
" while parsing /odoo/OpenUpgrade/addons/point_of_sale/migrations/12.0.1.0.1/noupdate_changes.xml:3, near
<record id="product_product_consumable" model="product.product">
    <field name="categ_id" ref="point_of_sale.product_category_pos"/>
    <field name="available_in_pos">True</field>
  </record>
...

Traceback (most recent call last):
  File "/odoo/OpenUpgrade/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/OpenUpgrade/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/OpenUpgrade/odoo/models.py", line 3878, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/OpenUpgrade/odoo/models.py", line 3792, in _load_records_create
    return self.create(values)
  File "<decorator-gen-142>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/product/models/product.py", line 342, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-116>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/odoo/models.py", line 3567, in create
for data in parent_data_list
  File "<decorator-gen-131>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/product/models/product_template.py", line 348, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-116>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/odoo/models.py", line 3573, in create
    records = self._create(data_list)
  File "/odoo/OpenUpgrade/odoo/models.py", line 3673, in _create
    cr.execute(query, params)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (77, null, 1, null, null, null, consu, f, 12, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2019-10-22 09:44:03.505063, 1, 2019-10-22 09:44:03.505063, 1, 0, none, null, null, null, null, null, 0, null, null, null, null, null, t, f, null, receive, no-message, null, null, null, null).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1644, in wrapped_function
    if use_env2 else cr, version)
  File "/odoo/OpenUpgrade/addons/point_of_sale/migrations/12.0.1.0.1/post-migration.py", line 22, in migrate
    cr, 'point_of_sale', 'migrations/12.0.1.0.1/noupdate_changes.xml')
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 302, in load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode=mode)
  File "/odoo/OpenUpgrade/odoo/tools/convert.py", line 870, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/OpenUpgrade/odoo/tools/convert.py", line 769, in parse
    exc_info[2]
  File "/odoo/OpenUpgrade/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/OpenUpgrade/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/OpenUpgrade/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/OpenUpgrade/odoo/models.py", line 3878, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/OpenUpgrade/odoo/models.py", line 3792, in _load_records_create
    return self.create(values)
  File "<decorator-gen-142>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/product/models/product.py", line 342, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-116>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
File "/odoo/OpenUpgrade/odoo/models.py", line 3567, in create
    for data in parent_data_list
  File "<decorator-gen-131>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/product/models/product_template.py", line 348, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-116>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/odoo/models.py", line 3573, in create
    records = self._create(data_list)
  File "/odoo/OpenUpgrade/odoo/models.py", line 3673, in _create
    cr.execute(query, params)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (77, null, 1, null, null, null, consu, f, 12, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2019-10-22 09:44:03.505063, 1, 2019-10-22 09:44:03.505063, 1, 0, none, null, null, null, null, null, 0, null, null, null, null, null, t, f, null, receive, no-message, null, null, null, null).
" while parsing /odoo/OpenUpgrade/addons/point_of_sale/migrations/12.0.1.0.1/noupdate_changes.xml:3, near
<record id="product_product_consumable" model="product.product">
    <field name="categ_id" ref="point_of_sale.product_category_pos"/>
    <field name="available_in_pos">True</field>
  </record>
2019-10-22 09:44:26,074 101912 ERROR Vimaflore_test odoo.modules.loading: Error executing post migration script for module point_of_sale
`-> pos_reprint
: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (77, null, 1, null, null, null, consu, f, 12, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2019-10-22 09:44:03.505063, 1, 2019-10-22 09:44:03.505063, 1, 0, none, null, null, null, null, null, 0, null, null, null, null, null, t, f, null, receive, no-message, null, null, null, null).
" while parsing /odoo/OpenUpgrade/addons/point_of_sale/migrations/12.0.1.0.1/noupdate_changes.xml:3, near
<record id="product_product_consumable" model="product.product">
    <field name="categ_id" ref="point_of_sale.product_category_pos"/>
    <field name="available_in_pos">True</field>
  </record>
2019-10-22 09:44:26,084 101912 WARNING Vimaflore_test odoo.modules.loading: Transient module states were reset
2019-10-22 09:44:26,136 101912 ERROR Vimaflore_test odoo.modules.registry: Failed to load registry
...
2019-10-22 09:44:26,142 101912 CRITICAL Vimaflore_test odoo.service.server: Failed to initialize database `Vimaflore_test`.
Traceback (most recent call last):
  File "/odoo/OpenUpgrade/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/OpenUpgrade/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/OpenUpgrade/odoo/models.py", line 3878, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/OpenUpgrade/odoo/models.py", line 3792, in _load_records_create
    return self.create(values)
  File "<decorator-gen-142>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/product/models/product.py", line 342, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-116>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/odoo/models.py", line 3567, in create
    for data in parent_data_list
  File "<decorator-gen-131>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/product/models/product_template.py", line 348, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-116>", line 2, in create
File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/OpenUpgrade/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/odoo/OpenUpgrade/odoo/models.py", line 3573, in create
    records = self._create(data_list)
  File "/odoo/OpenUpgrade/odoo/models.py", line 3673, in _create
    cr.execute(query, params)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (77, null, 1, null, null, null, consu, f, 12, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2019-10-22 09:44:03.505063, 1, 2019-10-22 09:44:03.505063, 1, 0, none, null, null, null, null, null, 0, null, null, null, null, null, t, f, null, receive, no-message, null, null, null, null).
....

Do you think these are error messages ?

**Comment by pedrobaeza** [comment]
This is because you have removed some data from that module. You have to upgrade all your modules in previous version before trying to migrate, and that records will be restored, so they don't give error when migrating.

**Comment by ggdnstyle** [comment]
> This is because you have removed some data from that module. You have to upgrade all your modules in previous version before trying to migrate, and that records will be restored, so they don't give error when migrating.

Ok, thanks for your reply. Can you tell me how to upgrade modules in version 11?
I don't know how to do modules updates.

**Comment by pedrobaeza** [comment]
Just press the "Update" button in module base or `-u all` in command line. This is out of scope of OpenUpgrade and it's basic stuff.

**Comment by ggdnstyle** [comment]
> Just press the "Update" button in module base or `-u all` in command line. This is out of scope of OpenUpgrade and it's basic stuff.

👍  I will try and I will tell you if it's good

**Comment by ggdnstyle** [comment]
Hi, for information, I updated all module before upgrading to version 12 but I have always theses error messages.
If I don't remove POS module, migration fails.
