### ISSUE TITLE
[8.0 -> 9.0] fail to migrate sale /purchase module (UoS / UoM not the same category)

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#2075]
Hi all,

I’m currently working on a migration from 8 to 12, and I have a problem with a step of the migration `sale` in the migration from 8.0 to 9.0.

Step to reproduce with a fresh Odoo 8.0 version with sale and stock installed : 

**Configuration**

considering a product, named : « Oil »
uom_id : kilo
uos_id : Liter

![image](https://user-images.githubusercontent.com/3407482/67863809-e623a180-fb24-11e9-9c7b-bf4b9ef38e87.png)

![image](https://user-images.githubusercontent.com/3407482/67863792-db690c80-fb24-11e9-8c23-3ef971e385f8.png)

When I realize a sale in V8, here is a sale.order.line : 

![image](https://user-images.githubusercontent.com/3407482/67863893-0bb0ab00-fb25-11e9-9a04-5ad86f545b34.png)

**Here is the picking :** 

![image](https://user-images.githubusercontent.com/3407482/67863943-1ff4a800-fb25-11e9-8f81-dab658f43aad.png)

**here is the invoice :** 

![image](https://user-images.githubusercontent.com/3407482/67863984-3438a500-fb25-11e9-955d-dfee0d7a17b9.png)

**Log during OpenUpgrade migration**

```
2019-10-30 14:00:27,917 22895 INFO test_unite openerp.modules.module: module sale: creating or updating database tables
2019-10-30 14:00:28,732 22895 WARNING test_unite openerp.models.schema: Table `sale_config_settings`: column `module_website_quote` has changed type (DB=bool, def=selection), data moved to column `module_website_quote_moved0`
2019-10-30 14:00:28,736 22895 WARNING test_unite openerp.models.schema: Table `sale_config_settings`: column `group_discount_per_so_line` has changed type (DB=bool, def=selection), data moved to column `group_discount_per_so_line_moved0`
2019-10-30 14:00:28,739 22895 WARNING test_unite openerp.models.schema: Table `sale_config_settings`: column `module_sale_margin` has changed type (DB=bool, def=selection), data moved to column `module_sale_margin_moved0`
2019-10-30 14:00:28,747 22895 WARNING test_unite openerp.models.schema: Table `sale_config_settings`: column `group_uom` has changed type (DB=bool, def=selection), data moved to column `group_uom_moved0`
2019-10-30 14:00:28,750 22895 WARNING test_unite openerp.models.schema: Table `sale_config_settings`: column `group_sale_delivery_address` has changed type (DB=bool, def=selection), data moved to column `group_sale_delivery_address_moved0`
2019-10-30 14:00:28,869 22895 INFO test_unite openerp.models: Storing computed values of sale.order fields invoice_status
2019-10-30 14:00:28,871 22895 INFO test_unite openerp.models: Storing computed values of sale.order.line fields currency_id, invoice_status, price_reduce, price_subtotal, price_tax, price_total, qty_invoiced, qty_to_invoice
2019-10-30 14:00:28,891 22895 INFO test_unite openerp.models: Actual recompute of field sale.order.line.currency_id for 22 recs.
2019-10-30 14:00:28,932 22895 INFO test_unite openerp.models: Actual recompute of field sale.order.line.price_subtotal for 22 recs.
2019-10-30 14:00:29,095 22895 INFO test_unite openerp.models: Actual recompute of field sale.order.line.price_reduce for 22 recs.
2019-10-30 14:00:29,147 22895 INFO test_unite openerp.models: Actual recompute of field sale.order.amount_total for 9 recs.
2019-10-30 14:00:29,179 22895 INFO test_unite openerp.models: Actual recompute of field sale.order.line.qty_invoiced for 22 recs.
2019-10-30 14:00:29,221 22895 ERROR test_unite openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/modules/loading.py", line 178, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/modules/module.py", line 317, in init_module_models
    obj_list[0].recompute(cr, openerp.SUPERUSER_ID, {})
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/models.py", line 5951, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/models.py", line 5951, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/models.py", line 5818, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/fields.py", line 832, in __get__
    self.determine_value(record)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/fields.py", line 916, in determine_value
    self.compute_value(recs)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/fields.py", line 896, in compute_value
    self._compute_value(records)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/fields.py", line 886, in _compute_value
    getattr(records, self.compute)()
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/addons/sale/sale.py", line 552, in _get_invoice_qty
    qty_invoiced += self.env['product.uom']._compute_qty_obj(invoice_line.uom_id, invoice_line.quantity, line.product_uom)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/grap_dev/grap-odoo-upgrade/src/grap-odoo-env_09.0-open-upgrade/src/odoo/addons/product/product.py", line 122, in _compute_qty_obj
    raise UserError(_('Conversion from Product UoM %s to Default UoM %s is not possible as they both belong to different Category!.') % (from_unit.name,to_unit.name))
UserError: (u'Conversion from Product UoM Liter(s) to Default UoM kg is not possible as they both belong to different Category!.', None)
```

Another similar bug is referenced here https://github.com/OCA/OpenUpgrade/issues/629 by @jbeficent, but it is closed, and the error is not exactly the same because, in the other case, there was a null value. here not.

Do you have an idea, how to fix it ? I'm OK to make a PR against OpenUpgrade, but I really don't know how to fix this "normal usage of Odoo".

CC : @StefanRijnhart, @pedrobaeza, @sebastienbeau

**Comment by pedrobaeza** [comment]
Ouch, difficult question... This is a gap in Odoo code itself. Let me put you the general picture and possible solutions, but not easy...:

- In v8, you have in module `product` the fields UoS for product, in `sale` module the one for sales order line, and in `account` the field for invoice lines.
- But in v9, everything is handled in core in UoM, leaving a residual module `product_uos`.
- This module adds the UoS at product and sales order line level, but not on invoice line.
- In fact, the v8 UoS field in invoice lines is renamed to current UoM v9 field (there were no UoM at v8).
- The difference is now that in v9, you always invoice in UoM, no matter the UoS (which is a bit misleading at user level, doing the SO in one unit and invoice in another), but this prevents the conversion problem that you have faced in standard v9.

So, what to do?

1. Change before doing this computation all the invoice lines to use the quantity and the UoM instead of the UoS for mimicking the v9 behavior, but the information is altered, and you will find inconsistent information in PDFs, journal items, etc, so not very recommended.
2. If product UoS is from different category than product UoM, create a new UoM with same name as the product UoS, but in the same category than product UoM (can be archived?), and with conversion factor equivalent to the one you put in UoS coeff. Then replace UoS in invoice lines by this new UoM. A dirty hack, but can do the trick.

**Comment by StefanRijnhart** [comment]
That summarizes it nicely @pedrobaeza! @legalsylvain I guess with the benefit of hindsight it was a bug in Odoo to allow UoS from a different category than the UoM.

**Comment by legalsylvain** [comment]
Hi ! 
First, thanks a lot for this exhaustive analysis. Community rocks !

Here is the current requests I executed to pass the migration. I realized the same for purchase order, as I had the same problem. 
(Note, my db is 9 years old (2010) and comes from 3 previous migrations 5 -> 6.1 -> 7.0 -> 8.0. Thanks to openUpgrade project.)

For the time being, it is the approach 1 (of @pedrobaeza comment) because it is the easier way to move forward but it is the _not very recommanded_ one. ;-)

### Sale
before, migration, If ``sale.order.line`` uom categ != ``account.invoice.line`` uos categ, replace invoice line uos by order line uom.

    UPDATE account_invoice_line ail
    SET uos_id = sol.product_uom
    FROM sale_order_line_invoice_rel rel,
        sale_order_line sol,
        product_uom pu_sol,
        product_uom pu_ail
    WHERE sol.id = rel.order_line_id
    AND ail.id = rel.invoice_id
    AND pu_sol.id = sol.product_uom
    AND pu_ail.id = ail.uos_id
    AND pu_sol.category_id != pu_ail.category_id;

### Purchase
before, migration, If ``purchase.order.line`` uom categ != ``account.invoice.line`` uos categ, replace invoice line uos by order line uom.

    UPDATE account_invoice_line ail
    SET uos_id = pol.product_uom
    FROM purchase_order_line_invoice_rel rel,
        purchase_order_line pol,
        product_uom pu_pol,
        product_uom pu_ail
    WHERE pol.id = rel.order_line_id
    AND ail.id = rel.invoice_id
    AND pu_pol.id = pol.product_uom
    AND pu_ail.id = ail.uos_id
    AND pu_pol.category_id != pu_ail.category_id;


If this solution is not acceptable for the OCA, i can develop the second one.
(in some weeks, because first I want to identify all the problems from 8.0 -> 12.0)

FIY, i'm currently facing with the very similar problem that uos is optional in invoice line, but uom is mandatory in sale and purchase line. I opened another issue, because I think that the fix is easier to do.
(#2076)

**Comment by pedrobaeza** [comment]
You have to change also quantity in account.invoice.line, or computations won't match. For OCA, I would prefer solution 2. Any way, see that few people uses UoS in this way or this would raise before.

**Comment by StefanRijnhart** [comment]
Agreed with @pedrobaeza . Or maybe we should just add a check query to detect whether this occurs in the database and then raise an exception referring to this issue. People can then decide which hack to apply themselves manually.

**Comment by miscs** [comment]
Hi all,

I think I just ran into the same problem, could anybody confirm this by looking at my log below? That would help me a lot!
If so I will try the suggested solutions above.

Thanks
Stephan

```
2019-12-16 10:40:49,368 3935 ERROR migratedb_migrated OpenUpgrade: Found these mismatching UoM in related sale.order.line and account.invoice.line records: [{'invoice_line_id': 4981,
  'invoice_line_product_id': 1,
  'invoice_line_product_template_name': u'Development',
  'invoice_line_uom_category_id': 3,
  'invoice_line_uom_id': 20,
  'order_line_id': 343,
  'order_line_product_id': 4,
  'order_line_uom_category_id': 1,
  'order_line_uom_id': 1},

```

**Comment by pedrobaeza** [comment]
Yes, that's the problem put in a prettier way since last merged PRs.

**Comment by miscs** [comment]
Perfect, thank you again!

**Comment by pedrobaeza** [comment]
Closing as stalled.
