### ISSUE TITLE
[11.0 -> 12.0] Failed to migrate website field is_published

### ISSUE THREAD

**Issue by Danoolo** [OCA/OpenUpgrade#2082]
Impacted versions: OpenUpgrade 12.0

Steps to reproduce:
Trying to migrate an odoo 11.0 instance to 12.0 with openupgrade

Current behavior:
```
2019-11-14 18:37:04,723 15368 CRITICAL AP12.0 odoo.service.server: Failed to initialize database `AP12.0`. 
Traceback (most recent call last):
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/service/server.py", line 1118, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 194, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib-3.0.0-py3.6.egg/openupgradelib/openupgrade.py", line 1691, in wrapped_function
    if use_env2 else cr, version)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/addons/website/migrations/12.0.1.0/pre-migration.py", line 332, in migrate
    openupgrade.rename_fields(env, _field_renames)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib-3.0.0-py3.6.egg/openupgradelib/openupgrade.py", line 561, in rename_fields
    """, (new_field, old_field, model),
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "ir_model_fields_name_unique"
DETAIL:  Key (model, name)=(website.page, is_published) already exists.
```
Expected behavior:
Apply migration scripts to this module.

Hi guys!!...the error marks that a duplicate field 'is_published' for 'website.page' exists but i didn't see any duplicate field in that model even for third party modules...anyways reading the pre-migration script for website im not sure if _field_renames variable is well written..thanks in advance.

**Comment by pedrobaeza** [comment]
Scripts are working in several migrations I have done. Check why you have an `ir.model.fields` record for `is_published` prior to this renaming.

Why do you say the `_field_renames` variable is not well written?

**Comment by Danoolo** [comment]
Hi Pedro, thanks for answering me...i said that because of format in that list of tuple, i thought it was (old_name, new_name) but i have to read this specific variable in openupgrade.py api. I'll try your advises and give feedback...thanks again Pedro!

**Comment by Danoolo** [comment]
Well...someway there was that column in table ` ir.model.fields`, but i never introduced in some own or third module...could it be because i migrate and fix errors in the same db backup?....
ps: I read openupgrade api and make up my mind with _field_renames variable how is built.

**Comment by flotho** [comment]
Hi @Danoolo 

How did you solved this issue?
I have the same issue coming from the v10 and the field didn't exists in the v10.
