### ISSUE TITLE
Migration from 11.0 to 12.0 error: The user cannot have more than one user types

### ISSUE THREAD

**Issue by GabbasovDinar** [OCA/OpenUpgrade#2086]
Hello, after migrating Odoo 11.0 to Odoo 12.0, I try to update the `website` module, but I have an error: 

```
2019-11-20 07:03:40,779 1 INFO dixion12 odoo.modules.loading: loading website/security/website_security.xml 
2019-11-20 07:03:41,058 1 WARNING dixion12 odoo.modules.loading: Transient module states were reset 
2019-11-20 07:03:41,059 1 ERROR dixion12 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/odoo/src/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/src/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/src/odoo/models.py", line 3811, in _load_records
    data['record']._load_records_write(data['values'])
  File "/odoo/src/odoo/models.py", line 3749, in _load_records_write
    self.write(values)
  File "/odoo/src/addons/mail/models/res_users.py", line 157, in write
    write_res = super(res_groups_mail_channel, self).write(vals)
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 976, in write
    res = super(GroupsView, self).write(values)
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 881, in write
    res = super(GroupsImplied, self).write(values)
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 181, in write
    return super(Groups, self).write(vals)
  File "/odoo/src/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/odoo/src/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/odoo/src/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 113, in _check_one_user_type
    self.mapped('users')._check_one_user_type()
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 399, in _check_one_user_type
    raise ValidationError(_('The user cannot have more than one user types.'))
odoo.exceptions.ValidationError: ('The user cannot have more than one user types.', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/src/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/src/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/odoo/src/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/src/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo/src/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/src/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/src/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/src/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/odoo/src/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/src/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/src/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/src/odoo/models.py", line 3811, in _load_records
    data['record']._load_records_write(data['values'])
  File "/odoo/src/odoo/models.py", line 3749, in _load_records_write
    self.write(values)
  File "/odoo/src/addons/mail/models/res_users.py", line 157, in write
    write_res = super(res_groups_mail_channel, self).write(vals)
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 976, in write
    res = super(GroupsView, self).write(values)
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 881, in write
    res = super(GroupsImplied, self).write(values)
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 181, in write
    return super(Groups, self).write(vals)
  File "/odoo/src/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/odoo/src/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/odoo/src/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 113, in _check_one_user_type
    self.mapped('users')._check_one_user_type()
  File "/odoo/src/odoo/addons/base/models/res_users.py", line 399, in _check_one_user_type
    raise ValidationError(_('The user cannot have more than one user types.'))
odoo.tools.convert.ParseError: "The user cannot have more than one user types.
None" while parsing /odoo/src/addons/website/security/website_security.xml:7, near
<record id="group_website_designer" model="res.groups">
        <field name="name">Editor and Designer</field>
        <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]"/>
        <field name="implied_ids" eval="[(4, ref('group_website_publisher'))]"/>
        <field name="category_id" ref="base.module_category_website"/>
    </record>
2019-11-20 07:03:41,062 1 ERROR dixion12 odoo.http: Exception during JSON request handling. 
```

How can I fix it? 
Thanks

**Comment by GabbasovDinar** [comment]
I was able to solve the problem myself

**Comment by colmeirin** [comment]
Hello, I'm facing the same issue and I was wondering if you could explain how did you solved it @GabbasovDinar ?
Thank you.

**Comment by GabbasovDinar** [comment]
Hello @colmeirin 
It's means the user has two groups of the same object. You need to check which the user and which the group has the problem. For example, if user has the next groups:
`account.group_show_line_subtotals_tax_included`
`account.group_show_line_subtotals_tax_excluded`
you will get the same error.

I found the problem user and remove an extra group

**Comment by colmeirin** [comment]
Thank you! It was an user within portal and employee group.
Regards!

**Comment by sebastienclaude** [comment]
Hello,
thanks for you tip but could you tell me more on how to find the problem . I don't know where to find the redundant user or group...

**Comment by cubells** [comment]
@sebastienclaude 
user can't belong to groups `Tax display B2B` and `Tax display B2C` at the same time.

**Comment by pedrobaeza** [comment]
In fact this has nothing to do with that groups, but with the simultaneous belonging to "Employee", "Portal" and "Public" groups.

**Comment by david-birtum** [comment]
Thanks @pedrobaeza . In my case someone else  put the user **Default User Template** as Portal,  and when i tried to install  Manufacturing module, i generated that error, I just put it again as  Employee type

**Comment by ivantodorovich** [comment]
I've encountered the same thing in one of our databases.

I've solved it with this script, and I'm currently running it on all migrated databases

```py
    # Fix users in conflicting groups.
    _logger.info('Fixing users with conflicting groups')
    users = env['res.users'].search([])
    for user in users:
        if (
            user.has_group('base.group_user') and
            (
                user.has_group('base.group_portal')
                or user.has_group('base.group_public')
            )
        ):
            _logger.warning('Conflict in user groups: %s' % user.name)
            user.groups_id = [
                (3, env.ref('base.group_portal').id),
                (3, env.ref('base.group_public').id),
            ]
        if (
            user.has_group('base.group_portal')
            and user.has_group('base.group_public')
        ):
            _logger.warning('Conflict in public groups: %s' % user.name)
            user.groups_id = [
                (3, env.ref('base.group_public').id),
            ]
```

I don't know if it makes sense to add it to openugprade because the error is actually reporting a misconfiguration, and I'm not sure we should solve it automatically.. but IDK. I'm sharing this in case someone else needs it

**Comment by pedrobaeza** [comment]
Yes, it's not possible to determine automatically which is the correct group to keep, so it should be done manually.

**Comment by matmicro** [comment]
> I've encountered the same thing in one of our databases.
> 
> I've solved it with this script, and I'm currently running it on all migrated databases
> 
> ```python
>     # Fix users in conflicting groups.
>     _logger.info('Fixing users with conflicting groups')
>     users = env['res.users'].search([])
>     for user in users:
>         if (
>             user.has_group('base.group_user') and
>             (
>                 user.has_group('base.group_portal')
>                 or user.has_group('base.group_public')
>             )
>         ):
>             _logger.warning('Conflict in user groups: %s' % user.name)
>             user.groups_id = [
>                 (3, env.ref('base.group_portal').id),
>                 (3, env.ref('base.group_public').id),
>             ]
>         if (
>             user.has_group('base.group_portal')
>             and user.has_group('base.group_public')
>         ):
>             _logger.warning('Conflict in public groups: %s' % user.name)
>             user.groups_id = [
>                 (3, env.ref('base.group_public').id),
>             ]
> ```
> 
> I don't know if it makes sense to add it to openugprade because the error is actually reporting a misconfiguration, and I'm not sure we should solve it automatically.. but IDK. I'm sharing this in case someone else needs it

Hi @ivantodorovich 

Where to you run this script ?
Is it a script to past into "migration" folder of a specify module ?
How to run it from command line ?

Thanks for your help
