### ISSUE TITLE
V11 to V12 stock rule table not present

### ISSUE THREAD

**Issue by ictpackc** [OCA/OpenUpgrade#2101]
Impacted versions: 
12

Steps to reproduce:
Migrate a version 11 database to version 12 database

Current behavior:
2019-12-04 12:41:08,349 8084 INFO afr12 odoo.models: Storing computed values of stock.rule.route_sequence 
2019-12-04 12:41:08,494 8084 ERROR afr12 odoo.sql_db: bad query: ALTER TABLE "stock_warehouse" ADD FOREIGN KEY ("mto_pull_id") REFERENCES "stock_rule"("id") ON DELETE set null
ERROR: insert or update on table "stock_warehouse" violates foreign key constraint "stock_warehouse_mto_pull_id_fkey"
DETAIL:  Key (mto_pull_id)=(42) is not present in table "stock_rule".
 
2019-12-04 12:41:08,497 8084 WARNING afr12 odoo.modules.loading: Transient module states were reset 
2019-12-04 12:41:08,516 8084 ERROR afr12 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/odoo/OpenUpgrade/odoo/modules/registry.py", line 301, in init_models
    func()
  File "/opt/odoo/OpenUpgrade/odoo/fields.py", line 2158, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/opt/odoo/OpenUpgrade/odoo/tools/sql.py", line 185, in fix_foreign_key
    return add_foreign_key(cr, tablename1, columnname1, tablename2, columnname2, ondelete)
  File "/opt/odoo/OpenUpgrade/odoo/tools/sql.py", line 158, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: insert or update on table "stock_warehouse" violates foreign key constraint "stock_warehouse_mto_pull_id_fkey"
DETAIL:  Key (mto_pull_id)=(42) is not present in table "stock_rule".

2019-12-04 12:41:08,518 8084 CRITICAL afr12 odoo.service.server: Failed to initialize database `afr12`. 
Traceback (most recent call last):
  File "/opt/odoo/OpenUpgrade/odoo/service/server.py", line 1118, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/OpenUpgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/odoo/OpenUpgrade/odoo/modules/registry.py", line 301, in init_models
    func()
  File "/opt/odoo/OpenUpgrade/odoo/fields.py", line 2158, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/opt/odoo/OpenUpgrade/odoo/tools/sql.py", line 185, in fix_foreign_key
    return add_foreign_key(cr, tablename1, columnname1, tablename2, columnname2, ondelete)
  File "/opt/odoo/OpenUpgrade/odoo/tools/sql.py", line 158, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: insert or update on table "stock_warehouse" violates foreign key constraint "stock_warehouse_mto_pull_id_fkey"
DETAIL:  Key (mto_pull_id)=(42) is not present in table "stock_rule".
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because you are migrating a DB with extra modules (I guess it's `stock_mts_mto_rule`), and that one doesn't have migration scripts, so it's something to add to it, but not in OpenUpgrade.
