### ISSUE TITLE
Error in migration script pre-migration.py: Duplicate Table

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#2103]
When I try to do a migration from Odoo 9.0 to 10.0, the migration stop with this error message:
``` python
2019-12-05 10:39:19,410 65 INFO migration_db_migrated odoo.sql_db: bad query: ALTER INDEX IF EXISTS "product_attribute_line_product_attribute_value_rel_val_id_index" RENAME TO "product_attribute_line_product_attribute_value_rel_product_attribute_value_id_index"
2019-12-05 10:39:19,410 65 ERROR migration_db_migrated OpenUpgrade: product: error in migration script product/migrations/10.0.1.2/pre-migration.py: DuplicateTable('relation "product_attribute_line_product_attribute_value_rel_product_attr" already exists\n',)
2019-12-05 10:39:19,410 65 ERROR migration_db_migrated OpenUpgrade: relation "product_attribute_line_product_attribute_value_rel_product_attr" already exists
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1691, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/product/migrations/10.0.1.2/pre-migration.py", line 28, in migrate
    openupgrade.rename_columns(cr, _column_renames)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 520, in rename_columns
    (table, old, table, new)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
DuplicateTable: relation "product_attribute_line_product_attribute_value_rel_product_attr" already exists

2019-12-05 10:39:19,414 65 WARNING migration_db_migrated odoo.modules.loading: Transient module states were reset
2019-12-05 10:39:19,422 65 ERROR migration_db_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 441, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 326, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 146, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 178, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1691, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/product/migrations/10.0.1.2/pre-migration.py", line 28, in migrate
    openupgrade.rename_columns(cr, _column_renames)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 520, in rename_columns
    (table, old, table, new)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
DuplicateTable: relation "product_attribute_line_product_attribute_value_rel_product_attr" already exists
```

I use the latest version of OpenUpgrade.

**Comment by pedrobaeza** [comment]
This is something being discussed here: https://github.com/OCA/openupgradelib/pull/173
