### ISSUE TITLE
[8.0 -> 9.0] fast_compute_cash_basis -> DataError: division by zero 

### ISSUE THREAD

**Issue by miscs** [OCA/OpenUpgrade#2121]
Hi all,

I am trying to migrate from 8 to 9 and installed openupgradelib 3.0.0 and psycopg2 2.7.
I am getting a "DataError: division by zero" in account/migrations/9.0.1.1/post-migration.py.

I found a similar error googling, which said the currency exchange rate must not be 0. But I don´t think thats the case in my data, because it is set to 1.

Any hints would be highly appreciated!

Thanks in advance
Stephan

relevant log (if something important is missing, I can attach the whole log):

````
2019-12-15` 21:03:18,359 13732 INFO migratedb_migrated OpenUpgrade: Executing method fast_compute_cash_basis
2019-12-15 21:03:18,437 13732 INFO migratedb_migrated openerp.sql_db: bad query: 
            UPDATE account_move
            SET matched_percentage = sub.matched_percentage
            FROM (
                SELECT
                    aml.move_id,
                    CASE
                        WHEN 0.0 = ROUND(
                            SUM(ABS(COALESCE(aml.debit, 0.0) - COALESCE(aml.credit, 0.0))),
                            CASE
                                WHEN MAX(COALESCE(rc.rounding, 0)) BETWEEN 0 AND 1
                                THEN CEIL(LOG(1 / MAX(rc.rounding)))
                                ELSE 0
                            END::INTEGER
                        )
                        THEN 1.0
                        ELSE SUM(COALESCE(apr.amount, 0)) / SUM(ABS(COALESCE(aml.debit, 0) - COALESCE(aml.credit, 0)))
                    END AS matched_percentage
                FROM
                    account_move_line aml
                    LEFT JOIN account_partial_reconcile apr
                    ON aml.id = apr.credit_move_id OR aml.id = apr.debit_move_id
                    LEFT JOIN res_currency rc ON aml.currency_id = rc.id
                    LEFT JOIN account_account_type aat ON aml.user_type_id = aat.id
                WHERE aat.type IN ('receivable', 'payable')
                GROUP BY aml.move_id
            ) AS sub
            WHERE id = sub.move_id
        
2019-12-15 21:03:18,437 13732 ERROR migratedb_migrated OpenUpgrade: account: error in migration script account/migrations/9.0.1.1/post-migration.py: DataError('division by zero\n',)
2019-12-15 21:03:18,437 13732 ERROR migratedb_migrated OpenUpgrade: division by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1694, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1310, in migrate
    fast_compute_cash_basis(env)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1631, in wrapped_function
    return func(*args, **kwargs)
	File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1011, in fast_compute_cash_basis
	    """,
	  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1161, in logged_query
	    cr.execute(query, args)
	  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
	    return f(self, *args, **kwargs)
	  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
	    res = self._obj.execute(query, params)
	DataError: division by zero

	2019-12-15 21:03:18,438 13732 ERROR migratedb_migrated openerp.modules.loading: Error executing post migration script for module account
	`-> account_accountant
	   `-> account_asset
	   `-> hr_expense
	      `-> sale_expense
	`-> account_bank_statement_import
	`-> account_budget
	`-> account_cancel
	`-> account_full_reconcile
	`-> account_voucher
	`-> base_iban
	`-> base_vat
	   `-> l10n_de
	`-> payment
	   `-> payment_transfer
	: division by zero

	2019-12-15 21:03:18,493 13732 ERROR migratedb_migrated openerp.modules.registry: Failed to load registry
	Traceback (most recent call last):
	  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
	    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
	  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
	    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
	  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
	    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
	  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 214, in load_module_graph
	    migrations.migrate_module(package, 'post')
	  File "/var/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 170, in migrate_module
	    mod.migrate(self.cr, installed_version)
	  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1694, in wrapped_function
	    if use_env2 else cr, version)
		File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1310, in migrate
		    fast_compute_cash_basis(env)
		  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1631, in wrapped_function
		    return func(*args, **kwargs)
		  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1011, in fast_compute_cash_basis
		    """,
		  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1161, in logged_query
		    cr.execute(query, args)
		  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
		    return f(self, *args, **kwargs)
		  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
		    res = self._obj.execute(query, params)
		DataError: division by zero

		2019-12-15 21:03:18,493 13732 CRITICAL migratedb_migrated openerp.service.server: Failed to initialize database `migratedb_migrated`.
		Traceback (most recent call last):
		  File "/var/tmp/openupgrade/9.0/server/openerp/service/server.py", line 894, in preload_registries
		    registry = RegistryManager.new(dbname, update_module=update_module)
		  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
		    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
		  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
		    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
		  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
		    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
		  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 214, in load_module_graph
		    migrations.migrate_module(package, 'post')
		  File "/var/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 170, in migrate_module
		    mod.migrate(self.cr, installed_version)
		  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1694, in wrapped_function
		    if use_env2 else cr, version)
		  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1310, in migrate
		    fast_compute_cash_basis(env)
		  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1631, in wrapped_function
		    return func(*args, **kwargs)
		  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 1011, in fast_compute_cash_basis
		    """,
		  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1161, in logged_query
		    cr.execute(query, args)
		  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
		    return f(self, *args, **kwargs)
		  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
		    res = self._obj.execute(query, params)
			DataError: division by zero

			2019-12-15 21:03:18,494 13732 INFO migratedb_migrated openerp.service.server: Stopping gracefully
```

**Comment by pedrobaeza** [comment]
It should be fixed in #2119

**Comment by miscs** [comment]
Thank you very much for your unbelievable fast answer!
#2119 seems to work for me, migration just went past that module :)

**Comment by StefanRijnhart** [comment]
Thanks for reporting back on the fix!
