### ISSUE TITLE
[8.0 -> 9.0] Sale module: CREATE INDEX IF NOT EXISTS "wkf_triggers_ins...

### ISSUE THREAD

**Issue by miscs** [OCA/OpenUpgrade#2122]
Hi all,

now I am close to the end of the migration, I hope.
I am getting the following error in sale/migrations/9.0.1.0/pre-migration.py (again I hope I have the relevant log snipped):

Any hints highly appreciated!
Thanks
Stephan

```
2019-12-15 21:59:10,602 16144 INFO migratedb_migrated OpenUpgrade: Executing method drop_workflows
2019-12-15 21:59:10,603 16144 INFO migratedb_migrated openerp.sql_db: Programming error: syntax error at or near "NOT"
LINE 2:                 CREATE INDEX IF NOT EXISTS "wkf_triggers_ins...
                                        ^
, in query Composed([SQL('\n                CREATE INDEX IF NOT EXISTS '), Identifier('wkf_triggers_instance_id_index'), SQL(' ON '), Identifier(
'wkf_triggers'), SQL('\n                USING BTREE('), Identifier('instance_id'), SQL(')\n            ')])
2019-12-15 21:59:10,603 16144 ERROR migratedb_migrated OpenUpgrade: Error after 0:00:00.000745 running 
                CREATE INDEX IF NOT EXISTS "wkf_triggers_instance_id_index" ON "wkf_triggers"
                USING BTREE("instance_id")
            
2019-12-15 21:59:10,603 16144 ERROR migratedb_migrated OpenUpgrade: sale: error in migration script sale/migrations/9.0.1.0/pre-migration.py: Pro
grammingError('syntax error at or near "NOT"\nLINE 2:                 CREATE INDEX IF NOT EXISTS "wkf_triggers_ins...\n                          
              ^\n',)
2019-12-15 21:59:10,603 16144 ERROR migratedb_migrated OpenUpgrade: syntax error at or near "NOT"
LINE 2:                 CREATE INDEX IF NOT EXISTS "wkf_triggers_ins...
                                        ^
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1694, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/sale/migrations/9.0.1.0/pre-migration.py", line 76, in migrate
    drop_workflows(env)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1631, in wrapped_function
    return func(*args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/sale/migrations/9.0.1.0/pre-migration.py", line 65, in drop_workflows
    openupgrade.delete_model_workflow(env.cr, "sale.order")
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 953, in delete_model_workflow
    """).format(index, table, col)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1161, in logged_query
    cr.execute(query, args)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "NOT"
LINE 2:                 CREATE INDEX IF NOT EXISTS "wkf_triggers_ins...
2019-12-15 21:59:10,604 16144 ERROR migratedb_migrated openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1694, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/9.0/addons/sale/migrations/9.0.1.0/pre-migration.py", line 76, in migrate
    drop_workflows(env)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1631, in wrapped_function
    return func(*args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/sale/migrations/9.0.1.0/pre-migration.py", line 65, in drop_workflows
    openupgrade.delete_model_workflow(env.cr, "sale.order")
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 953, in delete_model_workflow
    """).format(index, table, col)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1161, in logged_query
    cr.execute(query, args)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "NOT"
LINE 2:                 CREATE INDEX IF NOT EXISTS "wkf_triggers_ins...
```

**Comment by pedrobaeza** [comment]
Which Postgres version are you using? I think you need a higher one.

**Comment by miscs** [comment]
I was on 9.3, updated to 9.5 and the problem is gone. Thank you!
