### ISSUE TITLE
[8.0 -> 9.0] Error with SQL Reports?

### ISSUE THREAD

**Issue by miscs** [OCA/OpenUpgrade#2127]
Hi all,

my next problem... sorry for all the noise and thanks again for assisting me so much!

I can´t figure out what the problem is. Should I maybe try to de-install SQL Reports before migration?

Thanks again for any pointers.
Stephan

```
2019-12-16 12:27:51,110 15110 WARNING migratedb_migrated OpenUpgrade: FILTER DISABLED: Global Filter 'From 2018' for model 'x_bi_sql_view.invoice_without_aa' has been disabled as it contains an in
valid domain.
2019-12-16 12:27:51,111 15110 INFO migratedb_migrated openerp.sql_db: bad query: UPDATE "ir_filters" SET "active"=false,"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (218)
2019-12-16 12:27:51,111 15110 ERROR migratedb_migrated openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 486, in load_modules
    deferred_90.migrate_deferred(cr, registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/openupgrade/deferred_90.py", line 70, in migrate_deferred
    disable_invalid_filters(cr)
  File "/var/tmp/openupgrade/9.0/server/openerp/openupgrade/deferred_90.py", line 46, in disable_invalid_filters
    openupgrade.disable_invalid_filters(env)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 2048, in disable_invalid_filters
    f.active = False
  File "/var/tmp/openupgrade/9.0/server/openerp/fields.py", line 868, in __set__
    record.write({self.name: self.convert_to_write(value)})
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 3898, in write
    self._write(old_vals)
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 4016, in _write
    cr.execute(query, params + (sub_ids,))
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

2019-12-16 12:27:51,112 15110 CRITICAL migratedb_migrated openerp.service.server: Failed to initialize database `migratedb_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 486, in load_modules
    deferred_90.migrate_deferred(cr, registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/openupgrade/deferred_90.py", line 70, in migrate_deferred
    disable_invalid_filters(cr)
  File "/var/tmp/openupgrade/9.0/server/openerp/openupgrade/deferred_90.py", line 46, in disable_invalid_filters
    openupgrade.disable_invalid_filters(env)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 2048, in disable_invalid_filters
    f.active = False
	  File "/var/tmp/openupgrade/9.0/server/openerp/fields.py", line 868, in __set__
	    record.write({self.name: self.convert_to_write(value)})
	  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
	    return new_api(self, *args, **kwargs)
	  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 3898, in write
	    self._write(old_vals)
	  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
	    return new_api(self, *args, **kwargs)
	  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 574, in new_api
	    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
	  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 4016, in _write
	    cr.execute(query, params + (sub_ids,))
	  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 154, in wrapper
	    return f(self, *args, **kwargs)
	  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 233, in execute
	    res = self._obj.execute(query, params)
	InternalError: current transaction is aborted, commands ignored until end of transaction block

	2019-12-16 12:27:51,112 15110 INFO migratedb_migrated openerp.service.server: Stopping gracefully
```

**Comment by pedrobaeza** [comment]
Sorry, but this is disabling invalid filters, so it shouldn't give any error. The traceback is not significant.

**Comment by miscs** [comment]
Just for the record, if anyone also hits this problem.

It seems that filters created by https://github.com/OCA/reporting-engine/tree/8.0/bi_sql_editor crashed the migration for me somehow. I deinstalled the module and deleted these filters manually from the database (every filter with domain_id like 'x_bi_sql_%'). Then the migration went through. I hope no side-effects by just deleting these filters (if I will report back).

I do not see a success message, but I hope log stopping at 

```
2019-12-16 16:03:15,046 6030 INFO migratedb_migrated openerp.modules.loading: Modules loaded.
2019-12-16 16:03:15,057 6030 INFO migratedb_migrated openerp.models: Computing parent left and right for table ir_ui_menu...
2019-12-16 16:03:15,179 6030 INFO migratedb_migrated openerp.modules.registry: Registry changed, signaling through the database
2019-12-16 16:03:15,180 6030 INFO migratedb_migrated openerp.service.server: Stopping gracefully
```

shows a finished migration?

Best Stephan
