### ISSUE TITLE
[9.0 -> 10.0] Programming error: syntax error at or near "NOT"

### ISSUE THREAD

**Issue by miscs** [OCA/OpenUpgrade#2131]
Hi all,

after successful 8.0 -> 9.0 migration (thanks again for the support!) I am trying to take the next step by migration to 10.0.
The error (log below) seems to indicate a problem with my postgres version again. I am using postgres 9.5 at the moment, which worked for 8.0->9.0. Is that assumption correct?

Which postgres version is best to do the migrations (I am trying to migrate to 12.0)?

Thanks
Stephan

```
2019-12-17 15:18:29,072 24212 INFO migratedb_migrated_migrated odoo.modules.migration: module hr_timesheet: Running migration [>10.0.1.0] pre-migration
2019-12-17 15:18:29,072 24212 INFO migratedb_migrated_migrated odoo.modules.migration: module hr_timesheet: Running migration [>10.0.1.0] pre-migration
2019-12-17 15:18:29,074 24212 INFO migratedb_migrated_migrated OpenUpgrade: hr_timesheet: pre-migration script called with version 9.0.1.0
2019-12-17 15:18:29,074 24212 INFO migratedb_migrated_migrated OpenUpgrade: table account_analytic_account, column use_timesheets: renaming to openupgrade_legac
y_10_0_use_timesheets
2019-12-17 15:18:29,075 24212 INFO migratedb_migrated_migrated odoo.sql_db: bad query: 
       ALTER TABLE account_analytic_line ADD COLUMN IF NOT EXISTS department_id INT;

       WITH departments AS (
          SELECT r.user_id AS user_id, MAX(e.department_id) AS dpt_id
             FROM hr_employee e JOIN resource_resource r
                                ON e.resource_id = r.id
          GROUP BY user_id
       )
       UPDATE account_analytic_line aal SET department_id=departments.dpt_id
       FROM departments WHERE aal.user_id = departments.user_id AND aal.department_id IS NULL;
    
2019-12-17 15:18:29,075 24212 ERROR migratedb_migrated_migrated OpenUpgrade: hr_timesheet: error in migration script hr_timesheet/migrations/10.0.1.0/pre-migrat
ion.py: ProgrammingError('syntax error at or near "NOT"\nLINE 2: ...  ALTER TABLE account_analytic_line ADD COLUMN IF NOT EXISTS...\n                           
                                  ^\n',)
2019-12-17 15:18:29,075 24212 ERROR migratedb_migrated_migrated OpenUpgrade: syntax error at or near "NOT"
LINE 2: ...  ALTER TABLE account_analytic_line ADD COLUMN IF NOT EXISTS...
                                                             ^
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1694, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/hr_timesheet/migrations/10.0.1.0/pre-migration.py", line 62, in migrate
    create_and_populate_department(env.cr)
  File "/var/tmp/openupgrade/10.0/addons/hr_timesheet/migrations/10.0.1.0/pre-migration.py", line 30, in create_and_populate_department
    ''')
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "NOT"
LINE 2: ...  ALTER TABLE account_analytic_line ADD COLUMN IF NOT EXISTS...
                                                             ^

2019-12-17 15:18:29,080 24212 WARNING migratedb_migrated_migrated odoo.modules.loading: Transient module states were reset
2019-12-17 15:18:29,094 24212 ERROR migratedb_migrated_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 441, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 326, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 146, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 178, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1694, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/hr_timesheet/migrations/10.0.1.0/pre-migration.py", line 62, in migrate
    create_and_populate_department(env.cr)
  File "/var/tmp/openupgrade/10.0/addons/hr_timesheet/migrations/10.0.1.0/pre-migration.py", line 30, in create_and_populate_department
    ''')
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "NOT"
LINE 2: ...  ALTER TABLE account_analytic_line ADD COLUMN IF NOT EXISTS...
                                                             ^

2019-12-17 15:18:29,095 24212 CRITICAL migratedb_migrated_migrated odoo.service.server: Failed to initialize database `migratedb_migrated_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/service/server.py", line 974, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 441, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 326, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 146, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 178, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-3.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1694, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/hr_timesheet/migrations/10.0.1.0/pre-migration.py", line 62, in migrate
    create_and_populate_department(env.cr)
  File "/var/tmp/openupgrade/10.0/addons/hr_timesheet/migrations/10.0.1.0/pre-migration.py", line 30, in create_and_populate_department
    ''')
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "NOT"
LINE 2: ...  ALTER TABLE account_analytic_line ADD COLUMN IF NOT EXISTS...
                                                             ^

2019-12-17 15:18:29,096 24212 INFO migratedb_migrated_migrated odoo.service.server: Stopping gracefully
```

**Comment by pedrobaeza** [comment]
9.6 minimum.
