### ISSUE TITLE
[11.0 -> 12.0] UoM category Unit should only have one reference unit of measure

### ISSUE THREAD

**Issue by miscs** [OCA/OpenUpgrade#2135]
Hi all,

I made my way from 8.0 to 11.0 but now I get another error by migration 11.0 -> 12.0.
Is this something I need to fix in 8.0 before doing all the migrations? I am a bit confused the error pops up only now.

Any pointers whats to problem and how to fix would be highly appreciated.

Thanks
Stephan

```
2019-12-18 20:48:42,125 27742 WARNING migdb_migrated_migrated_migrated_migrated odoo.modules.loading: Transient module states were reset 
2019-12-18 20:48:42,134 27742 ERROR migdb_migrated_migrated_migrated_migrated odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3851, in _load_records
    data['record']._load_records_write(data['values'])
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3789, in _load_records_write
    self.write(values)
  File "/var/tmp/openupgrade/12.0/addons/uom/models/uom_uom.py", line 109, in write
    return super(UoM, self).write(values)
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3334, in write
    self._write(store_vals)
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3470, in _write
    self._validate_fields(vals)
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 1116, in _validate_fields
    check(self)
  File "/var/tmp/openupgrade/12.0/addons/uom/models/uom_uom.py", line 94, in _check_category_reference_uniqueness
    raise ValidationError(_("UoM category %s should only have one reference unit of measure.") % (self.env['uom.category'].browse(uom_data['category_id']).name,))
odoo.exceptions.ValidationError: ('UoM category Unit should only have one reference unit of measure.', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 249, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 807, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 870, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 760, in parse
    self.parse(rec, mode)
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 769, in parse
    exc_info[2]
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3851, in _load_records
    data['record']._load_records_write(data['values'])
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3789, in _load_records_write
    self.write(values)
  File "/var/tmp/openupgrade/12.0/addons/uom/models/uom_uom.py", line 109, in write
    return super(UoM, self).write(values)
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3334, in write
    self._write(store_vals)
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3470, in _write
    self._validate_fields(vals)
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 1116, in _validate_fields
    check(self)
  File "/var/tmp/openupgrade/12.0/addons/uom/models/uom_uom.py", line 94, in _check_category_reference_uniqueness
    raise ValidationError(_("UoM category %s should only have one reference unit of measure.") % (self.env['uom.category'].browse(uom_data['category_id']).name,))
odoo.tools.convert.ParseError: "UoM category Unit should only have one reference unit of measure.
None" while parsing /var/tmp/openupgrade/12.0/addons/uom/data/uom_data.xml:30, near
<record id="product_uom_unit" model="uom.uom">
            <field name="category_id" ref="product_uom_categ_unit"/>
            <field name="name">Unit(s)</field>
            <field name="factor" eval="1.0"/>
            <field name="rounding" eval="0.001"/>
        </record>
2019-12-18 20:48:42,141 27742 CRITICAL migdb_migrated_migrated_migrated_migrated odoo.service.server: Failed to initialize database `migdb_migrated_migrated_migrated_migrated`. 
Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3851, in _load_records
    data['record']._load_records_write(data['values'])
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3789, in _load_records_write
    self.write(values)
  File "/var/tmp/openupgrade/12.0/addons/uom/models/uom_uom.py", line 109, in write
    return super(UoM, self).write(values)
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3334, in write
    self._write(store_vals)
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3470, in _write
    self._validate_fields(vals)
  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 1116, in _validate_fields
    check(self)
  File "/var/tmp/openupgrade/12.0/addons/uom/models/uom_uom.py", line 94, in _check_category_reference_uniqueness
    raise ValidationError(_("UoM category %s should only have one reference unit of measure.") % (self.env['uom.category'].browse(uom_data['category_id']).name,))
odoo.exceptions.ValidationError: ('UoM category Unit should only have one reference unit of measure.', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/service/server.py", line 1126, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
	  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 476, in load_modules
	    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
	  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 360, in load_marked_modules
	    upg_registry=upg_registry,
	  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 249, in load_module_graph
	    load_data(cr, idref, mode, kind='data', package=package, report=report)
	  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 72, in load_data
	    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
	  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 807, in convert_file
	    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
	  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 870, in convert_xml_import
	    obj.parse(doc.getroot(), mode=mode)
	  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 760, in parse
	    self.parse(rec, mode)
	  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 769, in parse
	    exc_info[2]
	  File "/var/tmp/openupgrade/12.0/server/odoo/tools/pycompat.py", line 86, in reraise
	    raise value.with_traceback(tb)
	  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 763, in parse
	    self._tags[rec.tag](rec, de, mode=mode)
	  File "/var/tmp/openupgrade/12.0/server/odoo/tools/convert.py", line 668, in _tag_record
	    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
	  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3851, in _load_records
	    data['record']._load_records_write(data['values'])
	  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3789, in _load_records_write
	    self.write(values)
	  File "/var/tmp/openupgrade/12.0/addons/uom/models/uom_uom.py", line 109, in write
	    return super(UoM, self).write(values)
	  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3334, in write
	    self._write(store_vals)
	  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 3470, in _write
	    self._validate_fields(vals)
	  File "/var/tmp/openupgrade/12.0/server/odoo/models.py", line 1116, in _validate_fields
	    check(self)
	  File "/var/tmp/openupgrade/12.0/addons/uom/models/uom_uom.py", line 94, in _check_category_reference_uniqueness
	    raise ValidationError(_("UoM category %s should only have one reference unit of measure.") % (self.env['uom.category'].browse(uom_data['category_id']).name,))
	odoo.tools.convert.ParseError: "UoM category Unit should only have one reference unit of measure.
	None" while parsing /var/tmp/openupgrade/12.0/addons/uom/data/uom_data.xml:30, near
	<record id="product_uom_unit" model="uom.uom">
	            <field name="category_id" ref="product_uom_categ_unit"/>
	            <field name="name">Unit(s)</field>
	            <field name="factor" eval="1.0"/>
	            <field name="rounding" eval="0.001"/>
	        </record>
	2019-12-18 20:48:42,142 27742 INFO migdb_migrated_migrated_migrated_migrated odoo.service.server: Stopping gracefully
```

**Comment by pedrobaeza** [comment]
The error is clear: there are several UoMs that are put as reference unit for the category. It's shown now as the check has been added in this version.

**Comment by miscs** [comment]
Sorry I overlooked: https://github.com/OCA/OpenUpgrade/issues/1914
Still not sure how to fix this. In my odoo 8.0 I am looking at 

Sales -> Configuration -> Unit of Measure Categories
and
Sales -> Configuration -> Units of Measure

and its not clear to me what could be wrong there. Will try to check in the DB directly.

**Comment by miscs** [comment]
it is too late again. got it. sorry.
