### ISSUE TITLE
Survey Module Migration For Version 7 and Version 8

### ISSUE THREAD

**Issue by vijaypatil091** [OCA/OpenUpgrade#214]
Key (survey_id)=(1) is not present in table "survey_survey".

**Comment by StefanRijnhart** [comment]
Did you check if the survey module is covered already for this edition? Also, include more context if you want us to be able to say something about it (link to the log file (level: debug) of the full migration on some pastebin).

**Comment by vijaypatil091** [comment]
Hi,

Sorry for delay.Here is error log.

ALTER TABLE "survey_page" ADD FOREIGN KEY ("survey_id") REFERENCES "survey_survey" ON DELETE cascade
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "survey_page" violates foreign key constraint "survey_page_survey_id_fkey"
DETAIL:  Key (survey_id)=(1) is not present in table "survey_survey".

2015-02-19 09:20:25,709 9965 CRITICAL Internal_HR_migrated openerp.service.server: Failed to initialize database `Internal_HR_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 398, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 295, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 186, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/module.py", line 290, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 2749, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "survey_page" violates foreign key constraint "survey_page_survey_id_fkey"
DETAIL:  Key (survey_id)=(1) is not present in table "survey_survey".

**Comment by objectsbloom** [comment]
Hi everyone,
did you fix this issue? Can you share the procedure? I tried to fixed it by hand as suggested in /var/tmp/openupgrade/migration.log but it didn't work. 

I will be grateful for any help you can provide.

openerp@demo-virtual-machine:~$ /var/tmp/openupgrade/8.0/server/openerp-server -update=all 
2015-02-26 18:58:45,387 1881 INFO ? openerp: OpenERP version 8.0
2015-02-26 18:58:45,387 1881 INFO ? openerp: addons paths: ['/opt/openerp/.local/share/Odoo/addons/8.0', u'/var/tmp/openupgrade/8.0/server/openerp/addons', u'/var/tmp/openupgrade/8.0/server/addons']
2015-02-26 18:58:45,387 1881 INFO ? openerp: database hostname: localhost
2015-02-26 18:58:45,387 1881 INFO ? openerp: database port: 5432
2015-02-26 18:58:45,387 1881 INFO ? openerp: database user: openerp
2015-02-26 18:58:45,866 1881 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-02-26 18:59:16,563 1881 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
2015-02-26 18:59:18,172 1881 INFO ? openerp.addons.report.models.report: You need wkhtmltopdf to print a pdf version of the reports.
2015-02-26 18:59:18,856 1881 INFO ? openerp.http: HTTP Configuring static files
2015-02-26 18:59:18,894 1881 INFO None openerp.http: Generating nondb routing
2015-02-26 18:59:18,913 1881 INFO None werkzeug: 192.168.122.1 - - [26/Feb/2015 18:59:18] "GET / HTTP/1.1" 303 -
2015-02-26 18:59:18,951 1881 INFO None werkzeug: 192.168.122.1 - - [26/Feb/2015 18:59:18] "GET /web HTTP/1.1" 303 -
2015-02-26 18:59:19,010 1881 INFO None werkzeug: 192.168.122.1 - - [26/Feb/2015 18:59:19] "GET /web/database/selector HTTP/1.1" 200 -
2015-02-26 18:59:19,045 1881 INFO ? werkzeug: 192.168.122.1 - - [26/Feb/2015 18:59:19] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 200 -
2015-02-26 18:59:19,067 1881 INFO ? werkzeug: 192.168.122.1 - - [26/Feb/2015 18:59:19] "GET /web/static/src/css/base.css HTTP/1.1" 200 -
2015-02-26 18:59:19,075 1881 INFO ? werkzeug: 192.168.122.1 - - [26/Feb/2015 18:59:19] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 200 -
2015-02-26 18:59:19,132 1881 INFO ? werkzeug: 192.168.122.1 - - [26/Feb/2015 18:59:19] "GET /web/static/src/img/form_sheetbg.png HTTP/1.1" 200 -
2015-02-26 18:59:31,366 1881 INFO None werkzeug: 192.168.122.1 - - [26/Feb/2015 18:59:31] "GET /web?db=Mobiletalk_migrated HTTP/1.1" 302 -
2015-02-26 18:59:31,469 1881 INFO Mobiletalk_migrated openerp.modules.loading: loading 1 modules...
2015-02-26 18:59:31,693 1881 INFO Mobiletalk_migrated openerp.modules.loading: 1 modules loaded in 0.20s, 0 queries
2015-02-26 18:59:31,774 1881 INFO Mobiletalk_migrated OpenUpgrade: Selecting autoinstallable modules survey_crm,hr_applicant_document,payment,marketing_crm
2015-02-26 18:59:31,786 1881 WARNING Mobiletalk_migrated openerp.modules.module: module document_ftp: module not found
2015-02-26 18:59:31,787 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module document_ftp: not installable, skipped
2015-02-26 18:59:31,801 1881 WARNING Mobiletalk_migrated openerp.modules.module: module portal_crm: module not found
2015-02-26 18:59:31,801 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module portal_crm: not installable, skipped
2015-02-26 18:59:31,821 1881 WARNING Mobiletalk_migrated openerp.modules.module: module account_report_company: module not found
2015-02-26 18:59:31,822 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module account_report_company: not installable, skipped
2015-02-26 18:59:31,832 1881 WARNING Mobiletalk_migrated openerp.modules.module: module project_gtd: module not found
2015-02-26 18:59:31,832 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module project_gtd: not installable, skipped
2015-02-26 18:59:31,843 1881 WARNING Mobiletalk_migrated openerp.modules.module: module google_base_account: module not found
2015-02-26 18:59:31,843 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module google_base_account: not installable, skipped
2015-02-26 18:59:31,880 1881 WARNING Mobiletalk_migrated openerp.modules.module: module google_docs: module not found
2015-02-26 18:59:31,880 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module google_docs: not installable, skipped
2015-02-26 18:59:31,909 1881 WARNING Mobiletalk_migrated openerp.modules.module: module base_status: module not found
2015-02-26 18:59:31,909 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module base_status: not installable, skipped
2015-02-26 18:59:31,916 1881 WARNING Mobiletalk_migrated openerp.modules.module: module portal_hr_employees: module not found
2015-02-26 18:59:31,916 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module portal_hr_employees: not installable, skipped
2015-02-26 18:59:31,934 1881 WARNING Mobiletalk_migrated openerp.modules.module: module project_long_term: module not found
2015-02-26 18:59:31,934 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module project_long_term: not installable, skipped
2015-02-26 18:59:31,935 1881 WARNING Mobiletalk_migrated openerp.modules.module: module portal_project_long_term: module not found
2015-02-26 18:59:31,936 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module portal_project_long_term: not installable, skipped
2015-02-26 18:59:31,937 1881 WARNING Mobiletalk_migrated openerp.modules.module: module idea: module not found
2015-02-26 18:59:31,937 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module idea: not installable, skipped
2015-02-26 18:59:31,938 1881 WARNING Mobiletalk_migrated openerp.modules.module: module process: module not found
2015-02-26 18:59:31,938 1881 WARNING Mobiletalk_migrated openerp.modules.graph: module process: not installable, skipped
2015-02-26 18:59:32,106 1881 WARNING Mobiletalk_migrated openerp.modules.graph: Some modules were not loaded.
2015-02-26 18:59:32,315 1881 INFO Mobiletalk_migrated openerp.modules.loading: loading 66 modules...
2015-02-26 18:59:33,911 1881 INFO Mobiletalk_migrated openerp.modules.module: module hr_evaluation: creating or updating database tables
2015-02-26 18:59:34,722 1881 INFO Mobiletalk_migrated openerp.models: column user_to_review_id (Employee to evaluate) converted to a function, removed from table hr_evaluation_interview
2015-02-26 18:59:34,850 1881 WARNING Mobiletalk_migrated openerp.models: WARNING: unable to set column phase_id of table hr_evaluation_interview not null !
Try to re-run: openerp-server --update=module
If it doesn't work, update records and execute manually:
ALTER TABLE hr_evaluation_interview ALTER COLUMN phase_id SET NOT NULL
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 2702, in _auto_init
    cr.execute('ALTER TABLE "%s" ALTER COLUMN "%s" SET NOT NULL' % (self._table, k))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "phase_id" contains null values

2015-02-26 18:59:35,154 1881 INFO Mobiletalk_migrated werkzeug: 192.168.122.1 - - [26/Feb/2015 18:59:35] "GET /web?db=Mobiletalk_migrated HTTP/1.1" 500 -
2015-02-26 18:59:35,206 1881 INFO Mobiletalk_migrated openerp.modules.loading: loading 1 modules...
2015-02-26 18:59:35,225 1881 ERROR Mobiletalk_migrated werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 280, in app
    return self.app(e, s)
  File "/var/tmp/openupgrade/8.0/server/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/var/tmp/openupgrade/8.0/server/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 1214, in **call**
    return self.dispatch(environ, start_response)
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 1188, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/share/pyshared/werkzeug/wsgi.py", line 411, in **call**
    return self.app(environ, start_response)
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 1346, in dispatch
    ir_http = request.registry['ir.http']
  File "/var/tmp/openupgrade/8.0/server/openerp/http.py", line 318, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 293, in get
    update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 398, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 295, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 186, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/module.py", line 290, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 2749, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "hr_evaluation_plan_phase" violates foreign key constraint "hr_evaluation_plan_phase_survey_id_fkey"
DETAIL:  Key (survey_id)=(1) is not present in table "survey_survey".
