### ISSUE TITLE
V7 => V8 : Error : 'MissingError', 'One of the documents you are trying to access has been deleted, please try again after refreshing.'

### ISSUE THREAD

**Issue by clikinfo** [OCA/OpenUpgrade#216]
I have this error : 

2015-01-19 18:33:59,880 1839 ERROR CLIKINFO_migrated openerp.tools.yaml_import: ('MissingError', 'One of the documents you are trying to access has been deleted, please try again after refreshing.')
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/yaml_import.py", line 896, in process
    self._process_node(node)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/yaml_import.py", line 909, in _process_node
    self.process_python(node)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/yaml_import.py", line 583, in process_python
    unsafe_eval(code_obj, {'ref': self.get_id}, code_context)
  File "/var/tmp/openupgrade/8.0/addons/stock/stock_data.yml", line 4, in <module>
    self.write(cr, uid, ref('base.main_partner'), {'property_stock_customer':main_warehouse.lot_stock_id.id})
  File "/var/tmp/openupgrade/8.0/server/openerp/fields.py", line 717, in __get__
    return record._cache[self]
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 5788, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/var/tmp/openupgrade/8.0/server/openerp/fields.py", line 55, in get
    raise self.exception
MissingError: ('MissingError', 'One of the documents you are trying to access has been deleted, please try again after refreshing.')
2015-01-19 18:33:59,969 1839 CRITICAL CLIKINFO_migrated openerp.service.server: Failed to initialize database `CLIKINFO_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 398, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 295, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 205, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 120, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 900, in convert_file
    convert_yaml_import(cr, module, fp, kind, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/yaml_import.py", line 960, in yaml_import
    yaml_interpreter.process(yaml_string)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/yaml_import.py", line 896, in process
    self._process_node(node)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/yaml_import.py", line 909, in _process_node
    self.process_python(node)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/yaml_import.py", line 583, in process_python
    unsafe_eval(code_obj, {'ref': self.get_id}, code_context)
  File "/var/tmp/openupgrade/8.0/addons/stock/stock_data.yml", line 4, in <module>
    self.write(cr, uid, ref('base.main_partner'), {'property_stock_customer':main_warehouse.lot_stock_id.id})
  File "/var/tmp/openupgrade/8.0/server/openerp/fields.py", line 717, in __get__
    return record._cache[self]
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 5788, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/var/tmp/openupgrade/8.0/server/openerp/fields.py", line 55, in get
    raise self.exception
MissingError: ('MissingError', 'One of the documents you are trying to access has been deleted, please try again after refreshing.')
2015-01-19 18:33:59,970 1839 INFO CLIKINFO_migrated openerp.service.server: Initiating shutdown
2015-01-19 18:33:59,970 1839 INFO CLIKINFO_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

I dont understand....

Can you help me ?

Thanks

**Comment by StefanRijnhart** [comment]
On 19-01-15 19:46, clikinfo wrote:

> //self.write(cr, uid, ref('base.main_partner'),
> {'property_stock_customer':main_warehouse.lot_stock_id.id})//

It's either the partner or the warehouse/location that is missing from
your database. The main_partner, on a newly installed database, is the
partner of the first company in your database. The warehouse is the
warehouse of the first company. Maybe this warehouse does not have a
stock location in your 7.0 database?

**Comment by clikinfo** [comment]
Yes, it's true. Thank. Lot of problem with stock module... :)

**Comment by manippts** [comment]
ty
