### ISSUE TITLE
[9.0 -> 10.0]Unexpected keyword argument "styles" in website/migrations/10.0.1.0/pre-migration.py

### ISSUE THREAD

**Issue by treviser** [OCA/OpenUpgrade#2175]
Impacted versions:
Latest version of Openupgrade 10.0 installed with 

`sudo -H pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
`
Steps to reproduce:
Started a migration of a database from version 9.0 to 10.0

Current behavior:
Odoo shuts down with the following traceback:

```
2020-01-26 14:22:07,188 14453 ERROR MyDatabaseName OpenUpgrade: website: error in migration script website/migrations/10.0.1.0/pre-migration.py: TypeError("convert_xml_node() got an unexpected keyword argument 'styles'",)
2020-01-26 14:22:07,188 14453 ERROR MyDatabaseName OpenUpgrade: convert_xml_node() got an unexpected keyword argument 'styles'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1734, in wrapped_function
    if use_env2 else cr, version)
  File "/odoo/openupgrade/addons/website/migrations/10.0.1.0/pre-migration.py", line 91, in migrate
    update_website_views(env)
  File "/odoo/openupgrade/addons/website/migrations/10.0.1.0/pre-migration.py", line 74, in update_website_views
    new_content = convert_html_fragment(old_content, REPLACEMENTS)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade_tools.py", line 91, in convert_html_fragment
    convert_xml_node(node, **instructions)
TypeError: convert_xml_node() got an unexpected keyword argument 'styles'
2020-01-26 14:22:07,192 14453 WARNING MyDatabaseName odoo.modules.loading: Transient module states were reset
2020-01-26 14:22:07,194 14453 ERROR MyDatabaseName odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/openupgrade/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/openupgrade/odoo/modules/loading.py", line 441, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/odoo/openupgrade/odoo/modules/loading.py", line 326, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/odoo/openupgrade/odoo/modules/loading.py", line 146, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/odoo/openupgrade/odoo/modules/migration.py", line 178, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1734, in wrapped_function
    if use_env2 else cr, version)
  File "/odoo/openupgrade/addons/website/migrations/10.0.1.0/pre-migration.py", line 91, in migrate
    update_website_views(env)
  File "/odoo/openupgrade/addons/website/migrations/10.0.1.0/pre-migration.py", line 74, in update_website_views
    new_content = convert_html_fragment(old_content, REPLACEMENTS)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade_tools.py", line 91, in convert_html_fragment
    convert_xml_node(node, **instructions)
TypeError: convert_xml_node() got an unexpected keyword argument 'styles'
2020-01-26 14:22:07,194 14453 CRITICAL MyDatabaseName odoo.service.server: Failed to initialize database `MyDatabaseName`.
Traceback (most recent call last):
  File "/odoo/openupgrade/odoo/service/server.py", line 974, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo/openupgrade/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/openupgrade/odoo/modules/loading.py", line 441, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/odoo/openupgrade/odoo/modules/loading.py", line 326, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/odoo/openupgrade/odoo/modules/loading.py", line 146, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/odoo/openupgrade/odoo/modules/migration.py", line 178, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1734, in wrapped_function
    if use_env2 else cr, version)
  File "/odoo/openupgrade/addons/website/migrations/10.0.1.0/pre-migration.py", line 91, in migrate
    update_website_views(env)
  File "/odoo/openupgrade/addons/website/migrations/10.0.1.0/pre-migration.py", line 74, in update_website_views
    new_content = convert_html_fragment(old_content, REPLACEMENTS)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade_tools.py", line 91, in convert_html_fragment
    convert_xml_node(node, **instructions)
TypeError: convert_xml_node() got an unexpected keyword argument 'styles'
```

**Comment by pedrobaeza** [comment]
If the problem is with that module (website_img_bg_style), put the issue in OCA/website, not here.
