### ISSUE TITLE
 [8->9->10->11] The 'odoo.addons.web' package was not installed in a way that PackageLoader understands.

### ISSUE THREAD

**Issue by miscs** [OCA/OpenUpgrade#2178]
Hi all,

sorry for bothering again. I did  a lot of cleanup in the v8 database and started migration again. [8->9->10] works without errors. 
Now I am migrating [10->11] and getting the following error:

```
2020-01-27 21:23:04,487 31894 INFO ? odoo: Odoo version 11.0
2020-01-27 21:23:04,487 31894 INFO ? odoo: Using configuration file at /var/tmp/openupgrade/11.0/server.cfg
2020-01-27 21:23:04,488 31894 INFO ? odoo: addons paths: ['/opt/odoo/filestorage/addons/11.0', '/var/tmp/openupgrade/11.0/server/addons', '/var/tmp/openupgrade/11.0/server/odoo/addons', '/var/tmp/openupgrade/11.0/addons']
2020-01-27 21:23:04,488 31894 INFO ? odoo: database: odoo@localhost:default
2020-01-27 21:23:04,504 31894 CRITICAL ? odoo.modules.module: Couldn't load module web
2020-01-27 21:23:04,504 31894 CRITICAL ? odoo.modules.module: The 'odoo.addons.web' package was not installed in a way that PackageLoader understands.
2020-01-27 21:23:04,504 31894 ERROR ? odoo.service.server: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/11.0/server/odoo/service/server.py", line 955, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/var/tmp/openupgrade/11.0/server/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>
  File "/var/tmp/openupgrade/11.0/server/addons/web/controllers/__init__.py", line 4, in <module>
    from . import main, pivot
  File "/var/tmp/openupgrade/11.0/server/addons/web/controllers/main.py", line 56, in <module>
    loader = jinja2.PackageLoader('odoo.addons.web', "views")
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 290, in __init__
    " PackageLoader understands." % package_name
ValueError: The 'odoo.addons.web' package was not installed in a way that PackageLoader understands.
```

I know this looks like a problem with the addons path but the web module is present. I also never ran in this problem before in my test-migrations. Could be something wrong with my migrated v10 database which is causing this error?

Thanks for any pointers.... bit confused here.
Best
Stephan

**Comment by pedrobaeza** [comment]
This seems something on your addons path, but nothing on OpenUpgrade itself.

**Comment by miscs** [comment]
Not with OpenUpgrade, but also not related to the addons path. So just for reference, if somebody runs into this as well: This error occurs since jinja2 has been migrated to version 2.11.0. Rollbacking to version 2.10.3 worked for me.
