### ISSUE TITLE
[V10 to V11] Error migration due to old row

### ISSUE THREAD

**Issue by FranciscoBigWings** [OCA/OpenUpgrade#2263]
Hello everyone, I leave this error here. I cant solve it

2020-03-31 16:45:35,412 16008 ERROR odoopruebas112 odoo.sql_db: bad query: DELETE FROM account_account_type WHERE id IN (37)
ERROR: el valor null para la columna «user_type_id» viola la restricción not null
DETAIL:  La fila que falla contiene (545, 1, 472, 2015-07-03 11:04:29.482676, Hacienda Pública. IVA soportado, null, null, 2, 1, null, f, 2020-03-30 19:49:34.583183, f, null).
CONTEXT:  sentencia SQL: «UPDATE ONLY "public"."account_account_template" SET "user_type_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "user_type_id"»

2020-03-31 16:45:35,415 16008 WARNING odoopruebas112 odoo.modules.loading: Transient module states were reset
2020-03-31 16:45:35,415 16008 ERROR odoopruebas112 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/OCB11/OCB/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/OCB11/OCB/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/OCB11/OCB/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'odoopruebas112'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/OCB11/OCB/odoo/http.py", line 1476, in dispatch
    odoo.registry(db).check_signaling()
  File "/opt/odoo/OCB11/OCB/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/OCB11/OCB/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/opt/odoo/OCB11/OCB/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OCB11/OCB/odoo/modules/loading.py", line 414, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/opt/odoo/OCB11/OCB/odoo/addons/base/ir/ir_model.py", line 1657, in _process_end
    record.unlink()
  File "/opt/odoo/OCB11/OCB/odoo/models.py", line 2990, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/odoo/OCB11/OCB/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/OCB11/OCB/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: el valor null para la columna «user_type_id» viola la restricción not null
DETAIL:  La fila que falla contiene (545, 1, 472, 2015-07-03 11:04:29.482676, Hacienda Pública. IVA soportado, null, null, 2, 1, null, f, 2020-03-30 19:49:34.583183, f, null).
CONTEXT:  sentencia SQL: «UPDATE ONLY "public"."account_account_template" SET "user_type_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "user_type_id"»

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/OCB11/OCB/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/OCB11/OCB/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/OCB11/OCB/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'odoopruebas112'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/OCB11/OCB/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OCB11/OCB/odoo/modules/loading.py", line 414, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/opt/odoo/OCB11/OCB/odoo/addons/base/ir/ir_model.py", line 1657, in _process_end
    record.unlink()
  File "/opt/odoo/OCB11/OCB/odoo/models.py", line 2990, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/odoo/OCB11/OCB/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/OCB11/OCB/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: el valor null para la columna «user_type_id» viola la restricción not null
DETAIL:  La fila que falla contiene (545, 1, 472, 2015-07-03 11:04:29.482676, Hacienda Pública. IVA soportado, null, null, 2, 1, null, f, 2020-03-30 19:49:34.583183, f, null).
CONTEXT:  sentencia SQL: «UPDATE ONLY "public"."account_account_template" SET "user_type_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "user_type_id"»

2020-03-31 16:45:35,417 16008 INFO odoopruebas112 werkzeug: 172.16.3.50 - - [31/Mar/2020 16:45:35] "POST /longpolling/poll HTTP/1.1" 500 -
2020-03-31 16:45:35,428 16008 ERROR odoopruebas112 werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/OCB11/OCB/odoo/service/server.py", line 348, in app
    return self.app(e, s)
  File "/opt/odoo/OCB11/OCB/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/OCB11/OCB/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/OCB11/OCB/odoo/http.py", line 1321, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/OCB11/OCB/odoo/http.py", line 1295, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo/.local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/OCB11/OCB/odoo/http.py", line 1497, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/odoo/OCB11/OCB/odoo/http.py", line 286, in __exit__
    elif self.registry:
  File "/opt/odoo/OCB11/OCB/odoo/http.py", line 378, in registry
    return odoo.registry(self.db)
  File "/opt/odoo/OCB11/OCB/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/OCB11/OCB/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/opt/odoo/OCB11/OCB/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OCB11/OCB/odoo/modules/loading.py", line 414, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/opt/odoo/OCB11/OCB/odoo/addons/base/ir/ir_model.py", line 1657, in _process_end
    record.unlink()
  File "/opt/odoo/OCB11/OCB/odoo/models.py", line 2990, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/odoo/OCB11/OCB/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/OCB11/OCB/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: el valor null para la columna «user_type_id» viola la restricción not null
DETAIL:  La fila que falla contiene (545, 1, 472, 2015-07-03 11:04:29.482676, Hacienda Pública. IVA soportado, null, null, 2, 1, null, f, 2020-03-30 19:49:34.583183, f, null).
CONTEXT:  sentencia SQL: «UPDATE ONLY "public"."account_account_template" SET "user_type_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "user_type_id"»

I think the error is related to an old row from 2015 when the DB was created in V8. This error didnt appear in previous migrations

Thanks

**Comment by pedrobaeza** [comment]
You have to fix it in your DB. It's not something of OpenUpgrade itself.

**Comment by FranciscoBigWings** [comment]
Ok thank you Pedro,  could you point me in the right direction? I cant find anything on the website that helps me

Thanks for the support always

**Comment by pedrobaeza** [comment]
This seems to be the generic chart of accounts installed in v8. Remove that records.
