### ISSUE TITLE
[12.0 -> 13.0] [product] Error while updating product module.

### ISSUE THREAD

**Issue by mojtabaakbarpour** [OCA/OpenUpgrade#2268]
Hi
When migrate product module from 12.0 to 13.0 get this error:

`2020-04-05 04:30:19,985 14716 ERROR odoo12 odoo.sql_db: bad query: UPDATE "product_product" SET "combination_indices"='',"can_image_variant_1024_be_zoomed"=false,"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32)
ERROR: duplicate key value violates unique constraint "product_product_combination_unique"
DETAIL:  Key (product_tmpl_id, combination_indices)=(9, ) already exists.
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "product_product_combination_unique"
DETAIL:  Key (product_tmpl_id, combination_indices)=(9, ) already exists.`

**Comment by kos94ok-3D** [comment]
HI, @MojtabaAp.
Can you write attributes and attributes values set on a product template with ID = 9?
And will be good if you write which combinations attribute values have an active product variant.

**Comment by adam-codeberg** [comment]
Getting a similar error when migrating from Odoo12 > 13 via OpenUpgrade branch 13.0

```
2020-09-01 05:47:46,887 24007 INFO bcs13 odoo.modules.registry: module product: creating or updating database tables                                                                  
2020-09-01 05:47:47,825 24007 ERROR bcs13 odoo.sql_db: bad query: CREATE UNIQUE INDEX IF NOT EXISTS product_product_combination_unique ON product_product (product_tmpl_id, combination_indices) WHERE active is true
ERROR: could not create unique index "product_product_combination_unique"                                                                                                             
DETAIL:  Key (product_tmpl_id, combination_indices)=(1100,1316,1803,2284,2434,2632,3007,3050,3166,3969) is duplicated.                                                               
                                                                                                                                                                                      
2020-09-01 05:47:47,827 24007 WARNING bcs13 odoo.modules.loading: Transient module states were reset                                                                                                        
2020-09-01 05:47:47,902 24007 ERROR bcs13 odoo.modules.registry: Failed to load registry                                                                                              
Traceback (most recent call last):                                                                                                                                                    
  File "/srv/OpenUpgrade/odoo/modules/registry.py", line 86, in new                                                                                                                   
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)                                                                                                        
  File "/srv/OpenUpgrade/odoo/modules/loading.py", line 479, in load_modules                                                                                                          
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)                                                                                              
  File "/srv/OpenUpgrade/odoo/modules/loading.py", line 363, in load_marked_modules                                                                                                   
    upg_registry=upg_registry,                                                                                                                                                                              
  File "/srv/OpenUpgrade/odoo/modules/loading.py", line 225, in load_module_graph                                                                                                     
    registry.init_models(cr, model_names, {'module': package.name}, new_install)                                                                                                                           
  File "/srv/OpenUpgrade/odoo/modules/registry.py", line 352, in init_models                                                                                                                                
    model.init()                                                                                                                                                                                            
  File "/srv/OpenUpgrade/addons/product/models/product.py", line 203, in init                                                                                                         
    % self._table)                                                                                                                                                                    
  File "/srv/OpenUpgrade/odoo/sql_db.py", line 168, in wrapper                                                                                                                                              
    return f(self, *args, **kwargs)                                                                                                                                                   
  File "/srv/OpenUpgrade/odoo/sql_db.py", line 245, in execute                                                                                                                        
    res = self._obj.execute(query, params)                                                                                                                                            
psycopg2.IntegrityError: could not create unique index "product_product_combination_unique"                                                                                           
DETAIL:  Key (product_tmpl_id, combination_indices)=(1100, 1316,1803,2284,2434,2632,3007,3050,3166,3969) is duplicated.  
```

**Comment by kos94ok-3D** [comment]
@adam-codeberg 
It`s the problem in your database.
You have more than one product variant with the same combinations of product.attribute.value for product template with id = 1100

**Comment by adam-codeberg** [comment]
> You have more than one product variant with the same combinations of product.attribute.value for product template with id = 1100

Thanks. I've confirmed template 1100 had x2 variants with an identical combination of attributes.
The other products didn't have variants, so i'll run another migration and see where that gets us.
Thanks for the heads up. 

--- 
Checking back in. Had to go through all product variants carefully and archive the ones with identical attribute combinations, but after doing that the migration went through smoothly. Thanks @kos94ok-3D
