### ISSUE TITLE
11.0 : Migration of ir.values's ir_model_data

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/OpenUpgrade#2270]
Hi all,

I'm wondering if you ever encountered this issue before.

I'm migrating a database from `9.0` to `12.0`, going step by step.

For some reason, `ir.model.data` of previous `ir.values` actions are not updated. 
Its `model` field is `ir.values`.

Accessing that record obviously raises an Exception:
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'ir.values'
```

Have you encountered something like this before?

--

Impacted versions:
11.0

Steps to reproduce:
Migrate a database

Current behavior:
model field of ir_model_data of previous ir.values records still points to ir.value model, which does not exist anymore

Expected behavior:
The model shoud be ir.actions.act_window

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/1914185/78567707-61e6f000-7821-11ea-884b-361a5c4d528b.png)

**Comment by ivantodorovich** [comment]
Just checked another database migrated a while back.
In this case the customer didn't even notice the issue, but it's the same.

![image](https://user-images.githubusercontent.com/1914185/78569321-b8edc480-7823-11ea-8a8f-efa62f487142.png)

**Comment by ivantodorovich** [comment]
@pedrobaeza @legalsylvain what do you think about this one?

In my particular case, I'm just removing the `ir.model.data` records for `ir.values` worked. The xmlids are freed and when module update loads them again, they are correct.

```py
    ir_model_data = env['ir.model.data'].search([
        ('model', '=', 'ir.values')])
    ir_model_data.unlink()
```

I think it should be added in the `base` migration scripts for `11.0`. Does it make sense?

**Comment by pedrobaeza** [comment]
Please migrate again with this commit included:

https://github.com/OCA/OpenUpgrade/commit/596ebed4348b98040f52133b8e026d2d726a03b9
