### ISSUE TITLE
[12.0->13.0][base] Error when running rename_ir_module_category function

### ISSUE THREAD

**Issue by veetoki** [OCA/OpenUpgrade#2289]
Hello,
I have this error when running OpenUpgrade.

```
2020-04-11 03:59:27,796 434 CRITICAL k12_001 odoo.service.server: Failed to initialize database `k12_001`. 
Traceback (most recent call last):
  File "/opt/odoo/code/projects/OpenUpgrade/odoo/service/server.py", line 1179, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/code/projects/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/code/projects/OpenUpgrade/odoo/modules/loading.py", line 413, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/opt/odoo/code/projects/OpenUpgrade/odoo/modules/loading.py", line 190, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/code/projects/OpenUpgrade/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1778, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/code/projects/OpenUpgrade/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 750, in migrate
    rename_ir_module_category(env)
  File "/opt/odoo/code/projects/OpenUpgrade/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 719, in rename_ir_module_category
    method="sql")
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade_merge_records.py", line 530, in merge_records
    record_ids = env[model_name].browse(record_ids).exists().ids
  File "/opt/odoo/code/projects/OpenUpgrade/odoo/api.py", line 463, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/opt/odoo/code/projects/OpenUpgrade/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'ir.module.category'
```

Did i do something wrong or miss something when running OpenUpgrade?
This is the command i run: `./odoo-bin -d k12_001 -u all --stop-after-init`

**Comment by pedrobaeza** [comment]
It seems the registry is not properly loaded, but I'm not able to reproduce it.

**Comment by nolte-eng** [comment]
Hello, 
I have exactly the same error, also with a new created database
`2020-04-11 13:06:06,197 5805 ERROR test OpenUpgrade: 'ir.module.category'
Traceback (most recent call last):
  File "/home/nolte/.local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1778, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/OpenUpgrade/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 750, in migrate
    rename_ir_module_category(env)
  File "/var/tmp/OpenUpgrade/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 719, in rename_ir_module_category
    method="sql")
  File "/home/nolte/.local/lib/python3.6/site-packages/openupgradelib/openupgrade_merge_records.py", line 530, in merge_records
    record_ids = env[model_name].browse(record_ids).exists().ids
  File "/var/tmp/OpenUpgrade/odoo/api.py", line 463, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/var/tmp/OpenUpgrade/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'ir.module.category'`

**Comment by veetoki** [comment]
> 
> 
> Hello,
> I have exactly the same error, also with a new created database
> `2020-04-11 13:06:06,197 5805 ERROR test OpenUpgrade: 'ir.module.category' Traceback (most recent call last): File "/home/nolte/.local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1778, in wrapped_function if use_env2 else cr, version) File "/var/tmp/OpenUpgrade/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 750, in migrate rename_ir_module_category(env) File "/var/tmp/OpenUpgrade/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 719, in rename_ir_module_category method="sql") File "/home/nolte/.local/lib/python3.6/site-packages/openupgradelib/openupgrade_merge_records.py", line 530, in merge_records record_ids = env[model_name].browse(record_ids).exists().ids File "/var/tmp/OpenUpgrade/odoo/api.py", line 463, in __getitem__ return self.registry[model_name]._browse(self, (), ()) File "/var/tmp/OpenUpgrade/odoo/modules/registry.py", line 178, in __getitem__ return self.models[model_name] KeyError: 'ir.module.category'`

Hello @pedrobaeza ,
As @nolte-eng said you can face this issue when trying to upgrade a new empty database v12 to v13.

**Comment by pedrobaeza** [comment]
Fixed. You require to update your openupgradelib including OCA/openupgradelib@49827a8 and download latest OpenUpgrade including  68b51bc

**Comment by khaeusler** [comment]
> Fixed. You require to update your openupgradelib including [OCA/openupgradelib@49827a8](https://github.com/OCA/openupgradelib/commit/49827a8) and download latest OpenUpgrade including [68b51bc](https://github.com/OCA/OpenUpgrade/commit/68b51bc75ff7f2cf5a810213ea3bcdeee6ef4813)

Hello @pedrobaeza 

we have also the problem with the base key error
openupgradelib and openupgrade are up2date

```[…]
2020-04-15 20:23:41,286 1193 DEBUG KH_4 OpenUpgrade: 1 rows affected after 0:00:00.000191 running UPDATE ir_model_data SET module = 'base', name = 'module_category_human_resources_recruitment' WHERE module = 'base' and name = 'module_category_hr_recruitment' 
2020-04-15 20:23:41,348 1193 ERROR KH_4 OpenUpgrade: base: error in migration script base/migrations/13.0.1.3/pre-migration.py: 'base' 
2020-04-15 20:23:41,348 1193 ERROR KH_4 OpenUpgrade: 'base' 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade.py", line 1778, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/lib/odoo/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 750, in migrate
    rename_ir_module_category(env)
  File "/opt/odoo/lib/odoo/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 719, in rename_ir_module_category
    method="sql", model_table="ir_module_category")
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade_merge_records.py", line 556, in merge_records
    _change_foreign_key_refs(*args3)
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade_merge_records.py", line 41, in _change_foreign_key_refs
    with env.cr.savepoint():
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 428, in savepoint
    flush_env(self)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 68, in flush_env
    env['base'].flush()
  File "/opt/odoo/lib/odoo/odoo/api.py", line 463, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'base'
2020-04-15 20:23:41,389 1193 WARNING KH_4 odoo.modules.loading: Transient module states were reset 
2020-04-15 20:23:41,414 1193 ERROR KH_4 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 413, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 190, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/lib/odoo/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade.py", line 1778, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/lib/odoo/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 750, in migrate
    rename_ir_module_category(env)
  File "/opt/odoo/lib/odoo/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 719, in rename_ir_module_category
    method="sql", model_table="ir_module_category")
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade_merge_records.py", line 556, in merge_records
    _change_foreign_key_refs(*args3)
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade_merge_records.py", line 41, in _change_foreign_key_refs
    with env.cr.savepoint():
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 428, in savepoint
    flush_env(self)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 68, in flush_env
    env['base'].flush()
  File "/opt/odoo/lib/odoo/odoo/api.py", line 463, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'base'
2020-04-15 20:23:41,415 1193 CRITICAL KH_4 odoo.service.server: Failed to initialize database `KH_4`. 
Traceback (most recent call last):
  File "/opt/odoo/lib/odoo/odoo/service/server.py", line 1179, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 413, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 190, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/lib/odoo/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade.py", line 1778, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/lib/odoo/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 750, in migrate
    rename_ir_module_category(env)
  File "/opt/odoo/lib/odoo/odoo/addons/base/migrations/13.0.1.3/pre-migration.py", line 719, in rename_ir_module_category
    method="sql", model_table="ir_module_category")
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade_merge_records.py", line 556, in merge_records
    _change_foreign_key_refs(*args3)
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade_merge_records.py", line 41, in _change_foreign_key_refs
    with env.cr.savepoint():
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 428, in savepoint
    flush_env(self)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 68, in flush_env
    env['base'].flush()
  File "/opt/odoo/lib/odoo/odoo/api.py", line 463, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'base'
```
