### ISSUE TITLE
[11→12] 500: internal server error

### ISSUE THREAD

**Issue by nikiwaibel** [OCA/OpenUpgrade#2307]
openupgrade runs (almost) fine (comments below), but accessing odoo12 results in
![Selection_999(4007)](https://user-images.githubusercontent.com/548023/79451818-74aeb100-7fe7-11ea-9dcd-ef130ebc174b.png)
after selecting the converted DB. (access is okay when upgrading/converting a tiny/fresh odoo11 DB  with just demo data to odoo12).

commands to import and convert the DB:
```
dropdb odooUpgrade
createdb --owner=odoo --lc-collate=C --template=template0 odooUpgrade
psql odooUpgrade < dump.sql
time /opt/odoo/OpenUpgrade/odoo-bin -c /opt/odoo/conf/odooUpgrade.conf --addons-path=/opt/odoo/OpenUpgrade/addons,/opt/odoo/custom/addons -d odooUpgrade --log-handler=:WARN --update=all --stop-after-init --logfile=/tmp/migration.log

real    6m56.127s
user    4m46.998s
sys     0m5.910s
```
(i've also copied the filestore and renamed the related directory to odooUpgrade).

in case odoo12 is started and the odooUpgrade DB is selected, it produces:
```
Apr 16 12:47:47 odoo2020 odoo[32586]: 2020-04-16 10:47:47,698 32593 ERROR odooUpgrade odoo.addons.website.models.ir_http: 500 Internal Server Error:
Apr 16 12:47:47 odoo2020 odoo[32586]: Traceback (most recent call last):
Apr 16 12:47:47 odoo2020 odoo[32586]:   File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 347, in _compiled_fn
Apr 16 12:47:47 odoo2020 odoo[32586]:     return compiled(self, append, new, options, log)
Apr 16 12:47:47 odoo2020 odoo[32586]:   File "<template>", line 1, in template_website_layout_75
Apr 16 12:47:47 odoo2020 odoo[32586]:   File "<template>", line 2, in body_call_content_74
Apr 16 12:47:47 odoo2020 odoo[32586]: AttributeError: 'website' object has no attribute 'payment_icons'
Apr 16 12:47:47 odoo2020 odoo[32586]: During handling of the above exception, another exception occurred:
Apr 16 12:47:47 odoo2020 odoo[32586]: Traceback (most recent call last):
Apr 16 12:47:47 odoo2020 odoo[32586]:   File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
Apr 16 12:47:47 odoo2020 odoo[32586]:     result = request.dispatch()
Apr 16 12:47:47 odoo2020 odoo[32586]:   File "/opt/odoo/odoo/odoo/http.py", line 835, in dispatch
Apr 16 12:47:47 odoo2020 odoo[32586]:     r = self._call_function(**self.params)
Apr 16 12:47:47 odoo2020 odoo[32586]:   File "/opt/odoo/odoo/odoo/http.py", line 346, in _call_function
Apr 16 12:47:47 odoo2020 odoo[32586]:     return checked_call(self.db, *args, **kwargs)
[…]
```
 (full [journalctl-u-odoo.log](https://github.com/OCA/OpenUpgrade/files/4486737/journalctl-u-odoo.log))

openupgrade errors (i guess unreleated):
```
# grep ERROR /tmp/migration.log
2020-04-16 09:27:11,112 31992 ERROR odooUpgrade odoo.modules.loading: Some modules have inconsistent states, some dependencies may be missing: ['account_budget', 'enterprise_theme', 'ups_delivery_carrier', 'website_forum_doc', 'website_terms_conditions'] 
2020-04-16 09:27:28,453 31992 ERROR odooUpgrade odoo.sql_db: bad query: UPDATE digest_digest_res_users_rel
ERROR: duplicate key value violates unique constraint "digest_digest_res_users_rel_digest_digest_id_res_users_id_key"
2020-04-16 09:27:28,453 31992 ERROR odooUpgrade OpenUpgrade: Error after 0:00:00.000474 running UPDATE digest_digest_res_users_rel
2020-04-16 09:27:28,454 31992 ERROR odooUpgrade odoo.sql_db: bad query: UPDATE digest_digest_res_users_rel
ERROR: duplicate key value violates unique constraint "digest_digest_res_users_rel_digest_digest_id_res_users_id_key"
2020-04-16 09:27:28,454 31992 ERROR odooUpgrade OpenUpgrade: Error after 0:00:00.000403 running UPDATE digest_digest_res_users_rel
```
(full [migration.log](https://github.com/OCA/OpenUpgrade/files/4486653/migration.log))

i am more concerned about:
```
Apr 16 12:47:11 odoo2020 odoo[32586]: 2020-04-16 10:47:11,568 32590 WARNING odooUpgrade odoo.fields: Field product.package.weight_uom_id with unknown comodel_name 'product.uom'
Apr 16 12:47:12 odoo2020 odoo[32586]: 2020-04-16 10:47:12,121 32590 WARNING odooUpgrade odoo.sql_db: Cursor not closed explicitly
Apr 16 12:47:12 odoo2020 odoo[32586]: Please enable sql debugging to trace the caller.
Apr 16 12:47:14 odoo2020 odoo[32586]: 2020-04-16 10:47:14,732 32611 WARNING odooUpgrade odoo.modules.loading: Transient module states were reset
```
after odoo12 is started, but not sure if that causes the "500: internal server error".

**Comment by pedrobaeza** [comment]
You have to check and clean your QWeb website views.

**Comment by nikiwaibel** [comment]
any hint/tip how/where to start with that?

**Comment by pedrobaeza** [comment]
With the view that is failing, the one that contains `payment_icons` as said in the logs.

**Comment by nikiwaibel** [comment]
hmm, v11 has `addons/website_payment/views/website_payment_templates.xml` which uses/calls `request.website.payment_icons()` from `./addons/website_payment/models/website.py`.

btw, v12 has `addons/website_payment/views/payment_acquirer.xml`, which seem to contain a typo: `acquirer_form_webiste` should actually become `acquirer_form_website`, i guess.

in the database i can find `request.website.payment_icons()` in `ir_ui_view`, with different `id`s in v11 and v12.

in which place shall this be fixed/cleaned?
1. in v11 from the webbrowser somehow?
2. in v11 in the database?
3. after conversion/migration in v12 in the database?
4. or should have any OpenUpdate conversion module taken care of this?
5. or someplace somehow else?
