### ISSUE TITLE
[12.0] - Sale Management - Sequence Error

### ISSUE THREAD

**Issue by gabrielcontessotto** [OCA/OpenUpgrade#2309]
Impacted versions: 12.0

When i run the OpenUpgrade the system give me this error:
```

2020-04-21 03:17:51,401 1 CRITICAL odoo11_-_infogt odoo.service.server: Failed to initialize database `odoo11_-_infogt`. 
Traceback (most recent call last):
  File "/var/www/odoo/odoo12/odoo/service/server.py", line 1151, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/www/odoo/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/www/odoo/odoo12/odoo/modules/loading.py", line 480, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/var/www/odoo/odoo12/odoo/modules/loading.py", line 364, in load_marked_modules
    upg_registry=upg_registry,
  File "/var/www/odoo/odoo12/odoo/modules/loading.py", line 194, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/www/odoo/odoo12/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib-3.0.0-py3.6.egg/openupgradelib/openupgrade.py", line 1778, in wrapped_function
    if use_env2 else cr, version)
  File "/var/www/odoo/odoo12/addons/sale_management/migrations/12.0.1.0/pre-migration.py", line 145, in migrate
    fill_sale_order_template_line_sections(cr)
  File "/var/www/odoo/odoo12/addons/sale_management/migrations/12.0.1.0/pre-migration.py", line 100, in fill_sale_order_template_line_sections
    """,
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib-3.0.0-py3.6.egg/openupgradelib/openupgrade.py", line 1245, in logged_query
    cr.execute(query, args)
  File "/var/www/odoo/odoo12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/var/www/odoo/odoo12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "sequence" does not exist
LINE 7: ...     PARTITION BY sale_order_template_id ORDER BY sequence, ...
                                                             ^
```

Something i'm doing wrong?

**Comment by pedrobaeza** [comment]
Your DB seems unstable because it has `sale_quote_line` table but no sequence in it, and you can see here that the model has this field in 11.0:

https://github.com/OCA/OpenUpgrade/blob/9ad6c75d0b069b3232225b240ab1dc831f2d9470/addons/website_quote/models/sale_quote.py#L47

and the table is renamed here:

https://github.com/OCA/OpenUpgrade/blob/f889b69663e71bea95885a7a5dc0fabbb1c90c23/addons/sale_management/migrations/12.0.1.0/pre-migration.py#L37

You have to check why you have this situation and act accordingly, but no OpenUpgrade problem.
