### ISSUE TITLE
[12.0->13.0][utm] relation "utm_stage" does not exist

### ISSUE THREAD

**Issue by khaeusler** [OCA/OpenUpgrade#2317]
Hello,

If only utm is installed in a v12 DB, the migration will fail with this error

```
DEBUG KH_5 odoo.modules.loading: loading module utm (18/134) 
INFO KH_5 odoo.modules.migration: module utm: Running migration [>13.0.1.0] pre-migration 
INFO KH_5 OpenUpgrade: utm: pre-migration script called with version 12.0.1.0 
INFO KH_5 odoo.modules.registry: module utm: creating or updating database tables 
DEBUG KH_5 odoo.schema: Table 'utm_medium': dropped index 'utm_medium_name_index' 
DEBUG KH_5 odoo.schema: Table 'utm_medium': dropped index 'utm_medium_active_index' 
DEBUG KH_5 odoo.schema: Table 'utm_medium': dropped index 'utm_medium_create_uid_index' 
DEBUG KH_5 odoo.schema: Table 'utm_medium': dropped index 'utm_medium_create_date_index' 
DEBUG KH_5 odoo.schema: Table 'utm_medium': dropped index 'utm_medium_write_uid_index' 
DEBUG KH_5 odoo.schema: Table 'utm_medium': dropped index 'utm_medium_write_date_index' 
DEBUG KH_5 odoo.schema: Table 'utm_campaign': dropped index 'utm_campaign_name_index' 
DEBUG KH_5 odoo.schema: Table 'utm_campaign': added column 'user_id' of type int4 
DEBUG KH_5 odoo.models: Table 'utm_campaign': setting default value of new column user_id to 1 
DEBUG KH_5 odoo.schema: Table 'utm_campaign': column 'user_id': added constraint NOT NULL 
DEBUG KH_5 odoo.schema: Table 'utm_campaign': dropped index 'utm_campaign_user_id_index' 
DEBUG KH_5 odoo.schema: Table 'utm_campaign': added column 'stage_id' of type int4 
ERROR KH_5 odoo.sql_db: bad query: SELECT "utm_stage".id FROM "utm_stage" ORDER BY "utm_stage"."sequence"   limit 1
ERROR: relation "utm_stage" does not exist
LINE 1: SELECT "utm_stage".id FROM "utm_stage" ORDER BY "utm_stage"....
                                   ^
 
WARNING KH_5 odoo.modules.loading: Transient module states were reset 
ERROR KH_5 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 479, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 349, in init_models
    model._auto_init()
  File "/opt/odoo/lib/odoo/odoo/models.py", line 2476, in _auto_init
    new = field.update_db(self, columns)
  File "/opt/odoo/lib/odoo/odoo/fields.py", line 2369, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/opt/odoo/lib/odoo/odoo/fields.py", line 853, in update_db
    self.update_db_notnull(model, column)
  File "/opt/odoo/lib/odoo/odoo/fields.py", line 893, in update_db_notnull
    model._init_column(self.name)
  File "/opt/odoo/lib/odoo/odoo/models.py", line 2402, in _init_column
    value = field.default(self)
  File "/opt/odoo/lib/odoo/addons/utm/models/utm.py", line 28, in <lambda>
    default=lambda self: self.env['utm.stage'].search([], limit=1),
  File "/opt/odoo/lib/odoo/odoo/models.py", line 1612, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/lib/odoo/odoo/models.py", line 4394, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "utm_stage" does not exist
LINE 1: SELECT "utm_stage".id FROM "utm_stage" ORDER BY "utm_stage"....
                                   ^

CRITICAL KH_5 odoo.service.server: Failed to initialize database `KH_5`. 
Traceback (most recent call last):
  File "/opt/odoo/lib/odoo/odoo/service/server.py", line 1179, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 479, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 349, in init_models
    model._auto_init()
  File "/opt/odoo/lib/odoo/odoo/models.py", line 2476, in _auto_init
    new = field.update_db(self, columns)
  File "/opt/odoo/lib/odoo/odoo/fields.py", line 2369, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/opt/odoo/lib/odoo/odoo/fields.py", line 853, in update_db
    self.update_db_notnull(model, column)
  File "/opt/odoo/lib/odoo/odoo/fields.py", line 893, in update_db_notnull
    model._init_column(self.name)
  File "/opt/odoo/lib/odoo/odoo/models.py", line 2402, in _init_column
    value = field.default(self)
  File "/opt/odoo/lib/odoo/addons/utm/models/utm.py", line 28, in <lambda>
    default=lambda self: self.env['utm.stage'].search([], limit=1),
  File "/opt/odoo/lib/odoo/odoo/models.py", line 1612, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/lib/odoo/odoo/models.py", line 4394, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "utm_stage" does not exist
LINE 1: SELECT "utm_stage".id FROM "utm_stage" ORDER BY "utm_stage"....
```

Steps to reproduce:
- create a new db and init the db only with the addon utm
- migrate this db to v13

The migration does not fail if mass_mailing was previously installed.

**Comment by BalramY** [comment]
Hello All,

I have been facing same issue while migrating to version 13 from v12.

I have commented 1 line on below file  and it worked for me.

Model : utm.campaing

Field : stage_id

And I commented the default value of this field

        #default=lambda self: self.env['utm.stage'].search([], limit=1),

File  = /var/tmp/openupgrade/13.0/server/addons/utm/models/utm.py
Line no : 28.

Let me know if you need more info on info@wangoes.com

**Comment by ruddy32** [comment]
I replace in utm.py line 27 :
```
stage_id = fields.Many2one('utm.stage', string='Stage', ondelete='restrict', required=True,
        default=lambda self: self.env['utm.stage'].search([], limit=1),
        group_expand='_group_expand_stage_ids')
```

with

```
stage_id = fields.Many2one('utm.stage', string='Stage', ondelete='restrict', required=True,
        default=0,
        group_expand='_group_expand_stage_ids')
```
It seems to fix the problem but upgrade raise another problem with mail migration.
