### ISSUE TITLE
How do I restore a migrated database (v7 -> v8)

### ISSUE THREAD

**Issue by bennals** [OCA/OpenUpgrade#233]
Hi.  I have migrated a v7 database to v8 using the migration script.  Everything seemed to go properly with no errors (it's a pretty small database).  Here is the log

2015-02-09 07:51:30,314 1254 INFO ? openerp: OpenERP version 8.0
2015-02-09 07:51:30,315 1254 INFO ? openerp: addons paths: ['/home/headgeek/.local/share/Odoo/addons/8.0', u'/var/tmp/openupgrade/8.0/server/openerp/addons', u'/var/tmp/openupgrade/8.0/addons']
2015-02-09 07:51:30,315 1254 INFO ? openerp: database hostname: localhost
2015-02-09 07:51:30,315 1254 INFO ? openerp: database port: 5432
2015-02-09 07:51:30,315 1254 INFO ? openerp: database user: openerp70
2015-02-09 07:51:31,543 1254 INFO rgerpbak_migrated openerp.modules.loading: loading 1 modules...
2015-02-09 07:51:31,587 1254 INFO rgerpbak_migrated openerp.modules.migration: module base: Running migration [>8.0.1.3] pre-migration
2015-02-09 07:51:31,587 1254 INFO rgerpbak_migrated openerp.modules.migration: module base: Running migration [>8.0.1.3] pre-migration
2015-02-09 07:51:31,627 1254 INFO rgerpbak_migrated OpenUpgrade: base: pre-migration script called with version 7.0.1.3
2015-02-09 07:51:31,631 1254 DEBUG rgerpbak_migrated OpenUpgrade: Running UPDATE ir_module_module SET name = procurement_jit WHERE name = mrp_jit
2015-02-09 07:51:31,631 1254 DEBUG rgerpbak_migrated OpenUpgrade: 1 rows affected
2015-02-09 07:51:31,632 1254 DEBUG rgerpbak_migrated OpenUpgrade: Running UPDATE ir_model_data SET module = procurement_jit WHERE module = mrp_jit 
2015-02-09 07:51:31,632 1254 DEBUG rgerpbak_migrated OpenUpgrade: 0 rows affected

When I tried to log in to the migrated database from the v7 interface I got the following error, which I assumed was just a basic compatibility issue

  File "/opt/openerp70/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

I then used the Manage Databases facility to create a backup of the migrated database which seemed to work fine (no errors reported).  I then entered the Odoo Manage Databases facility and attempted to restore the backup of the migrated database.  The two notifications gave contradictory messages, one successful the other not successful.  Now when I try to connect via a browser I get a 500 internal server error and can't connect to the login screen or the manage databases screen.  Here is the log that is written when I attempt it (sorry about the length):

2015-02-09 22:21:31,493 1235 INFO rgerp2 openerp.modules.loading: loading 1 modules...
2015-02-09 22:21:31,600 1235 INFO rgerp2 openerp.modules.loading: 1 modules loaded in 0.11s, 0 queries
2015-02-09 22:21:31,607 1235 WARNING rgerp2 openerp.modules.module: module stock_location: module not found
2015-02-09 22:21:31,607 1235 WARNING rgerp2 openerp.modules.graph: module stock_location: not installable, skipped
2015-02-09 22:21:31,607 1235 WARNING rgerp2 openerp.modules.module: module plugin: module not found
2015-02-09 22:21:31,608 1235 WARNING rgerp2 openerp.modules.graph: module plugin: not installable, skipped
2015-02-09 22:21:31,608 1235 WARNING rgerp2 openerp.modules.module: module base_status: module not found
2015-02-09 22:21:31,608 1235 WARNING rgerp2 openerp.modules.graph: module base_status: not installable, skipped
2015-02-09 22:21:31,610 1235 WARNING rgerp2 openerp.modules.module: module plugin_thunderbird: module not found
2015-02-09 22:21:31,610 1235 WARNING rgerp2 openerp.modules.graph: module plugin_thunderbird: not installable, skipped
2015-02-09 22:21:31,613 1235 WARNING rgerp2 openerp.modules.module: module donation2: module not found
2015-02-09 22:21:31,613 1235 WARNING rgerp2 openerp.modules.graph: module donation2: not installable, skipped
2015-02-09 22:21:31,618 1235 WARNING rgerp2 openerp.modules.module: module idea: module not found
2015-02-09 22:21:31,618 1235 WARNING rgerp2 openerp.modules.graph: module idea: not installable, skipped
2015-02-09 22:21:31,620 1235 WARNING rgerp2 openerp.modules.module: module process: module not found
2015-02-09 22:21:31,620 1235 WARNING rgerp2 openerp.modules.graph: module process: not installable, skipped
2015-02-09 22:21:31,621 1235 WARNING rgerp2 openerp.modules.module: module account_report_company: module not found
2015-02-09 22:21:31,621 1235 WARNING rgerp2 openerp.modules.graph: module account_report_company: not installable, skipped
2015-02-09 22:21:31,623 1235 WARNING rgerp2 openerp.modules.module: module project_gtd: module not found
2015-02-09 22:21:31,623 1235 WARNING rgerp2 openerp.modules.graph: module project_gtd: not installable, skipped
2015-02-09 22:21:31,624 1235 WARNING rgerp2 openerp.modules.module: module project_long_term: module not found
2015-02-09 22:21:31,624 1235 WARNING rgerp2 openerp.modules.graph: module project_long_term: not installable, skipped
2015-02-09 22:21:31,625 1235 WARNING rgerp2 openerp.modules.module: module workshop2: module not found
2015-02-09 22:21:31,625 1235 WARNING rgerp2 openerp.modules.graph: module workshop2: not installable, skipped
2015-02-09 22:21:31,636 1235 ERROR rgerp2 openerp.modules.graph: module purchase: Unmet dependencies: stock_account
2015-02-09 22:21:31,636 1235 ERROR rgerp2 openerp.modules.graph: module account_analytic_default: Unmet dependencies: sale_stock
2015-02-09 22:21:31,636 1235 ERROR rgerp2 openerp.modules.graph: module delivery: Unmet dependencies: sale_stock
2015-02-09 22:21:31,636 1235 ERROR rgerp2 openerp.modules.graph: module stock_invoice_directly: Unmet dependencies: delivery
2015-02-09 22:21:31,636 1235 ERROR rgerp2 openerp.modules.graph: module sale_analytic_plans: Unmet dependencies: account_analytic_plans
2015-02-09 22:21:31,636 1235 ERROR rgerp2 openerp.modules.graph: module point_of_sale: Unmet dependencies: sale_stock
2015-02-09 22:21:31,636 1235 ERROR rgerp2 openerp.modules.graph: module purchase_analytic_plans: Unmet dependencies: purchase, account_analytic_plans
2015-02-09 22:21:31,636 1235 ERROR rgerp2 openerp.modules.graph: module account_analytic_plans: Unmet dependencies: account_analytic_default
2015-02-09 22:21:31,636 1235 ERROR rgerp2 openerp.modules.graph: module sale_stock: Unmet dependencies: stock_account
2015-02-09 22:21:31,636 1235 WARNING rgerp2 openerp.modules.graph: Some modules were not loaded.
2015-02-09 22:21:31,720 1235 INFO rgerp2 openerp.modules.loading: loading 66 modules...
2015-02-09 22:21:32,777 1235 INFO rgerp2 openerp.modules.module: module stock: creating or updating database tables
2015-02-09 22:21:33,573 1235 INFO rgerp2 openerp.modules.loading: loading stock/security/stock_security.xml
2015-02-09 22:21:34,711 1235 INFO rgerp2 openerp.modules.loading: loading stock/security/ir.model.access.csv
2015-02-09 22:21:35,095 1235 INFO rgerp2 openerp.modules.loading: loading stock/stock_data.xml
2015-02-09 22:21:35,117 1235 INFO rgerp2 werkzeug: 192.168.1.5 - - [09/Feb/2015 22:21:35] "GET / HTTP/1.1" 500 -
2015-02-09 22:21:35,145 1235 ERROR rgerp2 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 281, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1280, in **call**
    return self.dispatch(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1254, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1412, in dispatch
    ir_http = request.registry['ir.http']
  File "/opt/odoo/openerp/http.py", line 339, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/opt/odoo/openerp/modules/registry.py", line 335, in get
    update_module)
  File "/opt/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/stock/stock.py", line 161, in create
    return super(stock_location, self).create(cr, uid, default, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4025, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4163, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "insert or update on table "stock_location" violates foreign key constraint "stock_location_location_id_fkey"
DETAIL:  Key (location_id)=(3) is not present in table "stock_location".
" while parsing /opt/odoo/addons/stock/stock_data.xml:73, near
<record id="stock_location_inter_wh" model="stock.location">
            <field name="name">Inter Company Transit</field>
            <field name="location_id" ref="stock_location_locations_virtual"/>
            <field name="usage">transit</field>
            <field name="company_id"/>
        </record>

Any ideas on how to progress?

Thanks,

Bill.

**Comment by bennals** [comment]
Quick update - I tried the whole restore process from the backup of the migrated database on a fresh installation of Ubuntu 14.04 and Odoo.  Again I got the conflicting notifications, one saying "Could not restore the database", the other saying "the database was restored" or something to that effect - this was the one that appears briefly and then disappears.

The last few lines of the log after attempting this restore are below:

File "/opt/odoo/openerp/service/db.py", line 217, in exp_restore
    restore_db(db_name, data_file.name, copy=copy)
  File "/opt/odoo/openerp/service/db.py", line 260, in restore_db
    if openerp.tools.exec_pg_command(pg_cmd, *pg_args):
  File "/opt/odoo/openerp/tools/misc.py", line 127, in exec_pg_command
    raise Exception('Postgres subprocess %s error %s' % (args2, rc))
NameError: global name 'args2' is not defined

The restored database does appear in the database selector list but attempting to log in to it causes the internal server error.  I've learned that you have to clear the browser cache to get back to the manage databases screen now, so that's something!

I suspect the way I imported the migrated database is the problem, i.e.: migrate using automated script -> create backup dump in v7 of migrated database -> restore backup of migrated database in v8

Is this the correct way to do it?  Perhaps something could be added to the online docs to clarify how to do this?

Thanks,

Bill

**Comment by StefanRijnhart** [comment]
Your migration script is pretty small, 20 lines or so. It only shows migration of the base module, no other modules (and from the error I gather that you do have stock installed). Maybe your addons path contains the regular addons from Odoo instead of (or as well as) the OpenUpgrade addons with their migration scripts? Note that for stock and maybe other modules, you need to merge in some of the pending pull requests.

**Comment by bennals** [comment]
Thanks for replying Stefan.  I'll revisit the migration process again and try and sort out the addons path issue.  I'll also try and incorporate the latest changes for the stock module.  I'm guessing that will mean I can't use the automatic migration script?

Bill.

**Comment by legalsylvain** [comment]
Yes you can, but with a branch that merge all the pending work. (stock, etc..)

**Comment by bennals** [comment]
Thanks legalsylvain.  I will try and do that next.  In the meantime, I deleted the stock module from the database to migrate and ran the migration script again, this time having the right addons path.  The process seemed to go properly (very long log) with a number of warnings but got stuck on this part

2015-03-11 21:43:46,074 1767 ERROR rgerp70_migrated openerp.sql_db: Programming error: relation "stock_warehouse_orderpoint" does not exist
, in query ALTER TABLE "stock_warehouse_orderpoint" RENAME "procurement_id" TO "openupgrade_legacy_8_0_procurement_id"
2015-03-11 21:43:46,074 1767 ERROR rgerp70_migrated OpenUpgrade: procurement: error in migration script /var/tmp/openupgrade/8.0/addons/procu
rement/migrations/8.0.1.0/pre-migration.py: relation "stock_warehouse_orderpoint" does not exist

2015-03-11 21:43:46,074 1767 ERROR rgerp70_migrated OpenUpgrade: relation "stock_warehouse_orderpoint" does not exist
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 752, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/procurement/migrations/8.0.1.0/pre-migration.py", line 51, in migrate
    openupgrade.rename_columns(cr, column_renames)
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 190, in rename_columns
    'ALTER TABLE "%s" RENAME "%s" TO "%s"' % (table, old, new,))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "stock_warehouse_orderpoint" does not exist

2015-03-11 21:43:46,102 1767 CRITICAL rgerp70_migrated openerp.service.server: Failed to initialize database `rgerp70_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 398, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 295, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 162, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 752, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/procurement/migrations/8.0.1.0/pre-migration.py", line 51, in migrate
    openupgrade.rename_columns(cr, column_renames)
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 190, in rename_columns
    'ALTER TABLE "%s" RENAME "%s" TO "%s"' % (table, old, new,))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "stock_warehouse_orderpoint" does not exist

I was surprised by this given the stock module is not installed.  Is there a specific pull request I should try and merge to deal with this error?

Thanks,

Bill.

**Comment by bennals** [comment]
Thanks legalsylvain.  I will try and do that next.  In the meantime, I deleted the stock module from the database to migrate and ran the migration script again, this time having the right addons path.  The process seemed to go properly (very long log) with a number of warnings but got stuck on this part

2015-03-11 21:43:46,074 1767 ERROR rgerp70_migrated openerp.sql_db: Programming error: relation "stock_warehouse_orderpoint" does not exist
, in query ALTER TABLE "stock_warehouse_orderpoint" RENAME "procurement_id" TO "openupgrade_legacy_8_0_procurement_id"
2015-03-11 21:43:46,074 1767 ERROR rgerp70_migrated OpenUpgrade: procurement: error in migration script /var/tmp/openupgrade/8.0/addons/procu
rement/migrations/8.0.1.0/pre-migration.py: relation "stock_warehouse_orderpoint" does not exist

2015-03-11 21:43:46,074 1767 ERROR rgerp70_migrated OpenUpgrade: relation "stock_warehouse_orderpoint" does not exist
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 752, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/procurement/migrations/8.0.1.0/pre-migration.py", line 51, in migrate
    openupgrade.rename_columns(cr, column_renames)
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 190, in rename_columns
    'ALTER TABLE "%s" RENAME "%s" TO "%s"' % (table, old, new,))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "stock_warehouse_orderpoint" does not exist

2015-03-11 21:43:46,102 1767 CRITICAL rgerp70_migrated openerp.service.server: Failed to initialize database `rgerp70_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 398, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 295, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 162, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 752, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/procurement/migrations/8.0.1.0/pre-migration.py", line 51, in migrate
    openupgrade.rename_columns(cr, column_renames)
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 190, in rename_columns
    'ALTER TABLE "%s" RENAME "%s" TO "%s"' % (table, old, new,))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "stock_warehouse_orderpoint" does not exist

I was surprised by this given the stock module is not installed.  Is there a specific pull request I should try and merge to deal with this error?

Thanks,

Bill.

**Comment by pedrobaeza** [comment]
You should try now that stock migration script is completed (but in beta testing yet). I close this issue meanwhile.
