### ISSUE TITLE
[8.0 -> 9.0] Impossible to migrate if products of a Purchase Order are different from products in its invoice

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#2353]
Impacted versions:

OpenUpgrade 9.0

Steps to reproduce:

On a v8.0
- Create a Purchase Order with lines
- Invoice the Purchase Order but modify it's invoice lines to invoice other products
- Try to migrate to v9.0

Current behavior:

Error:
```
CRITICAL migration_db openerp.service.server: Failed to initialize database `migration_db`.
      Traceback (most recent call last):
        File "/OpenUpgrade/openerp/service/server.py", line 894, in preload_registries
          registry = RegistryManager.new(dbname, update_module=update_module)
        File "/OpenUpgrade/openerp/modules/registry.py", line 390, in new
          openerp.modules.load_modules(registry._db, force_demo, status, update_module)
        File "/OpenUpgrade/openerp/modules/loading.py", line 446, in load_modules
          force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
        File "/OpenUpgrade/openerp/modules/loading.py", line 331, in load_marked_modules
          perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
        File "/OpenUpgrade/openerp/modules/loading.py", line 178, in load_module_graph
          init_module_models(cr, package.name, models)
        File "/OpenUpgrade/openerp/modules/module.py", line 317, in init_module_models
          obj_list[0].recompute(cr, openerp.SUPERUSER_ID, {})
        File "/OpenUpgrade/openerp/api.py", line 250, in wrapper
          return old_api(self, *args, **kwargs)
        File "/OpenUpgrade/openerp/api.py", line 354, in old_api
          result = method(recs, *args, **kwargs)
        File "/OpenUpgrade/openerp/models.py", line 5951, in recompute
          vals = rec._convert_to_write({n: rec[n] for n in ns})
        File "/OpenUpgrade/openerp/models.py", line 5951, in <dictcomp>
          vals = rec._convert_to_write({n: rec[n] for n in ns})
        File "/OpenUpgrade/openerp/models.py", line 5818, in __getitem__
          return self._fields[key].__get__(self, type(self))
        File "/OpenUpgrade/openerp/fields.py", line 832, in __get__
          self.determine_value(record)
        File "/OpenUpgrade/openerp/fields.py", line 916, in determine_value
          self.compute_value(recs)
        File "/OpenUpgrade/openerp/fields.py", line 896, in compute_value
          self._compute_value(records)
        File "/OpenUpgrade/openerp/fields.py", line 886, in _compute_value
          getattr(records, self.compute)()
        File "/OpenUpgrade/addons/sale/sale.py", line 552, in _get_invoice_qty
          qty_invoiced += self.env['product.uom']._compute_qty_obj(invoice_line.uom_id, invoice_line.quantity, line.product_uom)
        File "/OpenUpgrade/openerp/api.py", line 248, in wrapper
          return new_api(self, *args, **kwargs)
        File "/OpenUpgrade/openerp/api.py", line 490, in new_api
          result = method(self._model, cr, uid, *args, **old_kwargs)
        File "/OpenUpgrade/addons/product/product.py", line 122, in _compute_qty_obj
          raise UserError(_('Conversion from Product UoM %s to Default UoM %s is not possible as they both belong to different Category!.') % (from_unit.name,to_unit.name))
      UserError: (u'Conversion from Product UoM Hour to Default UoM PCE is not possible as they both belong to different Category!.', None)
```

Expected behavior:

OpenUpgrade do not stop and do not raise exception

**Comment by pedrobaeza** [comment]
Yes, that's something expected, as that's something that you can't do also in upper versions without the same error. You need to break the link between them if you want to avoid the problem (but you'll get others). Anyway, this reminds me the kind of deformations people can do using the software...

**Comment by legalsylvain** [comment]
Hi @sebastienhasa. I faced similar issue, migrating for 8 to 9. (the database dates from 2010, and has been migrated from 5 to 6.1, then to 7.0 then to 8.0, so there are a lot of errors like this one.)

I wrote some sql command to try to fix these bug. This one could maybe help you to pass the step. Otherwise, breaking the link as pedro proposed is also a good idea.

```
-- [purchase] clean bad uos_id on account.invoice.line (incorrect category)
UPDATE account_invoice_line ail
SET uos_id = pol.product_uom
FROM purchase_order_line_invoice_rel rel,
    purchase_order_line pol,
    product_uom pu_pol,
    product_uom pu_ail
WHERE pol.id = rel.order_line_id
AND ail.id = rel.invoice_id
AND pu_pol.id = pol.product_uom
AND pu_ail.id = ail.uos_id
AND pu_pol.category_id != pu_ail.category_id;
```

**Comment by pedrobaeza** [comment]
@legalsylvain it's not exactly the same, as he has also different products, so changing that way the UoM will lead to later problems in the normal operation.
