### ISSUE TITLE
Migration v11 --> v12

### ISSUE THREAD

**Issue by mosaabdulali** [OCA/OpenUpgrade#2363]
Impacted versions:
Migration from v11 to v12

Steps to reproduce:
OpenUpgrade Migration

Current behavior:
Failing while migration POS; new stored columns not added (amount_tax, amount_total, amount_paid ... etc) and tried to set those set them as not nullable and failed to do so even though all orders have their calculated amount totals/paid in v11.

Expected behavior:
POS to be successfully migrated with new columns and their values added

Video/Screenshot link (optional):

```
2020-07-11 12:38:10,193 13413 ERROR MY_DB odoo.sql_db: bad query: ALTER TABLE "pos_order" ALTER COLUMN "amount_tax" SET NOT NULL
ERROR: column "amount_tax" contains null values
 
2020-07-11 12:38:10,194 13413 WARNING MY_DB odoo.schema: Table 'pos_order': unable to set NOT NULL on column 'amount_tax'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "pos_order" ALTER COLUMN "amount_tax" SET NOT NULL 
Traceback (most recent call last):
  File "../OpenUpgrade/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "../OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "../OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: column "amount_tax" contains null values

2020-07-11 12:38:10,195 13413 ERROR MY_DB odoo.sql_db: bad query: ALTER TABLE "pos_order" ALTER COLUMN "amount_total" SET NOT NULL
ERROR: column "amount_total" contains null values
 
2020-07-11 12:38:10,195 13413 WARNING MY_DB odoo.schema: Table 'pos_order': unable to set NOT NULL on column 'amount_total'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "pos_order" ALTER COLUMN "amount_total" SET NOT NULL 
Traceback (most recent call last):
  File "../OpenUpgrade/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "../OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "../OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: column "amount_total" contains null values

2020-07-11 12:38:10,196 13413 ERROR MY_DB odoo.sql_db: bad query: ALTER TABLE "pos_order" ALTER COLUMN "amount_paid" SET NOT NULL
ERROR: column "amount_paid" contains null values
 
2020-07-11 12:38:10,196 13413 WARNING MY_DB odoo.schema: Table 'pos_order': unable to set NOT NULL on column 'amount_paid'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "pos_order" ALTER COLUMN "amount_paid" SET NOT NULL 
Traceback (most recent call last):
  File "../OpenUpgrade/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "../OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "../OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: column "amount_paid" contains null values

2020-07-11 12:38:10,196 13413 ERROR MY_DB odoo.sql_db: bad query: ALTER TABLE "pos_order" ALTER COLUMN "amount_return" SET NOT NULL
ERROR: column "amount_return" contains null values
 
2020-07-11 12:38:10,196 13413 WARNING MY_DB odoo.schema: Table 'pos_order': unable to set NOT NULL on column 'amount_return'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "pos_order" ALTER COLUMN "amount_return" SET NOT NULL 
Traceback (most recent call last):
  File "../OpenUpgrade/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "../OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "../OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: column "amount_return" contains null values
```

![image](https://user-images.githubusercontent.com/34865819/87246982-95a56780-c459-11ea-8ca9-c9fdfe5bb6bf.png)

**Comment by pedrobaeza** [comment]
But they are not blocking errors AFAIK.

**Comment by pedrobaeza** [comment]
Closing as no more answer.
