### ISSUE TITLE
[10.0 -> 11.0] Error while load module `odoo/addons/base/migrations/11.0.1.3/pre-migration.py`

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#2390]
Impacted versions:

OpenUpgrande, branch 11.0, commit b73127be5bf

Steps to reproduce:

- Install OpenUpgrade as tell in documentation
- Launch OpenUpgrade as tell in documentation

Current behavior:

When OpenUpgrand start, it stop quickly with error code 255.

The log print this error:
```
ERROR migration_db odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/OpenUpgrade/odoo/modules/loading.py", line 385, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/OpenUpgrade/odoo/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/OpenUpgrade/odoo/modules/migration.py", line 191, in migrate_module
    mod = load_script(pyfile, name)
  File "/OpenUpgrade/odoo/modules/migration.py", line 38, in load_script
    return imp.load_module(module_name, fp, fname, ('.py', 'r', imp.PY_SOURCE))
ValueError: load_module arg#2 should be a file or None
2020-08-06 15:44:00,148 66 CRITICAL migration_db odoo.service.server: Failed to initialize database `migration_db`.
Traceback (most recent call last):
  File "/OpenUpgrade/odoo/service/server.py", line 1043, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/OpenUpgrade/odoo/modules/loading.py", line 385, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/OpenUpgrade/odoo/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/OpenUpgrade/odoo/modules/migration.py", line 191, in migrate_module
    mod = load_script(pyfile, name)
  File "/OpenUpgrade/odoo/modules/migration.py", line 38, in load_script
    return imp.load_module(module_name, fp, fname, ('.py', 'r', imp.PY_SOURCE))
ValueError: load_module arg#2 should be a file or None
```

If I inspect with GDB, I can see that the `fp` variable is type
`_io.TextIOWrapper`.

Expected behavior:

OpenUpgrade start without error

**Comment by pedrobaeza** [comment]
Sorry, but the fact that Travis is green proves that the OpenUpgrade migration mechanism is not broken, so your problem is clearly in the way you do your migration in your environment, so there's nothing that can be fixed. I have never found this problem, so I can't say what are you doing wrong, so if anybody had this problem and figure out why, can answer here. You have also a mailing list for OpenUpgrade general questions, but I have to close the issue not being such.
