### ISSUE TITLE
upgrading from  v9 to v10 purchase_order_line state field already defined

### ISSUE THREAD

**Issue by IJOL** [OCA/OpenUpgrade#2469]
Trying to upgrade a v9 db to v10 i get this error:

2020-12-04 08:48:03,012 23 ERROR fun_copia_v9 OpenUpgrade: purchase: error in migration script purchase/migrations/10.0.1.2/pre-migration.py: ProgrammingError('ya existe la columna \xc2\xabstate\xc2\xbb en la relaci\xc3\xb3n \xc2\xabpurchase_order_line\xc2\xbb\n',)
2020-12-04 08:48:03,012 23 ERROR fun_copia_v9 OpenUpgrade: ya existe la columna «state» en la relación «purchase_order_line»
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1391, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/auto/addons/purchase/migrations/10.0.1.2/pre-migration.py", line 14, in migrate
    copy_state_to_purchase_lines(env.cr)
  File "/opt/odoo/auto/addons/purchase/migrations/10.0.1.2/pre-migration.py", line 5, in copy_state_to_purchase_lines
    cr.execute('ALTER TABLE purchase_order_line ADD COLUMN state VARCHAR;')
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ya existe la columna «state» en la relación «purchase_order_line»

This was v8 db and we are doing the next step till v10, we had the state field in purchase_order_line already in v8, just checked, so whats is going on here?, if we get rid of purchase/migrations/10.0.1.2/pre-migration.py it ends without any more issues, just trying to understand such a skew in versions we have..

**Comment by legalsylvain** [comment]
> This was v8 db and we are doing the next step till v10, we had the state field in purchase_order_line already in v8, just checked, so whats is going on here?, if we get rid of purchase/migrations/10.0.1.2/pre-migration.py it ends without any more issues, just trying to understand such a skew in versions we have..

Not sure to understand. the field exists in V8, doesn't exist in V9, and exists in V10, right ? 
if yes, at the end of the migration from 8, to 9, you should not have a state field. If yes, the 9 to 10 version will fail.

I just realized a migration from 8 to 12 recently with openupgrade with purchase module installed, and I didn't face this issue.

**Comment by IJOL** [comment]
Ok, I don't actually know if in v9 the fields exist or not at all, just
that we have it in v8 and it seems to resurface in v10, I will try some
more times for this db is really quick, and check code and db in v9 step to
see what is there.. Just trying to understand what the problem was.. Thanks
Anyway..Your insight was really helpful..


Saludos,
--------------------------------------------
Ignacio J.Ortega

**Comment by legalsylvain** [comment]
OK. you don't have the correct file. your file ``/opt/odoo/auto/addons/purchase/migrations/10.0.1.2/pre-migration.py`` is two years old.
see history : https://github.com/OCA/OpenUpgrade/commits/10.0/addons/purchase/migrations/10.0.1.2/pre-migration.py
