### ISSUE TITLE
[13.0] account group_show_line_subtotals_tax_included / excluded

### ISSUE THREAD

**Issue by estraka** [OCA/OpenUpgrade#2487]
Impacted versions:
13.0 

Steps to reproduce:

I have configured that the users see the subtotals with taxes included (group_show_line_subtotals_tax_included), and when I execute the migration, it fails me because the users cannot have both options marked.

ERROR:
```
2020-12-22 10:55:48,970 1 CRITICAL CadenetMig odoo.service.server: Failed to initialize database `CadenetMig`. 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4139, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4077, in _load_records_write
    self.write(values)
  File "/opt/odoo/auto/addons/mail/models/res_users.py", line 177, in write
    write_res = super(res_groups_mail_channel, self).write(vals)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_users.py", line 1048, in write
    res = super(GroupsView, self).write(values)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_users.py", line 981, in write
    self._check_one_user_type()
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_users.py", line 112, in _check_one_user_type
    self.users._check_one_user_type()
  File "/opt/odoo/auto/addons/account/models/res_users.py", line 24, in _check_one_user_type
    raise ValidationError(_("A user cannot have both Tax B2B and Tax B2C.\n"
odoo.exceptions.ValidationError: ('Un usuario no puede tener dos tipos de impuestos B2B (Empresa a Empresa) y B2C (Empresa a Cliente).\nDebe ir a Configuración general y elegir Mostrar precios de los productos.\n con "Impuestos incluidos" o en el modo "Sin impuestos" (o cambie entre los modo si ya está en el deseado).', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 1190, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 479, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 256, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/odoo/custom/src/odoo/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1844, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/auto/addons/account/migrations/13.0.1.1/post-migration.py", line 1025, in migrate
    env.cr, "account", "migrations/13.0.1.1/noupdate_changes.xml")
  File "/usr/local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 298, in load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode=mode)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 808, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 726, in parse
    exc_info[2]
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4139, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4077, in _load_records_write
    self.write(values)
  File "/opt/odoo/auto/addons/mail/models/res_users.py", line 177, in write
    write_res = super(res_groups_mail_channel, self).write(vals)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_users.py", line 1048, in write
    res = super(GroupsView, self).write(values)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_users.py", line 981, in write
    self._check_one_user_type()
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_users.py", line 112, in _check_one_user_type
    self.users._check_one_user_type()
  File "/opt/odoo/auto/addons/account/models/res_users.py", line 24, in _check_one_user_type
    raise ValidationError(_("A user cannot have both Tax B2B and Tax B2C.\n"
odoo.tools.convert.ParseError: "Un usuario no puede tener dos tipos de impuestos B2B (Empresa a Empresa) y B2C (Empresa a Cliente).
Debe ir a Configuración general y elegir Mostrar precios de los productos.
 con "Impuestos incluidos" o en el modo "Sin impuestos" (o cambie entre los modo si ya está en el deseado).
None" while parsing /opt/odoo/auto/addons/account/migrations/13.0.1.1/noupdate_changes.xml:2, near
<odoo>
  <record id="account_bank_statement_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="account_bank_statement_line_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="account_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="account_fiscal_position_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="account_invoice_line_rule_portal" model="ir.rule">
    <field name="domain_force">[('move_id.type', 'in', ('out_invoice', 'out_refund', 'in_invoice', 'in_refund')), ('move_id.message_partner_ids','child_of',[user.commercial_partner_id.id])]</field>
    <field name="model_id" ref="account.model_account_move_line"/>
  </record>
  <record id="account_invoice_rule_portal" model="ir.rule">
    <field name="domain_force">[('type', 'in', ('out_invoice', 'out_refund', 'in_invoice', 'in_refund')), ('message_partner_ids','child_of',[user.commercial_partner_id.id])]</field>
    <field name="model_id" ref="account.model_account_move"/>
  </record>
  <record id="account_move_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="account_move_line_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="account_payment_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="account_payment_term_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="account_reconcile_model_template_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="action_open_settings" model="ir.actions.act_window">
    <field name="context" eval="{'module': 'general_settings', 'bin_size': False}"/>
  </record>
  <record id="base.group_user" model="res.groups">
    <field name="implied_ids" eval="[(4, ref('account.group_show_line_subtotals_tax_excluded'))]"/>
  </record>
  <record id="data_unaffected_earnings" model="account.account.type">
    <field name="internal_group">equity</field>
  </record>
  <record id="email_template_edi_invoice" model="mail.template">
    <field name="body_html" type="html">
      <div style="margin: 0px; padding: 0px;">
        <p style="margin: 0px; padding: 0px; font-size: 13px;">
        Dear
        % if object.partner_id.parent_id:
            ${object.partner_id.name} (${object.partner_id.parent_id.name}),
        % else:
            ${object.partner_id.name},
        % endif
        <br/><br/>
        Here is your
        % if object.name:
            invoice <strong>${object.name}</strong>
        % else:
            invoice
        %endif
        % if object.invoice_origin:
            (with reference: ${object.invoice_origin})
        % endif
        amounting in <strong>${format_amount(object.amount_total, object.currency_id)}</strong>
        from ${object.company_id.name}.
        % if object.invoice_payment_state == 'paid':
            This invoice is already paid.
        % else:
            Please remit payment at your earliest convenience.
        % endif
        <br/><br/>
        Do not hesitate to contact us if you have any questions.
    </p>
      </div>
    </field>
    <field name="email_from">${(object.invoice_user_id.email_formatted or user.email_formatted) |safe}</field>
    <field name="model_id" ref="account.model_account_move"/>
    <field name="report_name">Invoice_${(object.name or '').replace('/','_')}${object.state == 'draft' and '_draft' or ''}</field>
    <field name="subject">${object.company_id.name} Invoice (Ref ${object.name or 'n/a'})</field>
  </record>
  <record id="invoice_analysis_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="journal_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
  <record id="mail_template_data_payment_receipt" model="mail.template">
    <field name="body_html" type="xml">
      <div style="margin: 0px; padding: 0px;">
        <p style="margin: 0px; padding: 0px; font-size: 13px;">
        Dear ${object.partner_id.name}<br/><br/>
        Thank you for your payment.
        Here is your payment receipt <strong>${(object.name or '').replace('/','-')}</strong> amounting
        to <strong>${format_amount(object.amount, object.currency_id)}</strong> from ${object.company_id.name}.
        <br/><br/>
        Do not hesitate to contact us if you have any questions.
        <br/><br/>
        Best regards,<br/>
        % if user and user.signature:
        ${user.signature | safe}
        % endif
    </p>
      </div>
    </field>
  </record>
  <record id="mt_invoice_created" model="mail.message.subtype">
    <field name="res_model">account.move</field>
  </record>
  <record id="mt_invoice_paid" model="mail.message.subtype">
    <field name="res_model">account.move</field>
  </record>
  <record id="mt_invoice_validated" model="mail.message.subtype">
    <field name="res_model">account.move</field>
  </record>
  <record id="tax_comp_rule" model="ir.rule">
    <field name="domain_force">['|',('company_id','=',False),('company_id', 'in', company_ids)]</field>
  </record>
</odoo>
```

I think the problem is in the file update_changes.xml of Migration, in the lines:
```
<record id="base.group_user" model="res.groups">
    <field name="implied_ids" eval="[(4, ref('account.group_show_line_subtotals_tax_excluded'))]"/>
 </record>
```
If I change the code an set account.group_show_line_subtotals_tax_excluded to account.group_show_line_subtotals_tax_included, the process not fail because it passes the validation of res_users.py

I am starting with OpenUpgrade and I don't know how it would be correct, so I report this bug and if you consider it as such, you can correct it. There will be other people who have their system configured with taxes excluded ...

**Comment by legalsylvain** [comment]
Hi @estraka.
Thanks for reporting. Some links : 
- Constraint In V12 : https://github.com/odoo/odoo/blob/12.0/addons/account/models/res_users.py#L13
- Constraint in V13 : https://github.com/odoo/odoo/blob/13.0/addons/account/models/res_users.py#L13
- no_update.xml file in OpenUpgrade : https://github.com/OCA/OpenUpgrade/blob/13.0/addons/account/migrations/13.0.1.1/noupdate_changes.xml#L41https://github.com/OCA/OpenUpgrade/blob/13.0/addons/account/migrations/13.0.1.1/post-migration.py#L1024

Indeed, it looks that if users are member of ``account.group_show_line_subtotals_tax_included`` AND member of ``base.group_user`` in V12, the upgrade process to V13 will fail.

To fix the problem in a generic way, you should add a function ``def _fix_member_group_show_line`` in the post-migration.py script, and in this function, remove the membership of ``account.group_show_line_subtotals_tax_included`` for the users member of ``base.group_user``, then call this function before [that call](https://github.com/OCA/OpenUpgrade/blob/13.0/addons/account/migrations/13.0.1.1/post-migration.py#L1024)

> I am starting with OpenUpgrade and I don't know how it would be correct

What do you think ? Could try to make a PR ? 
welcome in Openupgrade project !

regards.

**Comment by estraka** [comment]
Hi @legalsylvain . I'm working to fix the bug.
In addition to what was commented before, I had to delete the relation 
`base.group_user <--> account.group_show_line_subtotals_tax_included `
in the res_groups_implied_rel table.

I believe that this will not cause any problem, because in the file noupdate_changes.xml the relation 
`group_user <--> account.group_show_line_subtotals_tax_excluded` 
is created.

I'm going to try to launch the PR, to see if I know.

**Comment by pedrobaeza** [comment]
For me the solution is simple: comment this line in the noupdate records and let the user configuration:

https://github.com/OCA/OpenUpgrade/blob/050399414ab70667ca837b90d34205a51f978859/addons/account/migrations/13.0.1.1/noupdate_changes.xml#L42

**Comment by estraka** [comment]
Hi @pedrobaeza I am a novice in openupgrade and I followed the indications of @legalsylvain . 
What you comment was the test that I did to finish my migration in tests, but since I do not know enough about the project, I asked here and let me advise, because I imagined that if that line was there, it would be for some reason that I escaped .
To me it would seem like the best solution if you can comment on that line, because that way users are not deconfigured, because the solution provided forces you to re-set the group to the users you want

**Comment by pedrobaeza** [comment]
Closing this issue to continue commenting on the PR.
