### ISSUE TITLE
Error while manual migration from v11 to v12

### ISSUE THREAD

**Issue by Jawaid94** [OCA/OpenUpgrade#2490]
I am running OpenUpgrade-12.0 to upgrade my db v11. I am running through this "-c C:\Users\JAWAID\Desktop\Odoo\OpenUpgrade-12.0\debian\odoo.conf -d db11_to_12 --update all --stop-after-init" but I got error while upgrading base module
Current behavior:
2020-12-30 05:19:13,193 9416 ERROR db11_to_12 odoo.addons.base.models.ir_model: Failed to insert ir_model_data
('base', 'field_base__id', 'ir.model.fields', 1, False)
('base', 'field_base__display_name', 'ir.model.fields', 2, False)
('base', 'field_base____last_update', 'ir.model.fields', 3, False) 
2020-12-30 05:19:13,198 9416 WARNING db11_to_12 odoo.modules.loading: Transient module states were reset 
2020-12-30 05:19:13,199 9416 ERROR db11_to_12 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "C:\Users\JAWAID\Desktop\Odoo\OpenUpgrade-12.0\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Users\JAWAID\Desktop\Odoo\OpenUpgrade-12.0\odoo\modules\loading.py", line 414, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "C:\Users\JAWAID\Desktop\Odoo\OpenUpgrade-12.0\odoo\modules\loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "C:\Users\JAWAID\Desktop\Odoo\OpenUpgrade-12.0\odoo\modules\registry.py", line 318, in init_models
    func()
  File "C:\Users\JAWAID\Desktop\Odoo\OpenUpgrade-12.0\odoo\models.py", line 287, in _reflect
    self.env['ir.model.fields']._reflect_model(self)
  File "c:\users\jawaid\desktop\odoo\openupgrade-12.0\odoo\addons\base\models\ir_model.py", line 915, in _reflect_model
    for name in to_xmlids
  File "c:\users\jawaid\desktop\odoo\openupgrade-12.0\odoo\addons\base\models\ir_model.py", line 1573, in _update_xmlids
    self.env.cr.execute(query, [arg for row in sub_rows for arg in row])
  File "C:\Users\jawaid\Desktop\Odoo\OpenUpgrade-12.0\odoo\sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\jawaid\Desktop\Odoo\OpenUpgrade-12.0\odoo\sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near "ON"
LINE 4:             ON CONFLICT (module, name)
                    ^

2020-12-30 05:19:13,206 9416 CRITICAL db11_to_12 odoo.service.server: Failed to initialize database `db11_to_12`.

**Comment by pedrobaeza** [comment]
Seems outdated Postgres version.

**Comment by kos94ok-3D** [comment]
@Jawaid94  `ON CONFLICT` appeared in Postgresql 9.5
