### ISSUE TITLE
insert or update on table "repair_order" violates foreign key constraint "repair_order_invoice_id_fkey"

### ISSUE THREAD

**Issue by pleirb** [OCA/OpenUpgrade#2523]
Impacted versions: OpenUpgrade 13

Steps to reproduce: Run migration

Current behavior: Does not finish migrating

Expected behavior: Complete migration

Video/Screenshot link (optional):

Any ideas? The repair module has already been migrated?

2021-02-03 21:16:36,397 5083 WARNING DBX odoo.modules.loading: Transient module states were reset 
2021-02-03 21:16:36,406 5083 ERROR DBX odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/odoo/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/OpenUpgrade/odoo/modules/loading.py", line 477, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/OpenUpgrade/odoo/modules/loading.py", line 225, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/odoo/OpenUpgrade/odoo/modules/registry.py", line 375, in init_models
    func()
  File "/odoo/OpenUpgrade/odoo/fields.py", line 2472, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/odoo/OpenUpgrade/odoo/tools/sql.py", line 184, in fix_foreign_key
    return add_foreign_key(cr, tablename1, columnname1, tablename2, columnname2, ondelete)
  File "/odoo/OpenUpgrade/odoo/tools/sql.py", line 157, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: insert or update on table "repair_order" violates foreign key constraint "repair_order_invoice_id_fkey"
DETALLE:  Key (invoice_id)=(915) is not present in table "account_move".

2021-02-03 21:16:36,417 5083 CRITICAL DBX odoo.service.server: Failed to initialize database `DBX`. 
Traceback (most recent call last):
  File "/odoo/OpenUpgrade/odoo/service/server.py", line 1190, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/OpenUpgrade/odoo/modules/loading.py", line 477, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/OpenUpgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/OpenUpgrade/odoo/modules/loading.py", line 225, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/odoo/OpenUpgrade/odoo/modules/registry.py", line 375, in init_models
    func()
  File "/odoo/OpenUpgrade/odoo/fields.py", line 2472, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/odoo/OpenUpgrade/odoo/tools/sql.py", line 184, in fix_foreign_key
    return add_foreign_key(cr, tablename1, columnname1, tablename2, columnname2, ondelete)
  File "/odoo/OpenUpgrade/odoo/tools/sql.py", line 157, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/OpenUpgrade/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: insert or update on table "repair_order" violates foreign key constraint "repair_order_invoice_id_fkey"
DETALLE:  Key (invoice_id)=(915) is not present in table "account_move".

**Comment by legalsylvain** [comment]
> Any ideas? The repair module has already been migrated?

No. You can follow the migration state of the modules here : 

https://github.com/OCA/OpenUpgrade/blob/13.0/odoo/openupgrade/doc/source/modules120-130.rst
