### ISSUE TITLE
[12.0] hr_expense migration script violates not-null constraint

### ISSUE THREAD

**Issue by vifonne** [OCA/OpenUpgrade#2545]
Hello,

I am facing issues when I try to a database from Odoo 11.0 to 12.0 with OpenUpgrade. The script `hr_expense/migrations/12.0.2.0/post-m.py` try to insert a null value in column name, and the column name has a not-null constraint.

Impacted versions:
12.0

Steps to reproduce:
1. Duplicate an Odoo 11.0 database with hr_expense module installed and uses
2. Clone OpenUpgrade (this repository) on branch 12.0
3. Stop all Odoo instances on the server
4. Start the migration using this command : `./odoo-bin --addons-path=/usr/local/odoo/paid_addons_12/,/usr/local/odoo/migration_addons/ --database XXXXX --update all --stop-after-init -r XXXX -w "XXXXX" --db_host X.X.X.X --db_port X --logfile /tmp/migration.log`

Current behavior:
The migration stops with an exception raised at `while parsing /usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/noupdate_changes.xml:3` 

Expected behavior:
The hr_expense migration script should not violates a not-null constraint.
Traceback:
```
2021-02-09 14:41:52,996 27848 ERROR odoo-ophelia-senors-dev-12 odoo.sql_db: bad query: INSERT INTO "product_template" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "can_be_expensed", "categ_id", "company_id", "list_price", "produce_delay", "purchase_ok", "rental", "responsible_id", "sale_delay", "sale_ok", "sequence", "tracking", "type", "uom_id", "uom_po_id") VALUES (nextval('product_template_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), true, false, 3, 1, '1.00', 0.0, true, false, 1, 0.0, true, 1, 'none', 'consu', 1, 1) RETURNING id
ERROR: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).

2021-02-09 14:41:52,997 27848 ERROR odoo-ophelia-senors-dev-12 OpenUpgrade: hr_expense: error in migration script hr_expense/migrations/12.0.2.0/post-m.py: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).
" while parsing /usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/noupdate_changes.xml:3, near
<record id="product_product_fixed_cost" model="product.product">
    <field name="default_code">EXP_GEN</field>
    <field name="categ_id" ref="product.cat_expense"/>
  </record>
2021-02-09 14:41:52,997 27848 ERROR odoo-ophelia-senors-dev-12 OpenUpgrade: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).
" while parsing /usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/noupdate_changes.xml:3, near
<record id="product_product_fixed_cost" model="product.product">
    <field name="default_code">EXP_GEN</field>
    <field name="categ_id" ref="product.cat_expense"/>
  </record>
Traceback (most recent call last):
  File "/root/upgrade/12/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/root/upgrade/12/odoo/models.py", line 3915, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/root/upgrade/12/odoo/models.py", line 3829, in _load_records_create
    return self.create(values)
  File "<decorator-gen-168>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/product/models/product.py", line 344, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3604, in create
    for data in parent_data_list
  File "<decorator-gen-304>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/root/upgrade/12/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/local/odoo/migration_addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "<decorator-gen-157>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/local/odoo/migration_addons/product/models/product_template.py", line 348, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3610, in create
    records = self._create(data_list)
  File "/root/upgrade/12/odoo/models.py", line 3710, in _create
    cr.execute(query, params)
  File "/root/upgrade/12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/root/upgrade/12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1873, in wrapped_function
    if use_env2 else cr, version)
  File "/usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/post-m.py", line 22, in migrate
    env.cr, 'hr_expense', 'migrations/12.0.2.0/noupdate_changes.xml')
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 300, in load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 870, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 769, in parse
    exc_info[2]
  File "/root/upgrade/12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/root/upgrade/12/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/root/upgrade/12/odoo/models.py", line 3915, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/root/upgrade/12/odoo/models.py", line 3829, in _load_records_create
    return self.create(values)
  File "<decorator-gen-168>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/product/models/product.py", line 344, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3604, in create
    for data in parent_data_list
  File "<decorator-gen-304>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/root/upgrade/12/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/local/odoo/migration_addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "<decorator-gen-157>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/local/odoo/migration_addons/product/models/product_template.py", line 348, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3610, in create
    records = self._create(data_list)
  File "/root/upgrade/12/odoo/models.py", line 3710, in _create
    cr.execute(query, params)
  File "/root/upgrade/12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/root/upgrade/12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).
" while parsing /usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/noupdate_changes.xml:3, near
<record id="product_product_fixed_cost" model="product.product">
    <field name="default_code">EXP_GEN</field>
    <field name="categ_id" ref="product.cat_expense"/>
  </record>
2021-02-09 14:41:53,026 27848 ERROR odoo-ophelia-senors-dev-12 odoo.modules.loading: Error executing post migration script for module hr_expense
: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).
" while parsing /usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/noupdate_changes.xml:3, near
<record id="product_product_fixed_cost" model="product.product">
    <field name="default_code">EXP_GEN</field>
    <field name="categ_id" ref="product.cat_expense"/>
  </record>
2021-02-09 14:41:53,044 27848 ERROR odoo-ophelia-senors-dev-12 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/root/upgrade/12/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/root/upgrade/12/odoo/models.py", line 3915, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/root/upgrade/12/odoo/models.py", line 3829, in _load_records_create
    return self.create(values)
  File "<decorator-gen-168>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/product/models/product.py", line 344, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3604, in create
    for data in parent_data_list
  File "<decorator-gen-304>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/root/upgrade/12/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/local/odoo/migration_addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "<decorator-gen-157>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/local/odoo/migration_addons/product/models/product_template.py", line 348, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3610, in create
    records = self._create(data_list)
  File "/root/upgrade/12/odoo/models.py", line 3710, in _create
    cr.execute(query, params)
  File "/root/upgrade/12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/root/upgrade/12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/upgrade/12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/root/upgrade/12/odoo/modules/loading.py", line 480, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/root/upgrade/12/odoo/modules/loading.py", line 364, in load_marked_modules
    upg_registry=upg_registry,
  File "/root/upgrade/12/odoo/modules/loading.py", line 257, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/root/upgrade/12/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1873, in wrapped_function
    if use_env2 else cr, version)
  File "/usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/post-m.py", line 22, in migrate
    env.cr, 'hr_expense', 'migrations/12.0.2.0/noupdate_changes.xml')
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 300, in load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 870, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 769, in parse
    exc_info[2]
  File "/root/upgrade/12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/root/upgrade/12/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/root/upgrade/12/odoo/models.py", line 3915, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/root/upgrade/12/odoo/models.py", line 3829, in _load_records_create
    return self.create(values)
  File "<decorator-gen-168>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/product/models/product.py", line 344, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3604, in create
    for data in parent_data_list
  File "<decorator-gen-304>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/root/upgrade/12/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/local/odoo/migration_addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "<decorator-gen-157>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/local/odoo/migration_addons/product/models/product_template.py", line 348, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3610, in create
    records = self._create(data_list)
  File "/root/upgrade/12/odoo/models.py", line 3710, in _create
    cr.execute(query, params)
  File "/root/upgrade/12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/root/upgrade/12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).
" while parsing /usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/noupdate_changes.xml:3, near
<record id="product_product_fixed_cost" model="product.product">
    <field name="default_code">EXP_GEN</field>
    <field name="categ_id" ref="product.cat_expense"/>
  </record>
2021-02-09 14:41:53,047 27848 CRITICAL odoo-ophelia-senors-dev-12 odoo.service.server: Failed to initialize database `odoo-ophelia-senors-dev-12`.
Traceback (most recent call last):
  File "/root/upgrade/12/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/root/upgrade/12/odoo/models.py", line 3915, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/root/upgrade/12/odoo/models.py", line 3829, in _load_records_create
    return self.create(values)
  File "<decorator-gen-168>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/product/models/product.py", line 344, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3604, in create
    for data in parent_data_list
  File "<decorator-gen-304>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/root/upgrade/12/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/local/odoo/migration_addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "<decorator-gen-157>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/local/odoo/migration_addons/product/models/product_template.py", line 348, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3610, in create
    records = self._create(data_list)
  File "/root/upgrade/12/odoo/models.py", line 3710, in _create
    cr.execute(query, params)
  File "/root/upgrade/12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/root/upgrade/12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/upgrade/12/odoo/service/server.py", line 1162, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/root/upgrade/12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/root/upgrade/12/odoo/modules/loading.py", line 480, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/root/upgrade/12/odoo/modules/loading.py", line 364, in load_marked_modules
    upg_registry=upg_registry,
  File "/root/upgrade/12/odoo/modules/loading.py", line 257, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/root/upgrade/12/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1873, in wrapped_function
    if use_env2 else cr, version)
  File "/usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/post-m.py", line 22, in migrate
    env.cr, 'hr_expense', 'migrations/12.0.2.0/noupdate_changes.xml')
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 300, in load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 870, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 769, in parse
    exc_info[2]
  File "/root/upgrade/12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/root/upgrade/12/odoo/tools/convert.py", line 763, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/root/upgrade/12/odoo/tools/convert.py", line 668, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/root/upgrade/12/odoo/models.py", line 3915, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/root/upgrade/12/odoo/models.py", line 3829, in _load_records_create
    return self.create(values)
  File "<decorator-gen-168>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/product/models/product.py", line 344, in create
    products = super(ProductProduct, self.with_context(create_product_product=True)).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3604, in create
    for data in parent_data_list
  File "<decorator-gen-304>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/root/upgrade/12/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/local/odoo/migration_addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "<decorator-gen-157>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/local/odoo/migration_addons/product/models/product_template.py", line 348, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-127>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/local/odoo/migration_addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/root/upgrade/12/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/root/upgrade/12/odoo/models.py", line 3610, in create
    records = self._create(data_list)
  File "/root/upgrade/12/odoo/models.py", line 3710, in _create
    cr.execute(query, params)
  File "/root/upgrade/12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/root/upgrade/12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (298, null, 1, null, null, null, consu, f, 3, 1.00, null, null, t, t, 1, 1, 1, t, null, null, null, null, 1, 2021-02-09 14:41:16.419048, 1, 2021-02-09 14:41:16.419048, 1, 0, none, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, f, null, null, null, null, null, 0, null).
" while parsing /usr/local/odoo/migration_addons/hr_expense/migrations/12.0.2.0/noupdate_changes.xml:3, near
<record id="product_product_fixed_cost" model="product.product">
    <field name="default_code">EXP_GEN</field>
    <field name="categ_id" ref="product.cat_expense"/>
  </record>
2021-02-09 14:41:53,049 27848 INFO odoo-ophelia-senors-dev-12 odoo.service.server: Initiating shutdown
2021-02-09 14:41:53,050 27848 INFO odoo-ophelia-senors-dev-12 odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.```

**Comment by pedrobaeza** [comment]
That's because you deleted the product `Expense` that comes with this module. You must always do an `update all` on your DB before upgrading, and this product will be recovered.

**Comment by vifonne** [comment]
Thanks for your quick reply. It was helpful.
Is there some other requirements listed somwhere ? I did not find any information (maybe I did not look at the right place ?)

**Comment by pedrobaeza** [comment]
No, but that requirement is not for OpenUpgrade, it's a general Odoo one. If not, bad things can happen when installing any module, etc.
