### ISSUE TITLE
[14.0] account - not applying new module models

### ISSUE THREAD

**Issue by olivierb2** [OCA/OpenUpgrade#2595]
I'm not sure if this is too early yet, it's not very clear if new migration system based on module is already ready. I'm having trouble to upgrade my odoo 13 to 14. I have only few external module, but anyway, seems the core account module upgrade didn't pass. Apparently a foreign key reference try to use non existing table from account module while the module itself has those models. I tried various upgrade combination, but I'm not sure yet how to have those models applied to my existing database.

Impacted versions: 14.0

Steps to reproduce:

- Installed new odoo 14 virtual machine.
- Migrating modules into /opt/odoo/addons/
- Adding openupgrade_framework and openupgrade_scripts modules to /opt/odoo/addons/
- Importing database.
- Running command `odoo -u all -c /etc/odoo/odoo.conf --upgrade-path=/opt/odoo/addons/openupgrade_scripts/scripts/ -d my-db --stop-after-init --load=web,openupgrade_framework`

Current behavior:
The migration starts and after few dozen of seconds, the following error is displayed.

~~~
2021-02-25 13:51:58,202 6380 ERROR my-db odoo.sql_db: bad query: ALTER TABLE "account_reconcile_model_analytic_tag_rel" ADD FOREIGN KEY ("account_reconcile_model_line_id") REFERENCES "account_reconcile_model_line"("id") ON DELETE cascade
ERROR: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist
 
2021-02-25 13:51:58,209 6380 WARNING my-db odoo.modules.loading: Transient module states were reset 
2021-02-25 13:51:58,219 6380 ERROR my-db odoo.modules.registry: Failed to load registry 
2021-02-25 13:51:58,219 6380 CRITICAL my-db odoo.service.server: Failed to initialize database `my-db`. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 198, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 418, in init_models
    self.check_foreign_keys(cr)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 496, in check_foreign_keys
    sql.add_foreign_key(cr, table1, column1, table2, column2, ondelete)
  File "/usr/lib/python3/dist-packages/odoo/tools/sql.py", line 170, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "<decorator-gen-3>", line 2, in execute
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist

~~~

Expected behavior:
Having the upgrade running until the end of course.

**Comment by pedrobaeza** [comment]
Yes, too soon. There's nothing migrated.

**Comment by olivierb2** [comment]
Thanks !

**Comment by azmykn** [comment]
I have the same error , 
I try a clear DB and also have same 

```
2021-03-17 19:29:00,773 31298 ERROR 133 odoo.sql_db: bad query: ALTER TABLE "account_reconcile_model_analytic_tag_rel" ADD FOREIGN KEY ("account_reconcile_model_line_id") REFERENCES "account_reconcile_model_line"("id") ON DELETE cascade
ERROR: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist
```
# Commend : 
` ./odoo-bin --config=debian/odoo.conf --database=133 --update all --stop-after-init
`
# odoo.cnf 
`
; server_wide_modules = base,web

server_wide_modules = web,openupgrade_framework

upgrade_path = add2/openupgrade_scripts/scripts`

**Comment by pedrobaeza** [comment]
There's nothing migrated yet.

**Comment by azmykn** [comment]
> There's nothing migrated yet.
Thanks a lot , 
How to fix this error , is stop the script .

**Comment by olivierb2** [comment]
What @pedrobaeza said is that OpenUpgrade is not yet ready to make migration from 13.0 to 14.0.

**Comment by azmykn** [comment]
> What @pedrobaeza said is that OpenUpgrade is not yet ready to make migration from 13.0 to 14.0.

Thanks a lot ...

**Comment by ronny-montano** [comment]
I have this error migrating 13.0 to 14.0:

ALTER TABLE "account_reconcile_model_analytic_tag_rel" ADD FOREIGN KEY ("account_reconcile_model_line_id") REFERENCES "account_reconcile_model_line"("id") ON DELETE cascade
ERROR: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist
