### ISSUE TITLE
[13.0 -> 14.0] Migration fail due to "foreign key constraint does not exist"

### ISSUE THREAD

**Issue by TheNick87** [OCA/OpenUpgrade#2665]
Hi,
i'm trying to migrate from Odoo 13 to Odoo 14 (i'm an Odoo newbie), but it fails when trying to reference at a not existing table (account_reconcile_model_line).
I also find that in file <path>/odoo/addons/account/models/account_reconcile_model.py model AccountReconcileModelLine exists, so what is the problem?

Impacted versions: OpenUpgrade 14.0

Steps to reproduce: Just by executing procedure until it fail

Current behavior: 

2021-04-16 14:19:45,506 12355 ERROR <db_name_masked> odoo.sql_db: bad query: ALTER TABLE "account_reconcile_model_analytic_tag_rel" ADD FOREIGN KEY ("account_reconcile_model_line_id") REFERENCES "account_reconcile_model_line"("id") ON DELETE cascade
ERROR: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist
 
2021-04-16 14:19:45,523 12355 WARNING <db_name_masked> odoo.modules.loading: Transient module states were reset 
2021-04-16 14:19:45,526 12355 ERROR <db_name_masked> odoo.modules.registry: Failed to load registry 
2021-04-16 14:19:45,526 12355 CRITICAL <db_name_masked> odoo.service.server: Failed to initialize database `<db_name_masked>`. 
Traceback (most recent call last):
  File "/opt/openupgrade/odoo-14/odoo/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/openupgrade/odoo-14/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openupgrade/odoo-14/odoo/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/openupgrade/odoo-14/odoo/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/openupgrade/odoo-14/odoo/odoo/modules/loading.py", line 198, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/opt/openupgrade/odoo-14/odoo/odoo/modules/registry.py", line 418, in init_models
    self.check_foreign_keys(cr)
  File "/opt/openupgrade/odoo-14/odoo/odoo/modules/registry.py", line 496, in check_foreign_keys
    sql.add_foreign_key(cr, table1, column1, table2, column2, ondelete)
  File "/opt/openupgrade/odoo-14/odoo/odoo/tools/sql.py", line 170, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/openupgrade/odoo-14/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/openupgrade/odoo-14/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist

Expected behavior: Expect that it find table "account_reconcile_model_line"

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
`account` module is not yet migrated.

**Comment by perrysmg** [comment]
@pedrobaeza how can I skip the migration of "account" in the process?
I hit the same issue and am stuck in the migration process, what can I do to move forward to migrate other modules? since "account" module is not migrated yet and no way to migrate it.

**Comment by pedrobaeza** [comment]
You can't skip anything. A DB is not able to be migrated if you don't have all the migration scripts for the whole module list.

**Comment by perrysmg** [comment]
@pedrobaeza thanks for your reply!
but my question is: How can I do now if I am willing to migrate my v13 system to v14? 
The community edition v13 I am working on is typical and seems the migration in this project is the only way if I am going to work on v14. and I assume that the migration should work because the v13 is typical and the community edition v14 (Sources) is downloaded from https://www.odoo.com/page/download.

**Comment by pedrobaeza** [comment]
That's not possible for now if you have account installed. You have to wait.

**Comment by perrysmg** [comment]
@pedrobaeza thanks for your information! 
Does your team have plan to support 'account'? when might it be ready?

**Comment by pedrobaeza** [comment]
See the progress in #2190

**Comment by perrysmg** [comment]
@pedrobaeza thanks! I will track it there.
