### ISSUE TITLE
Error Migrating v7 to v8 

### ISSUE THREAD

**Issue by fred0716** [OCA/OpenUpgrade#269]
After changing user to openerp and running migrate.py.
There are lots of error message. 

The following are error messages in migration.log file.

2015-03-25 14:53:36,218 23756 ERROR IPRO_migrated OpenUpgrade: Invalid value 'tree_account_reconciliation' in the table 'ir_ui_view' for the
 field 'type'. (1 rows).
2015-03-25 14:54:17,035 23756 ERROR IPRO_migrated openerp.addons.base.ir.ir_ui_view: Field `menu_id` does not exist

Error context:
View `res.users.groups`
[view_id: 159, xml_id: base.user_groups_view, model: res.users, parent_id: 156]
2015-03-25 14:54:17,310 23756 ERROR IPRO_migrated openerp.addons.base.ir.ir_ui_view: Field `menu_id` does not exist

Error context:
View `res.users.groups`
[view_id: 159, xml_id: base.user_groups_view, model: res.users, parent_id: 156]
2015-03-25 14:54:48,413 23756 INFO IPRO_migrated OpenUpgrade: base: post-migration script called with version 7.0.1.3
2015-03-25 14:55:52,975 23756 INFO IPRO_migrated OpenUpgrade: Selecting autoinstallable modules portal,auth_crypt,payment,bus,pad_project
2015-03-25 14:56:25,853 23756 INFO IPRO_migrated OpenUpgrade: resource: pre-migration script called with version 7.0.1.1
2015-03-25 14:56:59,404 23756 INFO IPRO_migrated OpenUpgrade: mail: pre-migration script called with version 7.0.1.0
2015-03-25 14:56:59,405 23756 INFO IPRO_migrated OpenUpgrade: table mail_mail, column email_from: renaming to openupgrade_legacy_8_0_email_f
rom
2015-03-25 14:56:59,416 23756 INFO IPRO_migrated OpenUpgrade: table mail_mail, column mail_server_id: renaming to openupgrade_legacy_8_0_mai
l_server_id
2015-03-25 14:56:59,418 23756 INFO IPRO_migrated OpenUpgrade: table mail_mail, column reply_to: renaming to openupgrade_legacy_8_0_reply_to
2015-03-25 14:56:59,421 23756 INFO IPRO_migrated OpenUpgrade: table res_partner, column notification_email_send: renaming to openupgrade_leg
acy_8_0_notification_email_send
2015-03-25 14:57:04,860 23756 ERROR IPRO_migrated openerp.sql_db: bad query: ALTER TABLE "mail_message" ADD FOREIGN KEY ("author_id") REFERE
NCES "res_partner" ON DELETE set null
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "mail_message" violates foreign key constraint "mail_message_author_id_fkey"
DETAIL:  Key (author_id)=(450) is not present in table "res_partner".

2015-03-25 14:57:04,866 23756 CRITICAL IPRO_migrated openerp.service.server: Failed to initialize database `IPRO_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 909, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks
, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 179, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/module.py", line 293, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 2705, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "mail_message" violates foreign key constraint "mail_message_author_id_fkey"
DETAIL:  Key (author_id)=(450) is not present in table "res_partner".

**Comment by ikus060** [comment]
I have the same issue here. Did you, by any chance, managed to fix this issue ?

**Comment by ikus060** [comment]
After some digging, I manage to fix the error by deleting the orphan row in `mail_notification` table.

```
SELECT * FROM mail_notification WHERE message_id NOT IN (SELECT id FROM mail_message);
DELETE FROM mail_notification WHERE message_id NOT IN (SELECT id FROM mail_message);
```
