### ISSUE TITLE
[13.0][product] Images not showing and variants are deactivated after migration

### ISSUE THREAD

**Issue by vkanev** [OCA/OpenUpgrade#2731]
Impacted versions: 13.0

Steps to reproduce: migrate a v12.0 database to v13.0 with products with at least 2 variants with images.

Current behavior: Images aren't shown after migration in website and backend. All variants are deactivated and Ecommerce throws an error when loading particular product:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_sale_product_1174
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 994, in _get_first_possible_combination
    return next(self._get_possible_combinations(parent_combination, necessary_values), self.env['product.template.attribute.value'])
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 1120, in _get_possible_combinations
    for partial_combination in self._cartesian_product(product_template_attribute_values_per_line, parent_combination):
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 1042, in _cartesian_product
    current_ptav = current_line_values[current_ptav_index]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5735, in __getitem__
    return self.browse((self._ids[key],))
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1236, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1229, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1191, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 344, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1199, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 340, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: tuple index out of range
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_sale_product_1174
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 994, in _get_first_possible_combination
    return next(self._get_possible_combinations(parent_combination, necessary_values), self.env['product.template.attribute.value'])
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 1120, in _get_possible_combinations
    for partial_combination in self._cartesian_product(product_template_attribute_values_per_line, parent_combination):
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 1042, in _cartesian_product
    current_ptav = current_line_values[current_ptav_index]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5735, in __getitem__
    return self.browse((self._ids[key],))
IndexError: tuple index out of range

Error to render compiling AST
IndexError: tuple index out of range
Template: website_sale.product
Path: /t/t[1]
Node: <t t-set="combination" t-value="product._get_first_possible_combination()"/>
```

Expected behavior: Variants data is still in database, but everything is "inactive".
Some columns are not populated with data:
```
product_template_attribute_value.ptav_active
product_template_attribute_value.attribute_id
product_template_attribute_value.attribute_line_id.
```

Maybe there are more columns not populated with data in other tables.

Looking at the pre_migration and post_migration scripts, I can see at pre_migration.py:65 records are inserted in product_template_attribute_line with active column marked as False. At post_migration.py:7 data is filled, but only for `product_template_attribute_line.active = TRUE` products, which is none at this moment of migration process.

After setting `product_template_attribute_line.active = True` and executing the query at post_migration.py:7 again `product_template_attribute_value.attribute_line_id` and `product_template_attribute_value.attribute_id` are populated.

Still variants should be activated, where needed. I assume all records in `product_template_attribute_value` without any value in `product_template_attribute_value.attribute_line_id` and `product_template_attribute_value.attribute_id` are single variant products, so they don't need to be activated (just guessing):
`update product_template_attribute_value set ptav_active = 'f' where attribute_id is null and attribute_line_id is null;`
and others should be activated:
`update product_template_attribute_value set ptav_active = 't' where attribute_id is not null and attribute_line_id is not null;`

As I am not very well informed of all flags in the database, maybe more checks should be made before changing `product_template_attribute_value.ptav_active = 't'`.

All my suggestions and changes aren't fixing the images.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is working on my side. Please provide a set of data that reproduces the problem.

**Comment by vkanev** [comment]
Not relevant anymore.
