### ISSUE TITLE
Fail to start after upgrade from v7 to v8

### ISSUE THREAD

**Issue by webgourou** [OCA/OpenUpgrade#279]
Hi,

I made an upgrade via migrate.py. Everything seems correct, but when I want to start an instance on a working odoo server, I got this error message
2015-04-15 14:20:21,379 2491 INFO lesa2_migrated_migrated openerp.addons.base.ir.ir_http: Generating routing map
2015-04-15 14:20:24,762 2491 INFO lesa2_migrated_migrated werkzeug: 127.0.0.1 - - [15/Apr/2015 14:20:24] "GET /favicon.ico HTTP/1.1" 500 -
2015-04-15 14:20:24,770 2491 ERROR lesa2_migrated_migrated werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/media/Media/Devel/odoo/openerp/service/server.py", line 281, in app
    return self.app(e, s)
  File "/media/Media/Devel/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/media/Media/Devel/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/media/Media/Devel/odoo/openerp/http.py", line 1280, in **call**
    return self.dispatch(environ, start_response)
  File "/media/Media/Devel/odoo/openerp/http.py", line 1254, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/media/Media/Devel/odoo/openerp/http.py", line 1421, in dispatch
    result = ir_http._dispatch()
  File "/media/Media/Devel/odoo/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/media/Media/Devel/odoo/openerp/addons/base/ir/ir_http.py", line 153, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/Media/Devel/odoo/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/Media/Devel/odoo/openerp/addons/base/ir/ir_http.py", line 200, in routing_map
    self._routing_map = http.routing_map(mods, False, converters=self._get_converters())
  File "/media/Media/Devel/odoo/openerp/http.py", line 843, in routing_map
    url = o._cp_path.rstrip('/') + '/' + url.lstrip('/')
AttributeError: 'Home (extended by JsColor, AuthSignupHome)' object has no attribute '_cp_path'

on url = o._cp_path, the o value is Home (extended by JsColor, AuthSignupHome): <openerp.http.Home (extended by JsColor, AuthSignupHome) object at 0x7fe64f713f90>

If someone could have an idea how to fix it...
Thanks

Aurelien

**Comment by webgourou** [comment]
ok the bug comes from custom_module widget_color, the module web_color is supported

Thanks
