### ISSUE TITLE
Errors migrating from 7 to 8

### ISSUE THREAD

**Issue by javierobcn** [OCA/OpenUpgrade#283]
Hello, I'm stuck some days with the following error, any ideas are very welcome:

First error i obtain is:
Invalid value 'tree_account_reconciliation' in the table 'ir_ui_view' for the field 'type'. (1 rows).

then, later:

2015-04-22 18:16:53,850 10492 ERROR db_prod_migrated OpenUpgrade: Invalid value 'email' in the model 'ir_actions_server' for the field 'state'. (id 568).Please overload the new ir_actions_server._get_state function.
2015-04-22 18:16:53,850 10492 ERROR db_prod_migrated OpenUpgrade: Invalid value 'email' in the model 'ir_actions_server' for the field 'state'. (id 601).Please overload the new ir_actions_server._get_state function.

And later:

2015-04-22 18:18:51,634 10492 ERROR db_prod_migrated openerp.sql_db: bad query: ALTER TABLE "stock_picking" ALTER COLUMN "picking_type_id" SET NOT NULL
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "picking_type_id" contains null values

2015-04-22 18:18:51,636 10492 WARNING db_prod_migrated openerp.models: WARNING: unable to set column picking_type_id of table stock_picking not null !
Try to re-run: openerp-server --update=module
If it doesn't work, update records and execute manually:
ALTER TABLE stock_picking ALTER COLUMN picking_type_id SET NOT NULL
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 2658, in _auto_init
    cr.execute('ALTER TABLE "%s" ALTER COLUMN "%s" SET NOT NULL' % (self._table, k))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "picking_type_id" contains null values

And this:

2015-04-22 18:19:41,354 10492 INFO db_prod_migrated OpenUpgrade: table stock_picking, column sale_id: renaming to openupgrade_legacy_8_0_sale_id
2015-04-22 18:19:41,355 10492 ERROR db_prod_migrated openerp.sql_db: Programming error: column "sale_id" does not exist
, in query ALTER TABLE "stock_picking" RENAME "sale_id" TO "openupgrade_legacy_8_0_sale_id"
2015-04-22 18:19:41,355 10492 ERROR db_prod_migrated OpenUpgrade: sale_stock: error in migration script /var/tmp/openupgrade/8.0/addons/sale_stock/migrations/8.0.1.0/pr$

Finally:

2015-04-22 18:19:41,355 10492 ERROR db_prod_migrated OpenUpgrade: column "sale_id" does not exist
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 805, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/sale_stock/migrations/8.0.1.0/pre-migration.py", line 33, in migrate
    openupgrade.rename_columns(cr, column_renames)
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 194, in rename_columns
    'ALTER TABLE "%s" RENAME "%s" TO "%s"' % (table, old, new,))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "sale_id" does not exist

Thanks for your time and for this project

**Comment by o-w** [comment]
Same issue OpenUpgrade: Invalid value 'tree_account_reconciliation' in the table 'ir_ui_view' for the field 'type'.

**Comment by o-w** [comment]
Regarding the "tree_account_reconciliation" error ->
https://github.com/OpenUpgrade/OpenUpgrade/issues/220

**Comment by o-w** [comment]
I've got the same error after that:

"bad query: ALTER TABLE "stock_picking" ALTER COLUMN "picking_type_id" SET NOT NULL" 

Gonna try running the SQL statement from psql and get back to you. Let me know how your migration is going!

**Comment by javierobcn** [comment]
despite these problems seems that migration performs well . Partners , sales , invoices etc. seems well... i can open the database with the last odoo 8, i need make more tests but seems migrated...
