### ISSUE TITLE
from v7 to v8 the Report module not found.

### ISSUE THREAD

**Issue by csrocha** [OCA/OpenUpgrade#288]
I tried to update from v7 to v8, but migration script dead with the following error:

```
$ ./migrate.py --config=/.../etc/openerp-server.conf --database=ctmil_v7_0 --run-migrations=8.0 -B ../.. -A l10n_ar_migrate.py
$ tail -f migration.log
Traceback (most recent call last):
  File "/home/crocha/Projects/Update/8.0/server/openerp/service/server.py", line 909, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/crocha/Projects/Update/8.0/server/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/crocha/Projects/Update/8.0/server/openerp/modules/loading.py", line 369, in load_modules
    modobj.button_upgrade(cr, SUPERUSER_ID, ids)
  File "/home/crocha/Projects/Update/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/crocha/Projects/Update/8.0/server/openerp/addons/base/module/module.py", line 564, in button_upgrade
    raise orm.except_orm(_('Error'), _('You try to upgrade a module that depends on the module: %s.\nBut this module is not available in your system.') % (dep.name,))
except_orm: (u'Error', u'\ufeffIntenta actualizar un m\xf3dulo que depende del m\xf3dulo: report.\nPero este m\xf3dulo no est\xe1 disponible en su sistema.')
```

The first module with problem is "sale". Removing dependencies to "report" continue the migration, when other module with "report" dependency appear.

I think the main problem is because migration script no update the list of modules before load modules.

**Comment by hbrunn** [comment]
openupgrade should do that internally. Did you verify that `/home/crocha/Projects/Update/8.0/server.cfg` exists and points to the correct `addons_path`s?

**Comment by hbrunn** [comment]
there's also a possibility that you mess up things in `l10n_ar_migrate.py` - could you post its contents?

**Comment by csrocha** [comment]
@hbrunn,Thanks for your answer. This are the log's head lines:

```
$ head migration.log 
2015-05-05 19:24:39,273 2165 INFO ? openerp: OpenERP version 8.0
2015-05-05 19:24:39,273 2165 INFO ? openerp: addons paths:
 ['/home/crocha/.local/share/Odoo/addons/8.0',
 u'/home/crocha/Projects/Update/8.0/server/openerp/addons',
 u'/home/crocha/Projects/Update/8.0/l10n_ar_vat_reports',
 u'/home/crocha/Projects/Update/8.0/l10n_ar_wsafip',
 u'/home/crocha/Projects/Update/8.0/l10n_ar_bank',
 u'/home/crocha/Projects/Update/8.0/report_tex',
 u'/home/crocha/Projects/Update/8.0/l10n_ar_chart',
 u'/home/crocha/Projects/Update/8.0/crypto', 
 u'/home/crocha/Projects/Update/8.0/l10n_ar_invoice_tex',
 u'/home/crocha/Projects/Update/8.0/l10n_ar_states',
 u'/home/crocha/Projects/Update/8.0/odoo-crypto',
 u'/home/crocha/Projects/Update/8.0/l10n_ar_base_vat',
 u'/home/crocha/Projects/Update/8.0/odoo',
 u'/home/crocha/Projects/Update/8.0/l10n_ar_partner_title',
 u'/home/crocha/Projects/Update/8.0/addons',
 u'/home/crocha/Projects/Update/8.0/l10n_ar_invoice',
 u'/home/crocha/Projects/Update/8.0/l10n_ar_wsafip_fe']
```

The important directory is _/home/crocha/Projects/Update/8.0/addons_ where exists report directory/addon. 

```
$ ls /home/crocha/Projects/Update/8.0/addons/report
controllers  i18n         __init__.pyc  models          security  tests
data         __init__.py  migrations    __openerp__.py  static    views
```

And the l10n_ar_migrate.py script is:

``` python
migrations = {
    '8.0': {
        'addons': {
            'l10n_ar_bank': {
                'url': 'git@github.com:odoo-l10n-ar/l10n_ar_bank.git',
                'type': 'git',
            },
            'l10n_ar_base_vat': {
                'url': 'git@github.com:odoo-l10n-ar/l10n_ar_base_vat.git',
                'type': 'git',
            },
            'l10n_ar_chart': {
                'url': 'git@github.com:odoo-l10n-ar/l10n-ar-chart.git',
                'type': 'git',
            },
            'l10n_ar_invoice': {
                'url': 'git@github.com:odoo-l10n-ar/l10n_ar_invoice.git',
                'type': 'git',
            },
            'l10n_ar_invoice_tex': {
                'url': 'git@github.com:odoo-l10n-ar/l10n_ar_invoice_tex.git',
                'type': 'git',
            },
            'l10n_ar_partner_title': {
                'url': 'git@github.com:odoo-l10n-ar/l10n_ar_states.git',
                'type': 'git',
            },
            'l10n_ar_states': {
                'url': 'git@github.com:odoo-l10n-ar/l10n_ar_states.git',
                'type': 'git',
            },
            'l10n_ar_vat_reports': {
                'url': 'git@github.com:odoo-l10n-ar/l10n_ar_vat_reports.git',
                'type': 'git',
            },
            'l10n_ar_wsafip': {
                'url': 'git@github.com:odoo-l10n-ar/l10n_ar_wsafip.git',
                'type': 'git',
            },
            'l10n_ar_wsafip_fe': {
                'url': 'git@github.com:odoo-l10n-ar/l10n_ar_wsafip_fe.git',
                'type': 'git',
            },
            'crypto': {
                'url': 'git@github.com:ctmil/odoo-crypto.git',
                'type': 'git',
            },
            'odoo': {
                'url': 'git@github.com:odoo/odoo.git',
                'type': 'git',
            },
            'odoo-crypto': {
                'url': 'git@github.com:ctmil/odoo-crypto.git',
                'type': 'git',
            },
            'report_tex': {
                'url': 'git@github.com:ctmil/odoo-report-tex.git',
                'type': 'git',
            },
        }
    }
}
```

**Comment by hbrunn** [comment]
the `odoo` entry in your .py-file will cause problems later, so you should remove it (openupgrade has its own copy of the stock addons). But I'm not sure that's your current problem. Try it without anyways to see what happens.
Did you check all the addon paths if one of them contains a directory called `report`?

If none of the above helps, what happens if you leave out `-B` and `-A`? (that's just to double check that nothing local interferes, he'll download everything to /var/tmp/openupgrade then)

**Comment by StefanRijnhart** [comment]
@hbrunn The l10n_ar repos don't have a module directory level. Does migrate.py support such repos? One of the modules is bound to have a report subdirectory masking the 'report' core addon.

**Comment by csrocha** [comment]
@hbrunn, you are right. When migration.py setup the addons_path value for the server.cfg use the main directories for all repositories, and one of them have the _report_ directory, and use it for the "report" addons and not the real one.

Exists a lot of modules which use the root directory of the repository as the root module directory, and all of them will not work downloding them in this way.

**Comment by StefanRijnhart** [comment]
Closing as per discussion on #321
