### ISSUE TITLE
[10.0->11.0] Issue when migration from 11 to 12

### ISSUE THREAD

**Issue by rb3606** [OCA/OpenUpgrade#2881]
I am migrating from 10 to 12. 11 is done successfully. but when start for 11 to 12. i have below error. 

`2021-08-03 13:18:52,210 22725 INFO odoomijardin_10 odoo.modules.registry: module base: creating or updating database tables 
2021-08-03 13:18:52,264 22725 INFO odoomijardin_10 odoo.models: Computing parent_path for table ir_ui_menu... 
2021-08-03 13:18:53,501 22725 INFO odoomijardin_10 odoo.models: Computing parent_path for table res_partner_category... 
2021-08-03 13:18:54,727 22725 INFO odoomijardin_10 odoo.models: Storing computed values of ir.model.fields.relation_field_id 
2021-08-03 13:18:54,750 22725 INFO odoomijardin_10 odoo.models: Storing computed values of ir.model.fields.related_field_id 
2021-08-03 13:18:55,027 22725 INFO odoomijardin_10 odoo.models: Storing computed values of res.currency.decimal_places 
2021-08-03 13:18:55,111 22725 INFO odoomijardin_10 odoo.models: Actual recompute of field res.currency.decimal_places for 172 recs. 
2021-08-03 13:18:55,116 22725 INFO odoomijardin_10 odoo.models: Actual recompute of field ir.model.fields.related_field_id for 6278 recs. 
2021-08-03 13:18:55,186 22725 ERROR odoomijardin_10 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1091, in __get__
    value = record.env.cache.get(record, self)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.model.fields(9,).related_field_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 421, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 323, in init_models
    models[0].recompute()
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/models.py", line 5344, in recompute
    vals = {n: rec[n] for n in ns}
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/models.py", line 5344, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/models.py", line 5174, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1095, in __get__
    self.determine_value(record)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1184, in determine_value
    self.compute_value(recs)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1162, in compute_value
    self._compute_value(records)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1153, in _compute_value
    getattr(records, self.compute)()
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 420, in _compute_related_field_id
    field = rec._related_field()
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 469, in _related_field
    model = self.env[self.model or self.model_id.model]
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'stock.picking'
2021-08-03 13:18:55,187 22725 CRITICAL odoomijardin_10 odoo.service.server: Failed to initialize database `odoomijardin_10`. 
Traceback (most recent call last):
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1091, in __get__
    value = record.env.cache.get(record, self)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.model.fields(9,).related_field_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/service/server.py", line 1164, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 421, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 323, in init_models
    models[0].recompute()
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/models.py", line 5344, in recompute
    vals = {n: rec[n] for n in ns}
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/models.py", line 5344, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/models.py", line 5174, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1095, in __get__
    self.determine_value(record)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1184, in determine_value
    self.compute_value(recs)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1162, in compute_value
    self._compute_value(records)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/fields.py", line 1153, in _compute_value
    getattr(records, self.compute)()
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 420, in _compute_related_field_id
    field = rec._related_field()
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 469, in _related_field
    model = self.env[self.model or self.model_id.model]
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/var/tmp/openupgrade/OpenUpgrade/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'stock.picking'
`

**Comment by pedrobaeza** [comment]
You have bad dependencies in any module, but nothing on OpenUpgrade itself.

**Comment by rb3606** [comment]
@pedrobaeza i didnt have any custom module this is all odoo modules only.  So how dependencies issue come?

**Comment by pedrobaeza** [comment]
A related field tries to get `stock.picking`, so something incorrect is in your end. Maybe a bad uninstallation of something.

**Comment by rb3606** [comment]
Thanks for advise let me check if i can find anything.

**Comment by rb3606** [comment]
@pedrobaeza I found problem. In odoo 10 i have some custom fields in Transfer(stock.picking). Actually those are not using custom module but direct from UI of odoo. those fields are related with sales(sale.order). For now i deleted those fields from UI and its working. But actually i think it should not give error in such situation.

**Comment by pedrobaeza** [comment]
`Custom module` = anything custom, but that's it the problem. You shouldn't create anything from UI if you want a resilient system. This error can't be avoided due to the way Odoo works, but it's your risk if you create such things on the wild.

**Comment by rb3606** [comment]
You are right. Its wrong way to do customization from UI. Thanks for support.

**Comment by rb3606** [comment]
@pedrobaeza I just migrated db to 13. but when i checkout for 14.0 (openupgrade) there is no structure for migration. Is that changed or still not developed ?

**Comment by pedrobaeza** [comment]
Yes, check docs
