### ISSUE TITLE
[13.0->14.0] psycopg2.IntegrityError: could not create unique index "ir_property_unique_index"

### ISSUE THREAD

**Issue by rb3606** [OCA/OpenUpgrade#2889]
When start migration from 13 to 14. 

`2021-08-06 13:02:23,557 19956 DEBUG odoomijardin_11 OpenUpgrade: 0 rows affected after 0:00:00.001480 running UPDATE res_partner SET lang = 'tl_PH' WHERE lang = 'fil_PH' 
2021-08-06 13:02:23,624 19956 INFO odoomijardin_11 odoo.modules.registry: module base: creating or updating database tables 
2021-08-06 13:02:23,651 19956 INFO odoomijardin_11 odoo.schema: Table 'ir_model_data': unable to add constraint 'ir_model_data_name_nospaces' as CHECK(name NOT LIKE '% %') 
2021-08-06 13:02:23,733 19956 ERROR odoomijardin_11 odoo.sql_db: bad query: 
            CREATE UNIQUE INDEX IF NOT EXISTS ir_property_unique_index
            ON ir_property (fields_id, COALESCE(company_id, 0), COALESCE(res_id, ''))
        
ERROR: could not create unique index "ir_property_unique_index"
DETAIL:  Key (fields_id, COALESCE(company_id, 0), COALESCE(res_id, ''::character varying))=(3169, 3, ) is duplicated.
 
2021-08-06 13:02:23,734 19956 WARNING odoomijardin_11 odoo.modules.loading: Transient module states were reset 
2021-08-06 13:02:23,734 19956 ERROR odoomijardin_11 odoo.modules.registry: Failed to load registry 
2021-08-06 13:02:23,734 19956 CRITICAL odoomijardin_11 odoo.service.server: Failed to initialize database `odoomijardin_11`. 
Traceback (most recent call last):
  File "/opt/odoo14/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo14/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo14/odoo/modules/loading.py", line 401, in load_modules
    report=report, models_to_check=models_to_check)
  File "/opt/odoo14/odoo/modules/loading.py", line 198, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/opt/odoo14/odoo/modules/registry.py", line 404, in init_models
    model.init()
  File "/opt/odoo14/odoo/addons/base/models/ir_property.py", line 69, in init
    self.env.cr.execute(query % self._table)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo14/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo14/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: could not create unique index "ir_property_unique_index"
DETAIL:  Key (fields_id, COALESCE(company_id, 0), COALESCE(res_id, ''::character varying))=(3169, 3, ) is duplicated.

`

**Comment by pedrobaeza** [comment]
I don't think you are doing the process correctly. You need to put more evidences of a failure of OpenUpgrade itself. Closing meanwhile.

**Comment by rb3606** [comment]
I run migration for 13 using this command
python3 odoo-bin --addons-path=/opt/odoo14/addons,/var/tmp/openupgrade/OpenUpgrade -d odoodb_copy --upgrade-path=/var/tmp/openupgrade/OpenUpgrade/openupgrade_scripts/scripts/ --load=web,openupgrade_framework -u all

And after some second progress error occured. 

I have latest openupgrade library installed and latest repositary update.

**Comment by pedrobaeza** [comment]
You can check in https://github.com/OCA/OpenUpgrade/runs/3261585302?check_suite_focus=true#step:12:1 how is this working well.

**Comment by rb3606** [comment]
This is my initial log. One question do i have to run odoo13 instance or 14 ? 

`2021-08-06 13:02:23,332 19956 INFO odoomijardin_11 odoo.modules.migration: module base: Running migration [>14.0.1.3] pre-migrate 
2021-08-06 13:02:23,362 19956 INFO odoomijardin_11 OpenUpgrade: base: pre-migration script called with version 13.0.1.3 
2021-08-06 13:02:23,363 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000211 running UPDATE ir_model_data SET module = 'base', name = 'module_category_human_resources_expenses' WHERE module = 'base' and name = 'module_category_accounting_expenses' 
2021-08-06 13:02:23,363 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000183 running UPDATE ir_model_data SET module = 'base', name = 'module_category_productivity_discuss' WHERE module = 'base' and name = 'module_category_discuss' 
2021-08-06 13:02:23,364 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000098 running UPDATE ir_model_data SET module = 'base', name = 'module_category_accounting_localizations_account_charts' WHERE module = 'base' and name = 'module_category_localization_account_charts' 
2021-08-06 13:02:23,364 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000086 running UPDATE ir_model_data SET module = 'base', name = 'module_category_marketing_surveys' WHERE module = 'base' and name = 'module_category_marketing_survey' 
2021-08-06 13:02:23,364 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000097 running UPDATE ir_model_data SET module = 'base', name = 'module_category_services_helpdesk' WHERE module = 'base' and name = 'module_category_operations_helpdesk' 
2021-08-06 13:02:23,365 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000084 running UPDATE ir_model_data SET module = 'base', name = 'module_category_inventory_inventory' WHERE module = 'base' and name = 'module_category_operations_inventory' 
2021-08-06 13:02:23,365 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000083 running UPDATE ir_model_data SET module = 'base', name = 'module_category_inventory_delivery' WHERE module = 'base' and name = 'module_category_operations_inventory_delivery' 
2021-08-06 13:02:23,365 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000121 running UPDATE ir_model_data SET module = 'base', name = 'module_category_manufacturing_maintenance' WHERE module = 'base' and name = 'module_category_operations_maintenance' 
2021-08-06 13:02:23,365 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000083 running UPDATE ir_model_data SET module = 'base', name = 'module_category_services_project' WHERE module = 'base' and name = 'module_category_operations_project' 
2021-08-06 13:02:23,366 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000081 running UPDATE ir_model_data SET module = 'base', name = 'module_category_inventory_purchase' WHERE module = 'base' and name = 'module_category_operations_purchase' 
2021-08-06 13:02:23,366 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000080 running UPDATE ir_model_data SET module = 'base', name = 'module_category_services_timesheets' WHERE module = 'base' and name = 'module_category_operations_timesheets' 
2021-08-06 13:02:23,512 19956 DEBUG odoomijardin_11 OpenUpgrade: 11974 rows affected after 0:00:00.145619 running 
        UPDATE ir_model_data
        SET create_date = COALESCE(date_init, create_date),
            write_date = COALESCE(date_update, write_date)
        WHERE (create_date IS NULL OR write_date IS NULL) AND
            (date_init IS NOT NULL OR date_update IS NOT NULL)
         
2021-08-06 13:02:23,513 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000168 running UPDATE ir_module_module SET name = 'account_edi_facturx' WHERE name = 'account_facturx' 
2021-08-06 13:02:23,513 19956 DEBUG odoomijardin_11 OpenUpgrade: 1 rows affected after 0:00:00.000179 running UPDATE ir_model_data SET name = 'module_account_edi_facturx' WHERE name = 'module_account_facturx' AND module = 'base' AND model='ir.module.module'  
`

**Comment by pedrobaeza** [comment]
v14

**Comment by rb3606** [comment]
Then i am following correct things. I dont know why this error occured.

**Comment by rb3606** [comment]
link you shared have different log than me. Initially i dont have alter table drop constraint. Is that might issue ?
Also this showing different version as well.

 Running migration [>13.0.1.3] pre-migration  I have   Running migration [>14.0.1.3] pre-migrate

Also this line different as well
pre-migration script called with version 13.0.1.3 ( i have)
pre-migration script called with version 12.0.1.3 (link you given)

**Comment by pedrobaeza** [comment]
Yes, that means that it's not processing migration scripts.

**Comment by rb3606** [comment]
No. In that case it should given error. : Unable to load migration file as per migration.py line no : 172

**Comment by pedrobaeza** [comment]
I don't think so. That error is in other cases. Aren't you forgotting `base` in `load` command?
