### ISSUE TITLE
Error when running the upgrade

### ISSUE THREAD

**Issue by obayit** [OCA/OpenUpgrade#2912]
I get the following output from running the upgrade:
```
2021-09-19 09:41:09,459 26269 INFO ? odoo: Odoo version 12.0 
2021-09-19 09:41:09,459 26269 INFO ? odoo: Using configuration file at /home/obayit/.config/odoo/v12upgrade_ether 
2021-09-19 09:41:09,459 26269 INFO ? odoo: addons paths: ['/home/obayit/.local/share/Odoo/addons/12.0', '/home/obayit/src/oca/openupgrade12/addons', '/home/obayit/src/ether12', '/home/obayit/src/dev_tools', '/home/obayit/src/oca/openupgrade12/odoo/addons'] 
2021-09-19 09:41:09,459 26269 INFO ? odoo: database: default@default:default 
2021-09-19 09:41:09,538 26269 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2021-09-19 09:41:09,654 26269 CRITICAL ? odoo.modules.module: Couldn't load module openupgrade_framework 
2021-09-19 09:41:09,654 26269 CRITICAL ? odoo.modules.module: No module named 'openupgrade_framework' 
2021-09-19 09:41:09,654 26269 ERROR ? odoo.service.server: Failed to load server-wide module `openupgrade_framework`. 
Traceback (most recent call last):
  File "/home/obayit/src/oca/openupgrade12/odoo/service/server.py", line 1111, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/home/obayit/src/oca/openupgrade12/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/obayit/src/oca/openupgrade12/odoo/modules/module.py", line 61, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
  File "/usr/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'openupgrade_framework'
2021-09-19 09:41:09,663 26269 INFO ? odoo.modules.loading: init db 

```

The command I used was:
```
odoo -c ~/.config/odoo/v12upgrade_ether --update all --stop-after-init --load=base,web,openupgrade_framework
```

Installed openupgrading using the following steps:
1. Shallow clone only branch `12.0`
```
git clone --depth 1 git@github.com/oca/openupgrade -b 12.0 ~/src/oca/openupgrade12
```
2. create a virtual environment and install openupgrade dependencies
```
python3.6 -m virtualenv openupgrade12-36
source openupgrade12-36/bin/activate
python3.6 -m pip install -r ~/src/oca/openupgrade12/requirements.txt
```
3. install openupgrade's odoo itself, so that i can simply run odoo with the command `odoo`
```
python3.6 -m pip install -e ~/src/oca/openupgrade12/
```
Any help?

**Edit**
The upgrade will continue normally, but i am conserned with the critical error in the first few lines.

**Comment by pedrobaeza** [comment]
You are doing the v13 > v14 procedure. Such module doesn't exist in v13.
