### ISSUE TITLE
v13->v14:- AttributeError: 'NoneType' object has no attribute 'start'

### ISSUE THREAD

**Issue by Chanakya-OSI** [OCA/OpenUpgrade#2920]
/odoo/odoo/models.py", line 4057, in _compute_field_value
    getattr(self, field.compute)()

/addons/account/models/sequence_mixin.py", line 83, in _compute_split_sequence
    record.sequence_prefix = sequence[:matching.start(1)]
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by pedrobaeza** [comment]
Context of this?

**Comment by Chanakya-OSI** [comment]
el 
2021-09-27 04:46:44,033 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.001586 running ALTER TABLE "account_reconcile_model_analytic_tag_rel" DROP CONSTRAINT "account_analytic_tag_account_re_account_reconcile_model_id_fkey" 
2021-09-27 04:46:44,033 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000503 running ALTER TABLE "account_reconcile_model_analytic_tag_rel" DROP CONSTRAINT "account_analytic_tag_account_recon_account_analytic_tag_id_fkey" 
2021-09-27 04:46:44,035 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000860 running ALTER TABLE "account_reconcile_model_account_tax_rel" DROP CONSTRAINT "account_reconcile_model_account_account_reconcile_model_id_fkey" 
2021-09-27 04:46:44,036 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000619 running ALTER TABLE "account_reconcile_model_account_tax_rel" DROP CONSTRAINT "account_reconcile_model_account_tax_rel_account_tax_id_fkey" 
2021-09-27 04:46:44,038 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.001210 running ALTER TABLE "account_reconcile_model_template_account_tax_template_rel" DROP CONSTRAINT "account_reconcile_model_temp_account_reconcile_model_temp_fkey2" 
2021-09-27 04:46:44,039 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000475 running ALTER TABLE "account_reconcile_model_template_account_tax_template_rel" DROP CONSTRAINT "account_reconcile_model_template_a_account_tax_template_id_fkey" 
2021-09-27 04:46:44,040 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000434 running ALTER TABLE "account_reconcile_model_tmpl_account_tax_bis_rel" DROP CONSTRAINT "account_reconcile_model_tmpl__account_reconcile_model_temp_fkey" 
2021-09-27 04:46:44,041 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000362 running ALTER TABLE "account_reconcile_model_tmpl_account_tax_bis_rel" DROP CONSTRAINT "account_reconcile_model_tmpl_accou_account_tax_template_id_fkey" 
2021-09-27 04:46:44,041 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000164 running 
        ALTER TABLE account_reconcile_model_analytic_tag_rel
        ALTER COLUMN account_reconcile_model_id DROP NOT NULL
         
2021-09-27 04:46:44,041 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000185 running 
        ALTER TABLE account_reconcile_model_analytic_tag_rel
        ADD COLUMN account_reconcile_model_line_id integer
         
2021-09-27 04:46:44,897 633676 DEBUG test_24_13 OpenUpgrade: 67708 rows affected after 0:00:00.855186 running 
        UPDATE account_payment ap
        SET currency_id = COALESCE(aj.currency_id, rc.currency_id)
        FROM account_journal aj
        JOIN res_company rc ON aj.company_id = rc.id
        WHERE ap.journal_id = aj.id
         
2021-09-27 04:46:44,897 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000549 running 
        ALTER TABLE account_payment
        ADD COLUMN move_id integer
         
2021-09-27 04:46:44,898 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000503 running 
        ALTER TABLE account_move
        ADD COLUMN payment_id integer
         
2021-09-27 04:46:49,846 633676 DEBUG test_24_13 OpenUpgrade: 65893 rows affected after 0:00:04.948173 running 
        UPDATE account_move am
        SET payment_id = aml.payment_id
        FROM account_move_line aml
        WHERE aml.move_id = am.id AND aml.payment_id IS NOT NULL
         


2021-09-27 05:32:06,434 633676 DEBUG test_24_13 OpenUpgrade: 66472 rows affected after 0:45:16.586469 running 
        UPDATE account_payment ap
        SET move_id = am.id
        FROM account_move am
        WHERE (am.name NOT IN ('', '/') AND (ap.move_name = am.name OR (
            ap.payment_reference = am.name AND ap.move_name IS NULL)))
            OR am.payment_id = ap.id 
2021-09-27 05:32:23,777 633676 DEBUG test_24_13 OpenUpgrade: 366 rows affected after 0:00:17.342471 running 
        UPDATE account_payment ap
        SET move_id = am.id
        FROM account_move am
        WHERE ap.move_id IS NULL AND ap.communication NOT IN ('', '/') AND (
            am.payment_reference = ap.communication OR am.ref = ap.communication
            OR am.name = ap.communication)
         
2021-09-27 05:32:30,935 633676 DEBUG test_24_13 OpenUpgrade: 57616 rows affected after 0:00:07.157864 running 
        UPDATE account_move am
        SET payment_id = ap.id
        FROM account_payment ap
        WHERE am.id = ap.move_id
         
2021-09-27 05:32:30,936 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000584 running 
            ALTER TABLE account_bank_statement_line
            ADD COLUMN currency_id integer
             
2021-09-27 05:32:31,419 633676 DEBUG test_24_13 OpenUpgrade: 35786 rows affected after 0:00:00.482322 running 
        UPDATE account_bank_statement_line absl
        SET currency_id = COALESCE(aj.currency_id, rc.currency_id)
        FROM account_bank_statement bs
        JOIN account_journal aj ON bs.journal_id = aj.id
        JOIN res_company rc ON aj.company_id = rc.id
        WHERE absl.statement_id = bs.id
         
2021-09-27 05:32:31,420 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000522 running 
        ALTER TABLE account_bank_statement_line
        ADD COLUMN move_id integer
         
2021-09-27 05:32:31,421 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000830 running 
            ALTER TABLE account_move
            ADD COLUMN statement_line_id integer
             
2021-09-27 05:32:39,457 633676 DEBUG test_24_13 OpenUpgrade: 69431 rows affected after 0:00:08.035090 running 
        UPDATE account_move am
        SET statement_line_id = aml.statement_line_id
        FROM account_move_line aml
        WHERE aml.move_id = am.id AND aml.statement_line_id IS NOT NULL
         





2021-09-27 05:55:09,646 633676 DEBUG test_24_13 OpenUpgrade: 33607 rows affected after 0:22:30.188571 running 
        UPDATE account_bank_statement_line absl
        SET move_id = am.id
        FROM account_move am
        WHERE (am.name NOT IN ('', '/') AND (absl.move_name = am.name OR (
            absl.payment_ref = am.name AND absl.move_name IS NULL)))
            OR am.statement_line_id = absl.id
         
2021-09-27 05:55:09,734 633676 DEBUG test_24_13 OpenUpgrade: 37 rows affected after 0:00:00.087344 running 
        UPDATE account_bank_statement_line absl
        SET move_id = ap.move_id
        FROM account_payment ap
        WHERE absl.move_id IS NULL AND absl.payment_ref NOT IN ('', '/')
            AND absl.payment_ref = ap.communication
         
2021-09-27 05:55:09,746 633676 DEBUG test_24_13 OpenUpgrade: 0 rows affected after 0:00:00.012550 running 
        UPDATE account_bank_statement_line absl
        SET move_id = am.id
        FROM account_move am
        WHERE absl.move_id IS NULL AND absl.account_number NOT IN ('', '/')
            AND absl.account_number = am.ref
         
2021-09-27 05:55:10,470 633676 DEBUG test_24_13 OpenUpgrade: 119 rows affected after 0:00:00.723136 running 
        UPDATE account_move am
        SET statement_line_id = absl.id
        FROM account_bank_statement_line absl
        WHERE am.id = absl.move_id AND am.statement_line_id IS NULL
         
2021-09-27 05:55:10,501 633676 DEBUG test_24_13 OpenUpgrade: 10 rows affected after 0:00:00.030679 running 
        UPDATE account_payment
        SET partner_type = 'customer'
        WHERE partner_type IS NULL
         
2021-09-27 05:55:10,501 633676 DEBUG test_24_13 OpenUpgrade: -1 rows affected after 0:00:00.000447 running 
        ALTER TABLE account_move_line
        DROP CONSTRAINT IF EXISTS account_move_line_check_amount_currency_balance_sign
         
2021-09-27 05:56:34,776 633676 DEBUG test_24_13 OpenUpgrade: 939559 rows affected after 0:01:24.273917 running 
        UPDATE account_move_line
        SET currency_id = company_currency_id
        WHERE currency_id IS NULL
         
2021-09-27 05:56:34,806 633676 DEBUG test_24_13 OpenUpgrade: 0 rows affected after 0:00:00.029887 running 
        UPDATE account_payment ap
        SET partner_id = rc.partner_id
        FROM account_journal aj
        JOIN res_company rc ON aj.company_id = rc.id
        WHERE ap.payment_type = 'transfer'
         
2021-09-27 05:56:35,014 633676 WARNING test_24_13 odoo.fields: res.config.settings.google_maps_theme: selection=[('default', 'Default'), ('aubergine', 'Aubergine'), ('night', 'Night'), ('dark', 'Dark'), ('retro', 'Retro'), ('silver', 'Silver'), ('atlas', 'Atlas')] overrides existing selection; use selection_add instead 
2021-09-27 05:56:35,184 633676 WARNING test_24_13 odoo.fields: Field bwchange.change.state: unknown parameter 'rack_visibility', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2021-09-27 05:56:35,184 633676 WARNING test_24_13 odoo.fields: bwchange.change.state: selection attribute will be ignored as the field is related 
2021-09-27 05:56:35,342 633676 INFO test_24_13 odoo.modules.registry: module account: creating or updating database tables 
2021-09-27 05:56:35,398 633676 INFO test_24_13 odoo.schema: Table 'account_group': unable to add constraint 'account_group_check_length_prefix' as CHECK(char_length(COALESCE(code_prefix_start, '')) = char_length(COALESCE(code_prefix_end, ''))) 
2021-09-27 05:56:37,450 633676 INFO test_24_13 odoo.schema: Table 'account_move_line': unable to add constraint 'account_move_line_check_amount_currency_balance_sign' as CHECK(
                (
                    (currency_id != company_currency_id)
                    AND
                    (
                        (debit - credit <= 0 AND amount_currency <= 0)
                        OR
                        (debit - credit >= 0 AND amount_currency >= 0)
                    )
                )
                OR
                (
                    currency_id = company_currency_id
                    AND
                    ROUND(debit - credit - amount_currency, 2) = 0
                )
            ) 
2021-09-27 05:56:38,573 633676 INFO test_24_13 odoo.models: Storing computed values of account.account.is_off_balance 
2021-09-27 05:56:38,578 633676 INFO test_24_13 odoo.models: Storing computed values of account.journal.suspense_account_id 
2021-09-27 05:56:38,947 633676 INFO test_24_13 odoo.models: Storing computed values of account.move.sequence_prefix 
2021-09-27 05:56:38,962 633676 INFO test_24_13 odoo.models: Storing computed values of account.move.sequence_number 
2021-09-27 05:56:42,353 633676 INFO test_24_13 odoo.models: Storing computed values of account.move.line.matching_number 
2021-09-27 05:56:42,557 633676 INFO test_24_13 odoo.models: Storing computed values of account.partial.reconcile.debit_currency_id 
2021-09-27 05:56:42,559 633676 INFO test_24_13 odoo.models: Storing computed values of account.partial.reconcile.credit_currency_id 
2021-09-27 05:56:42,564 633676 INFO test_24_13 odoo.schema: Table 'account_payment': unable to set NOT NULL on column 'move_id' 
2021-09-27 05:56:42,787 633676 INFO test_24_13 odoo.models: Storing computed values of account.payment.is_reconciled 
2021-09-27 05:56:42,788 633676 INFO test_24_13 odoo.models: Storing computed values of account.payment.is_matched 
2021-09-27 05:56:42,790 633676 INFO test_24_13 odoo.models: Storing computed values of account.payment.partner_bank_id 
2021-09-27 05:56:42,791 633676 INFO test_24_13 odoo.models: Storing computed values of account.payment.is_internal_transfer 
2021-09-27 05:56:42,792 633676 INFO test_24_13 odoo.models: Storing computed values of account.payment.destination_account_id 
2021-09-27 05:56:42,796 633676 INFO test_24_13 odoo.models: Storing computed values of account.bank.statement.previous_statement_id 
2021-09-27 05:56:42,796 633676 INFO test_24_13 odoo.models: Storing computed values of account.bank.statement.is_valid_balance_start 
2021-09-27 05:56:42,796 633676 INFO test_24_13 odoo.models: Storing computed values of account.bank.statement.sequence_prefix 
2021-09-27 05:56:42,796 633676 INFO test_24_13 odoo.models: Storing computed values of account.bank.statement.sequence_number 
2021-09-27 05:56:42,803 633676 INFO test_24_13 odoo.schema: Table 'account_bank_statement_line': unable to set NOT NULL on column 'move_id' 
2021-09-27 05:56:42,876 633676 INFO test_24_13 odoo.models: Storing computed values of account.bank.statement.line.amount_residual 
2021-09-27 05:56:42,878 633676 INFO test_24_13 odoo.models: Storing computed values of account.bank.statement.line.is_reconciled 
2021-09-27 05:56:42,891 633676 INFO test_24_13 odoo.models: Storing computed values of res.company.account_tax_fiscal_country_id 
2021-09-27 05:57:23,228 633676 WARNING test_24_13 odoo.modules.loading: Transient module states were reset 
2021-09-27 05:57:23,234 633676 ERROR test_24_13 odoo.modules.registry: Failed to load registry 
2021-09-27 05:57:23,234 633676 CRITICAL test_24_13 odoo.service.server: Failed to initialize database `test_24_13`. 
Traceback (most recent call last):
  File "/opt/odoo/test/test-odoo/odoo/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/test/test-odoo/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/test/test-odoo/odoo/odoo/modules/loading.py", line 456, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/test/test-odoo/odoo/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/test/test-odoo/odoo/odoo/modules/loading.py", line 198, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/opt/odoo/test/test-odoo/odoo/odoo/modules/registry.py", line 420, in init_models
    env['base'].flush()
  File "/opt/odoo/test/test-odoo/odoo/odoo/models.py", line 5432, in flush
    self.recompute()
  File "/opt/odoo/test/test-odoo/odoo/odoo/models.py", line 5891, in recompute
    process(field)
  File "/opt/odoo/test/test-odoo/odoo/odoo/models.py", line 5875, in process
    field.recompute(recs)
  File "/opt/odoo/test/test-odoo/odoo/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/opt/odoo/test/test-odoo/odoo/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/test/test-odoo/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/opt/odoo/test/test-odoo/odoo/odoo/models.py", line 4057, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/test/test-odoo/odoo/addons/account/models/sequence_mixin.py", line 83, in _compute_split_sequence
    record.sequence_prefix = sequence[:matching.start(1)]
AttributeError: 'NoneType' object has no attribute 'start'
2021-09-27 05:57:23,241 633676 INFO test_24_13 odoo.service.server: Initiating shutdown 
2021-09-27 05:57:23,241 633676 INFO test_24_13 odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by pedrobaeza** [comment]
`account` module is not officially merged, so you are working with something draft. Anyways, the problem seems to be on your numbers in the old PR. Closing as not valid.
