### ISSUE TITLE
stock .picking -> old picking could not be invoiced (v7 to v8)

### ISSUE THREAD

**Issue by webgourou** [OCA/OpenUpgrade#296]
Hi,

on my picking still in back order once I deliver them, they could not be invoiced. 
Error message:
Traceback (most recent call last):
  File "/media/Media/Devel/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/Media/Devel/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/media/Media/Devel/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/media/Media/Devel/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/media/Media/Devel/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/media/Media/Devel/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/media/Media/Devel/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/media/Media/Devel/odoo/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/media/Media/Devel/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/media/Media/Devel/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/Media/Devel/odoo/addons/stock_account/wizard/stock_invoice_onshipping.py", line 91, in open_invoice
    raise osv.except_osv(_('Error!'), _('No invoice created!'))

And if I make a partial transfer, old picking and new picking become "not invoicable".

Does someone have an idea ?

Thanks 

Aurelien

**Comment by pedrobaeza** [comment]
But have you checked that this is something to do with the upgrade itself or it's an issue with your installation?

**Comment by webgourou** [comment]
yes it is due to upgrade, because I have no trouble to transform to invoice with new pickings.

**Comment by webgourou** [comment]
it seems that the invoice_state of the stock.move are set to 'none'.
When trying to create invoice with method action_invoice_create, as the invoice_state is none, nothing is created:

-- This part of code --
for move in picking.move_lines:
                if move.invoice_state == '2binvoiced':
                    if (move.state != 'cancel') and not move.scrapped:
                        todo.setdefault(key, [])
                        todo[key].append(move)

**Comment by webgourou** [comment]
when change manually the invoice_state to 2binvoiced, everything works fine.

**Comment by StefanRijnhart** [comment]
Fixed in the pending PR on stock_account for 8.0 (#297)
