### ISSUE TITLE
[13.0] Migration from v12 docker version

### ISSUE THREAD

**Issue by AmeliaPessoa** [OCA/OpenUpgrade#2962]
## Module
Base

## Describe the bug
I am just trying to migrate a clean instance of Odoo v12 that was created using docker and I have the following error:
```
2021-11-10 16:28:30,636 71474 ERROR odoo12db odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 394, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 983, in postprocess_and_fields
    attrs_fields = get_attrs_field_names(self.env, node, Model, editable)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 147, in get_attrs_field_names
    process(arch, model, editable)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 145, in process
    process(child, model, editable, get)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 145, in process
    process(child, model, editable, get)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 129, in process
    process_attrs(val, get, key, val)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 105, in process_attrs
    for domain in safe_eval(expr).values():
  File "OpenUpgrade-13.0/odoo/tools/safe_eval.py", line 352, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "OpenUpgrade-13.0/odoo/tools/safe_eval.py", line 213, in test_expr
    assert_valid_codeobj(allowed_codes, code_obj, expr)
  File "OpenUpgrade-13.0/odoo/tools/safe_eval.py", line 189, in assert_valid_codeobj
    raise ValueError("forbidden opcode(s) in %r: %s" % (expr, ', '.join(opname[x] for x in codes)))
ValueError: forbidden opcode(s) in "{'invisible': [                                 '|', '|',                                 '&', ('active', '=', True), ('active_partner', '=', True),                                 '&', ('active', '=', False), ('active_partner', '=', False),                                 '&', ('active', '=', True), ('active_partner', '=', False),                             ]}": LIST_EXTEND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "OpenUpgrade-13.0/odoo/models.py", line 4152, in _load_records
    data['record']._load_records_write(data['values'])
  File "OpenUpgrade-13.0/odoo/models.py", line 4090, in _load_records_write
    self.write(values)
  File "OpenUpgrade-13.0/odoo/addons/base/models/res_users.py", line 1049, in write
    self._update_user_groups_view()
  File "OpenUpgrade-13.0/odoo/addons/base/models/res_users.py", line 1149, in _update_user_groups_view
    view.with_context(new_context).write({'arch': xml_content})
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 494, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "OpenUpgrade-13.0/odoo/models.py", line 3648, in write
    fields[0].determine_inverse(real_recs)
  File "OpenUpgrade-13.0/odoo/fields.py", line 1156, in determine_inverse
    getattr(records, self.inverse)()
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 494, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "OpenUpgrade-13.0/odoo/models.py", line 3643, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "OpenUpgrade-13.0/odoo/models.py", line 1215, in _validate_fields
    check(self)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating view\n\nforbidden opcode(s) in "{\'invisible\': [                                 \'|\', \'|\',                                 \'&\', (\'active\', \'=\', True), (\'active_partner\', \'=\', True),                                 \'&\', (\'active\', \'=\', False), (\'active_partner\', \'=\', False),                                 \'&\', (\'active\', \'=\', True), (\'active_partner\', \'=\', False),                             ]}": LIST_EXTEND', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenUpgrade-13.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "OpenUpgrade-13.0/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "OpenUpgrade-13.0/odoo/modules/loading.py", line 248, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "OpenUpgrade-13.0/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 741, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 808, in convert_xml_import
    obj.parse(doc.getroot())
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 720, in parse
    pycompat.reraise(
  File "OpenUpgrade-13.0/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "OpenUpgrade-13.0/odoo/models.py", line 4152, in _load_records
    data['record']._load_records_write(data['values'])
  File "OpenUpgrade-13.0/odoo/models.py", line 4090, in _load_records_write
    self.write(values)
  File "OpenUpgrade-13.0/odoo/addons/base/models/res_users.py", line 1049, in write
    self._update_user_groups_view()
  File "OpenUpgrade-13.0/odoo/addons/base/models/res_users.py", line 1149, in _update_user_groups_view
    view.with_context(new_context).write({'arch': xml_content})
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 494, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "OpenUpgrade-13.0/odoo/models.py", line 3648, in write
    fields[0].determine_inverse(real_recs)
  File "OpenUpgrade-13.0/odoo/fields.py", line 1156, in determine_inverse
    getattr(records, self.inverse)()
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 494, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "OpenUpgrade-13.0/odoo/models.py", line 3643, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "OpenUpgrade-13.0/odoo/models.py", line 1215, in _validate_fields
    check(self)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating view

forbidden opcode(s) in "{'invisible': [                                 '|', '|',                                 '&', ('active', '=', True), ('active_partner', '=', True),                                 '&', ('active', '=', False), ('active_partner', '=', False),                                 '&', ('active', '=', True), ('active_partner', '=', False),                             ]}": LIST_EXTEND
None" while parsing OpenUpgrade-13.0/odoo/addons/base/security/base_groups.xml:2, near
<odoo>
    <data>

        <!--
            Users Groups
            Note that the field 'category_id' is set later in
            base/data/ir_module_category_data.xml
        -->
        <record model="res.groups" id="group_erp_manager">
            <field name="name">Access Rights</field>
        </record>

        <record model="res.groups" id="group_system">
            <field name="name">Settings</field>
            <field name="implied_ids" eval="[(4, ref('group_erp_manager'))]"/>
            <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]"/>
        </record>

        <record model="res.groups" id="group_user">
            <field name="name">Internal User</field>
        </record>

        <record id="default_user" model="res.users">
            <field name="groups_id" eval="[(4,ref('base.group_user'))]"/>
        </record>

        <record model="res.groups" id="group_multi_company">
            <field name="name">Multi Companies</field>
        </record>

        <record model="res.groups" id="group_multi_currency">
            <field name="name">Multi Currencies</field>
        </record>

        <record model="res.groups" id="group_no_one">
            <field name="name">Technical Features</field>
        </record>
        <record model="res.groups" id="group_user">
            <field name="implied_ids" eval="[(4, ref('group_no_one'))]"/>
            <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]"/>
        </record>

        <record model="res.groups" id="group_partner_manager">
            <field name="name">Contact Creation</field>
            <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]"/>
        </record>

        <record id="default_user" model="res.users">
            <field name="groups_id" eval="[(4,ref('base.group_partner_manager'))]"/>
        </record>

        <!--
            A group dedicated to the portal users, making groups
            restrictions more convenient.
        -->
        <record id="group_portal" model="res.groups">
            <field name="name">Portal</field>
            <field name="comment">Portal members have specific access rights (such as record rules and restricted menus).
                They usually do not belong to the usual Odoo groups.</field>
        </record>
        <!--
            A group dedicated to the public user only, making groups
            restrictions more convenient.
        -->
        <record id="group_public" model="res.groups">
            <field name="name">Public</field>
            <field name="comment">Public users have specific access rights (such as record rules and restricted menus).
                They usually do not belong to the usual Odoo groups.</field>
        </record>

        <record id="public_user" model="res.users">
            <field name="groups_id" eval="[(4, ref('base.group_public'))]"/>
        </record>

        <!-- Default template user for new users signing in -->
        <record id="template_portal_user_id" model="res.users">
            <field name="name">Portal User Template</field>
            <field name="login">portaltemplate</field>
            <field name="active" eval="False"/>
            <field name="groups_id" eval="[(6, 0, [ref('base.group_portal')])]"/>
        </record>

        <record id="default_template_user_config" model="ir.config_parameter">
            <field name="key">base.template_portal_user_id</field>
            <field name="value" ref="template_portal_user_id"/>
        </record>

    </data>
</odoo>
2021-11-10 16:28:30,717 71474 CRITICAL odoo12db odoo.service.server: Failed to initialize database `odoo12db`. 
Traceback (most recent call last):
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 394, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 983, in postprocess_and_fields
    attrs_fields = get_attrs_field_names(self.env, node, Model, editable)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 147, in get_attrs_field_names
    process(arch, model, editable)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 145, in process
    process(child, model, editable, get)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 145, in process
    process(child, model, editable, get)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 129, in process
    process_attrs(val, get, key, val)
  File "OpenUpgrade-13.0/odoo/tools/view_validation.py", line 105, in process_attrs
    for domain in safe_eval(expr).values():
  File "OpenUpgrade-13.0/odoo/tools/safe_eval.py", line 352, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "OpenUpgrade-13.0/odoo/tools/safe_eval.py", line 213, in test_expr
    assert_valid_codeobj(allowed_codes, code_obj, expr)
  File "OpenUpgrade-13.0/odoo/tools/safe_eval.py", line 189, in assert_valid_codeobj
    raise ValueError("forbidden opcode(s) in %r: %s" % (expr, ', '.join(opname[x] for x in codes)))
ValueError: forbidden opcode(s) in "{'invisible': [                                 '|', '|',                                 '&', ('active', '=', True), ('active_partner', '=', True),                                 '&', ('active', '=', False), ('active_partner', '=', False),                                 '&', ('active', '=', True), ('active_partner', '=', False),                             ]}": LIST_EXTEND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "OpenUpgrade-13.0/odoo/models.py", line 4152, in _load_records
    data['record']._load_records_write(data['values'])
  File "OpenUpgrade-13.0/odoo/models.py", line 4090, in _load_records_write
    self.write(values)
  File "OpenUpgrade-13.0/odoo/addons/base/models/res_users.py", line 1049, in write
    self._update_user_groups_view()
  File "OpenUpgrade-13.0/odoo/addons/base/models/res_users.py", line 1149, in _update_user_groups_view
    view.with_context(new_context).write({'arch': xml_content})
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 494, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "OpenUpgrade-13.0/odoo/models.py", line 3648, in write
    fields[0].determine_inverse(real_recs)
  File "OpenUpgrade-13.0/odoo/fields.py", line 1156, in determine_inverse
    getattr(records, self.inverse)()
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 494, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "OpenUpgrade-13.0/odoo/models.py", line 3643, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "OpenUpgrade-13.0/odoo/models.py", line 1215, in _validate_fields
    check(self)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating view\n\nforbidden opcode(s) in "{\'invisible\': [                                 \'|\', \'|\',                                 \'&\', (\'active\', \'=\', True), (\'active_partner\', \'=\', True),                                 \'&\', (\'active\', \'=\', False), (\'active_partner\', \'=\', False),                                 \'&\', (\'active\', \'=\', True), (\'active_partner\', \'=\', False),                             ]}": LIST_EXTEND', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenUpgrade-13.0/odoo/service/server.py", line 1192, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "OpenUpgrade-13.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "OpenUpgrade-13.0/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "OpenUpgrade-13.0/odoo/modules/loading.py", line 248, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "OpenUpgrade-13.0/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 741, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 808, in convert_xml_import
    obj.parse(doc.getroot())
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 720, in parse
    pycompat.reraise(
  File "OpenUpgrade-13.0/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "OpenUpgrade-13.0/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "OpenUpgrade-13.0/odoo/models.py", line 4152, in _load_records
    data['record']._load_records_write(data['values'])
  File "OpenUpgrade-13.0/odoo/models.py", line 4090, in _load_records_write
    self.write(values)
  File "OpenUpgrade-13.0/odoo/addons/base/models/res_users.py", line 1049, in write
    self._update_user_groups_view()
  File "OpenUpgrade-13.0/odoo/addons/base/models/res_users.py", line 1149, in _update_user_groups_view
    view.with_context(new_context).write({'arch': xml_content})
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 494, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "OpenUpgrade-13.0/odoo/models.py", line 3648, in write
    fields[0].determine_inverse(real_recs)
  File "OpenUpgrade-13.0/odoo/fields.py", line 1156, in determine_inverse
    getattr(records, self.inverse)()
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 494, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "OpenUpgrade-13.0/odoo/models.py", line 3643, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "OpenUpgrade-13.0/odoo/models.py", line 1215, in _validate_fields
    check(self)
  File "OpenUpgrade-13.0/odoo/addons/base/models/ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating view

forbidden opcode(s) in "{'invisible': [                                 '|', '|',                                 '&', ('active', '=', True), ('active_partner', '=', True),                                 '&', ('active', '=', False), ('active_partner', '=', False),                                 '&', ('active', '=', True), ('active_partner', '=', False),                             ]}": LIST_EXTEND
None" while parsing OpenUpgrade-13.0/odoo/addons/base/security/base_groups.xml:2, near
<odoo>
    <data>

        <!--
            Users Groups
            Note that the field 'category_id' is set later in
            base/data/ir_module_category_data.xml
        -->
        <record model="res.groups" id="group_erp_manager">
            <field name="name">Access Rights</field>
        </record>

        <record model="res.groups" id="group_system">
            <field name="name">Settings</field>
            <field name="implied_ids" eval="[(4, ref('group_erp_manager'))]"/>
            <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]"/>
        </record>

        <record model="res.groups" id="group_user">
            <field name="name">Internal User</field>
        </record>

        <record id="default_user" model="res.users">
            <field name="groups_id" eval="[(4,ref('base.group_user'))]"/>
        </record>

        <record model="res.groups" id="group_multi_company">
            <field name="name">Multi Companies</field>
        </record>

        <record model="res.groups" id="group_multi_currency">
            <field name="name">Multi Currencies</field>
        </record>

        <record model="res.groups" id="group_no_one">
            <field name="name">Technical Features</field>
        </record>
        <record model="res.groups" id="group_user">
            <field name="implied_ids" eval="[(4, ref('group_no_one'))]"/>
            <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]"/>
        </record>

        <record model="res.groups" id="group_partner_manager">
            <field name="name">Contact Creation</field>
            <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]"/>
        </record>

        <record id="default_user" model="res.users">
            <field name="groups_id" eval="[(4,ref('base.group_partner_manager'))]"/>
        </record>

        <!--
            A group dedicated to the portal users, making groups
            restrictions more convenient.
        -->
        <record id="group_portal" model="res.groups">
            <field name="name">Portal</field>
            <field name="comment">Portal members have specific access rights (such as record rules and restricted menus).
                They usually do not belong to the usual Odoo groups.</field>
        </record>
        <!--
            A group dedicated to the public user only, making groups
            restrictions more convenient.
        -->
        <record id="group_public" model="res.groups">
            <field name="name">Public</field>
            <field name="comment">Public users have specific access rights (such as record rules and restricted menus).
                They usually do not belong to the usual Odoo groups.</field>
        </record>

        <record id="public_user" model="res.users">
            <field name="groups_id" eval="[(4, ref('base.group_public'))]"/>
        </record>

        <!-- Default template user for new users signing in -->
        <record id="template_portal_user_id" model="res.users">
            <field name="name">Portal User Template</field>
            <field name="login">portaltemplate</field>
            <field name="active" eval="False"/>
            <field name="groups_id" eval="[(6, 0, [ref('base.group_portal')])]"/>
        </record>

        <record id="default_template_user_config" model="ir.config_parameter">
            <field name="key">base.template_portal_user_id</field>
            <field name="value" ref="template_portal_user_id"/>
        </record>

    </data>
</odoo>
```

## To Reproduce
**Affected versions**: 12.0

1. Create an Odoo v12 instance using docker image
2. Before installing any app, try to run OpenUpgrade13.0:
```

python3 odoo-bin --update all --stop-after-init --addons-path=addons -d odoo12db -r admin -w admin --db_host localhost
``` 

**Expected behavior**
Database migration is done.

**Additional context**
Docker compose file:
```
version: '2'
services:
  odoo12web:
    container_name: odoo12web
    restart: always
    image: odoo:12.0
    depends_on:
      - odoo12db
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo12db
      - USER=admin
      - PASSWORD=admin
    volumes:
      - odoo-web12-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  odoo12db:
    container_name: odoo12db
    restart: always
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db12-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web12-data:
  odoo-db12-data:
```

**Comment by pedrobaeza** [comment]
That trace denotes that you are not using the Odoo provided with OpenUpgrade itself, so you have to change the deployment mode (or the way you run it) to fit this requirement for <v14. Closing as no OpenUpgrade issue.

**Comment by AmeliaPessoa** [comment]
Hi, @pedrobaeza I couldn't understand your answer. 
I am using `OpenUpgrade-13.0/odoo` to make the migration. I just said that the original database was created using docker image.
Could you explain to me how can I change the way to run it?

**Comment by pedrobaeza** [comment]
I can't say about your deployment method, as I don't use it, but you are running odoo-bin from standard Odoo package, not from OpenUpgrade one, and thus views validation is crashing instead of continuing. Please check this, and use discussions section for further things.

**Comment by AmeliaPessoa** [comment]
Ok, I opened a discussion: [https://github.com/OCA/OpenUpgrade/discussions/2963](https://github.com/OCA/OpenUpgrade/discussions/2963).
