### ISSUE TITLE
Issue while migrating DB from odoo10 to 11

### ISSUE THREAD

**Issue by salvini3** [OCA/OpenUpgrade#3176]
2022-03-11 14:24:11,023 82181 CRITICAL walplast_mig odoo.service.server: Failed to initialize database `walplast_mig`.
Traceback (most recent call last):
  File "/opt/odoo11_ou/OpenUpgrade-11.0/odoo/service/server.py", line 1054, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo11_ou/OpenUpgrade-11.0/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo11_ou/OpenUpgrade-11.0/odoo/modules/loading.py", line 388, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/opt/odoo11_ou/OpenUpgrade-11.0/odoo/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo11_ou/OpenUpgrade-11.0/odoo/modules/migration.py", line 190, in migrate_module
    mod = load_script(pyfile, name)
  File "/opt/odoo11_ou/OpenUpgrade-11.0/odoo/modules/migration.py", line 37, in load_script
    return imp.load_module(module_name, fp, fname, ('.py', 'r', imp.PY_SOURCE))
ValueError: load_module arg#2 should be a file or None

**Comment by pedrobaeza** [comment]
Sorry, something in your side that can't be discussed here.
