### ISSUE TITLE
Issue in migrating DB from odoo13 to 14 

### ISSUE THREAD

**Issue by salvini3** [OCA/OpenUpgrade#3187]
**Facing below error while migrating DB from odoo 13 to 14:**

HINT:  There is a column named "event_tz" in table "calendar_recurrence", but it cannot be referenced from this part of the query.
 
2022-03-22 08:39:58,635 826837 ERROR walplast_2 OpenUpgrade: column "event_tz" does not exist
LINE 7:             SELECT id,event_tz,rrule,rrule_type,end_type,int...
                              ^
HINT:  There is a column named "event_tz" in table "calendar_recurrence", but it cannot be referenced from this part of the query.
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/openupgradelib/openupgrade.py", line 1889, in wrapped_function
    func(
  File "/opt/ou_14/OpenUpgrade-14.0/openupgrade_scripts/scripts/calendar/14.0.1.0/post-migration.py", line 83, in migrate
    fill_calendar_recurrence_table(env)
  File "/opt/ou_14/OpenUpgrade-14.0/openupgrade_scripts/scripts/calendar/14.0.1.0/post-migration.py", line 29, in fill_calendar_recurrence_table
    openupgrade.logged_query(
  File "/usr/local/lib/python3.8/dist-packages/openupgradelib/openupgrade.py", line 1353, in logged_query
    cr.execute(query, args)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/ou_14/odoo14/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/ou_14/odoo14/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column "event_tz" does not exist
LINE 7:             SELECT id,event_tz,rrule,rrule_type,end_type,int...
                              ^
HINT:  There is a column named "event_tz" in table "calendar_recurrence", but it cannot be referenced from this part of the query.

2022-03-22 08:39:59,366 826837 WARNING walplast_2 odoo.modules.loading: Transient module states were reset 
2022-03-22 08:39:59,398 826837 ERROR walplast_2 odoo.modules.registry: Failed to load registry 
2022-03-22 08:39:59,398 826837 CRITICAL walplast_2 odoo.service.server: Failed to initialize database `walplast_2`. 
Traceback (most recent call last):
  File "/opt/ou_14/odoo14/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/ou_14/odoo14/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/ou_14/odoo14/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/ou_14/odoo14/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/ou_14/odoo14/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/ou_14/OpenUpgrade-14.0/openupgrade_framework/odoo_patch/odoo/modules/migration.py", line 18, in migrate_module
    MigrationManager.migrate_module._original_method(self, pkg, stage)
  File "/opt/ou_14/odoo14/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.8/dist-packages/openupgradelib/openupgrade.py", line 1889, in wrapped_function
    func(
  File "/opt/ou_14/OpenUpgrade-14.0/openupgrade_scripts/scripts/calendar/14.0.1.0/post-migration.py", line 83, in migrate
    fill_calendar_recurrence_table(env)
  File "/opt/ou_14/OpenUpgrade-14.0/openupgrade_scripts/scripts/calendar/14.0.1.0/post-migration.py", line 29, in fill_calendar_recurrence_table
    openupgrade.logged_query(
  File "/usr/local/lib/python3.8/dist-packages/openupgradelib/openupgrade.py", line 1353, in logged_query
    cr.execute(query, args)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/ou_14/odoo14/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/ou_14/odoo14/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column "event_tz" does not exist
LINE 7:             SELECT id,event_tz,rrule,rrule_type,end_type,int...
                              ^
HINT:  There is a column named "event_tz" in table "calendar_recurrence", but it cannot be referenced from this part of the query.

**Comment by pedrobaeza** [comment]
Closing as stalled.
