### ISSUE TITLE
ModuleNotFoundError: No module named 'openupgradelib', but openupgradelib is installed

### ISSUE THREAD

**Issue by siavash8** [OCA/OpenUpgrade#3224]
So I'm trying to upgrade from our 13.0 instance to 14.0. The live server is running on a Debian machine, but I have duplicated the database on my Windows machine to test everything before deploying the new database on the live server. I have added both openupgrade_framework and openupgrade_scripts to my addons path, and instaled openupgrade_script with no problem but I get the following error when trying to install openupgrade_framework:

```
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 625, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 311, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 670, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 351, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 340, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 390, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 377, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 464, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 574, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 428, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\openupgrade_framework\__init__.py", line 7, in <module>
    from . import odoo_patch
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\openupgrade_framework\odoo_patch\__init__.py", line 1, in <module>
    from . import odoo
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\openupgrade_framework\odoo_patch\odoo\__init__.py", line 1, in <module>
    from . import addons, api, models, modules
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\openupgrade_framework\odoo_patch\odoo\addons\__init__.py", line 1, in <module>
    from . import base
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\openupgrade_framework\odoo_patch\odoo\addons\base\__init__.py", line 1, in <module>
    from . import models
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\openupgrade_framework\odoo_patch\odoo\addons\base\models\__init__.py", line 1, in <module>
    from . import ir_model
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\openupgrade_framework\odoo_patch\odoo\addons\base\models\ir_model.py", line 3, in <module>
    from openupgradelib import openupgrade
ModuleNotFoundError: No module named 'openupgradelib'
```

However, openupgradelib is certainly installed since running 
`pip install git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib`
results in 
```
Collecting openupgradelib
  Cloning https://github.com/OCA/openupgradelib.git (to revision master) to c:\users\asadollahi\appdata\local\temp\pip-install-7q6g7ygd\openupgradelib_b610317f98964fe0a81736fed53ef698
  Running command git clone -q https://github.com/OCA/openupgradelib.git 'C:\Users\asadollahi\AppData\Local\Temp\pip-install-7q6g7ygd\openupgradelib_b610317f98964fe0a81736fed53ef698'
  Resolved https://github.com/OCA/openupgradelib.git to commit 99c20f6a205ec77932b05967c05bfc523f35a9ab
Requirement already satisfied: lxml in c:\python310\lib\site-packages (from openupgradelib) (4.8.0)
Requirement already satisfied: cssselect in c:\python310\lib\site-packages (from openupgradelib) (1.1.0)
```

So I'm not sure what I'm missing here. Is it a Windows related issue?

**Comment by pedrobaeza** [comment]
The Python environment where you are running the migration doesn't have such library on it, so you have to fix that, but nothing related to this project, so I close this issue. Running in Windows means a lot of troubles that you won't have on Linux, so think twice about using Windows on your daily basis. You can try also WSL.
