### ISSUE TITLE
ProgrammingError: cannot change data type of view column "value" from numeric to double precision

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#327]
Running a migration to version 8.0. It fails with the following error. mrp_bom also does not have a column product_tmpl_id in my 7.0 database. 

2015-07-05 12:37:31,106 50025 INFO rez-07-05_migrated openerp.modules.module: module mrp: creating or updating database tables
2015-07-05 12:37:31,514 50025 ERROR rez-07-05_migrated openerp.sql_db: bad query: ALTER TABLE "mrp_bom" ALTER COLUMN "product_tmpl_id" SET NOT NULL
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "product_tmpl_id" contains null values

2015-07-05 12:37:31,515 50025 WARNING rez-07-05_migrated openerp.models: WARNING: unable to set column product_tmpl_id of table mrp_bom not null !
Try to re-run: openerp-server --update=module
If it doesn't work, update records and execute manually:
ALTER TABLE mrp_bom ALTER COLUMN product_tmpl_id SET NOT NULL
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 2699, in _auto_init
    cr.execute('ALTER TABLE "%s" ALTER COLUMN "%s" SET NOT NULL' % (self._table, k))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "product_tmpl_id" contains null values

2015-07-05 12:37:34,046 50025 ERROR rez-07-05_migrated openerp.sql_db: Programming error: cannot change data type of view column "value" from numeric to double precision
, in query 
            create or replace view report_mrp_inout as (
                select
                    min(sm.id) as id,
                    to_char(sm.date,'YYYY:IW') as date,
                    sum(case when (sl.usage='internal') then
                        sm.price_unit \* sm.product_qty
                    else
                        0.0
                    end - case when (sl2.usage='internal') then
                        sm.price_unit \* sm.product_qty
                    else
                        0.0
                    end) as value, 
                    sm.company_id
                from
                    stock_move sm
                left join product_product pp
                    on (pp.id = sm.product_id)
                left join product_template pt
                    on (pt.id = pp.product_tmpl_id)
                left join stock_location sl
                    on ( sl.id = sm.location_id)
                left join stock_location sl2
                    on ( sl2.id = sm.location_dest_id)
                where
                    sm.state = 'done'
                group by
                    to_char(sm.date,'YYYY:IW'), sm.company_id
            )
2015-07-05 12:37:34,054 50025 CRITICAL rez-07-05_migrated openerp.service.server: Failed to initialize database `rez-07-05_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 919, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 179, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/module.py", line 290, in init_module_models
    obj.init(cr)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/mrp/report/mrp_report.py", line 99, in init
    )""")
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: cannot change data type of view column "value" from numeric to double precision

2015-07-05 12:37:34,057 50025 INFO rez-07-05_migrated openerp.service.server: Initiating shutdown
2015-07-05 12:37:34,057 50025 INFO rez-07-05_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by pedrobaeza** [comment]
mrp module migration is not yet covered. There's a work in progress here, but not yet finished: https://github.com/OCA/OpenUpgrade/pull/117
