### ISSUE TITLE
psycopg2.errors.UniqueViolation: could not create unique index "mail_channel_partner_partner_unique" DETAIL:  Key (channel_id, partner_id)=(1, 3) is duplicated.

### ISSUE THREAD

**Issue by codebuildhub** [OCA/OpenUpgrade#3495]
I have a database odoo 13 community and i have succeded to migrate to 14 community but when i migrate to v 15 community i found this error could you please support,

Traceback (most recent call last):
  File "/home/mostafa/MSI/ERP/odoo/source_code/odoo15/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/mostafa/MSI/ERP/odoo/source_code/odoo15/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/mostafa/MSI/ERP/odoo/source_code/odoo15/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/mostafa/MSI/ERP/odoo/source_code/odoo15/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/mostafa/MSI/ERP/odoo/source_code/odoo15/odoo/modules/loading.py", line 199, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/home/mostafa/MSI/ERP/odoo/source_code/odoo15/odoo/modules/registry.py", line 428, in init_models
    model.init()
  File "/home/mostafa/MSI/ERP/odoo/source_code/odoo15/addons/mail/models/mail_channel_partner.py", line 46, in init
    self.env.cr.execute("CREATE UNIQUE INDEX IF NOT EXISTS mail_channel_partner_partner_unique ON %s (channel_id, partner_id) WHERE partner_id IS NOT NULL" % self._table)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/mostafa/MSI/ERP/odoo/source_code/odoo15/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/home/mostafa/MSI/ERP/odoo/source_code/odoo15/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: could not create unique index "mail_channel_partner_partner_unique"
DETAIL:  Key (channel_id, partner_id)=(1, 3) is duplicated.

**Comment by codebuildhub** [comment]
[SOLVED]

Delete the records from the table from database that cause this error and it will be solved

**Comment by HafizAlwi** [comment]
Hi, i am now experiencing this problem , do you mean by deleting the record at table mail_channel_partner with channel id = 1 and partner_ id 3, i did the same but the problem still occurs, I have deleted it clearly from the database but odoo still say duplicate value exists. this is not even logical to me at this point,

mind you that i have exactly the same error as you and the channel id is really 1 and the partner id is really 3

**Comment by codebuildhub** [comment]
> Hi, i am now experiencing this problem , do you mean by deleting the record at table mail_channel_partner with channel id = 1 and partner_ id 3, i did the same but the problem still occurs, I have deleted it clearly from the database but odoo still say duplicate value exists. this is not even logical to me at this point,
> 
> mind you that i have exactly the same error as you and the channel id is really 1 and the partner id is really 3

I don't know but we solved buy delete the duplicate values from the database
