### ISSUE TITLE
12->13 fail upgrades to due violated constraint

### ISSUE THREAD

**Issue by chicco785** [OCA/OpenUpgrade#3496]
## Module
hr

## Describe the bug
During the upgrade from v12 to v13, it seems that new data are created that violates an existing contraint `hr_employee_user_uniq`,
due to that the upgrade fails.

```
odoo-migration-upgrade-1  | 2022-07-29 22:32:53,996 1 INFO odoo_martel_13 odoo.modules.loading: loading hr/data/hr_data.xml 
odoo-migration-upgrade-1  | 2022-07-29 22:32:54,085 1 ERROR odoo_martel_13 odoo.sql_db: bad query: INSERT INTO "hr_employee" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "address_home_id", "address_id", "certificate", "color", "company_id", "gender", "marital", "name", "resource_calendar_id", "resource_id", "user_id", "work_email") VALUES (nextval('hr_employee_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), true, 3, 3, 'other', 0, 1, 'male', 'single', 'Federico M. Facca', 2, 55, 54, 'root@example.com') RETURNING id
odoo-migration-upgrade-1  | ERROR: duplicate key value violates unique constraint "hr_employee_user_uniq"
odoo-migration-upgrade-1  | DETAIL:  Key (user_id, company_id)=(54, 1) already exists.
odoo-migration-upgrade-1  |  
odoo-migration-upgrade-1  | 2022-07-29 22:32:54,093 1 ERROR odoo_martel_13 odoo.modules.registry: Failed to load registry 
odoo-migration-upgrade-1  | Traceback (most recent call last):
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 717, in parse
odoo-migration-upgrade-1  |     self._tag_root(de)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
odoo-migration-upgrade-1  |     f(rec)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
odoo-migration-upgrade-1  |     f(rec)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 582, in _tag_record
odoo-migration-upgrade-1  |     record = model._load_records([data], self.mode == 'update')
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 4198, in _load_records
odoo-migration-upgrade-1  |     records = self._load_records_create([data['values'] for data in to_create])
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 4104, in _load_records_create
odoo-migration-upgrade-1  |     return self.create(values)
odoo-migration-upgrade-1  |   File "<decorator-gen-126>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in _model_create_single
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in <genexpr>
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/addons/hr/models/hr_employee.py", line 245, in create
odoo-migration-upgrade-1  |     employee = super(HrEmployeePrivate, self).create(vals)
odoo-migration-upgrade-1  |   File "<decorator-gen-110>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 338, in _model_create_multi
odoo-migration-upgrade-1  |     return create(self, [arg])
odoo-migration-upgrade-1  |   File "/openupgrade/addons/mail/models/mail_thread.py", line 269, in create
odoo-migration-upgrade-1  |     threads = super(MailThread, self).create(vals_list)
odoo-migration-upgrade-1  |   File "<decorator-gen-96>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in _model_create_single
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in <genexpr>
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/addons/resource/models/resource_mixin.py", line 45, in create
odoo-migration-upgrade-1  |     return super(ResourceMixin, self).create(values)
odoo-migration-upgrade-1  |   File "<decorator-gen-3>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 338, in _model_create_multi
odoo-migration-upgrade-1  |     return create(self, [arg])
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 3828, in create
odoo-migration-upgrade-1  |     records = self._create(data_list)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 3934, in _create
odoo-migration-upgrade-1  |     cr.execute(query, params)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/sql_db.py", line 173, in wrapper
odoo-migration-upgrade-1  |     return f(self, *args, **kwargs)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/sql_db.py", line 250, in execute
odoo-migration-upgrade-1  |     res = self._obj.execute(query, params)
odoo-migration-upgrade-1  | psycopg2.IntegrityError: duplicate key value violates unique constraint "hr_employee_user_uniq"
odoo-migration-upgrade-1  | DETAIL:  Key (user_id, company_id)=(54, 1) already exists.
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  | During handling of the above exception, another exception occurred:
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  | Traceback (most recent call last):
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/modules/registry.py", line 87, in new
odoo-migration-upgrade-1  |     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/modules/loading.py", line 489, in load_modules
odoo-migration-upgrade-1  |     force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/modules/loading.py", line 368, in load_marked_modules
odoo-migration-upgrade-1  |     upg_registry=upg_registry,
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/modules/loading.py", line 248, in load_module_graph
odoo-migration-upgrade-1  |     load_data(cr, idref, mode, kind='data', package=package, report=report)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/modules/loading.py", line 72, in load_data
odoo-migration-upgrade-1  |     tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 741, in convert_file
odoo-migration-upgrade-1  |     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 808, in convert_xml_import
odoo-migration-upgrade-1  |     obj.parse(doc.getroot())
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 726, in parse
odoo-migration-upgrade-1  |     exc_info[2]
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/pycompat.py", line 13, in reraise
odoo-migration-upgrade-1  |     raise value.with_traceback(tb)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 717, in parse
odoo-migration-upgrade-1  |     self._tag_root(de)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
odoo-migration-upgrade-1  |     f(rec)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
odoo-migration-upgrade-1  |     f(rec)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 582, in _tag_record
odoo-migration-upgrade-1  |     record = model._load_records([data], self.mode == 'update')
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 4198, in _load_records
odoo-migration-upgrade-1  |     records = self._load_records_create([data['values'] for data in to_create])
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 4104, in _load_records_create
odoo-migration-upgrade-1  |     return self.create(values)
odoo-migration-upgrade-1  |   File "<decorator-gen-126>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in _model_create_single
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in <genexpr>
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/addons/hr/models/hr_employee.py", line 245, in create
odoo-migration-upgrade-1  |     employee = super(HrEmployeePrivate, self).create(vals)
odoo-migration-upgrade-1  |   File "<decorator-gen-110>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 338, in _model_create_multi
odoo-migration-upgrade-1  |     return create(self, [arg])
odoo-migration-upgrade-1  |   File "/openupgrade/addons/mail/models/mail_thread.py", line 269, in create
odoo-migration-upgrade-1  |     threads = super(MailThread, self).create(vals_list)
odoo-migration-upgrade-1  |   File "<decorator-gen-96>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in _model_create_single
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in <genexpr>
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/addons/resource/models/resource_mixin.py", line 45, in create
odoo-migration-upgrade-1  |     return super(ResourceMixin, self).create(values)
odoo-migration-upgrade-1  |   File "<decorator-gen-3>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 338, in _model_create_multi
odoo-migration-upgrade-1  |     return create(self, [arg])
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 3828, in create
odoo-migration-upgrade-1  |     records = self._create(data_list)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 3934, in _create
odoo-migration-upgrade-1  |     cr.execute(query, params)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/sql_db.py", line 173, in wrapper
odoo-migration-upgrade-1  |     return f(self, *args, **kwargs)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/sql_db.py", line 250, in execute
odoo-migration-upgrade-1  |     res = self._obj.execute(query, params)
odoo-migration-upgrade-1  | odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "hr_employee_user_uniq"
odoo-migration-upgrade-1  | DETAIL:  Key (user_id, company_id)=(54, 1) already exists.
odoo-migration-upgrade-1  | " while parsing /openupgrade/addons/hr/data/hr_data.xml:2, near
odoo-migration-upgrade-1  | <odoo>
odoo-migration-upgrade-1  |     <data noupdate="1">
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="dep_administration" model="hr.department">
odoo-migration-upgrade-1  |           <field name="name">Administration</field>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="dep_sales" model="hr.department">
odoo-migration-upgrade-1  |           <field name="name">Sales</field>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="employee_admin" model="hr.employee">
odoo-migration-upgrade-1  |             <field name="name" eval="obj(ref('base.partner_admin')).name" model="res.partner"/>
odoo-migration-upgrade-1  |             <field name="user_id" ref="base.user_admin"/>
odoo-migration-upgrade-1  |             <field name="address_id" ref="base.partner_admin"/>
odoo-migration-upgrade-1  |             <field name="address_home_id" ref="base.partner_admin"/>
odoo-migration-upgrade-1  |             <field name="image_1920" eval="obj(ref('base.partner_admin')).image_1920" model="res.partner"/>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="onboarding_setup_it_materials" model="hr.plan.activity.type">
odoo-migration-upgrade-1  |             <field name="summary">Setup IT Materials</field>
odoo-migration-upgrade-1  |             <field name="responsible">manager</field>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="onboarding_plan_training" model="hr.plan.activity.type">
odoo-migration-upgrade-1  |             <field name="summary">Plan Training</field>
odoo-migration-upgrade-1  |             <field name="responsible">manager</field>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="onboarding_training" model="hr.plan.activity.type">
odoo-migration-upgrade-1  |             <field name="summary">Training</field>
odoo-migration-upgrade-1  |             <field name="responsible">employee</field>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="offboarding_setup_compute_out_delais" model="hr.plan.activity.type">
odoo-migration-upgrade-1  |             <field name="summary">Compute Out Delais</field>
odoo-migration-upgrade-1  |             <field name="responsible">manager</field>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="offboarding_take_back_hr_materials" model="hr.plan.activity.type">
odoo-migration-upgrade-1  |             <field name="summary">Take Back HR Materials</field>
odoo-migration-upgrade-1  |             <field name="responsible">manager</field>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="onboarding_plan" model="hr.plan">
odoo-migration-upgrade-1  |             <field name="name">Onboarding</field>
odoo-migration-upgrade-1  |             <field name="plan_activity_type_ids" eval="[(6, 0, [                 ref('hr.onboarding_setup_it_materials'),                 ref('hr.onboarding_plan_training'),                 ref('hr.onboarding_training'),                 ])]"/>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="offboarding_plan" model="hr.plan">
odoo-migration-upgrade-1  |             <field name="name">Offboarding</field>
odoo-migration-upgrade-1  |             <field name="plan_activity_type_ids" eval="[(6, 0, [                 ref('hr.offboarding_setup_compute_out_delais'),                 ref('hr.offboarding_take_back_hr_materials'),                 ])]"/>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record id="mail_template_data_unknown_employee_email_address" model="mail.template">
odoo-migration-upgrade-1  |             <field name="name">HR: mailgateway unknown employee bounce</field>
odoo-migration-upgrade-1  |             <field name="model_id" ref="base.model_ir_module_module"/>
odoo-migration-upgrade-1  |             <field name="subject">Your document has not been created</field>
odoo-migration-upgrade-1  |             <field name="email_from">${user.email_formatted | safe}</field>
odoo-migration-upgrade-1  |             <field name="email_to">${ctx['email_to']|safe}</field>
odoo-migration-upgrade-1  |             <field name="body_html" type="html">
odoo-migration-upgrade-1  | <table border="0" cellpadding="0" cellspacing="0" style="padding-top: 16px; background-color: #F1F1F1; font-family:Verdana, Arial,sans-serif; color: #454748; width: 100%; border-collapse:separate;"><tr><td align="center">
odoo-migration-upgrade-1  | <table border="0" cellpadding="0" cellspacing="0" width="590" style="padding: 16px; background-color: white; color: #454748; border-collapse:separate;">
odoo-migration-upgrade-1  | <tbody>
odoo-migration-upgrade-1  |     <tr>
odoo-migration-upgrade-1  |         <td align="center" style="min-width: 590px;">
odoo-migration-upgrade-1  |             <table border="0" cellpadding="0" cellspacing="0" width="590" style="min-width: 590px; background-color: white; padding: 0px 8px 0px 8px; border-collapse:separate;">
odoo-migration-upgrade-1  |                 <tr><td valign="top" style="font-size: 13px;">
odoo-migration-upgrade-1  |                     <div>
odoo-migration-upgrade-1  |                         Hi,<br/>
odoo-migration-upgrade-1  |                         Your document has not been created because your email address is not recognized. Please send emails with the email address recorded on your employee information, or contact your HR manager.
odoo-migration-upgrade-1  |                     </div>
odoo-migration-upgrade-1  |                 </td></tr>
odoo-migration-upgrade-1  |             </table>
odoo-migration-upgrade-1  |     </td></tr>
odoo-migration-upgrade-1  | </tbody>
odoo-migration-upgrade-1  | </table>
odoo-migration-upgrade-1  | </td></tr>
odoo-migration-upgrade-1  | <!-- POWERED BY -->
odoo-migration-upgrade-1  | <tr><td align="center" style="min-width: 590px;">
odoo-migration-upgrade-1  |     <table border="0" cellpadding="0" cellspacing="0" width="590" style="min-width: 590px; background-color: #F1F1F1; color: #454748; padding: 8px; border-collapse:separate;">
odoo-migration-upgrade-1  |       <tr><td style="text-align: center; font-size: 13px;">
odoo-migration-upgrade-1  |         Powered by <a target="_blank" href="https://www.odoo.com?utm_source=db&amp;utm_medium=hr" style="color: #875A7B;">Odoo</a>
odoo-migration-upgrade-1  |       </td></tr>
odoo-migration-upgrade-1  |     </table>
odoo-migration-upgrade-1  | </td></tr>
odoo-migration-upgrade-1  | </table>
odoo-migration-upgrade-1  |             </field>
odoo-migration-upgrade-1  |             <field name="lang">${user.lang}</field>
odoo-migration-upgrade-1  |             <field name="auto_delete" eval="True"/>
odoo-migration-upgrade-1  |             <field name="user_signature" eval="False"/>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |         <record model="ir.config_parameter" id="hr_presence_control_login" forcecreate="False">
odoo-migration-upgrade-1  |             <field name="key">hr.hr_presence_control_login</field>
odoo-migration-upgrade-1  |             <field name="value">True</field>
odoo-migration-upgrade-1  |         </record>
odoo-migration-upgrade-1  | 
odoo-migration-upgrade-1  |     </data>
odoo-migration-upgrade-1  | </odoo>
odoo-migration-upgrade-1  | 2022-07-29 22:32:54,109 1 CRITICAL odoo_martel_13 odoo.service.server: Failed to initialize database `odoo_martel_13`. 
odoo-migration-upgrade-1  | Traceback (most recent call last):
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 717, in parse
odoo-migration-upgrade-1  |     self._tag_root(de)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
odoo-migration-upgrade-1  |     f(rec)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
odoo-migration-upgrade-1  |     f(rec)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/tools/convert.py", line 582, in _tag_record
odoo-migration-upgrade-1  |     record = model._load_records([data], self.mode == 'update')
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 4198, in _load_records
odoo-migration-upgrade-1  |     records = self._load_records_create([data['values'] for data in to_create])
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 4104, in _load_records_create
odoo-migration-upgrade-1  |     return self.create(values)
odoo-migration-upgrade-1  |   File "<decorator-gen-126>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in _model_create_single
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in <genexpr>
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/addons/hr/models/hr_employee.py", line 245, in create
odoo-migration-upgrade-1  |     employee = super(HrEmployeePrivate, self).create(vals)
odoo-migration-upgrade-1  |   File "<decorator-gen-110>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 338, in _model_create_multi
odoo-migration-upgrade-1  |     return create(self, [arg])
odoo-migration-upgrade-1  |   File "/openupgrade/addons/mail/models/mail_thread.py", line 269, in create
odoo-migration-upgrade-1  |     threads = super(MailThread, self).create(vals_list)
odoo-migration-upgrade-1  |   File "<decorator-gen-96>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in _model_create_single
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 320, in <genexpr>
odoo-migration-upgrade-1  |     return self.browse().concat(*(create(self, vals) for vals in arg))
odoo-migration-upgrade-1  |   File "/openupgrade/addons/resource/models/resource_mixin.py", line 45, in create
odoo-migration-upgrade-1  |     return super(ResourceMixin, self).create(values)
odoo-migration-upgrade-1  |   File "<decorator-gen-3>", line 2, in create
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/api.py", line 338, in _model_create_multi
odoo-migration-upgrade-1  |     return create(self, [arg])
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 3828, in create
odoo-migration-upgrade-1  |     records = self._create(data_list)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/models.py", line 3934, in _create
odoo-migration-upgrade-1  |     cr.execute(query, params)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/sql_db.py", line 173, in wrapper
odoo-migration-upgrade-1  |     return f(self, *args, **kwargs)
odoo-migration-upgrade-1  |   File "/openupgrade/odoo/sql_db.py", line 250, in execute
odoo-migration-upgrade-1  |     res = self._obj.execute(query, params)
odoo-migration-upgrade-1  | psycopg2.IntegrityError: duplicate key value violates unique constraint "hr_employee_user_uniq"
odoo-migration-upgrade-1  | DETAIL:  Key (user_id, company_id)=(54, 1) already exists.
```
## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
You have to clean your v12 database from existing duplicates of employees of the same company pointing to the same user, as this version requires to be unique.
