### ISSUE TITLE
Openerp 7 to odoo 8 upgrade ImportError

### ISSUE THREAD

**Issue by kimkul** [OCA/OpenUpgrade#356]
Hi, 
I try to migrate from Openerp 7 to Odoo 8.0.

I have an error at the beginning of the migration process:
After the command: 
python migrate.py --config=/etc/openerp-server.conf --database=adv_dev_copy_restore --run-migrations=8.0

Openerp error:
[root@migr ~]# python migrate.py --config=/etc/openerp-server.conf --database=base --run-migrations=8.0
From git://github.com/OpenUpgrade/OpenUpgrade
- branch            8.0        -> FETCH_HEAD
  Already up-to-date.
  copying database base to base_migrated...
  Copying the database using 'with template'
  running migration for 8.0
  Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp-server", line 2, in <module>
    import openerp
  File "/var/tmp/openupgrade/8.0/server/openerp/**init**.py", line 76, in <module>
    import modules
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/**init**.py", line 27, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/graph.py", line 32, in <module>
    import openerp.osv as osv
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/**init**.py", line 22, in <module>
    import osv
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/osv.py", line 23, in <module>
    from .orm import Model, TransientModel, AbstractModel
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/orm.py", line 5, in <module>
    from ..models import (
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 61, in <module>
    from . import api
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 71, in <module>
    from openerp.tools import frozendict, classproperty
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/**init**.py", line 27, in <module>
    from convert import *
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 71, in <module>
    from openerp.openupgrade import openupgrade_log
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade_log.py", line 22, in <module>
    from openupgrade_tools import table_exists
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade_tools.py", line 33, in <module>
    _modules = __import__(_new_name, globals(), locals(), ['*'])
  ImportError: No module named openupgradelib.openupgrade_tools

My openerp-server.conf file:
[options]
; This is the password that allows database operations:
admin_passwd = admin
db_host = False
db_port = False
db_user = openerp
db_password = False
; list_db = False
logfile = /var/log/openerp/openerp-server.log
addons_path =/usr/lib/python2.7/site-packages/openerp-7.0_20140101_002439-py2.7.egg/openerp/addons

I google it, no answer for this error.
Any ideas?

**Comment by pedrobaeza** [comment]
OpenUpgrade has recently split its dependencies, delegating on openupgradelib some of the code. You should install it with pip: `sudo pip install openupgradelib`. But last version is still not pushed, so I'm not sure if this version is going to work. @StefanRijnhart, can you push to PyPi?

**Comment by hbrunn** [comment]
it should work, I just did a test migration for a customer with the current version of openupgradelib. The updated documentation mentioning this is in the works

**Comment by kimkul** [comment]
Thank you I manage to go further in the process of the migration. The migration has been completed.
There are some errors in the migration.log, it's a very long log, should I post it here?

I tried to restore the database in Odoo, when I try to access to the database restored in Odoo, I have an 500 Internal Server Error.
I was asking me when I saw this page :https://github.com/OCA/OpenUpgrade/wiki/Planned-migrations
if I use other official modules than those written in this page, the migration will not work if I don't uninstall them? 

Thank you for your quick answer before.

**Comment by pedrobaeza** [comment]
It depends if the modules needs migration or not (there's any change in the BD layout, for example). You should concentrate on the log errors, in the migration and in the server start, to detect possible problems. Also check if all the installed modules are covered in the migration or not in the docs (https://doc.therp.nl/openupgrade/modules70-80.html)

**Comment by kimkul** [comment]
Thank you it is the file I was searching ((https://doc.therp.nl/openupgrade/modules70-80.html) I already read it before.

I try the migration on two databases, one has a lot of errors, but the other one there was only one error, what can I do with the following error, or advices are welcomed, thank you.

2015-08-20 17:59:42,914 18658 ERROR jkgjgkj_migrated openerp.sql_db: bad query: update meeting_category_rel
        set event_id=calendar_event.id
        from calendar_event where event_id=openupgrade_legacy_8_0_crm_meeting_id
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

2015-08-20 17:59:42,914 18658 ERROR jkgjgkj_migrated OpenUpgrade: calendar: error in migration script /var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

2015-08-20 17:59:42,914 18658 ERROR jkgjgkj_migrated OpenUpgrade: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 870, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 179, in migrate
    import_crm_meeting(cr)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 86, in import_crm_meeting
    openupgrade.get_legacy_name('crm_meeting_id'),
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

2015-08-20 17:59:42,915 18658 ERROR jkgjgkj_migrated openerp.modules.loading: Error executing post migration script for module calendar
`-> crm
: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

2015-08-20 17:59:42,916 18658 CRITICAL jkgjgkj_migrated openerp.service.server: Failed to initialize database `jkgjgkj_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 919, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 208, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 870, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 179, in migrate
    import_crm_meeting(cr)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 86, in import_crm_meeting
    openupgrade.get_legacy_name('crm_meeting_id'),
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

**Comment by kimkul** [comment]
Thank you, https://doc.therp.nl/openupgrade/modules70-80.html was the file I was searching. I read it before and did'nt manage to find it again.

I try the migration on two databases, one has a lot of errors, the other one has only one error, I don't know how to go further with this error, any advice is welcome:

2015-08-20 17:59:42,914 18658 ERROR jkgjgkj_migrated openerp.sql_db: bad query: update meeting_category_rel
        set event_id=calendar_event.id
        from calendar_event where event_id=openupgrade_legacy_8_0_crm_meeting_id
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

2015-08-20 17:59:42,914 18658 ERROR jkgjgkj_migrated OpenUpgrade: calendar: error in migration script /var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

2015-08-20 17:59:42,914 18658 ERROR jkgjgkj_migrated OpenUpgrade: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 870, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 179, in migrate
    import_crm_meeting(cr)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 86, in import_crm_meeting
    openupgrade.get_legacy_name('crm_meeting_id'),
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

2015-08-20 17:59:42,915 18658 ERROR jkgjgkj_migrated openerp.modules.loading: Error executing post migration script for module calendar
`-> crm
: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

2015-08-20 17:59:42,916 18658 CRITICAL jkgjgkj_migrated openerp.service.server: Failed to initialize database `jkgjgkj_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 919, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 208, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 870, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 179, in migrate
    import_crm_meeting(cr)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 86, in import_crm_meeting
    openupgrade.get_legacy_name('crm_meeting_id'),
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "meeting_category_rel_event_id_type_id_key"
DETAIL:  Key (event_id, type_id)=(136, 8) already exists.

**Comment by pedrobaeza** [comment]
That error is not critical, so DB should start. Make --update=all with Odoo 8 code to see.
