### ISSUE TITLE
migrate.py 7-> 8 no longer working?

### ISSUE THREAD

**Issue by joeadcock** [OCA/OpenUpgrade#362]
I had recently updated my first database from v7 to v8 using OpenUpgrade's migrate.py.  This no longer seems to be working for me.  I am now getting a " ImportError: No module named openupgradelib.openupgrade_tools".  Am I missing something obvious?  Thanks!

Joe

```
$ python scripts/migrate.py --config=/etc/openerp/openerp-server.conf --database=hpdtest01 --run-migrations=8.0

linking server/addons to /var/tmp/openupgrade/8.0/addons
getting git://github.com/OpenUpgrade/OpenUpgrade.git
Cloning into '/var/tmp/openupgrade/8.0/server'...
remote: Counting objects: 16850, done.
remote: Compressing objects: 100% (13634/13634), done.
remote: Total 16850 (delta 3962), reused 9280 (delta 2352), pack-reused 0
Receiving objects: 100% (16850/16850), 78.53 MiB | 12.83 MiB/s, done.
Resolving deltas: 100% (3962/3962), done.
Checking connectivity... done.
Checking out files: 100% (14955/14955), done.
copying database hpdtest01 to hpdtest01_migrated...
Copying the database using 'with template'
running migration for 8.0
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp-server", line 2, in <module>
    import openerp
  File "/var/tmp/openupgrade/8.0/server/openerp/__init__.py", line 76, in <module>
    import modules
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/__init__.py", line 27, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/graph.py", line 32, in <module>
    import openerp.osv as osv
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/__init__.py", line 22, in <module>
    import osv
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/osv.py", line 23, in <module>
    from .orm import Model, TransientModel, AbstractModel
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/orm.py", line 5, in <module>
    from ..models import (
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 61, in <module>
    from . import api
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 71, in <module>
    from openerp.tools import frozendict, classproperty
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/__init__.py", line 27, in <module>
    from convert import *
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 71, in <module>
    from openerp.openupgrade import openupgrade_log
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade_log.py", line 22, in <module>
    from openupgrade_tools import table_exists
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade_tools.py", line 33, in <module>
    _modules = __import__(_new_name, globals(), locals(), ['*'])
ImportError: No module named openupgradelib.openupgrade_tools
```

**Comment by hbrunn** [comment]
It's not obvious even though it should be: We're busy moving a good part of OpenUpgrade's functionality to its own library: https://github.com/OCA/openupgradelib

`pip install openupgradelib`

should fix your acute problem
