### ISSUE TITLE
OCB 12 --> 13 Stock error migration (Memory error)

### ISSUE THREAD

**Issue by MiguelMachadoM** [OCA/OpenUpgrade#3629]
Hello,
Im trying migrate OCB 12 to 13

I have a problem in migration STOCK module  ->  Memory Error

## Module
Stock

## Describe the bug
No custom modulos, only some OCA modules (removed too but same error)

## Log

```
2022-11-28 13:47:46,484 27918 ERROR odoo odoo.modules.loading: Error executing post migration script for module product
`-> stock
:
2022-11-28 13:47:46,492 27918 ERROR odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/OpenUpgrade/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 489, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 256, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/OpenUpgrade/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 2055, in wrapped_function
    raise
  File "/usr/lib/python3.7/contextlib.py", line 524, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.7/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.7/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 2305, in savepoint
    yield
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/odoo/OpenUpgrade/odoo/sql_db.py", line 449, in savepoint
    flush_env(self, clear=False)
  File "/home/odoo/OpenUpgrade/odoo/sql_db.py", line 76, in flush_env
    env_to_flush['base'].flush()
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5532, in flush
    self.recompute()
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5974, in recompute
    process(field)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5958, in process
    recs.mapped(field.name)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5340, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5299, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5299, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5764, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 1033, in __get__
    self.compute_value(recs)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2001, in compute_value
    super().compute_value(records)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 1147, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 4023, in _compute_field_value
    field.compute(self)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 581, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name])
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2151, in _process_related
    return self._image_process(super()._process_related(value))
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2145, in _image_process
    verify_resolution=self.verify_resolution,
  File "/home/odoo/OpenUpgrade/odoo/tools/image.py", line 285, in image_process
    image.resize(max_width=size[0], max_height=size[1])
  File "/home/odoo/OpenUpgrade/odoo/tools/image.py", line 180, in resize
    self.image.thumbnail((asked_width, asked_height), Image.LANCZOS)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/Image.py", line 2132, in thumbnail
    im = self.resize(size, resample)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/Image.py", line 1804, in resize
    self.load()
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/ImageFile.py", line 223, in load
    s = read(self.decodermaxblock)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 362, in load_read
    s = self.fp.read(read_bytes)
MemoryError
2022-11-28 13:47:46,493 27918 CRITICAL odoo odoo.service.server: Failed to initialize database `odoo`.
Traceback (most recent call last):
  File "/home/odoo/OpenUpgrade/odoo/service/server.py", line 1194, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/OpenUpgrade/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 489, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 256, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/OpenUpgrade/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 2055, in wrapped_function
    raise
  File "/usr/lib/python3.7/contextlib.py", line 524, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.7/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.7/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 2305, in savepoint
    yield
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/odoo/OpenUpgrade/odoo/sql_db.py", line 449, in savepoint
    flush_env(self, clear=False)
  File "/home/odoo/OpenUpgrade/odoo/sql_db.py", line 76, in flush_env
    env_to_flush['base'].flush()
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5532, in flush
    self.recompute()
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5974, in recompute
    process(field)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5958, in process
    recs.mapped(field.name)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5340, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5299, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5299, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5764, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 1033, in __get__
    self.compute_value(recs)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2001, in compute_value
    super().compute_value(records)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 1147, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 4023, in _compute_field_value
    field.compute(self)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 581, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name])
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2151, in _process_related
    return self._image_process(super()._process_related(value))
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2145, in _image_process
    verify_resolution=self.verify_resolution,
  File "/home/odoo/OpenUpgrade/odoo/tools/image.py", line 285, in image_process
    image.resize(max_width=size[0], max_height=size[1])
  File "/home/odoo/OpenUpgrade/odoo/tools/image.py", line 180, in resize
    self.image.thumbnail((asked_width, asked_height), Image.LANCZOS)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/Image.py", line 2132, in thumbnail
    im = self.resize(size, resample)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/Image.py", line 1804, in resize
    self.load()
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/ImageFile.py", line 223, in load
    s = read(self.decodermaxblock)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 362, in load_read
    s = self.fp.read(read_bytes)
MemoryError

```
**Additional context**
Ubunto 18.04(wsl2), Python 3.7.5

**Comment by pedrobaeza** [comment]
Your server gets memory exhausted. You need a more powerful one.

**Comment by MiguelMachadoM** [comment]
update.
not a memory problem. 24GB never use more than 12%.
Is a filestore image problem, but cant know what files or attach is

**Comment by pedrobaeza** [comment]
If the message puts `MemoryError`, the problem is that one. Your 24 GB won't be used for the task.

**Comment by MiguelMachadoM** [comment]
I remove path for filestore and  update finish.

Im not sure, but i think problem occurs im product postmigration script.

With --data-dir path
```
INFO odoo OpenUpgrade: product: loading migrations/13.0.1.2/noupdate_changes.xml
2022-11-28 19:37:09,001 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 19988480 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,001 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 65536 bytes but only got 0. Skipping tag 3
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,001 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 524288 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,001 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1048576 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,001 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 131072 bytes but only got 0. Skipping tag 3
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,001 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 5242880 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,001 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 6291456 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,001 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 18874368 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,002 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 11010048 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,002 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 20971520 bytes but only got 792. Skipping tag 4
  " Skipping tag %s" % (size, len(data), tag))

2022-11-28 19:37:09,002 30844 WARNING odoo py.warnings: /home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:780: UserWarning: Corrupt EXIF data.  Expecting to read 12 bytes but only got 2.
  warnings.warn(str(msg))

2022-11-28 19:37:43,295 30844 INFO odoo OpenUpgrade: Executing method empty_template_pricelist_company
2022-11-28 19:37:44,400 30844 DEBUG odoo OpenUpgrade: 30082 rows affected after 0:00:01.104890 running UPDATE product_template SET company_id = NULL WHERE company_id is NOT NULL
2022-11-28 19:37:44,401 30844 DEBUG odoo OpenUpgrade: 0 rows affected after 0:00:00.000146 running UPDATE product_pricelist SET company_id = NULL WHERE company_id is NOT NULL
2022-11-28 19:43:18,962 30844 ERROR odoo odoo.modules.loading: Error executing post migration script for module product
`-> stock
:
2022-11-28 19:43:18,969 30844 ERROR odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/OpenUpgrade/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 489, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 256, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/OpenUpgrade/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 2055, in wrapped_function
    raise
  File "/usr/lib/python3.7/contextlib.py", line 524, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.7/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.7/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 2305, in savepoint
    yield
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/odoo/OpenUpgrade/odoo/sql_db.py", line 449, in savepoint
    flush_env(self, clear=False)
  File "/home/odoo/OpenUpgrade/odoo/sql_db.py", line 76, in flush_env
    env_to_flush['base'].flush()
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5532, in flush
    self.recompute()
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5974, in recompute
    process(field)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5958, in process
    recs.mapped(field.name)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5340, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5299, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5299, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5764, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 1033, in __get__
    self.compute_value(recs)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2001, in compute_value
    super().compute_value(records)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 1147, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 4023, in _compute_field_value
    field.compute(self)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 581, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name])
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2151, in _process_related
    return self._image_process(super()._process_related(value))
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2145, in _image_process
    verify_resolution=self.verify_resolution,
  File "/home/odoo/OpenUpgrade/odoo/tools/image.py", line 285, in image_process
    image.resize(max_width=size[0], max_height=size[1])
  File "/home/odoo/OpenUpgrade/odoo/tools/image.py", line 180, in resize
    self.image.thumbnail((asked_width, asked_height), Image.LANCZOS)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/Image.py", line 2132, in thumbnail
    im = self.resize(size, resample)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/Image.py", line 1804, in resize
    self.load()
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/ImageFile.py", line 223, in load
    s = read(self.decodermaxblock)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 362, in load_read
    s = self.fp.read(read_bytes)
MemoryError
2022-11-28 19:43:18,973 30844 CRITICAL odoo odoo.service.server: Failed to initialize database `odoo`.
Traceback (most recent call last):
  File "/home/odoo/OpenUpgrade/odoo/service/server.py", line 1194, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/OpenUpgrade/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 489, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/odoo/OpenUpgrade/odoo/modules/loading.py", line 256, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/OpenUpgrade/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 2055, in wrapped_function
    raise
  File "/usr/lib/python3.7/contextlib.py", line 524, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.7/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.7/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/openupgradelib/openupgrade.py", line 2305, in savepoint
    yield
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/odoo/OpenUpgrade/odoo/sql_db.py", line 449, in savepoint
    flush_env(self, clear=False)
  File "/home/odoo/OpenUpgrade/odoo/sql_db.py", line 76, in flush_env
    env_to_flush['base'].flush()
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5532, in flush
    self.recompute()
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5974, in recompute
    process(field)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5958, in process
    recs.mapped(field.name)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5340, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5299, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5299, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 5764, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 1033, in __get__
    self.compute_value(recs)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2001, in compute_value
    super().compute_value(records)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 1147, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/OpenUpgrade/odoo/models.py", line 4023, in _compute_field_value
    field.compute(self)
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 581, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name])
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2151, in _process_related
    return self._image_process(super()._process_related(value))
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 2145, in _image_process
    verify_resolution=self.verify_resolution,
  File "/home/odoo/OpenUpgrade/odoo/tools/image.py", line 285, in image_process
    image.resize(max_width=size[0], max_height=size[1])
  File "/home/odoo/OpenUpgrade/odoo/tools/image.py", line 180, in resize
    self.image.thumbnail((asked_width, asked_height), Image.LANCZOS)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/Image.py", line 2132, in thumbnail
    im = self.resize(size, resample)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/Image.py", line 1804, in resize
    self.load()
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/ImageFile.py", line 223, in load
    s = read(self.decodermaxblock)
  File "/home/odoo/odoo-venv/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 362, in load_read
    s = self.fp.read(read_bytes)
MemoryError
```

without data-dir path
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/OpenUpgrade/odoo/addons/base/models/ir_attachment.py", line 103, in _file_read
    with open(full_path,'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/odoo/.local/share/Odoo/filestore/odoo/57/573e98efc4a90a52e4d857be49a93ebe58384f5b'
2022-11-28 19:46:57,334 30889 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/odoo/16/1663a942f88ae07e502cb87e3152db571768b74d
Traceback (most recent call last):
  File "/home/odoo/OpenUpgrade/odoo/api.py", line 748, in get
    value = self._data[field][record._ids[0]]
KeyError: 9606

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/OpenUpgrade/odoo/fields.py", line 1038, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/OpenUpgrade/odoo/api.py", line 754, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(9606,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/OpenUpgrade/odoo/addons/base/models/ir_attachment.py", line 103, in _file_read
    with open(full_path,'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/odoo/.local/share/Odoo/filestore/odoo/16/1663a942f88ae07e502cb87e3152db571768b74d'
2022-11-28 19:46:58,289 30889 INFO odoo OpenUpgrade: Executing method empty_template_pricelist_company
2022-11-28 19:46:59,352 30889 DEBUG odoo OpenUpgrade: 30082 rows affected after 0:00:01.062801 running UPDATE product_template SET company_id = NULL WHERE company_id is NOT NULL
2022-11-28 19:46:59,352 30889 DEBUG odoo OpenUpgrade: 0 rows affected after 0:00:00.000174 running UPDATE product_pricelist SET company_id = NULL WHERE company_id is NOT NULL
2022-11-28 19:47:21,792 30889 INFO odoo odoo.addons.base.models.ir_translation: module product: loading translation file (es) for language es_ES
2022-11-28 19:47:21,792 30889 INFO odoo odoo.tools.translate: loading /home/odoo/OpenUpgrade/addons/product/i18n/es.po
2022-11-28 19:47:22,017 30889 INFO odoo odoo.modules.registry: module rating: creating or updating database tables
2022-11-28 19:47:22,111 30889 INFO odoo odoo.schema: Keep unexpected index res_partner_city_id_index on table res_partner
```

**Comment by pedrobaeza** [comment]
With that you have lost the images from for example products.

**Comment by MiguelMachadoM** [comment]
yes. but not found problem or dont know how locate image cause the error.

I have script encode and later import images again. or Export all images and upload after migration. 

I dont not, now conitune without images.

**Comment by pedrobaeza** [comment]
Maybe one of the images is incorrect and provoking such problem that goes outside Python and lies on the image processing library. The other possibility is to have too many images that exhaust the memory.

**Comment by MiguelMachadoM** [comment]
maybe around 15k products with image.

in any case  continue  migration to 14, and then I'll worry about the images

Gracias Pedro!!!
