### ISSUE TITLE
[14.0-->15.0] AttributeError: type object 'NameManager' has no attribute 'check'

### ISSUE THREAD

**Issue by Vraint** [OCA/OpenUpgrade#3651]
## Describe the bug
```
odoo@VM-0-14-ubuntu:~/OpenUpgrade-15.0$ odoo -c /etc/odoo/odoo.conf --update all --stop-after-init --load=base,web,openupgrade_framework
2022-12-13 14:51:13,485 5770 INFO ? odoo: Odoo version 14.0
2022-12-13 14:51:13,485 5770 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2022-12-13 14:51:13,485 5770 INFO ? odoo: addons paths: ['/usr/local/lib/python3.6/dist-packages/odoo-14.0-py3.6.egg/odoo/addons', '/var/lib/odoo/.local/share/Odoo/addons/14.0']
2022-12-13 14:51:13,486 5770 INFO ? odoo: database: odoo@default:default
2022-12-13 14:51:13,660 5770 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2022-12-13 14:51:13,741 5770 CRITICAL ? odoo.modules.module: Couldn't load module openupgrade_framework
2022-12-13 14:51:13,741 5770 CRITICAL ? odoo.modules.module: type object 'NameManager' has no attribute 'check'
2022-12-13 14:51:13,741 5770 ERROR ? odoo.service.server: Failed to load server-wide module `openupgrade_framework`.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/odoo-14.0-py3.6.egg/odoo/service/server.py", line 1148, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/usr/local/lib/python3.6/dist-packages/odoo-14.0-py3.6.egg/odoo/modules/module.py", line 358, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/var/lib/odoo/.local/share/Odoo/addons/14.0/openupgrade_framework/__init__.py", line 7, in <module>
    from . import odoo_patch
  File "/var/lib/odoo/.local/share/Odoo/addons/14.0/openupgrade_framework/odoo_patch/__init__.py", line 1, in <module>
    from . import odoo
  File "/var/lib/odoo/.local/share/Odoo/addons/14.0/openupgrade_framework/odoo_patch/odoo/__init__.py", line 1, in <module>
    from . import addons, api, models, modules
  File "/var/lib/odoo/.local/share/Odoo/addons/14.0/openupgrade_framework/odoo_patch/odoo/addons/__init__.py", line 1, in <module>
    from . import base
  File "/var/lib/odoo/.local/share/Odoo/addons/14.0/openupgrade_framework/odoo_patch/odoo/addons/base/__init__.py", line 1, in <module>
    from . import models
  File "/var/lib/odoo/.local/share/Odoo/addons/14.0/openupgrade_framework/odoo_patch/odoo/addons/base/models/__init__.py", line 2, in <module>
    from . import ir_ui_view
  File "/var/lib/odoo/.local/share/Odoo/addons/14.0/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py", line 66, in <module>
    check._original_method = NameManager.check
AttributeError: type object 'NameManager' has no attribute 'check'
2022-12-13 14:51:13,749 5770 INFO ? odoo.service.server: Initiating shutdown
2022-12-13 14:51:13,749 5770 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```

**Comment by pedrobaeza** [comment]
The addon is not available: `Failed to load server-wide module openupgrade_framework.`

Please check before posting issues.

**Comment by pedrobaeza** [comment]
And you are running it with a very old Python version. It requires a higher one.

**Comment by Vraint** [comment]
I try to use python 3.10.6, I will get the same error，openupgrade_framework and openupgrade_scripts Copied to addon path

**Comment by pedrobaeza** [comment]
You need to have Odoo v15 as well and run it with everything properly configured.
