### ISSUE TITLE
Error upgrading from version 13 to 14

### ISSUE THREAD

**Issue by ianriva** [OCA/OpenUpgrade#3657]
## Module openupgrade_framework  

When running  
`odoo --update all --stop-after-init --load=base,web,openupgrade_framework --upgrade-path=/mnt/extra-addons/openupgrade_scripts/scripts -d "test_database"`  
the following error appears:
`AttributeError: type object 'IrModelSelection' has no attribute '_process_ondelete'`

## To Reproduce  
**Affected versions**: Odoo 13 Docker community edition, openupgrade_framework branch 14.0

Steps to reproduce the behavior (Following the [OCA guide](https://oca.github.io/OpenUpgrade/migration_details.html)):  
1. Clone the OpenUpgrade repository
2. Checkout to branch 14.0 
3. Copy the openupgrade_framework and openupgrade_scripts modules to the web container
4.  Run the container with `odoo --update all --stop-after-init --load=base,web,openupgrade_framework --upgrade-path=/mnt/extra-addons/openupgrade_scripts/scripts -d "test_database"`

**Expected behavior**  
The database is upgraded to use with Odoo 14.0

Complete log:  
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1346, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 390, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 377, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-55>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 464, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 574, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 428, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/mnt/extra-addons/openupgrade_framework/__init__.py", line 7, in <module>
    from . import odoo_patch
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/__init__.py", line 1, in <module>
    from . import odoo
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/__init__.py", line 1, in <module>
    from . import addons, api, models, modules
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/addons/__init__.py", line 1, in <module>
    from . import base
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/addons/base/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/__init__.py", line 1, in <module>
    from . import ir_model
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_model.py", line 102, in <module>
    _process_ondelete._original_method = IrModelSelection._process_ondelete
AttributeError: type object 'IrModelSelection' has no attribute '_process_ondelete'
```

**Comment by pedrobaeza** [comment]
For migrating to v14, you must use Odoo v14, not v13.
