### ISSUE TITLE
Error migratin from v14 to v15

### ISSUE THREAD

**Issue by carlosajh** [OCA/OpenUpgrade#3668]
Hello,  upgrading from v14 to v15 i receive this error. Someone can help me?

2022-12-23 06:41:10,288 1230 CRITICAL Produccion odoo.service.server: Failed to initialize database `Produccion`.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 199, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 445, in init_models
    env['base'].flush()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5649, in flush
    self.recompute()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6122, in recompute
    process(field)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6106, in process
    field.recompute(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1247, in recompute
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1269, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 411, in _compute_field_value
    return super()._compute_field_value(field)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4262, in _compute_field_value
    self.filtered('id')._validate_fields(fnames)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1367, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_payment.py", line 639, in _check_payment_method_line_id
    raise ValidationError(_("Please define a payment method line on your payment."))
odoo.exceptions.ValidationError: Please define a payment method line on your payment.
2022-12-23 06:41:10,312 1230 INFO Produccion odoo.service.server: Stopping gracefully

**Comment by legalsylvain** [comment]
What is the step of the log provided ? When it occures ? I dont' see openupgrade in the log.
Thanks.

**Comment by carlosajh** [comment]
The last.

17.	 odoo --config=/etc/odoo/odoo.conf --database=Produccion --upgrade-path=/usr/lib/python3/dist-packages/odoo/addons/OpenUpgrade/openupgrade_scripts/scripts  --addons-path=/usr/lib/python3/dist-packages/odoo/addons/OpenUpgrade --update all --load=base,web,openupgrade_framework --stop-after-init --logfile /tmp/migration.log

**Comment by carlosajh** [comment]
have a written procedure with which I have successfully migrated from 13 to 14. It is the same procedure but it gives me that error in the last step.

**Comment by hussain** [comment]
I faced same issue! This is data issue not openupgrade issue.

Check your jounrals, all journals should have a "Payment Method" selected, 1 at lease... as the error is stating.

in v11 I use this query to check all journals for this issue.
```sql
select * from account_journal
where
	not id in (select journal_id from account_journal_inbound_payment_method_rel)
	or
	not id in (select journal_id from account_journal_outbound_payment_method_rel)
;
```

**Comment by pedrobaeza** [comment]
Thanks for the info, Hussain. Closing thus.
