### ISSUE TITLE
[11.0 to 12.0] Failed to load registry

### ISSUE THREAD

**Issue by hussain** [OCA/OpenUpgrade#3674]
I'm pretty sure this is not a bug in OpenUpgrade, but need guidance on where/what to look for to find the issue.

Odoo: 11.0 upgrading to 12.0 (target is 15.0)
OS: Ubuntu 20.04
PostgreSQL: 12

I moved a backup database to dev server with OpenUpgrade prepared.
When upgrading initially I faced some issues regarding tables not having `id` as `PK`, and got them fixed manually, also some orphan references (`FK` for `id`'s that does not exist, because of uninstalled modules).

Current error is not understandable by me, and the error reference key of `ir_model_fields` is changing after every postgresql restart!

<details><summary>Error Log</summary>

```log
2023-01-03 19:54:20,635 147050 INFO verde_m1 odoo.modules.registry: module base: creating or updating database tables 
2023-01-03 19:54:21,152 147050 INFO verde_m1 odoo.models: Computing parent_path for table ir_ui_menu... 
2023-01-03 19:54:23,510 147050 INFO verde_m1 odoo.models: Computing parent_path for table res_partner_category... 
2023-01-03 19:54:25,268 147050 INFO verde_m1 odoo.models: Storing computed values of ir.model.fields.relation_field_id 
2023-01-03 19:54:25,346 147050 INFO verde_m1 odoo.models: Storing computed values of ir.model.fields.related_field_id 
2023-01-03 19:54:27,225 147050 INFO verde_m1 odoo.models: Storing computed values of res.currency.decimal_places 
2023-01-03 19:54:27,762 147050 INFO verde_m1 odoo.models: Actual recompute of field res.currency.decimal_places for 170 recs. 
2023-01-03 19:54:27,775 147050 INFO verde_m1 odoo.models: Actual recompute of field ir.model.fields.related_field_id for 6325 recs. 
2023-01-03 19:54:27,947 147050 ERROR verde_m1 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 2935

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/fields.py", line 1091, in __get__
    value = record.env.cache.get(record, self)
  File "/migration/OpenUpgrade/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.model.fields(2935,).related_field_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/migration/OpenUpgrade/odoo/modules/loading.py", line 419, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/migration/OpenUpgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 322, in init_models
    models[0].recompute()
  File "/migration/OpenUpgrade/odoo/models.py", line 5346, in recompute
    vals = {n: rec[n] for n in ns}
  File "/migration/OpenUpgrade/odoo/models.py", line 5346, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/migration/OpenUpgrade/odoo/models.py", line 5176, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/migration/OpenUpgrade/odoo/fields.py", line 1095, in __get__
    self.determine_value(record)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1184, in determine_value
    self.compute_value(recs)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1162, in compute_value
    self._compute_value(records)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1153, in _compute_value
    getattr(records, self.compute)()
  File "/migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 420, in _compute_related_field_id
    field = rec._related_field()
  File "/migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 469, in _related_field
    model = self.env[self.model or self.model_id.model]
  File "/migration/OpenUpgrade/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'account.invoice'
2023-01-03 19:54:27,950 147050 CRITICAL verde_m1 odoo.service.server: Failed to initialize database `verde_m1`. 
Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 2935

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/fields.py", line 1091, in __get__
    value = record.env.cache.get(record, self)
  File "/migration/OpenUpgrade/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.model.fields(2935,).related_field_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/service/server.py", line 1164, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/migration/OpenUpgrade/odoo/modules/loading.py", line 419, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/migration/OpenUpgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 322, in init_models
    models[0].recompute()
  File "/migration/OpenUpgrade/odoo/models.py", line 5346, in recompute
    vals = {n: rec[n] for n in ns}
  File "/migration/OpenUpgrade/odoo/models.py", line 5346, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/migration/OpenUpgrade/odoo/models.py", line 5176, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/migration/OpenUpgrade/odoo/fields.py", line 1095, in __get__
    self.determine_value(record)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1184, in determine_value
    self.compute_value(recs)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1162, in compute_value
    self._compute_value(records)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1153, in _compute_value
    getattr(records, self.compute)()
  File "/migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 420, in _compute_related_field_id
    field = rec._related_field()
  File "/migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 469, in _related_field
    model = self.env[self.model or self.model_id.model]
  File "/migration/OpenUpgrade/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'account.invoice'
2023-01-03 19:54:27,951 147050 INFO verde_m1 odoo.service.server: Stopping gracefully 
```
</details>

**Comment by legalsylvain** [comment]
without trying to upgrade, is your instance running correctly ? 
thanks.

**Comment by hussain** [comment]
Thanks @legalsylvain for your quick reply.

Instance could not be run (ubuntu 20.04 python is 3.8, odoo 11 is not happy with it).

I tried in another server (ubuntu 16.04, postgres 10, python 3.7) and odoo 11 instance is running ok, then did upgrade with same previously faced errors and used same fixes, except last error which I don't know what to do next.

Steps I did after testing the v11 instance:

- change apt odoo source to 12.0 (odoo is installed using apt)
- apt update & apt upgrade => odoo 12.0 is installed
- checkout OpenUpgrade 12.0 and run upgrade command
```ssh
sudo -u odoo ./odoo-bin --update all --stop-after-init -d db_name
```
- key issues and fix using below sql
```sql
alter table res_users add primary key (id);
alter table ir_model add primary key (id);
alter table ir_module_module add primary key (id);
alter table res_groups add primary key (id);
alter table ir_ui_menu add primary key (id);
alter table res_company add primary key (id);
alter table ir_sequence add primary key (id);
alter table ir_ui_view add primary key (id);
alter table ir_ui_view_custom add primary key (id);
alter table report_paperformat add primary key (id);
alter table ir_module_category add primary key (id);
alter table ir_module_module_dependency add primary key (id);
alter table res_currency add primary key (id);
alter table res_country add primary key (id);
alter table res_partner_category add primary key (id);
alter table res_partner_title add primary key (id);
alter table res_partner add primary key (id);
alter table res_country_state add primary key (id);
alter table res_partner_industry add primary key (id);
alter table res_bank add primary key (id);
```
- face delete constraint error, changed OpenUpgrade sql to include `IF EXISTS`
```python
# /OpenUpgrade/odoo/addons/base/migrations/12.0.1.3/pre-migration.py
def fix_lang_constraints(env):
    """Avoid error on normal update process due to the removal + re-addition of
    constraints.
    """
    openupgrade.logged_query(
        env.cr, """ALTER TABLE ir_translation
        DROP CONSTRAINT IF EXISTS ir_translation_lang_fkey_res_lang
        """,
    )
```
- FK does not exist, fixed using below sql
```sql
delete from ir_model_fields where id in
(
	select id from ir_model_fields where not model_id in (select id from ir_model)
);
delete from ir_model_constraint where id in
(
	select id from ir_model_constraint where not model in (select id from ir_model)
);
delete from ir_model_access where id in
(
	select id from ir_model_access where not model_id in (select id from ir_model)
);
delete from ir_ui_view_custom where id in
(
	select id from ir_ui_view_custom where not ref_id in (select id from ir_ui_view)
);
delete from ir_act_window_view where id in
(
	select id from ir_act_window_view where not view_id in (select id from ir_ui_view)
);
delete from ir_default where id in
(
	select id from ir_default where not field_id in (select id from ir_model_fields)
);
delete from ir_module_module_dependency where id in
(
	select id from ir_module_module_dependency where not module_id in (select id from ir_module_module)
);
delete from res_groups where id in
(
	select id from res_groups where not category_id in (select id from ir_module_category)
);
```

**Comment by legalsylvain** [comment]
is **your V12** running correctly. (without upgrade and db). That was my question.

**Comment by pedrobaeza** [comment]
And the fact of doing such SQL operations highlights that something is not correct.

**Comment by hussain** [comment]
> is **your V12** running correctly. (without upgrade and db). That was my question.

interestingly not! I'm checking why now

**Comment by hussain** [comment]
@legalsylvain 
ok.. it was sass to be installed! V12 is working fine.

@pedrobaeza 
> And the fact of doing such SQL operations highlights that something is not correct.

I have same feeling... db backup in source server is done using this command: (filesstore is normal zip/unzip)
```ssh
sudo -u postgres pg_dump --blobs --encoding=utf8 --file=filename.sql --dbname=verde_m1
```

**Comment by hussain** [comment]
update:

created new db with no apps installed, upgraded all the way to V15 successfuly.

loaded new backup, removed all non-standard apps, no more db operations needed (almost).

I still get an error, but I feel this should be posted in discussion right?

**Comment by hussain** [comment]
I think I got a lead! it seems issue related to `x_fields` which is created directly in odoo for that instance.

How would OpenupGrade treat `x_` fields in models during upgrade?


Note: old school `_logger..info()` to catch the error! `x_business_type` is in `res.partner` and `res.users`.
```log
2023-01-07 21:06:11,217 17614 INFO verde odoo.addons.base.models.ir_model: ********** names: ['partner_id', 'x_business_type']
2023-01-07 21:06:11,287 17614 INFO verde odoo.addons.base.models.ir_model: ********** account.invoice or account.invoice is account.invoice
2023-01-07 21:06:11,294 17614 ERROR verde odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/fields.py", line 1091, in __get__
    value = record.env.cache.get(record, self)
  File "/migration/OpenUpgrade/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.model.fields(13,).related_field_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/migration/OpenUpgrade/odoo/modules/loading.py", line 421, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/migration/OpenUpgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 322, in init_models
    models[0].recompute()
  File "/migration/OpenUpgrade/odoo/models.py", line 5346, in recompute
    vals = {n: rec[n] for n in ns}
  File "/migration/OpenUpgrade/odoo/models.py", line 5346, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/migration/OpenUpgrade/odoo/models.py", line 5176, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/migration/OpenUpgrade/odoo/fields.py", line 1095, in __get__
    self.determine_value(record)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1184, in determine_value
    self.compute_value(recs)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1162, in compute_value
    self._compute_value(records)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1153, in _compute_value
    getattr(records, self.compute)()
  File "/migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 420, in _compute_related_field_id
    field = rec._related_field()
  File "/migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 471, in _related_field
    model = self.env[self.model or self.model_id.model]
  File "/migration/OpenUpgrade/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'account.invoice'
2023-01-07 21:06:11,300 17614 CRITICAL verde odoo.service.server: Failed to initialize database `verde`.
Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/fields.py", line 1091, in __get__
    value = record.env.cache.get(record, self)
  File "/migration/OpenUpgrade/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.model.fields(13,).related_field_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/migration/OpenUpgrade/odoo/service/server.py", line 1164, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/migration/OpenUpgrade/odoo/modules/loading.py", line 421, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/migration/OpenUpgrade/odoo/modules/loading.py", line 222, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 322, in init_models
    models[0].recompute()
  File "/migration/OpenUpgrade/odoo/models.py", line 5346, in recompute
    vals = {n: rec[n] for n in ns}
  File "/migration/OpenUpgrade/odoo/models.py", line 5346, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/migration/OpenUpgrade/odoo/models.py", line 5176, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/migration/OpenUpgrade/odoo/fields.py", line 1095, in __get__
    self.determine_value(record)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1184, in determine_value
    self.compute_value(recs)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1162, in compute_value
    self._compute_value(records)
  File "/migration/OpenUpgrade/odoo/fields.py", line 1153, in _compute_value
    getattr(records, self.compute)()
  File "/migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 420, in _compute_related_field_id
    field = rec._related_field()
  File "/migration/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 471, in _related_field
    model = self.env[self.model or self.model_id.model]
  File "/migration/OpenUpgrade/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/migration/OpenUpgrade/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'account.invoice'
2023-01-07 21:06:11,304 17614 INFO verde odoo.service.server: Initiating shutdown
2023-01-07 21:06:11,304 17614 INFO verde odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```

**Comment by pedrobaeza** [comment]
That model is no longer anymore, so you should handle the conversion with additional scripts.
