### ISSUE TITLE
[13.0 -> 14.0] sale_order_line_invoice_rel->invoice_line_id ids mapping

### ISSUE THREAD

**Issue by hussain** [OCA/OpenUpgrade#3677]
## Sales

In Odoo 13.0 there is no more `account.invoice` since invoices are actually journal entries `account.move` with special display.
It seems there is an issue in sale order line relation to invoice line in table `sale_order_line_invoice_rel` where `account_invoice_line` FK constraint is referring to table `account_move_line` instead of `account_invoice_line`. Issue will occur if there are some deleted journal entries where FK is using instead of the invoice lines id's.

May be it is my misunderstanding, I'm not sure!

## To Reproduce
**11.0 -> 12.0**: success.
**12.0 -> 13.0**: success. (issue is possible to happen here, but it didn't happen in my case)
**13.0 -> 14.0**: failed.

1. Prepare an instance where sales invoices count and journal entries count do not match, with some journal items deleted to have a missing id.
2. run script using command
```sh
sudo -u odoo ./odoo-bin --update all --stop-after-init -c /etc/odoo/odoo.conf --load=base,web,openupgrade_framework -d verde
```

```sh
# /etc/odoo/odoo.conf
[options]
db_host = False
db_port = 5432
db_user = odoo
db_password = False

addons_path = /migration/odoo/addons, /migration/OpenUpgrade/addons
```
<details>
<summary>Error Log</summary>

```log
2023-01-09 01:59:22,143 22171 INFO verde odoo.addons.base.models.ir_translation: module purchase_stock: no translation for language ar_SA
2023-01-09 01:59:22,172 22171 INFO verde odoo.modules.loading: Module purchase_stock loaded in 2.37s, 752 queries
2023-01-09 01:59:22,172 22171 INFO verde odoo.modules.loading: Loading module sale (55/61)
2023-01-09 01:59:22,383 22171 INFO verde odoo.modules.migration: module sale: Running migration [>14.0.1.1] pre-migration
2023-01-09 01:59:22,518 22171 INFO verde OpenUpgrade: sale: pre-migration script called with version 13.0.1.1
2023-01-09 01:59:22,519 22171 DEBUG verde OpenUpgrade: 1 rows affected after 0:00:00.000380 running UPDATE ir_model_data SET module = 'sale', name = 'access_product_product_attribute_custom_value_sale_manager' WHERE module = 'sale' and name = 'access_product_product_attribute_custom_value'
2023-01-09 01:59:22,520 22171 DEBUG verde OpenUpgrade: 1 rows affected after 0:00:00.000261 running UPDATE ir_model_data SET module = 'sale', name = 'account_invoice_rule_see_all' WHERE module = 'sale' and name = 'account_move_see_all'
2023-01-09 01:59:22,521 22171 DEBUG verde OpenUpgrade: 1 rows affected after 0:00:00.000244 running UPDATE ir_model_data SET module = 'sale', name = 'account_invoice_rule_see_personal' WHERE module = 'sale' and name = 'account_move_personal_rule'
2023-01-09 01:59:22,521 22171 DEBUG verde OpenUpgrade: 1 rows affected after 0:00:00.000239 running UPDATE ir_model_data SET module = 'sale', name = 'account_invoice_line_rule_see_all' WHERE module = 'sale' and name = 'account_move_line_see_all'
2023-01-09 01:59:22,522 22171 DEBUG verde OpenUpgrade: 1 rows affected after 0:00:00.000236 running UPDATE ir_model_data SET module = 'sale', name = 'account_invoice_line_rule_see_personal' WHERE module = 'sale' and name = 'account_move_line_personal_rule'
2023-01-09 01:59:22,523 22171 DEBUG verde OpenUpgrade: -1 rows affected after 0:00:00.000642 running
            ALTER TABLE sale_order
            ADD COLUMN currency_id integer
2023-01-09 01:59:22,903 22171 DEBUG verde OpenUpgrade: 8440 rows affected after 0:00:00.380307 running
        UPDATE sale_order so
        SET currency_id = pp.currency_id
        FROM product_pricelist pp
        WHERE so.pricelist_id = pp.id
2023-01-09 01:59:23,261 22171 INFO verde odoo.modules.registry: module sale: creating or updating database tables
2023-01-09 01:59:23,624 22171 WARNING verde odoo.addons.base.models.ir_model: Two fields (x_move_line_seq, sequence) of account.move.line() have the same label: Sequence.
2023-01-09 01:59:24,057 22171 ERROR verde odoo.sql_db: bad query: ALTER TABLE "sale_order_line_invoice_rel" ADD FOREIGN KEY ("invoice_line_id") REFERENCES "account_move_line"("id") ON DELETE cascade
ERROR: insert or update on table "sale_order_line_invoice_rel" violates foreign key constraint "sale_order_line_invoice_rel_invoice_line_id_fkey"
DETAIL:  Key (invoice_line_id)=(9) is not present in table "account_move_line".

2023-01-09 01:59:24,060 22171 WARNING verde odoo.modules.loading: Transient module states were reset
2023-01-09 01:59:24,063 22171 ERROR verde odoo.modules.registry: Failed to load registry
2023-01-09 01:59:24,064 22171 CRITICAL verde odoo.service.server: Failed to initialize database `verde`.
Traceback (most recent call last):
  File "/migration/odoo/odoo/service/server.py", line 1201, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/migration/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/migration/odoo/odoo/modules/loading.py", line 457, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/migration/odoo/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/migration/odoo/odoo/modules/loading.py", line 199, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/migration/odoo/odoo/modules/registry.py", line 420, in init_models
    self.check_foreign_keys(cr)
  File "/migration/odoo/odoo/modules/registry.py", line 499, in check_foreign_keys
    sql.add_foreign_key(cr, table1, column1, table2, column2, ondelete)
  File "/migration/odoo/odoo/tools/sql.py", line 170, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "<decorator-gen-3>", line 2, in execute
  File "/migration/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/migration/odoo/odoo/sql_db.py", line 300, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: insert or update on table "sale_order_line_invoice_rel" violates foreign key constraint "sale_order_line_invoice_rel_invoice_line_id_fkey"
DETAIL:  Key (invoice_line_id)=(9) is not present in table "account_move_line".

2023-01-09 01:59:24,066 22171 INFO verde odoo.service.server: Stopping gracefully
```
</details>

**Expected behavior**
Not sure, should be some query to remap `ids` of `invoice_line_id` in table `sale_order_line_invoice_rel` to their move lines in `account_move_line`.

**Additional context**
OS: Ubuntu 16.04 LTS
Python: 3.7.10
PostgreSQL: 10

**Comment by pedrobaeza** [comment]
Please check that your table `sale_order_line_invoice_rel` integrity is already OK on the source version. I would bet there are entries of invalid invoice line ids.

**Comment by hussain** [comment]
in both source database v11 and in in-progress upgrade database:

```sql
select count(invoice_line_id) from sale_order_line_invoice_rel 
where 
    not invoice_line_id in (select id from account_invoice_line);

-- OUTPUT
V11: count = 0
V13: count = 0
```

```sql
select count(invoice_line_id) from sale_order_line_invoice_rel 
where 
    not invoice_line_id in (select id from account_move_line);

-- OUTPUT
V11: count = 7880
V13: count = 7878 (i deleted 2 cancelled payments, so 2 are missing from original)
```

**Comment by pedrobaeza** [comment]
But then it seems you need to clean-up the table before starting the v14 migration.

**Comment by hussain** [comment]
Well, this is what I'm checking.

Since this change is in 12.0->13.0, I'm investigating why it did not execute even though code is there already.

table rename [here](https://github.com/OCA/OpenUpgrade/blob/bf162a697dc4c8312987fd980e09b65569997b24/addons/sale/migrations/13.0.1.1/pre-migration.py#L7)
remapping [here](https://github.com/OCA/OpenUpgrade/blob/bf162a697dc4c8312987fd980e09b65569997b24/addons/sale/migrations/13.0.1.1/post-migration.py#L36)

So this is not an issue, again! sorry for that @pedrobaeza and I really appreciate you guys respond very fast. Hopefully I will be able to contribute something after getting the upgrade experience.
