### ISSUE TITLE
[13.0][bug]

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/OpenUpgrade#3704]
Migrating from v12 to v13
Using the following odoo.conf with modules
```

addons_path = /usr/lib/python3/dist-packages/odoo/addons,
	/usr/lib/python3/dist-packages/odoo/custom-addons/l10n-brazil,
	/usr/lib/python3/dist-packages/odoo/custom-addons/account-financial-reporting,
	/usr/lib/python3/dist-packages/odoo/custom-addons/account-payment,
	/usr/lib/python3/dist-packages/odoo/custom-addons/bank-payment,
	/usr/lib/python3/dist-packages/odoo/custom-addons/account-invoicing,
	/usr/lib/python3/dist-packages/odoo/custom-addons/commission,
	/usr/lib/python3/dist-packages/odoo/custom-addons/web,
	/usr/lib/python3/dist-packages/odoo/custom-addons/mis-builder,
	/usr/lib/python3/dist-packages/odoo/custom-addons/server-ux,
	/usr/lib/python3/dist-packages/odoo/custom-addons/reporting-engine,
	/usr/lib/python3/dist-packages/odoo/custom-addons/field-service,
	/usr/lib/python3/dist-packages/odoo/custom-addons/geospatial,
	/usr/lib/python3/dist-packages/odoo/custom-addons/partner-contact,
	/usr/lib/python3/dist-packages/odoo/custom-addons/stock-logistics-warehouse,
	/usr/lib/python3/dist-packages/odoo/custom-addons/sale-workflow,
	/openupgrade/addons,
	/openupgrade/custom-addons/l10n-brazil,
	/openupgrade/custom-addons/account-financial-reporting,
	/openupgrade/custom-addons/account-payment,
	/openupgrade/custom-addons/bank-payment,
	/openupgrade/custom-addons/account-invoicing,
	/openupgrade/custom-addons/commission,
	/openupgrade/custom-addons/web,
	/openupgrade/custom-addons/mis-builder,
	/openupgrade/custom-addons/server-ux,
	/openupgrade/custom-addons/reporting-engine,
	#/usr/lib/python3/dist-packages/odoo/custom-addons/backend_theme,
	/openupgrade/custom-addons/field-service,
	/openupgrade/custom-addons/geospatial,
	/openupgrade/custom-addons/partner-contact,
	/openupgrade/custom-addons/stock-logistics-warehouse,
	/openupgrade/custom-addons/sale-workflow
```

```

2023-01-26 10:10:24,365 38320 INFO ismoke-prod odoo.modules.loading: loading base_address_city/views/res_city_view.xml 
2023-01-26 10:10:24,388 38320 ERROR ismoke-prod odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/openupgrade/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/openupgrade/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/openupgrade/odoo/models.py", line 4176, in _load_records
    data['record']._load_records_write(data['values'])
  File "/openupgrade/odoo/models.py", line 4101, in _load_records_write
    self.write(values)
  File "/openupgrade/odoo/addons/base/models/ir_actions.py", line 55, in write
    res = super(IrActions, self).write(vals)
  File "/openupgrade/odoo/models.py", line 3546, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'view_type' on model 'ir.actions.act_window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/openupgrade/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/openupgrade/odoo/modules/loading.py", line 489, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/openupgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/openupgrade/odoo/modules/loading.py", line 248, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/openupgrade/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/openupgrade/odoo/tools/convert.py", line 741, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/openupgrade/odoo/tools/convert.py", line 808, in convert_xml_import
    obj.parse(doc.getroot())
  File "/openupgrade/odoo/tools/convert.py", line 726, in parse
    exc_info[2]
  File "/openupgrade/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/openupgrade/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/openupgrade/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/openupgrade/odoo/models.py", line 4176, in _load_records
    data['record']._load_records_write(data['values'])
  File "/openupgrade/odoo/models.py", line 4101, in _load_records_write
    self.write(values)
  File "/openupgrade/odoo/addons/base/models/ir_actions.py", line 55, in write
    res = super(IrActions, self).write(vals)
  File "/openupgrade/odoo/models.py", line 3546, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
odoo.tools.convert.ParseError: "Invalid field 'view_type' on model 'ir.actions.act_window'" while parsing /usr/lib/python3/dist-packages/odoo/addons/base_address_city/views/res_city_view.xml:2, near
<odoo>
    <data>
        <record id="view_city_tree" model="ir.ui.view">
            <field name="model">res.city</field>
            <field name="arch" type="xml">
                <tree string="City" editable="top">
                    <field name="name"/>
                    <field name="zipcode"/>
                    <field name="country_id"/>
                    <field name="state_id"/>
                </tree>
            </field>
        </record>
        <record id="view_city_filter" model="ir.ui.view">
            <field name="model">res.city</field>
            <field name="arch" type="xml">
                <search string="Search City">
                    <field name="name" filter_domain="['|', ('name','ilike',self), ('zipcode','ilike',self)]" string="City"/>
                    <separator/>
                    <field name="country_id"/>
                </search>
            </field>
        </record>

        <record id="action_res_city_tree" model="ir.actions.act_window">
            <field name="name">Cities</field>
            <field name="type">ir.actions.act_window</field>
            <field name="res_model">res.city</field>
            <field name="view_type">form</field>
            <field name="view_mode">tree</field>
            <field name="help">
                Display and manage the list of all cities that can be assigned to
                your partner records. Note that an option can be set on each country separately
                to enforce any address of it to have a city in this list.
            </field>
        </record>
    </data>
</odoo>
2023-01-26 10:10:24,389 38320 CRITICAL ismoke-prod odoo.service.server: Failed to initialize database `ismoke-prod`. 
Traceback (most recent call last):
  File "/openupgrade/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/openupgrade/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/openupgrade/odoo/models.py", line 4176, in _load_records
    data['record']._load_records_write(data['values'])
  File "/openupgrade/odoo/models.py", line 4101, in _load_records_write
    self.write(values)
  File "/openupgrade/odoo/addons/base/models/ir_actions.py", line 55, in write
    res = super(IrActions, self).write(vals)
  File "/openupgrade/odoo/models.py", line 3546, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'view_type' on model 'ir.actions.act_window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/openupgrade/odoo/service/server.py", line 1194, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/openupgrade/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/openupgrade/odoo/modules/loading.py", line 489, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/openupgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/openupgrade/odoo/modules/loading.py", line 248, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/openupgrade/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/openupgrade/odoo/tools/convert.py", line 741, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/openupgrade/odoo/tools/convert.py", line 808, in convert_xml_import
    obj.parse(doc.getroot())
  File "/openupgrade/odoo/tools/convert.py", line 726, in parse
    exc_info[2]
  File "/openupgrade/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/openupgrade/odoo/tools/convert.py", line 717, in parse
    self._tag_root(de)
  File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/openupgrade/odoo/tools/convert.py", line 679, in _tag_root
    f(rec)
  File "/openupgrade/odoo/tools/convert.py", line 582, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/openupgrade/odoo/models.py", line 4176, in _load_records
    data['record']._load_records_write(data['values'])
  File "/openupgrade/odoo/models.py", line 4101, in _load_records_write
    self.write(values)
  File "/openupgrade/odoo/addons/base/models/ir_actions.py", line 55, in write
    res = super(IrActions, self).write(vals)
  File "/openupgrade/odoo/models.py", line 3546, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
odoo.tools.convert.ParseError: "Invalid field 'view_type' on model 'ir.actions.act_window'" while parsing /usr/lib/python3/dist-packages/odoo/addons/base_address_city/views/res_city_view.xml:2, near
<odoo>
    <data>
        <record id="view_city_tree" model="ir.ui.view">
            <field name="model">res.city</field>
            <field name="arch" type="xml">
                <tree string="City" editable="top">
                    <field name="name"/>
                    <field name="zipcode"/>
                    <field name="country_id"/>
                    <field name="state_id"/>
                </tree>
            </field>
        </record>
        <record id="view_city_filter" model="ir.ui.view">
            <field name="model">res.city</field>
            <field name="arch" type="xml">
                <search string="Search City">
                    <field name="name" filter_domain="['|', ('name','ilike',self), ('zipcode','ilike',self)]" string="City"/>
                    <separator/>
                    <field name="country_id"/>
                </search>
            </field>
        </record>

        <record id="action_res_city_tree" model="ir.actions.act_window">
            <field name="name">Cities</field>
            <field name="type">ir.actions.act_window</field>
            <field name="res_model">res.city</field>
            <field name="view_type">form</field>
            <field name="view_mode">tree</field>
            <field name="help">
                Display and manage the list of all cities that can be assigned to
                your partner records. Note that an option can be set on each country separately
                to enforce any address of it to have a city in this list.
            </field>
        </record>
    </data>
</odoo>
2023-01-26 10:10:24,391 38320 DEBUG ismoke-prod odoo.service.server: cron0 started! 
2023-01-26 10:10:24,391 38320 DEBUG ismoke-prod odoo.service.server: cron1 started! 
```

Those are all OCA modules, a imagine is something related to OpenUpgrade altought as the code is spaghetti to me i don't know where the problem starts

**Comment by pedrobaeza** [comment]
This has nothing to do with OpenUpgrade, but the module `base_address_city` is not the correct version. https://github.com/OCA/OpenUpgrade/blob/13.0/addons/base_address_city/views/res_city_view.xml doesn't contain anything about `view_type`.
