### ISSUE TITLE
[11 --> 12.0] Error in stock_rule updating

### ISSUE THREAD

**Issue by AungKoKoLin1997** [OCA/OpenUpgrade#3718]
I want to migrate my database to v11 to v15. So, I tried to test with demo database in v11.0 and run migration script to migrate to 12.0 first. But I got the issues in stock_rule.
Here is the error message.
```
RROR: null value in column "location_id" violates not-null constraint
DETAIL:  Failing row contains (14, Chicago Warehouse:  Buy, t, none, null, buy, 20, null, null, null, 11, make_to_stock, 5, 11, 0, null, t, 3, null, 1, 2023-02-13 07:43:47.661966, 1, 2023-02-13 09:09:53.618551, buy, null, manual).
CONTEXT:  SQL statement "UPDATE ONLY "public"."stock_rule" SET "location_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "location_id""
 
2023-02-13 10:22:26,381 17871 WARNING Migrate odoo.addons.base.models.ir_model: Could not delete obsolete record with id: 33 of model stock.location
Please refer to the log message right above 
Traceback (most recent call last):
  File "/home/akkl/openupgrade12/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 1755, in _process_end
    record.unlink()
  File "/home/akkl/openupgrade12/OpenUpgrade/odoo/models.py", line 3194, in unlink
    cr.execute(query, (sub_ids,))
  File "/home/akkl/openupgrade12/OpenUpgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/akkl/openupgrade12/OpenUpgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: null value in column "location_id" violates not-null constraint
DETAIL:  Failing row contains (14, Chicago Warehouse:  Buy, t, none, null, buy, 20, null, null, null, 11, make_to_stock, 5, 11, 0, null, t, 3, null, 1, 2023-02-13 07:43:47.661966, 1, 2023-02-13 09:09:53.618551, buy, null, manual).
CONTEXT:  SQL statement "UPDATE ONLY "public"."stock_rule" SET "location_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "location_id""

2023-02-13 10:22:26,382 17871 INFO Migrate odoo.addons.base.models.ir_model: Deleting 12@stock.picking.type (stock.chi_picking_type_out) 
2023-02-13 10:22:26,383 17871 ERROR Migrate odoo.sql_db: bad query: DELETE FROM stock_picking_type WHERE id IN (12)
ERROR: null value in column "picking_type_id" violates not-null constraint
DETAIL:  Failing row contains (9, Chic: Stock -> Customers, t, propagate, null, pull, 20, 3, 9, 33, 9, make_to_stock, 10, null, 0, null, t, 3, null, 1, 2023-02-13 07:32:47.286791, 1, 2023-02-13 07:32:47.286791, move, null, manual).
CONTEXT:  SQL statement "UPDATE ONLY "public"."stock_rule" SET "picking_type_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "picking_type_id""
```

I checked the database using query `select picking_type_id from stock_rule where id=14;` and I got the picking_type_id but why problem is occurred when migrate.

**Comment by pedrobaeza** [comment]
Because the `stock.location` with ID 33 is trying to be removed. If you don't want this, mark the corresponding XML-ID with noupdate.
