### ISSUE TITLE
Delete all transient instances before starting migration

### ISSUE THREAD

**Issue by ypapouin** [OCA/OpenUpgrade#3722]
This feature request is a proposal to add an automatic `DELETE * FROM self._table WHERE self._transient` query somewhere.
In fact it should probably be a pure SQL query to execute before loading the ORM registry.

I made this request because I just got this error case while migrating from 12.0 -> 13.0 -> 14.0

```
2023-02-17 07:31:30,540 2450427 WARNING mig_9008 odoo.modules.loading: Transient module states were reset 
2023-02-17 07:31:30,546 2450427 ERROR mig_9008 odoo.modules.registry: Failed to load registry 
2023-02-17 07:31:30,546 2450427 CRITICAL mig_9008 odoo.service.server: Failed to initialize database `mig_9008`. 
Traceback (most recent call last):
  File "/media/data/dec/projects/14.0/odoo/odoo/service/server.py", line 1201, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/media/data/dec/projects/14.0/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/media/data/dec/projects/14.0/odoo/odoo/modules/loading.py", line 493, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/media/data/dec/projects/14.0/odoo/odoo/modules/loading.py", line 381, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/media/data/dec/projects/14.0/odoo/odoo/modules/loading.py", line 221, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/media/data/dec/projects/14.0/odoo/odoo/modules/registry.py", line 422, in init_models
    env['base'].flush()
  File "/media/data/dec/projects/14.0/odoo/odoo/models.py", line 5475, in flush
    self.recompute()
  File "/media/data/dec/projects/14.0/odoo/odoo/models.py", line 5936, in recompute
    process(field)
  File "/media/data/dec/projects/14.0/odoo/odoo/models.py", line 5920, in process
    field.recompute(recs)
  File "/media/data/dec/projects/14.0/odoo/odoo/fields.py", line 1157, in recompute
    self.compute_value(recs)
  File "/media/data/dec/projects/14.0/odoo/odoo/fields.py", line 1179, in compute_value
    records._compute_field_value(self)
  File "/media/data/dec/projects/14.0/odoo/odoo/models.py", line 4080, in _compute_field_value
    getattr(self, field.compute)()
  File "/media/data/dec/projects/14.0/odoo/addons/account/wizard/account_payment_register.py", line 342, in _compute_partner_bank_id
    if wizard.can_edit_wizard:
  File "/media/data/dec/projects/14.0/odoo/odoo/fields.py", line 971, in __get__
    self.recompute(record)
  File "/media/data/dec/projects/14.0/odoo/odoo/fields.py", line 1157, in recompute
    self.compute_value(recs)
  File "/media/data/dec/projects/14.0/odoo/odoo/fields.py", line 1179, in compute_value
    records._compute_field_value(self)
  File "/media/data/dec/projects/14.0/odoo/odoo/models.py", line 4080, in _compute_field_value
    getattr(self, field.compute)()
  File "/media/data/dec/projects/14.0/odoo/addons/account/wizard/account_payment_register.py", line 273, in _compute_from_lines
    batches = wizard._get_batches()
  File "/media/data/dec/projects/14.0/odoo/addons/account/wizard/account_payment_register.py", line 223, in _get_batches
    raise UserError(_("You can't open the register payment wizard without at least one receivable/payable line."))
odoo.exceptions.UserError: You can't open the register payment wizard without at least one receivable/payable line.
```

The database snapshot used for migration was done 2 hours after someone proceed a wizard with `account.register.payments`. So no auto-transient-vacuum has been done before starting the update process.

And since Odoo is trying to recompute fields of a model that has been renamed (`account.payment.register`) and totally rewritten, that leads to a useless error that stops the upgrade process.

**Comment by pedrobaeza** [comment]
Well, this seems a punctual case that should be handled explicitly (and not clear which is). Adding processing time for cleaning this while Odoo does regularly, plus dealing with extra complications like one2many relations in transient models and so on, it doesn't worth IMO.

**Comment by ypapouin** [comment]
I agree that it is not necessarily worth developing a solution to this problem.
Maybe just adding a warning in a _Before Starting_ part of the openupgrade documention could help.
