### ISSUE TITLE
[6.0] Using openupgradelib - ImportError: No module named openerp

### ISSUE THREAD

**Issue by sebalix** [OCA/OpenUpgrade#373]
I think that the integration of `openupgradelib` in the 6.0 branch does not work (https://github.com/OCA/OpenUpgrade/commit/5f48ad16b8a912b2e1f3d70985c2e3e9cf20e372), but maybe it is a bug related to `openupgradelib` as the `openerp` Python package does not exist yet in 6.0.
Here is the traceback when I launch a 6.0 migration:

``` python
[2015-09-25 12:05:11,154][?] INFO:server:OpenERP version - 6.0.4
[2015-09-25 12:05:11,154][?] INFO:server:addons_path - /home/odoo/openupgrade/server/bin/addons,/home/odoo/openupgrade/server/addons,/home/odoo/openupgrade/addons
[2015-09-25 12:05:11,154][?] INFO:server:database hostname - localhost
[2015-09-25 12:05:11,154][?] INFO:server:database port - 5432
[2015-09-25 12:05:11,154][?] INFO:server:database user - odoo
[2015-09-25 12:05:11,154][?] INFO:server:initialising distributed objects services
Traceback (most recent call last):
  File "/home/odoo/openupgrade/server/bin/openerp-server.py", line 94, in <module>
    import report
  File "/home/odoo/openupgrade/server/bin/report/__init__.py", line 22, in <module>
    import interface
  File "/home/odoo/openupgrade/server/bin/report/interface.py", line 30, in <module>
    import addons
  File "/home/odoo/openupgrade/server/bin/addons/__init__.py", line 53, in <module>
    from openupgrade import openupgrade
  File "/home/odoo/openupgrade/server/bin/openupgrade/openupgrade.py", line 33, in <module>
    _modules = __import__(_new_name, globals(), locals(), ['*'])
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 26, in <module>
    from openerp import release, tools, SUPERUSER_ID
ImportError: No module named openerp
```

Version of `openupgradelib`: 1.1.0

If I checkout a previous commit (e.g. https://github.com/OCA/OpenUpgrade/commit/396289527074e039eec992b0813d2ca9e1b93481), all is working fine.

**Comment by pedrobaeza** [comment]
Curious, I'll do it some weeks ago with my PR branch and worked. Let me check again.

**Comment by sebalix** [comment]
The use of openupgradelib has been merged 3 days ago in the 6.0 branch, it can explain why you had no problem?

**Comment by pedrobaeza** [comment]
Yeah, but I "beta-tested" it merging also the PR in my OpenUpgrade branch. Let me check.

**Comment by StefanRijnhart** [comment]
Sorry, I did not bother to test this version either. But in 6.0 you could indeed not import openerp. Instead, there was the bin directory containing release and tools. SUPERUSER_ID wasn't there at all.
See http://bazaar.launchpad.net/~openupgrade-committers/openupgrade-server/6.0/view/head:/bin/openupgrade/openupgrade.py#L26. We need to try/catch both imports.

**Comment by pedrobaeza** [comment]
I tested from 6.1 version, that's why it worked. But I'll do a PR afterwards for solving this in a moment.

**Comment by pedrobaeza** [comment]
OK, done in https://github.com/OCA/openupgradelib/pull/21
