### ISSUE TITLE
"name 'test_assigned' is not defined" while evaluating u'test_assigned()'

### ISSUE THREAD

**Issue by odoo-mohsin** [OCA/OpenUpgrade#381]
Hi,

I am getting following error while migrating database from v7 to v8. 

I have more than 76000 stock moves, migrate_stock_qty() never gets completed. 

 Anyone has solution about this problem?

2015-10-12 11:38:37,389 11971 ERROR test_db_migrated OpenUpgrade: stock: error in migration script /var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/post-migration.py: "name 'test_assigned' is not defined" while evaluating
u'test_assigned()'
2015-10-12 11:38:37,390 11971 ERROR test_db_migrated OpenUpgrade: "name 'test_assigned' is not defined" while evaluating
u'test_assigned()'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.1.0-py2.7.egg/openupgradelib/openupgrade.py", line 912, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/post-migration.py", line 824, in migrate
    migrate_stock_qty(cr, registry)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/post-migration.py", line 698, in migrate_stock_qty
    stock_move_obj.action_done(cr, uid, ids_to_process, context=None)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/stock/stock.py", line 2443, in action_done
    self.action_assign(cr, uid, list(move_dest_ids), context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/stock/stock.py", line 2283, in action_assign
    quant_obj.quants_reserve(cr, uid, quants, move, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/stock/stock.py", line 385, in quants_reserve
    self.pool.get('stock.picking').write(cr, uid, [move.picking_id.id], {'recompute_pack_op': True}, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/stock/stock.py", line 951, in write
    res = super(stock_picking, self).write(cr, uid, ids, vals, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/mail/mail_thread.py", line 431, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3816, in write
    self._write(old_vals)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4065, in _write
    self.step_workflow(cr, user, ids, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3590, in step_workflow
    workflow.trg_write(uid, self._name, res_id, cr)
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/__init__.py", line 40, in trg_write
    return WorkflowService.new(cr, uid, res_type, res_id).write()
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/service.py", line 53, in write
    WorkflowInstance(self.session, self.record, {'id': instance_id}).update()
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/instance.py", line 86, in update
    WorkflowItem(self.session, self.record, work_item_values).process(stack=stack)
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/workitem.py", line 229, in _split_test
    if self.wkf_expr_check(transition,signal):
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/workitem.py", line 333, in wkf_expr_check
    return self.wkf_expr_eval_expr(transition['condition'])
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ValueError: "name 'test_assigned' is not defined" while evaluating
u'test_assigned()'
2015-10-12 11:38:37,448 11971 ERROR test_db_2015_10_12_migrated openerp.modules.loading: Error executing post migration script for module stock
: "name 'test_assigned' is not defined" while evaluating
u'test_assigned()'

**Comment by pedrobaeza** [comment]
Your stock.picking workflow hasn't been changed, because that condition for a transition should be already removed. Please check that you haven't manually change/duplicate the workflow in v7 before making the upgrade.

**Comment by odoo-mohsin** [comment]
Thanks Pedro,

It looks like I have issue with stock data. I will try to import stock quant manually.

I have magentoerpconnect modules installed, those might be creating problem. I uninstalled them before migrating database.

**Comment by pedrobaeza** [comment]
Closing until further notice.
