### ISSUE TITLE
7.0 to 8.0 script failure - stock_warehouse_orderpoint

### ISSUE THREAD

**Issue by bennals** [OCA/OpenUpgrade#386]
Hi,

I just tried migrating and the script stopped without completing.  This is the end of the log:

2015-10-13 03:00:06,600 2263 ERROR rgerp70_migrated OpenUpgrade: procurement: error in migration script /var/tmp/openupgrade/8.0/addons/procurement/migrations/8.0.1.0/pre-migration.py: relation "stock_warehouse_orderpoint" does not exist

2015-10-13 03:00:06,600 2263 ERROR rgerp70_migrated OpenUpgrade: relation "stock_warehouse_orderpoint" does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.1.0-py2.7.egg/openupgradelib/openupgrade.py", line 912, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/procurement/migrations/8.0.1.0/pre-migration.py", line 51, in migrate
    openupgrade.rename_columns(cr, column_renames)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.1.0-py2.7.egg/openupgradelib/openupgrade.py", line 209, in rename_columns
    'ALTER TABLE "%s" RENAME "%s" TO "%s"' % (table, old, new,))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "stock_warehouse_orderpoint" does not exist

2015-10-13 03:00:06,617 2263 CRITICAL rgerp70_migrated openerp.service.server: Failed to initialize database `rgerp70_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 919, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 156, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.1.0-py2.7.egg/openupgradelib/openupgrade.py", line 912, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/procurement/migrations/8.0.1.0/pre-migration.py", line 51, in migrate
    openupgrade.rename_columns(cr, column_renames)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.1.0-py2.7.egg/openupgradelib/openupgrade.py", line 209, in rename_columns
    'ALTER TABLE "%s" RENAME "%s" TO "%s"' % (table, old, new,))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "stock_warehouse_orderpoint" does not exist

2015-10-13 03:00:06,617 2263 INFO rgerp70_migrated openerp.service.server: Initiating shutdown
2015-10-13 03:00:06,617 2263 INFO rgerp70_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

I was having similar problems at the start of the year but haven't had a chance to come back to it since the the stock module has been included in OpenUpgrade.  This is the issue I posted at the time:

https://github.com/OCA/OpenUpgrade/issues/233

Any suggestions as to what my next step should be?

Thanks

Bill.

**Comment by pedrobaeza** [comment]
This is because your v7 DB doesn't have procurement module installed, but for v8 this module is required for another ones, causing that it's auto-installed and its migration scripts are run. You just need to remove migrations folder from procurement dir, and you will be able to continue.

**Comment by pedrobaeza** [comment]
Closing until further notice. Feel free to open again if this is not the case.

**Comment by bennals** [comment]
Thanks Pedro.  I just installed the procurement module (I'll probably start using it after migrating anyway) and the script did continue to run past that point.  I struck another error with survey_survey but I'll start another issue about that.
