### ISSUE TITLE
[15.0-->16.0] comunication error dashboard

### ISSUE THREAD

**Issue by lauraruggerilinea** [OCA/OpenUpgrade#3868]
## Describe the bug
When I migrate from 15 to 16 in the log I have this message:
`odoo.schema: Table 'mail_channel': unable to add constraint 'mail_channel_group_public_id_check' as CHECK (channel_type = 'channel' OR group_public_id IS NULL) `

When user login into odoo the chat display an error:
`Traceback (most recent call last):
  File "/odoolinea16/odoo-server/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoolinea16/odoo-server/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/odoolinea16/odoo-server/odoo/http.py", line 1613, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoolinea16/odoo-server/odoo/http.py", line 1810, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoolinea16/odoo-server/odoo/addons/base/models/ir_http.py", line 149, in _dispatch
    result = endpoint(**request.params)
  File "/odoolinea16/odoo-server/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoolinea16/odoo-server/addons/mail/controllers/discuss.py", line 195, in mail_init_messaging
    return request.env.user.sudo(False)._init_messaging()
  File "/odoolinea16/odoo-server/addons/mail_bot/models/res_users.py", line 28, in _init_messaging
    return super()._init_messaging()
  File "/odoolinea16/odoo-server/addons/mail/models/res_users.py", line 186, in _init_messaging
    'channels': self.partner_id._get_channels_as_member().channel_info(),
  File "/odoolinea16/odoo-server/addons/mail/models/res_partner.py", line 155, in _get_channels_as_member
    channels |= self.env['mail.channel'].search([
  File "/odoolinea16/odoo-server/odoo/models.py", line 1508, in search
    res = self._search(domain, offset=offset, limit=limit, order=order, count=count)
  File "/odoolinea16/odoo-server/odoo/models.py", line 4625, in _search
    self._apply_ir_rules(query, 'read')
  File "/odoolinea16/odoo-server/odoo/models.py", line 4420, in _apply_ir_rules
    expression.expression(domain, self.sudo(), self._table, query)
  File "/odoolinea16/odoo-server/odoo/osv/expression.py", line 447, in __init__
    self.parse()
  File "/odoolinea16/odoo-server/odoo/osv/expression.py", line 672, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
ValueError: Invalid field mail.channel.public in leaf ('public', '=', 'groups')

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://spazio16.lineacomputers.com/web/assets/2202-d8b353e/web.assets_backend.min.js:963:274
    makeErrorFromResponse@https://spazio16.lineacomputers.com/web/assets/2202-d8b353e/web.assets_backend.min.js:967:163
    jsonrpc/promise</<@https://spazio16.lineacomputers.com/web/assets/2202-d8b353e/web.assets_backend.min.js:975:34

`

**Comment by legalsylvain** [comment]
Hi @lauraruggerilinea. Did you check the coverage file ? 
It seems you are trying to upgrade a V15 database with ``mail`` installed. But for the time being, the migration script are not available for this module. See : 

https://oca.github.io/OpenUpgrade/modules150-160.html

**Comment by lauraruggerilinea** [comment]
On 15 which module should I uninstall before migrating to 16?

**Comment by legalsylvain** [comment]
> On 15 which module should I uninstall before migrating to 16?

You don't have to uninstall modules. if you uninstall mail, most of the other modules will be uninstalled by dependencies.
You can : 
- get the PR that interest you here : https://github.com/OCA/OpenUpgrade/pulls?q=is%3Aopen+is%3Apr+milestone%3A16.0
- contribute to openupgrade for modules that are not yet marked as done.

**Comment by lauraruggerilinea** [comment]
I downloaded this PR https://github.com/acsone/OpenUpgrade/tree/16.0-mail-mle
and worked correctly.
