### ISSUE TITLE
Gives error after migrated v7 database with demo data...

### ISSUE THREAD

**Issue by synconics** [OCA/OpenUpgrade#388]
Hello All,

I have created a test database [with demo data] for testing purpose.
And install some modules, sale,purchase,account,stock,survey,hr_evaluation ....
It successfully migrated in 8.0 without any error.
But it gives trace back on start the server with update all modules.
Please tell me whats going wrong?

2015-10-20 07:11:26,230 14676 ERROR with_demo_7_migrated openerp.sql_db: bad query: insert into meeting_category_rel (event_id,type_id) values (7, 1)
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "meeting_category_rel" violates foreign key constraint "meeting_category_rel_event_id_fkey"
DETAIL:  Key (event_id)=(7) is not present in table "crm_meeting".

2015-10-20 07:11:26,253 14676 CRITICAL with_demo_7_migrated openerp.service.server: Failed to initialize database `with_demo_7_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 919, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 201, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 120, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 904, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 990, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 856, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/convert.py", line 766, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_model.py", line 1094, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/calendar/calendar.py", line 1649, in create
    res = super(calendar_event, self).create(cr, uid, vals, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4116, in create
    record = self.browse(self._create(old_vals))
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4301, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/fields.py", line 1053, in set
    cr.execute('insert into '+rel+' ('+id1+','+id2+') values (%s, %s)', (id, act_nbr))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "insert or update on table "meeting_category_rel" violates foreign key constraint "meeting_category_rel_event_id_fkey"
DETAIL:  Key (event_id)=(7) is not present in table "crm_meeting".
" while parsing /var/tmp/openupgrade/8.0/addons/calendar/calendar_demo.xml:98, near
<record id="calendar_event_7" model="calendar.event">
            <field eval="1" name="active"/>
            <field name="user_id" ref="base.user_demo"/>  
            <field name="partner_ids" eval="[(6,0,[ref('base.res_partner_7')])]"/>
            <field name="name">Presentation of the new Calendar</field>
            <field name="categ_ids" eval="[(6,0,[ref('categ_meet1'), ref('categ_meet2')])]"/>
            <field eval="time.strftime('%Y-%m-16')" name="start"/>
            <field eval="time.strftime('%Y-%m-16')" name="stop"/>
            <field eval="8.5" name="duration"/>
            <field eval="1" name="allday"/>
            <field name="state">draft</field>
        </record>

**Comment by legalsylvain** [comment]
openupgrade is not working with demo data.

Ref #218. (and others).

Kind regards.

**Comment by synconics** [comment]
Thanks for your prompt reply, highly appreciated.
