### ISSUE TITLE
13.0 > 14.0: unknown field

### ISSUE THREAD

**Issue by BartvandenHout** [OCA/OpenUpgrade#3891]
## Module
OpneUpgrade 13.0 > 14.0

## Describe the bug
Seems to be an incompatible view.

1. OpenUpgrade went without errors.
2. Restored database to a new and clean Odoo-14
3. Error when rebuilding

Solution 1: deleting the view (and its parent) makes all good

## Error-log

2023-05-26 12:14:21,111 2271 INFO my_odoo_database odoo.addons.base.models.ir_ui_view: Onbekend veld "crm.lead.my_activity_date_deadline" in domain of <filter name="activities_overdue"> "[('my_activity_date_deadline', '<', context_today().strftime('%Y-%m-%d'))]"

View name: crm.lead.search.lead
Error context:
 view: ir.ui.view(2438,)
 xmlid: view_crm_case_leads_filter
 view.model: crm.lead
 file: /usr/lib/python3/dist-packages/odoo/addons/crm/views/crm_lead_views.xml
 
2023-05-26 12:14:21,128 2271 WARNING my_odoo_database odoo.modules.loading: Transient module states were reset 
2023-05-26 12:14:21,132 2271 ERROR my_odoo_database odoo.modules.registry: Failed to load registry 
2023-05-26 12:14:21,133 2271 CRITICAL my_odoo_database odoo.service.server: Failed to initialize database `my_odoo_database`. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4175, in _load_records
    data['record']._load_records_write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1835, in _load_records_write
    super(View, self)._load_records_write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4112, in _load_records_write
    self.write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3670, in write
    fields[0].determine_inverse(real_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1147, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3665, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1250, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 408, in _check_xml
    raise ValidationError(_(
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 955, in postprocess
    self._validate_attrs(node, name_manager, node_info)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1294, in _validate_attrs
    fields = self._get_server_domain_variables(expr, 'domain of <%s%s> ' % (node.tag, (' name="%s"' % node.get('name')) if node.get('name') else '' ), Model)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1540, in _get_server_domain_variables
    self.handle_view_error(msg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Fout bij het valideren van weergave:

Onbekend veld "crm.lead.my_activity_date_deadline" in domain of <filter name="activities_overdue"> "[('my_activity_date_deadline', '<', context_today().strftime('%Y-%m-%d'))]"

View name: crm.lead.search.lead
Error context:
 view: ir.ui.view(2438,)
 xmlid: view_crm_case_leads_filter
 view.model: crm.lead
 file: /usr/lib/python3/dist-packages/odoo/addons/crm/views/crm_lead_views.xml

**Comment by pedrobaeza** [comment]
I don't know what you mean by "rebuilding", but you have to perform a total update (`-u all`) after the migration itself, and if you have touch view inheritance manually, you will need to delete some things manually.

In any case, this is not an OpenUpgrade bug.
