### ISSUE TITLE
Failed to load server-wide module openupgrade_framework

### ISSUE THREAD

**Issue by mmarconm** [OCA/OpenUpgrade#3896]
## Describe the bug
I configured the odoo.conf as the documetation explains to upgrade the version of odoo from 14.0 to 15.0. cloned the OpenUpgrade repository on branch 15.0. installed the lib for openupgrade.
#
```
;; my odoo14_15.conf
[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons, /usr/lib/python3/dist-packages/odoo/extra-addons/OpenUpgrade
server_wide_modules = base,web,openupgrade_framework
db_host = db
db_name = odoo
db_password = odoo
db_user = odoo
db_port = 5432
```
#
and ran the command bellow. 
`odoo -d migrate_db -u all -c /usr/lib/python3/dist-packages/odoo/odoo/odoo14_15.conf --upgrade-path=/usr/lib/python3/dist-packages/odoo/extra-addons/OpenUpgrade/openupgrade_scripts/scripts --stop-after-init
`
#
After. i got the error on terminal... 
```
2023-05-30 17:27:16,481 19621 CRITICAL ? odoo.modules.module: Couldn't load module openupgrade_framework 
2023-05-30 17:27:16,481 19621 CRITICAL ? odoo.modules.module: type object 'NameManager' has no attribute 'check' 
2023-05-30 17:27:16,481 19621 ERROR ? odoo.service.server: Failed to load server-wide module `openupgrade_framework`. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1151, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 385, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/OpenUpgrade/openupgrade_framework/__init__.py", line 7, in <module>
    from . import odoo_patch
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/OpenUpgrade/openupgrade_framework/odoo_patch/__init__.py", line 1, in <module>
    from . import odoo
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/OpenUpgrade/openupgrade_framework/odoo_patch/odoo/__init__.py", line 1, in <module>
    from . import addons, api, models, modules
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/OpenUpgrade/openupgrade_framework/odoo_patch/odoo/addons/__init__.py", line 1, in <module>
    from . import base
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/OpenUpgrade/openupgrade_framework/odoo_patch/odoo/addons/base/__init__.py", line 1, in <module>
    from . import models
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/OpenUpgrade/openupgrade_framework/odoo_patch/odoo/addons/base/models/__init__.py", line 2, in <module>
    from . import ir_ui_view
  File "/usr/lib/python3/dist-packages/odoo/extra-addons/OpenUpgrade/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py", line 66, in <module>
    check._original_method = NameManager.check
AttributeError: type object 'NameManager' has no attribute 'check'
```

**Comment by legalsylvain** [comment]
What is thé version of your odoo base code ?

**Comment by mmarconm** [comment]
@legalsylvain Odoo 14.0 (Community Edition)

**Comment by legalsylvain** [comment]
> @legalsylvain Odoo 14.0 (Community Edition)

That's the point ! to upgrade from 14 to 15 you have to use odoo 15 with openupgrade 15.
Naive question : did you take a look on the documentation ? https://oca.github.io/OpenUpgrade/
(I'm working on the refactor of this doc, and I'd like to know if this point is not clear.)

regards.

**Comment by mmarconm** [comment]
Yes, indeed, I am using openupgrade 15.0 to perform the upgrade from version 14.0 to 15.0. Furthermore, it doesn't make sense for you to use Odoo 15.0 to upgrade a database that is still on version 14.0, mainly because it cannot be imported into version 15 yet due to compatibility issues. At least, that's what the documentation shows. There is another issue here on GitHub with exactly the same error as mine, but it was not properly explained what happened, and it gave the impression that the problem was something else. If you are documenting it again, please make this process very clear because it is very confusing. thank you for your attention and help.

**Comment by mmarconm** [comment]
Thank you for your support and attention. about the docs. The documentation is not clear about that part. odoo has be on the same version that i want to upgrade to.

**Comment by legalsylvain** [comment]
Thanks for your feedback !
