### ISSUE TITLE
File exists error while running migration from 7.0 to 8.0

### ISSUE THREAD

**Issue by pgu42** [OCA/OpenUpgrade#392]
Hello
I have the error below while running migration from 7.0 to 8.0
I'm running the script as root user. What is it about ?

linking server/addons to /var/tmp/openupgrade/8.0/addons
Traceback (most recent call last):
  File "/home/xxx/odoo-migrate/migrate.py", line 302, in <module>
    os.path.join(options.branch_dir, version, name))
OSError: [Errno 17] File exists

**Comment by yucer** [comment]
This is caused because something has failed in the previous execution and the files remained there.
I don't know if that is intended to remind you that you should erase that folder and do it all again. 

I did solve the problem  with:

``` bash
rm -rf /var/tmp/openupgrade
```

And then I'd executed the `migrate.py` script again.

**Comment by pgu42** [comment]
Thanks for your reply. This solved the problem.
But i still have another one with this error : "ImportError: No module named decorator"

Copying the database using 'with template'
running migration for 8.0
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp-server", line 2, in <module>
    import openerp
  File "/var/tmp/openupgrade/8.0/server/openerp/**init**.py", line 76, in <module>
    import modules
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/**init**.py", line 27, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/graph.py", line 32, in <module>
    import openerp.osv as osv
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/**init**.py", line 22, in <module>
    import osv
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/osv.py", line 23, in <module>
    from .orm import Model, TransientModel, AbstractModel
  File "/var/tmp/openupgrade/8.0/server/openerp/osv/orm.py", line 5, in <module>
    from ..models import (
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 61, in <module>
    from . import api
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 71, in <module>
    from openerp.tools import frozendict, classproperty
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/**init**.py", line 26, in <module>
    from misc import *
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/misc.py", line 54, in <module>
    from cache import *
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/cache.py", line 25, in <module>
    from decorator import decorator
ImportError: No module named decorator
