### ISSUE TITLE
'module' object has no attribute 'is_module_installed'

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#393]
Hi, Someone knows why this error happens?
I'm trying to migrate from 6.1 to 7.0

2015-11-06 18:07:50,316 4424 ERROR siesa021 OpenUpgrade: base: error in migration script /home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/addons/base/migrations/7.0.1.3/pre-migration.py: 'module' object has no attribute 'is_module_installed'
2015-11-06 18:07:50,316 4424 ERROR siesa021 OpenUpgrade: 'module' object has no attribute 'is_module_installed'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 912, in wrapped_function
    func(cr, version)
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/addons/base/migrations/7.0.1.3/pre-migration.py", line 232, in migrate
    create_users_partner(cr)
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/addons/base/migrations/7.0.1.3/pre-migration.py", line 176, in create_users_partner
    warning_installed = openupgrade.is_module_installed(cr, 'warning')
AttributeError: 'module' object has no attribute 'is_module_installed'
2015-11-06 18:07:50,357 4424 ERROR siesa021 openerp: Failed to initialize database `siesa021`.
Traceback (most recent call last):
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/cli/server.py", line 97, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname,update_module=update_module)
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/modules/registry.py", line 203, in get
    update_module)
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/modules/loading.py", line 329, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, registry=registry)
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/modules/loading.py", line 169, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/modules/migration.py", line 191, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 912, in wrapped_function
    func(cr, version)
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/addons/base/migrations/7.0.1.3/pre-migration.py", line 232, in migrate
    create_users_partner(cr)
  File "/home/dago-gallo/Development/odoo/7.0/OpenUpgrade/openerp/addons/base/migrations/7.0.1.3/pre-migration.py", line 176, in create_users_partner
    warning_installed = openupgrade.is_module_installed(cr, 'warning')
AttributeError: 'module' object has no attribute 'is_module_installed'

**Comment by pedrobaeza** [comment]
Update your openupgradelib to latest version.
