### ISSUE TITLE
Upgrade 13.0 to 14.0 fails with  AttributeError: type object 'IrModelSelection' has no attribute '_process_ondelete'

### ISSUE THREAD

**Issue by onorua** [OCA/OpenUpgrade#3960]
## Module
openupgrade_framework

## Describe the bug
I've done following:

```git clone https:⧸⧸github.co⧸OCA⧸OpenUpgrade.git
git checkout -b 14.0
pip3 install git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib
```
Then when I ran:
``` odoo -d odoo13 --load=base,web,openupgrade_framework -u all --stop-after-init```

where `openupgrade_framework` is in my /mnt/extra-addons folder copied from `OpenUpgrade/openupgrade_framework`

I receive following:
```2023-06-30 10:35:39,210 7616 INFO ? odoo: Odoo version 13.0-20221005 
2023-06-30 10:35:39,210 7616 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2023-06-30 10:35:39,210 7616 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons', '/var/lib/odoo/addons/13.0', '/mnt/extra-addons'] 
2023-06-30 10:35:39,210 7616 INFO ? odoo: database: odoo@db:5432 
2023-06-30 10:35:39,295 7616 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2023-06-30 10:35:39,337 7616 CRITICAL ? odoo.modules.module: Couldn't load module openupgrade_framework 
2023-06-30 10:35:39,338 7616 CRITICAL ? odoo.modules.module: type object 'IrModelSelection' has no attribute '_process_ondelete' 
2023-06-30 10:35:39,338 7616 ERROR ? odoo.service.server: Failed to load server-wide module `openupgrade_framework`. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1141, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/mnt/extra-addons/openupgrade_framework/__init__.py", line 7, in <module>
    from . import odoo_patch
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/__init__.py", line 1, in <module>
    from . import odoo
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/__init__.py", line 1, in <module>
    from . import addons, api, models, modules
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/addons/__init__.py", line 1, in <module>
    from . import base
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/addons/base/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/__init__.py", line 1, in <module>
    from . import ir_model
  File "/mnt/extra-addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_model.py", line 102, in <module>
    _process_ondelete._original_method = IrModelSelection._process_ondelete
AttributeError: type object 'IrModelSelection' has no attribute '_process_ondelete'

```

**Additional context**
I've done it using freshly installed odoo 13.0 from dockerhub, with one single app installed - point of sale.

**Comment by legalsylvain** [comment]
To upgrade from 13 to 14, you should use odoo 14. 

Could you review the documentation PR that explain that point ? https://github.com/OCA/OpenUpgrade/pull/3924

Thanks.
