### ISSUE TITLE
[14] type object 'IrModelSelection' has no attribute '_process_ondelete'

### ISSUE THREAD

**Issue by ilgrosso** [OCA/OpenUpgrade#4109]
## Module
openupgrade_framework

## Describe the bug
When starting upgrade to Odoo 14 CE with following command:

```
/usr/bin/odoo -d database --upgrade-path=/root/OpenUpgrade-14.0/openupgrade_scripts/scripts  \
  --load=base,web,openupgrade_framework --update all --stop-after-init --addons=/tmp/addons
```

where:

* `/root/OpenUpgrade-14.0` is a fresh copy of https://github.com/OCA/OpenUpgrade/tree/14.0/
* `/tmp/addons` contains only the folder [openupgrade_framework](https://github.com/OCA/OpenUpgrade/tree/14.0/openupgrade_framework)

the following log message is printed out:

```
2023-08-25 09:24:02,641 1962 INFO ? odoo: Odoo version 13.0-20221005 
2023-08-25 09:24:02,641 1962 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2023-08-25 09:24:02,641 1962 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons', '/var/lib/odoo/addons/13.0', '/tmp/addons'] 
2023-08-25 09:24:02,642 1962 INFO ? odoo: upgrade path: /root/OpenUpgrade-14.0/openupgrade_scripts/scripts 
2023-08-25 09:24:02,642 1962 INFO ? odoo: database: odoo@db:default 
2023-08-25 09:24:02,732 1962 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2023-08-25 09:24:02,794 1962 CRITICAL ? odoo.modules.module: Couldn't load module openupgrade_framework 
2023-08-25 09:24:02,794 1962 CRITICAL ? odoo.modules.module: type object 'IrModelSelection' has no attribute '_process_ondelete' 
2023-08-25 09:24:02,794 1962 ERROR ? odoo.service.server: Failed to load server-wide module `openupgrade_framework`. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1141, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/tmp/addons/openupgrade_framework/__init__.py", line 7, in <module>
    from . import odoo_patch
  File "/tmp/addons/openupgrade_framework/odoo_patch/__init__.py", line 1, in <module>
    from . import odoo
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/__init__.py", line 1, in <module>
    from . import addons, api, models, modules
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/addons/__init__.py", line 1, in <module>
    from . import base
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/addons/base/__init__.py", line 1, in <module>
    from . import models
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/__init__.py", line 1, in <module>
    from . import ir_model
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_model.py", line 102, in <module>
    _process_ondelete._original_method = IrModelSelection._process_ondelete
AttributeError: type object 'IrModelSelection' has no attribute '_process_ondelete'
```

## To Reproduce
**Affected versions**:
14

**Comment by pedrobaeza** [comment]
The method is there:

https://github.com/odoo/odoo/blob/408175a727ecbca88957a9d63d8ec28f3e54c9df/odoo/addons/base/models/ir_model.py#L1399

so there's something wrong on your deployment.

Closing as no OU issue.

**Comment by ilgrosso** [comment]
If I try to comment out line 102 from `/tmp/addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_model.py` and restart the process, I get the following error:

```
2023-08-25 09:41:04,329 1987 ERROR ? odoo.service.server: Failed to load server-wide module `openupgrade_framework`. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1141, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/tmp/addons/openupgrade_framework/__init__.py", line 7, in <module>
    from . import odoo_patch
  File "/tmp/addons/openupgrade_framework/odoo_patch/__init__.py", line 1, in <module>
    from . import odoo
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/__init__.py", line 1, in <module>
    from . import addons, api, models, modules
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/addons/__init__.py", line 1, in <module>
    from . import base
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/addons/base/__init__.py", line 1, in <module>
    from . import models
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/__init__.py", line 2, in <module>
    from . import ir_ui_view
  File "/tmp/addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py", line 59, in <module>
    handle_view_error._original_method = View.handle_view_error
AttributeError: type object 'View' has no attribute 'handle_view_error'
```

**Comment by ilgrosso** [comment]
@pedrobaeza thank you for your answer

I can see that the method is in [14](https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/models/ir_model.py) but not on [13](https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/models/ir_model.py).

I guess from this and your answer that OU 14 shall be run with Odoo 14 installed; this seems to be different from what used to happen until OU 13.

**Comment by pedrobaeza** [comment]
No, it doesn't. You always run OpenUpgrade on the target version, not on the prior version.

**Comment by ilgrosso** [comment]
I see, thanks for clarification.

I think that it has been working so far because until OU 13 I've been actually running `odoo-bin` from within OU checkout directory.

**Comment by pedrobaeza** [comment]
> I think that it has been working so far because until OU 13 I've been actually running odoo-bin from within OU checkout directory.

Yes, that can be.
