### ISSUE TITLE
[16.0] l10n_sg migration fails

### ISSUE THREAD

**Issue by AdrienAdB** [OCA/OpenUpgrade#4133]
After migrating from 15 to 16, this is our last issue. Any help on finding a solution to this?

2023-09-22 11:13:51,562 2242653 INFO odoo_db odoo.modules.loading: loading l10n_sg/data/account_tax_report_data.xml 
2023-09-22 11:13:51,567 2242653 DEBUG odoo_db odoo.tools.convert: while parsing /usr/lib/python3/dist-packages/odoo/addons/l10n_sg/data/account_tax_report_data.xml:3
For external id l10n_sg.tax_report when trying to create/update a record of model account.report found record of different model account.tax.report (278017)

View error context:
'-no context-'
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 599, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4357, in _load_records
    raise ValidationError(
odoo.exceptions.ValidationError: For external id l10n_sg.tax_report when trying to create/update a record of model account.report found record of different model account.tax.report (278017)
2023-09-22 11:13:51,573 2242653 WARNING odoo_db odoo.modules.loading: Transient module states were reset 
2023-09-22 11:13:51,575 2242653 ERROR odoo_db odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /usr/lib/python3/dist-packages/odoo/addons/l10n_sg/data/account_tax_report_data.xml:3
For external id l10n_sg.tax_report when trying to create/update a record of model account.report found record of different model account.tax.report (278017)

View error context:
'-no context-'

**Comment by legalsylvain** [comment]
l10n_sg has not been migrated yet. (https://github.com/OCA/OpenUpgrade/blob/16.0/docsource/modules150-160.rst)

Feel free to read the documentation and contribute. https://oca.github.io/OpenUpgrade/

Thanks !
