### ISSUE TITLE
Migrating from 14 to 15 using OpenUpgrade error

### ISSUE THREAD

**Issue by Jny-z** [OCA/OpenUpgrade#4142]
In OpenUpgrade when i try to use I get error

## Module
OpenUpgrade

## Describe the bug
I Have configured openupgrade15.0 as sames as in the documentation. When i run the script i got an error,

2023-10-04 09:56:47,976 29431 ERROR odoo15 odoo.modules.registry: Failed to load registry 
2023-10-04 09:56:47,976 29431 CRITICAL odoo15 odoo.service.server: Failed to initialize database `odoo15`. 
Traceback (most recent call last):
  File "/opt/odoo15/odoo/service/server.py", line 1258, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo15/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo15/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo15/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo15/odoo/modules/loading.py", line 198, in load_module_graph
    registry.setup_models(cr)
  File "/opt/odoo15/odoo/modules/registry.py", line 290, in setup_models
    model._setup_fields()
  File "/opt/odoo15/odoo/models.py", line 3049, in _setup_fields
    field.setup(self)
  File "/opt/odoo15/odoo/fields.py", line 462, in setup
    self.setup_related(model)
  File "/opt/odoo15/odoo/fields.py", line 538, in setup_related
    raise TypeError("Type of related field %s is inconsistent with %s" % (self, field))
TypeError: Type of related field base.document.layout.report_header is inconsistent with res.company.report_header

## To Reproduce

Download openupgrade 15.0 from github, create a 14 database in odoo 15 then run the script the error will display

**Affected versions**:15.0

**Comment by pedrobaeza** [comment]
This seems a bad procedure doing the migration. You should use Odoo 15 with OpenUpgrade 15 scripts to run the migration on the 14 DB.

Anyway, it's not an issue of the OpenUpgrade scripts, so closing.

For further questions, go to Discussions section.

**Comment by Jny-z** [comment]
I have done the procedure correctly, in the web script there is nothing to convert the fields report_header from text to html thats why i get this error.
