### ISSUE TITLE
Inherited view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition on `res_partner_views.xml`

### ISSUE THREAD

**Issue by ikus060** [OCA/OpenUpgrade#4159]
Trying to upgrade Odoo v15 to v16, I'm getting the following error: Inherited view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition

## Module
product

## Describe the bug
During the module loading, when processing the file `/usr/lib/python3/dist-packages/odoo/addons/product/views/res_partner_views.xml` an exception is generated which I believe is a migrate issue.

```
2023-10-12 19:16:57,886 1 INFO ikus odoo.modules.loading: Loading module product (31/81) 
2023-10-12 19:16:57,949 1 INFO ikus odoo.modules.registry: module product: creating or updating database tables 
2023-10-12 19:16:58,290 1 INFO ikus odoo.schema: Keep unexpected index product_template_message_main_attachment_id_index on table product_template 
2023-10-12 19:16:58,290 1 INFO ikus odoo.schema: Keep unexpected index product_product_message_main_attachment_id_index on table product_product 
2023-10-12 19:16:58,293 1 INFO ikus odoo.schema: Keep unexpected index decimal_precision_name_index on table decimal_precision 
2023-10-12 19:16:58,295 1 INFO ikus odoo.schema: Keep unexpected index res_partner_message_main_attachment_id_index on table res_partner 
2023-10-12 19:16:58,295 1 INFO ikus odoo.schema: Keep unexpected index res_users_create_date_index on table res_users 
2023-10-12 19:16:58,342 1 INFO ikus odoo.modules.loading: loading product/data/product_data.xml 
2023-10-12 19:16:58,349 1 INFO ikus odoo.modules.loading: loading product/security/product_security.xml 
2023-10-12 19:16:58,387 1 INFO ikus odoo.modules.loading: loading product/security/ir.model.access.csv 
2023-10-12 19:16:58,456 1 INFO ikus odoo.modules.loading: loading product/wizard/product_label_layout_views.xml 
2023-10-12 19:16:58,480 1 INFO ikus odoo.models.unlink: User #1 deleted ir.actions.act_window.view records with IDs: [213] 
2023-10-12 19:16:58,489 1 INFO ikus odoo.modules.loading: loading product/views/product_views.xml 
2023-10-12 19:16:58,572 1 INFO ikus odoo.models.unlink: User #1 deleted ir.actions.act_window.view records with IDs: [208, 209, 210] 
2023-10-12 19:16:58,617 1 INFO ikus odoo.modules.loading: loading product/views/res_config_settings_views.xml 
2023-10-12 19:16:58,701 1 INFO ikus odoo.modules.loading: loading product/views/product_attribute_views.xml 
2023-10-12 19:16:58,736 1 INFO ikus odoo.modules.loading: loading product/views/product_category_views.xml 
2023-10-12 19:16:58,756 1 INFO ikus odoo.modules.loading: loading product/views/product_packaging_views.xml 
2023-10-12 19:16:58,796 1 INFO ikus odoo.models.unlink: User #1 deleted ir.actions.act_window.view records with IDs: [211, 212] 
2023-10-12 19:16:58,799 1 INFO ikus odoo.modules.loading: loading product/views/product_pricelist_item_views.xml 
2023-10-12 19:16:58,828 1 INFO ikus odoo.modules.loading: loading product/views/product_pricelist_views.xml 
2023-10-12 19:16:58,858 1 INFO ikus odoo.modules.loading: loading product/views/product_supplierinfo_views.xml 
2023-10-12 19:16:58,884 1 INFO ikus odoo.modules.loading: loading product/views/product_template_views.xml 
2023-10-12 19:16:58,926 1 INFO ikus odoo.modules.loading: loading product/views/product_tag_views.xml 
2023-10-12 19:16:58,938 1 INFO ikus odoo.modules.loading: loading product/views/res_country_group_views.xml 
2023-10-12 19:16:58,944 1 INFO ikus odoo.modules.loading: loading product/views/res_partner_views.xml 
2023-10-12 19:16:58,948 1 DEBUG ikus odoo.tools.convert: while parsing /usr/lib/python3/dist-packages/odoo/addons/product/views/res_partner_views.xml:3
Inherited view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition

View error context:
'-no context-'
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 64, in __new__
    return cls.registries[db_name]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'ikus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 599, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4374, in _load_records
    data['record']._load_records_write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 2215, in _load_records_write
    super(View, self)._load_records_write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4305, in _load_records_write
    self.write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 573, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3787, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1352, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 482, in _check_groups
    raise ValidationError(_("Inherited view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition"))
odoo.exceptions.ValidationError: Inherited view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition
2023-10-12 19:16:58,953 1 WARNING ikus odoo.modules.loading: Transient module states were reset 
2023-10-12 19:16:58,953 1 ERROR ikus odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /usr/lib/python3/dist-packages/odoo/addons/product/views/res_partner_views.xml:3
Inherited view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition

View error context:
'-no context-'

2023-10-12 19:16:58,954 1 ERROR ikus odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1998, in __call__
    response = request._serve_db()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1563, in _serve_db
    self.registry = Registry(self.db).check_signaling()
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 66, in __new__
    return cls.new(db_name)
  File "<decorator-gen-14>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /usr/lib/python3/dist-packages/odoo/addons/product/views/res_partner_views.xml:3
Inherited view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition

View error context:
'-no context-'

```

**Comment by legalsylvain** [comment]
Hi. Product module migration works correctly. The CI run it, as the migration is "done"
https://oca.github.io/OpenUpgrade/modules150-160.html
The problem come from another module / or customization.

Could you investigate ?

(Closing in the meantime, feel free to reopen)
