### ISSUE TITLE
after migration 61 -> 7

### ISSUE THREAD

**Issue by PaulGiancarlo** [OCA/OpenUpgrade#419]
hi, i make a migration from 5 -> 6 ->6.1 and now 6.1 -> 7.0 and the data passed,  but i cant start the web-client. I have many warnings about modules.  I use OpenUpgrade 7.0 with comand:

```
python openerp-server -d 61_a_7 -u all --addons=/opt/openerp6/open7/modulo_web/odoo-7.0/addons/
```

 I put a few lines:
...

```
2015-12-09 23:10:44,225 23359 WARNING 61_a_7 openerp.modules.loading: Model migrade.application.installer.modules is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2015-12-09 23:10:44,225 23359 WARNING 61_a_7 openerp.modules.loading: Model product.installer is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2015-12-09 23:10:44,226 23359 WARNING 61_a_7 openerp.modules.loading: Model user.preferences.config is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2015-12-09 23:10:44,228 23359 WARNING 61_a_7 openerp.modules.loading: Model mail.message.common is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2015-12-09 23:10:43,825 23359 WARNING 61_a_7 openerp.modules.graph: module board_association: not installable, skipped
```

...

and in the web client  load the main page with the menus, but a pop up says :
Server error

```
Client Traceback (most recent call last):
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, **self.params)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/web/controllers/main.py", line 1039, in load_needaction
    return req.session.model('ir.ui.menu').get_needaction_data(menu_ids, req.context)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)


Server Traceback (most recent call last):
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, *params)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/base/ir/ir_ui_menu.py", line 340, in get_needaction_data
    res[menu.id]['needaction_counter'] = obj._needaction_count(cr, uid, dom, context=context)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/base/ir/ir_needaction.py", line 64, in _needaction_count
    res = self.search(cr, uid, (domain or []) + dom, limit=100, order='id DESC', context=context)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/base_calendar/crm_meeting.py", line 134, in search
    return super(mail_message, self).search(cr, uid, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/osv/orm.py", line 2390, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/portal/mail_message.py", line 45, in _search
    context=context, count=count, access_rights_uid=access_rights_uid)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/addons/mail/mail_message.py", line 608, in _search
    context=context, count=False, access_rights_uid=access_rights_uid)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/osv/orm.py", line 4983, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/osv/orm.py", line 4809, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/osv/expression.py", line 651, in __init__
    self.parse(cr, uid, context=context)
  File "/opt/openerp6/server7/openerp-7.0-20151124/openerp/osv/expression.py", line 815, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'state' in leaf "<osv.ExtendedLeaf: ('state', 'in', ['outgoing', 'exception']) on mail_message (ctx: )>"
```

running this version & comands
`openerp-7.0-20151124$ python openerp-server -d 61_a_7 -u all --update=all`

And a know error its when i try to make a report, says : 

```
SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data

http://domain:8069/web/webclient/js?db=61_a_7:3104
```

**Comment by pedrobaeza** [comment]
The warnings are due to models that have dissapeared through versions. Use database_cleanup in OCA/server-tools for purging them (if you know what you do), but they don't annoy.

The problem starting is because there is an action window or a menu with a context that contains an invalid field. I would bet that it's on the project area. Remove that context via SQL or interface (if you can get access).

**Comment by StefanRijnhart** [comment]
For the standard data in core, this is covered in mail/migrations/7.0.1.0/data.xml. Can you check the log files of your migration to check this file was loaded at any point?

**Comment by hbrunn** [comment]
closing due to lack of reaction from OP
