### ISSUE TITLE
test_assigned is not defined

### ISSUE THREAD

**Issue by cubells** [OCA/OpenUpgrade#420]
Any idea what's the problem?

I've got this error on upgrade from 7.0 to 8.0:

ValueError: "name 'test_assigned' is not defined" while evaluating
u'test_assigned()'
2015-12-14 07:08:43,501 25150 ERROR database_migrated openerp.modules.loading: Error executing post migration script for module stock
`-> procurement_jit_stock
: "name 'test_assigned' is not defined" while evaluating
u'test_assigned()'
2015-12-14 07:08:43,893 25150 CRITICAL database_migrated openerp.service.server: Failed to initialize database`database_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 208, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 948, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/post-migration.py", line 832, in migrate
    migrate_stock_qty(cr, registry)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/post-migration.py", line 701, in migrate_stock_qty
    move.action_done()
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 580, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/stock/stock.py", line 2481, in action_done
    picking_obj.write(cr, uid, done_picking, {'date_done': time.strftime(DEFAULT_SERVER_DATETIME_FORMAT)}, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/stock/stock.py", line 958, in write
    res = super(stock_picking, self).write(cr, uid, ids, vals, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 387, in old_api
    result = method(recs, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3831, in write
    self._write(old_vals)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 580, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 4085, in _write
    self.step_workflow(cr, user, ids, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 3605, in step_workflow
    workflow.trg_write(uid, self._name, res_id, cr)
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/__init__.py", line 40, in trg_write
    return WorkflowService.new(cr, uid, res_type, res_id).write()
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/service.py", line 53, in write
    WorkflowInstance(self.session, self.record, {'id': instance_id}).update()
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/instance.py", line 91, in update
    WorkflowItem(self.session, self.record, work_item_values).process(stack=stack)
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/workitem.py", line 229, in _split_test
    if self.wkf_expr_check(transition,signal):
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/workitem.py", line 333, in wkf_expr_check
    return self.wkf_expr_eval_expr(transition['condition'])
  File "/var/tmp/openupgrade/8.0/server/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/var/tmp/openupgrade/8.0/server/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ValueError: "name 'test_assigned' is not defined" while evaluating
u'test_assigned()'

**Comment by metaminux** [comment]
Same issue here…

@cubells Did you find a solution by now ? Does your database use custom modules or are they just native Odoo supported modules ?

This error occurs during the loop on "done" stock moves in order to create quants, as stated here :

> File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/post-migration.py", line 701, in migrate_stock_qty move.action_done()

My database contains 7027 done moves and 6892 of them are treated without any problem before this message shows up. The affected move doesn't seem to be special though…

**Comment by StefanRijnhart** [comment]
Looks like we need to remove the workflow (https://github.com/OCA/OpenUpgrade/blob/8.0/addons/stock/migrations/8.0.1.1/post-migration.py#L839) earlier, before https://github.com/OCA/OpenUpgrade/blob/8.0/addons/stock/migrations/8.0.1.1/post-migration.py#L832.

**Comment by metaminux** [comment]
Seems you're right, deleting the workflow just before migrating stock quantities did the trick for me.

Thanks,

**Comment by hbrunn** [comment]
@StefanRijnhart @metaminux but don't delete it, deactivating should be sufficient: https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L855

**Comment by mbcosta** [comment]
Hello, I confirm that it works once we apply the following patch:

```
index 59e35f9..29b5cb7 100644
--- a/addons/stock/migrations/8.0.1.1/post-migration.py
+++ b/addons/stock/migrations/8.0.1.1/post-migration.py
@@ -829,6 +829,7 @@ def migrate(cr, version):
         migrate_product_supply_method(cr, registry)
         migrate_procurement_order(cr, registry)

+    openupgrade.deactivate_workflow_transitions(cr, 'stock.picking')
     migrate_stock_qty(cr, registry)
     migrate_stock_production_lot(cr, registry)
```

**Comment by hbrunn** [comment]
...and don't forget to reenable afterwards

**Comment by mbcosta** [comment]
Thanks for the tip @hbrunn 

```
--- a/addons/stock/migrations/8.0.1.1/post-migration.py
+++ b/addons/stock/migrations/8.0.1.1/post-migration.py
@@ -829,6 +829,7 @@ def migrate(cr, version):
         migrate_product_supply_method(cr, registry)
         migrate_procurement_order(cr, registry)

+    deactivate_wfk = openupgrade.deactivate_workflow_transitions(cr, 'stock.picking')
     migrate_stock_qty(cr, registry)
     migrate_stock_production_lot(cr, registry)

@@ -841,3 +842,4 @@ def migrate(cr, version):
         cr, uid, registry, ['stock.production.lot', 'stock.picking'])
     migrate_move_inventory(cr, registry)
     reset_warehouse_data_ids(cr, registry)
+    openupgrade.reactivate_workflow_transitions(cr, deactivate_wfk)
```

**Comment by metaminux** [comment]
I wonder if reactivation is really needed here…

As stated by @StefanRijnhart, the complete 'stock.picking' workflow has to be remove and is actually deleted there : https://github.com/OCA/OpenUpgrade/blob/2c1270a0021c1dd59d2338fed0bc4fc8a54f0889/addons/stock/migrations/8.0.1.1/post-migration.py#L839

I tried deleting the workflow before calling the "migrate_stock_qty" method, everything worked well…

Do I make a PR ?

**Comment by hbrunn** [comment]
@metaminux I think it's good to be conservative, as there can be custom workflow steps of course. But on the other hand, they'll probably have to be rewritten anyways. On the third hand, I assume it's better to fail than to silently throw aways things, introducing subtle weirdnesses.
And yes, please make a PR

**Comment by StefanRijnhart** [comment]
Is this fixed by https://github.com/OCA/OpenUpgrade/pull/438?

**Comment by StefanRijnhart** [comment]
Let's assume it is.
