### ISSUE TITLE
Error installing Openupgrade Framework 14.0 on odoo 13.0

### ISSUE THREAD

**Issue by ludodoucet** [OCA/OpenUpgrade#4211]
## Module
Openupgrade Framework

## Describe the bug

Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1346, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 390, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 377, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 585, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 428, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/odoo/odoo-server/odoo/modules/module.py", line 405, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/odoo/custom/addons/openupgrade_framework/__init__.py", line 7, in <module>
    from . import odoo_patch
  File "/odoo/custom/addons/openupgrade_framework/odoo_patch/__init__.py", line 1, in <module>
    from . import odoo
  File "/odoo/custom/addons/openupgrade_framework/odoo_patch/odoo/__init__.py", line 1, in <module>
    from . import addons, api, models, modules
  File "/odoo/custom/addons/openupgrade_framework/odoo_patch/odoo/addons/__init__.py", line 1, in <module>
    from . import base
  File "/odoo/custom/addons/openupgrade_framework/odoo_patch/odoo/addons/base/__init__.py", line 1, in <module>
    from . import models
  File "/odoo/custom/addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/__init__.py", line 1, in <module>
    from . import ir_model
  File "/odoo/custom/addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_model.py", line 102, in <module>
    _process_ondelete._original_method = IrModelSelection._process_ondelete
AttributeError: type object 'IrModelSelection' has no attribute '_process_ondelete'

**Comment by legalsylvain** [comment]
openupgrade 14 should be installed with odoo 14
Please refer to the documentation https://oca.github.io/OpenUpgrade/intro.html

regards.

**Comment by ludodoucet** [comment]
I now have two instances of odoo: odoo 13 and odoo 14. But I cannot connect the odoo13 database to odoo14.
Do you have a clue to guide me?
I only have the option to restore a database via the browser.
