### ISSUE TITLE
AttributeError: module 'openupgradelib.openupgrade_160' has no attribute 'fill_analytic_distribution'

### ISSUE THREAD

**Issue by MAYURNAGAR-7069** [OCA/OpenUpgrade#4221]
Hello,
I am working on odoo migration15 --> 16.

When accounting module was migrating i gives me this error.

##Error
2023-11-08 12:23:07,028 408485 CRITICAL et_v16_01 odoo.service.server: Failed to initialize database `et_v16_01`. 
Traceback (most recent call last):
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/loading.py", line 183, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/mayurnagar/source/odoo/custom/OpenUpgrade-16.0/openupgrade_framework/odoo_patch/odoo/modules/migration.py", line 18, in migrate_module
    MigrationManager.migrate_module._original_method(self, pkg, stage)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/migration.py", line 189, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/mayurnagar/source/3_8_odoo_env/lib/python3.8/site-packages/openupgradelib/openupgrade.py", line 2277, in wrapped_function
    func(
  File "/home/mayurnagar/source/odoo/custom/OpenUpgrade-16.0/openupgrade_scripts/scripts/account/16.0.1.2/pre-migration.py", line 373, in migrate
    openupgrade_160.fill_analytic_distribution(
AttributeError: module 'openupgradelib.openupgrade_160' has no attribute 'fill_analytic_distribution'

**Comment by pedrobaeza** [comment]
You are not using latest openupgradelib version:

https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade_160.py#L406

Use always the repository one, not the one in pypi.

**Comment by MAYURNAGAR-7069** [comment]
@pedrobaeza Thank you
