### ISSUE TITLE
psycopg2.errors.ForeignKeyViolation: insert or update on table "stock_route_product" violates foreign key constraint "stock_route_product_route_id_fkey"

### ISSUE THREAD

**Issue by MAYURNAGAR-7069** [OCA/OpenUpgrade#4222]
=-query=- ALTER TABLE "stock_route_product" ADD FOREIGN KEY ("route_id") REFERENCES "stock_route"("id") ON DELETE cascade 
--> params None

2023-11-08 14:28:34,413 528620 ERROR et_v16_01 odoo.sql_db: bad query: ALTER TABLE "stock_route_product" ADD FOREIGN KEY ("route_id") REFERENCES "stock_route"("id") ON DELETE cascade
ERROR: insert or update on table "stock_route_product" violates foreign key constraint "stock_route_product_route_id_fkey"
DETAIL:  Key (route_id)=(14) is not present in table "stock_route".
 
2023-11-08 14:28:34,418 528620 WARNING et_v16_01 odoo.modules.loading: Transient module states were reset 
2023-11-08 14:28:34,433 528620 ERROR et_v16_01 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/loading.py", line 208, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/registry.py", line 541, in init_models
    self.check_foreign_keys(cr)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/registry.py", line 651, in check_foreign_keys
    sql.add_foreign_key(cr, table1, column1, table2, column2, ondelete)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/tools/sql.py", line 227, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/sql_db.py", line 329, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: insert or update on table "stock_route_product" violates foreign key constraint "stock_route_product_route_id_fkey"
DETAIL:  Key (route_id)=(14) is not present in table "stock_route".

ID (14) is from purchase_stock module "route_warehouse0_buy" XML ID.
This is an official module.

**Comment by pedrobaeza** [comment]
`stock` module is still not included in the migration scripts, so that's something expected. Check existing pull requests, and if there's something using them, put the comment there.

**Comment by luismata01** [comment]
I have the same error, is possible end the process and by pass this module stock?
