### ISSUE TITLE
[15.0 to 16.0]  module mail: creating or updating database tables - ERROR : psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: ""

### ISSUE THREAD

**Issue by luismata01** [OCA/OpenUpgrade#4234]
## Module
module mail: creating or updating database tables

## Describe the bug
When I try to migrate a database from 15.0 to 16.0 this error is happened when loading module mail in step (18/63)

> 2023-11-21 11:51:24,886 1 INFO devel_16tomigrate odoo.modules.loading: Loading module mail (18/63)
2023-11-21 11:51:25,938 1 INFO devel_16tomigrate odoo.modules.registry: module mail: creating or updating database tables
2023-11-21 11:51:30,097 1 WARNING devel_16tomigrate odoo.modules.loading: Transient module states were reset
2023-11-21 11:51:30,098 1 ERROR devel_16tomigrate odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 208, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 526, in init_models
    model._auto_init()
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 2578, in _auto_init
    new = field.update_db(self, columns)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1006, in update_db
    self.update_db_column(model, column)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1042, in update_db_column
    self._convert_db_column(model, column)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1046, in _convert_db_column
    sql.convert_column(model._cr, model._table, self.name, self.column_type[1])
  File "/opt/odoo/custom/src/odoo/odoo/tools/sql.py", line 128, in convert_column
    _convert_column(cr, tablename, columnname, columntype, using)
  File "/opt/odoo/custom/src/odoo/odoo/tools/sql.py", line 147, in _convert_column
    cr.execute(query, log_exceptions=False)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: ""
2023-11-21 11:51:30,107 1 CRITICAL devel_16tomigrate odoo.service.server: Failed to initialize database `devel_16tomigrate`.
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/opt/odoo/custom/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 208, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 526, in init_models
    model._auto_init()
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 2578, in _auto_init
    new = field.update_db(self, columns)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1006, in update_db
    self.update_db_column(model, column)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1042, in update_db_column
    self._convert_db_column(model, column)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1046, in _convert_db_column
    sql.convert_column(model._cr, model._table, self.name, self.column_type[1])
  File "/opt/odoo/custom/src/odoo/odoo/tools/sql.py", line 128, in convert_column
    _convert_column(cr, tablename, columnname, columntype, using)
  File "/opt/odoo/custom/src/odoo/odoo/tools/sql.py", line 147, in _convert_column
    cr.execute(query, log_exceptions=False)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: ""
2023-11-21 11:51:30,109 1 INFO devel_16tomigrate odoo.service.server: Stopping gracefully
ERROR: 255

**Comment by pedrobaeza** [comment]
There's no trace in your log about OpenUpgrade, so you are not doing the migration correctly. Please check the guides.
