### ISSUE TITLE
odoo 8 to odoo 9 problem

### ISSUE THREAD

**Issue by grauschnabel** [OCA/OpenUpgrade#426]
Hi there, 
I tried your script and it worked till the end, and it does not work.

in the openerp-server.log:
2016-01-09 12:40:04,191 31224 INFO kaffanke_from_8_migrated openerp.modules.loading: loading report/views/layouts.xml
2016-01-09 12:40:04,631 31224 INFO kaffanke_from_8_migrated openerp.addons.base.ir.ir_ui_view: Element '<t name="Report layout" t-name="report.layout">' kann nicht in der übergeordneten Ansicht lokalisiert werden.

Fehler Kontext:
Ansicht `Web layout`
[view_id: 165, xml_id: web.layout, model: k. A., parent_id: k. A.]
2016-01-09 12:40:04,661 31224 INFO kaffanke_from_8_migrated werkzeug: 192.168.56.101 - - [09/Jan/2016 12:40:04] "GET /web/database/selector HTTP/1.1" 500 -
2016-01-09 12:40:04,797 31224 ERROR kaffanke_from_8_migrated werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1416, in **call**
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1390, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 591, in **call**
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1565, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 354, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 354, in get
    update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 333, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 852, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 939, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 802, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 805, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 778, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 709, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 1080, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 374, in write
    context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3817, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3997, in _write
    recs._validate_fields(vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 1272, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
Element '<t name="Report layout" t-name="report.layout">' kann nicht in der \xfcbergeordneten Ansicht lokalisiert werden.
Fehler Kontext:
Ansicht `Web layout`
[view_id: 165, xml_id: web.layout, model: k. A., parent_id: k. A.]
None" while parsing None:22, near
<t name="Report layout" t-name="report.layout">&lt;!DOCTYPE html&gt;
    <html t-att-lang="lang and lang.replace('_', '-')" t-att-data-editable="'1' if editable else None" t-att-data-translatable="'1' if translatable else None" t-att-data-edit_translations="'1' if edit_translations else None" t-att-data-main-object="repr(main_object) if editable else None" t-att-data-report-margin-top="data_report_margin_top" t-att-data-report-header-spacing="data_report_header_spacing" t-att-data-report-dpi="data_report_dpi">
        <head>
            <meta charset="utf-8"/>
            <meta name="viewport" content="initial-scale=1"/>
            <title><t t-esc="title or 'Odoo Report'"/></title>
            <t t-call-assets="report.assets_common"/>
            <t t-if="editable">
                <t t-call-assets="web_editor.assets_editor"/>
                <t t-call-assets="report.assets_editor"/>
            </t>
        </head>
        <body class="container" t-att-style="editable and 'margin-top: 40px;'">
            <div id="wrapwrap">
                <main>
                    <t t-raw="0"/>
                </main>
            </div>
        </body>
    </html>
</t>

Maybe you can help me with that?

**Comment by pedrobaeza** [comment]
Migration to v9 is not yet completed. Please follow progress in https://github.com/OCA/OpenUpgrade/issues/400
