### ISSUE TITLE
Error migration openerp 7 to odoo 8.0 

### ISSUE THREAD

**Issue by vm50** [OCA/OpenUpgrade#431]
Hello ,

By migrating openerp 7 to 8.0 I get the following error. I do not see many or it may come.
Information the database isn't run on the Odoo Server
Do you have an idea ?

Thank you

2016-01-29 14:15:35,043 32600 INFO bdd_migrated OpenUpgrade: table crm_case_channel_id_seq: renaming to crm_tracking_medium_id_seq
2016-01-29 14:15:35,043 32600 INFO bdd_migrated OpenUpgrade: table crm_case_resource_type_id_seq: renaming to crm_tracking_campaign_id_seq
2016-01-29 14:15:35,044 32600 ERROR bdd_migrated openerp.sql_db: Programming error: syntax error at or near "EXISTS"
LINE 1: ALTER TABLE crm_lead DROP CONSTRAINT IF EXISTS crm_lead_chan...
                                                ^
, in query ALTER TABLE crm_lead DROP CONSTRAINT IF EXISTS crm_lead_channel_id_fkey
2016-01-29 14:15:35,044 32600 ERROR bdd_migrated OpenUpgrade: crm: error in migration script /var/tmp/openupgrade/8.0/addons/crm/migrations/8.0.1.0/pre-migration.py: syntax error at or near "EXISTS"
LINE 1: ALTER TABLE crm_lead DROP CONSTRAINT IF EXISTS crm_lead_chan...
                                                ^

2016-01-29 14:15:35,044 32600 ERROR bdd_migrated OpenUpgrade: syntax error at or near "EXISTS"
LINE 1: ALTER TABLE crm_lead DROP CONSTRAINT IF EXISTS crm_lead_chan...
                                                ^
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 948, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/crm/migrations/8.0.1.0/pre-migration.py", line 62, in migrate
    constraint))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "EXISTS"
LINE 1: ALTER TABLE crm_lead DROP CONSTRAINT IF EXISTS crm_lead_chan...
                                                ^

2016-01-29 14:15:35,045 32600 CRITICAL bdd_migrated openerp.service.server: Failed to initialize database `bdd_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 156, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 948, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/crm/migrations/8.0.1.0/pre-migration.py", line 62, in migrate
    constraint))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "EXISTS"
LINE 1: ALTER TABLE crm_lead DROP CONSTRAINT IF EXISTS crm_lead_chan...
                                                ^

2016-01-29 14:15:35,045 32600 INFO bdd_migrated openerp.service.server: Initiating shutdown
2016-01-29 14:15:35,045 32600 INFO bdd_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by pedrobaeza** [comment]
It seems you're running a very old Postgres version. Maybe 8.4? You need at least 9.0.

**Comment by vm50** [comment]
Yes i use postgres version 8.4 on debian 7 . So you have to switch to version 9?

**Comment by vm50** [comment]
OH i'm debian 6 ,I'll update

**Comment by pedrobaeza** [comment]
As you are upgrading, better to 9.4/9.5 to use latest features.

**Comment by vm50** [comment]
I upgrade to debian 7 and postgres 9.1  . I have the error 

2016-01-29 17:26:12,492 3275 DEBUG bdd_migrated OpenUpgrade: 1 rows affected
2016-01-29 17:26:12,492 3275 DEBUG bdd_migrated OpenUpgrade: Running UPDATE ir_model_data SET module = stock_account, name = stock_journal_sequence WHERE module = stock and name = stock_journal_sequence
2016-01-29 17:26:12,492 3275 DEBUG bdd_migrated OpenUpgrade: 1 rows affected
2016-01-29 17:26:12,493 3275 ERROR bdd_migrated openerp.sql_db: Programming error: column "location_id" of relation "stock_inventory" already exists
, in query ALTER TABLE stock_inventory ADD COLUMN location_id INTEGER
2016-01-29 17:26:12,493 3275 ERROR bdd_migrated OpenUpgrade: stock: error in migration script /var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/pre-migration.py: column "location_id" of relation "stock_inventory" already exists

2016-01-29 17:26:12,493 3275 ERROR bdd_migrated OpenUpgrade: column "location_id" of relation "stock_inventory" already exists
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 948, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/pre-migration.py", line 176, in migrate
    initialize_location_inventory(cr)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/pre-migration.py", line 104, in initialize_location_inventory
    cr.execute("ALTER TABLE stock_inventory ADD COLUMN location_id INTEGER")
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "location_id" of relation "stock_inventory" already exists

2016-01-29 17:26:12,494 3275 CRITICAL bdd_migrated openerp.service.server: Failed to initialize database `bdd_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 156, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 948, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/pre-migration.py", line 176, in migrate
    initialize_location_inventory(cr)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/pre-migration.py", line 104, in initialize_location_inventory
    cr.execute("ALTER TABLE stock_inventory ADD COLUMN location_id INTEGER")
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "location_id" of relation "stock_inventory" already exists

**Comment by vm50** [comment]
I advance slowly 

2016-01-29 17:50:37,737 3844 ERROR bdd_migrated openerp.addons.base.ir.ir_ui_view: Le champ `product_uom` n'existe pas

Contexte de l'erreur :
Vue `stock.inventory.line.form`
[view_id: 547, xml_id: n/a, model: stock.inventory.line, parent_id: n/a]
2016-01-29 17:50:37,737 3844 WARNING bdd_migrated openerp.addons.base.ir.ir_ui_view: Can't render view  for model: stock.inventory.line. If you are migrating between major versions of OpenERP, this is to be expected (otherwise, do not run OpenUpgrade server).
2016-01-29 17:50:37,789 3844 ERROR bdd_migrated openerp.addons.base.ir.ir_ui_view: The element '<group name="status" version="7.0">' can not be located in the parent view

Contexte de l'erreur :
Vue `product.product.form`
[view_id: 221, xml_id: product.product_normal_form_view, model: product.product, parent_id: 239]
2016-01-29 17:50:37,789 3844 CRITICAL bdd_migrated openerp.service.server: Failed to initialize database `bdd_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 483, in load_modules
    if not Views._validate_custom_views(cr, SUPERUSER_ID, model):
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 1128, in _validate_custom_views
    return self._check_xml(cr, uid, ids, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 197, in _check_xml
    view_def = self.read_combined(cr, uid, view.id, ['arch'], context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 556, in read_combined
    cr, uid, arch_tree, view_arch, parent_view['id'], context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 498, in apply_inheritance_specs
    self.raise_view_error(cr, uid, _("Element '%s' cannot be located in parent view") % tag, inherit_id, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 383, in raise_view_error
    raise AttributeError(message)
AttributeError: L'\xe9l\xe9ment '<group name="status" version="7.0">' ne peut \xeatre localis\xe9 dans la vue parente

Contexte de l'erreur :
Vue `product.product.form`
[view_id: 221, xml_id: product.product_normal_form_view, model: product.product, parent_id: 239]
2016-01-29 17:50:37,806 3844 INFO bdd_migrated openerp.service.server: Initiating shutdown
2016-01-29 17:50:37,806 3844 INFO bdd_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by pedrobaeza** [comment]
This is probably due to custom addons that you have, so it's something out of the scope of these project issues.

**Comment by vm50** [comment]
Hello , 

Thank for your answer .
I update openerp 7 with the last version 2016 ,it's faster  . But I still get the same error. I do not have a custom module as standard modules.

**Comment by StefanRijnhart** [comment]
Your last error seems to be triggered from a call to _validate_custom_views in openerp/modules/loading.py. You could check your custom views (views without an xml-id, most likely as a result of view customizations in the interface) but then again this error should not be fatal judging from a look at the code. Maybe the fatal error occurs before this snippet?

**Comment by vm50** [comment]
Hello , 

Thank you for this return

I deleted all custom views, but I get the same error

**Comment by vm50** [comment]
Actually I have other errors before

2016-02-03 23:16:03,655 23894 ERROR bdd_migrated openerp.sql_db: bad query: delete from stock_picking_type where id IN (2)
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "picking_type_id" violates not-null constraint
CONTEXT:  SQL statement "UPDATE ONLY "public"."stock_picking" SET "picking_type_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "picking_type_id""

2016-02-03 23:16:03,655 23894 WARNING bdd_migrated openerp.addons.base.ir.ir_model: Could not delete obsolete record with id: 2 of model stock.picking.type
Please refer to the log message right above
2016-02-03 23:16:03,655 23894 INFO bdd_migrated openerp.addons.base.ir.ir_model: Deleting 1@stock.picking.type
2016-02-03 23:16:03,656 23894 ERROR bdd_migrated openerp.sql_db: bad query: delete from stock_picking_type where id IN (1)
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "picking_type_id" violates not-null constraint
CONTEXT:  SQL statement "UPDATE ONLY "public"."stock_picking" SET "picking_type_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "picking_type_id""

2016-02-03 23:16:06,004 23894 ERROR bdd_migrated openerp.sql_db: bad query: delete from ir_ui_view where id IN (547)
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
DETAIL:  Key (id)=(547) is still referenced from table "ir_ui_view".

2016-02-03 23:16:06,258 23894 ERROR bdd_migrated openerp.sql_db: bad query: delete from ir_ui_view where id IN (539)
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
DETAIL:  Key (id)=(539) is still referenced from table "ir_ui_view".

2016-02-03 23:16:06,293 23894 ERROR bdd_migrated openerp.sql_db: bad query: delete from ir_ui_view where id IN (536)
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
DETAIL:  Key (id)=(536) is still referenced from table "ir_ui_view".

**Comment by vm50** [comment]
The table stock_picking_type does not exist . 

public | stock_partial_move                                   | table    | openerp
 public | stock_partial_move_id_seq                            | sequence | openerp
 public | stock_partial_move_line                              | table    | openerp
 public | stock_partial_move_line_id_seq                       | sequence | openerp
 public | stock_partial_picking                                | table    | openerp
 public | stock_partial_picking_id_seq                         | sequence | openerp
 public | stock_partial_picking_line                           | table    | openerp
 public | stock_partial_picking_line_id_seq                    | sequence | openerp
 public | stock_picking                                        | table    | openerp
 public | stock_picking_id_seq                                 | sequence | openerp
 public | stock_production_lot                                 | table    | openerp
 public | stock_production_lot_id_seq                          | sequence | openerp
 public | stock_production_lot_revision                        | table    | openerp
 public | stock_production_lot_revision_id_seq                 | sequence | openerp
 public | stock_report_prodlots

**Comment by StefanRijnhart** [comment]
Is it maybe the case that you have procurement installed in 7.0 but not stock? That may not be supported. In that case, try installing stock in 7.0 before migration.

**Comment by StefanRijnhart** [comment]
(the reason is that in 7.0, stock depends on procurement and in 8.0 it is exactly the other way around)

**Comment by StefanRijnhart** [comment]
Sorry, that was not correct. It has changed in the opposite direction. Please forget all my comments of today, I misread your last message thinking that all the tables you mentioned did not exist.

**Comment by StefanRijnhart** [comment]
Please post the full logs on some pastebin if you can. Partial logs can be misleading.

**Comment by vm50** [comment]
Hello ,

already thank you for your interest in my problem.

I made a new migration test here is the error in copying

http://pastebin.com/0fCQ8hLw

**Comment by vm50** [comment]
Hello ,

I kept looking at my side, I do not see how this problem corrected.
Do you have tracks with all the logs?

Thank

**Comment by vm50** [comment]
To continue in my tests I passed my database in postgresql 9.5. But what is worse, there is a calendar module level error.
I saw that there was an update 4 days ago from the calendar module.

2016-02-16 16:31:45,851 14215 INFO bdd_migrated OpenUpgrade: calendar: post-migration script called with version 7.0.1.0
2016-02-16 16:31:45,855 14215 ERROR bdd_migrated openerp.sql_db: Programming error: constraint "meeting_category_rel_event_id_type_id_key" of relation "meeting_category_rel" does not 
exist
, in query alter table meeting_category_rel
        drop constraint meeting_category_rel_event_id_type_id_key
2016-02-16 16:31:45,855 14215 ERROR bdd_migrated OpenUpgrade: calendar: error in migration script /var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py: constr
aint "meeting_category_rel_event_id_type_id_key" of relation "meeting_category_rel" does not exist

2016-02-16 16:31:45,855 14215 ERROR bdd_migrated OpenUpgrade: constraint "meeting_category_rel_event_id_type_id_key" of relation "meeting_category_rel" does not exist
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 948, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 190, in migrate
    import_crm_meeting(cr)
  File "/var/tmp/openupgrade/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py", line 87, in import_crm_meeting
    drop constraint meeting_category_rel_event_id_type_id_key''')
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: constraint "meeting_category_rel_event_id_type_id_key" of relation "meeting_category_rel" does not exist

2016-02-16 16:31:45,856 14215 ERROR bdd_migrated openerp.modules.loading: Error executing post migration script for module calendar
`-> crm
`-> crm_claim
      `-> claim_from_delivery
`-> portal_claim
`-> hr_holidays
`-> hr_payroll
: constraint "meeting_category_rel_event_id_type_id_key" of relation "meeting_category_rel" does not exist

2016-02-16 16:31:45,856 14215 CRITICAL bdd_migrated openerp.service.server: Failed to initialize database `bdd_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 208, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 948, in wrapped_function

**Comment by vm50** [comment]
I deleted the module's calendar changes, I got to the same stage as the previous entries still the same error on the stock table.

I tried the alter table in manually, but always without success.
Do you have any other ideas?

**Comment by StefanRijnhart** [comment]
Thanks for sharing. The main problem I see is indeed that Odoo attempts to remove the picking types that are only introduced in 8.0. Just to confirm, you don't have a stock_picking_type table in 7.0, do you? And you do start every migration attempt from a fresh copy of your 7.0 database?

**Comment by StefanRijnhart** [comment]
BTW. sorry for the regression with the calendar constraint (but also slightly surprized you don't have it).

**Comment by pedrobaeza** [comment]
I'm not sure that is a regression, because he must have it. Maybe he is not working from a fresh copy of the DB?

**Comment by vm50** [comment]
So I deleted the basis bdd merged, then stop Odoo service.
I get the latest version of git, so I have the same problem with the calendar module.
I again removed the changes.

And no i don't have stock_picking_type table in 7.0 . 

public | stock_partial_picking                                | table    | openerp
 public | stock_partial_picking_id_seq                         | sequence | openerp
 public | stock_partial_picking_line                           | table    | openerp
 public | stock_partial_picking_line_id_seq                    | sequence | openerp
 public | stock_picking                                        | table    | openerp
 public | stock_picking_id_seq                                 | sequence | openerp
 public | stock_production_lot                                 | table    | openerp
 public | stock_production_lot_id_seq                          | sequence | openerp
