### ISSUE TITLE
Projekt Long Term not upgraded 7 -> 8

### ISSUE THREAD

**Issue by anderswallenquist** [OCA/OpenUpgrade#432]
I have upgraded a database with accounting, project and project longterm. Accounting and project is fine but project long term does not work.
When I opens the upgrade dialog for the module, the upgrade button are in "Cancel upgrade". 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1247, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_actions.py", line 326, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3145, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3180, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3367, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/fields.py", line 1460, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_actions.py", line 266, in _search_view
    field_get = self.pool[act.res_model].fields_view_get(cr, uid,
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
KeyError: u'project.phase'

**Comment by dreispt** [comment]
AFAICT that was deprecated. You could port it to v8 and propose it to OCA/project.

**Comment by anderswallenquist** [comment]
It looks like to be ported to Odoo 8 by Ingadhoc
https://github.com/ingadhoc/odoo-addons/tree/8.0/project_long_term

How do I propose it to OCA/Project?

**Comment by StefanRijnhart** [comment]
You need to contact ingadhoc about proposing the module to the OCA. Closing this as out of scope for this project.
