### ISSUE TITLE
i cannot access to accounting 

### ISSUE THREAD

**Issue by ahmedanwer708** [OCA/OpenUpgrade#4437]
UncaughtPromiseError
وعد لم يتم رصده  > Missing field string information for the field 'account_cash_advances_id' from the 'account.journal' model
Error: Missing field string information for the field 'account_cash_advances_id' from the 'account.journal' model
    at https://aynma.alpha.com.se/web/assets/943-e2098c9/web.assets_backend.min.js:6773:258
    at traverse (https://aynma.alpha.com.se/web/assets/943-e2098c9/web.assets_backend.min.js:6768:200)
    at https://aynma.alpha.com.se/web/assets/943-e2098c9/web.assets_backend.min.js:6768:242
    at Function.each (https://aynma.alpha.com.se/web/assets/877-b152e00/web.assets_common.min.js:173:149)
    at traverse (https://aynma.alpha.com.se/web/assets/943-e2098c9/web.assets_backend.min.js:6768:211)
    at https://aynma.alpha.com.se/web/assets/943-e2098c9/web.assets_backend.min.js:6768:242
    at Function.each (https://aynma.alpha.com.se/web/assets/877-b152e00/web.assets_common.min.js:173:149)
    at traverse (https://aynma.alpha.com.se/web/assets/943-e2098c9/web.assets_backend.min.js:6768:211)
    at https://aynma.alpha.com.se/web/assets/943-e2098c9/web.assets_backend.min.js:6768:242
    at Function.each (https://aynma.alpha.com.se/web/assets/877-b152e00/web.assets_common.min.js:173:149)

**Comment by pedrobaeza** [comment]
Sorry, this doesn't seem something related with OpenUpgrade migration scripts, so this doesn't qualify as an issue. Open a discussion indicating also full information. The more information you put, the more people will be able (or willing) to help you.
