### ISSUE TITLE
[14.0][account] ERROR: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist

### ISSUE THREAD

**Issue by rvalyi** [OCA/OpenUpgrade#4494]
When migrating a database from 13.0 to 14.0 I'm getting a foreign key issue with the account_reconcile_model_analytic_tag_rel table.
This is a database that migrated quite easily from 12.0 to 13.0 without issue with with the account module.

## Module
account

## Describe the bug

```
2024-07-01 19:55:28,173 605 INFO database odoo.models: Storing computed values of res.company.account_tax_fiscal_country_id
2024-07-01 19:55:29,626 605 INFO database odoo.schema: Keep unexpected index account_move_statement_line_id_index on table account_move
2024-07-01 19:55:31,210 605 ERROR airandme14 odoo.sql_db: bad query: ALTER TABLE "account_reconcile_model_analytic_tag_rel" ADD FOREIGN KEY ("account_reconcile_model_line_id") REFERENCES "account_reconcile_model_line"("id") ON DELETE cascade
ERROR: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist

2024-07-01 19:55:31,289 605 WARNING airandme14 odoo.modules.loading: Transient module states were reset
2024-07-01 19:55:31,291 605 ERROR airandme14 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/src/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/src/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/src/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/src/odoo/modules/loading.py", line 199, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/odoo/src/odoo/modules/registry.py", line 420, in init_models
    self.check_foreign_keys(cr)
  File "/odoo/src/odoo/modules/registry.py", line 501, in check_foreign_keys
    sql.add_foreign_key(cr, table1, column1, table2, column2, ondelete)
  File "/odoo/src/odoo/tools/sql.py", line 170, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/env/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/odoo/src/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/odoo/src/odoo/sql_db.py", line 301, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist
```

## To Reproduce
Not to sure. I imagine there is no issue with a demo database as the CI is supposed to pass..

**Expected behavior**
No such error.

**Additional context**
This is a database that migrated quite easily from 12.0 to 13.0 without issue with with the account module.
The database was migrated using OpenUpgrade since v8 and has been used some 3 years in the v12 version before this new migration.

I could work around the bug with the following Odoo patch:
```
akretion@debian:~/odoo14/odoo/src$ git diff odoo/modules/registry.py
diff --git a/odoo/modules/registry.py b/odoo/modules/registry.py
index fd94d78c61d..f27b1f7e572 100644
--- a/odoo/modules/registry.py
+++ b/odoo/modules/registry.py
@@ -496,6 +496,8 @@ class Registry(Mapping):
             deltype = sql._CONFDELTYPES[ondelete.upper()]
             spec = existing.get(key)
             if spec is None:
+                if column1 == "account_reconcile_model_line_id":
+                    return
                 sql.add_foreign_key(cr, table1, column1, table2, column2, ondelete)
                 conname = sql.get_foreign_keys(cr, table1, column1, table2, column2, ondelete)[0]
                 model.env['ir.model.constraint']._reflect_constraint(model, conname, 'f', None, module
```

**Comment by rvalyi** [comment]
Damn!! I am SO STUPID, I forgot OpenUpgrade is different after v14 and it needs to be started with --load=base,web,openupgrade_framework

The script to add the column is indeed present in the account pre-migration script...

stupid me!!
