### ISSUE TITLE
Isuee when migrate from version 14 to 15

### ISSUE THREAD

**Issue by specks-zz** [OCA/OpenUpgrade#4546]
Hi everybody.

I have a problem when I try to migrate from version 14 to 15
## Module
Mail 15.0.0 

## Describe the bug
I have an instance with Odoo v13 that must be migrated to version 17. The migration to version 14 has been carried out successfully (including custom modules), and now that database must be migrated, however there is an error when migrating from version 14 to version 15.
The error refers to the Mail module in the OpenUpgrade folder.

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/odoo/odoo/openupgrade_15/openupgrade_framework/odoo_patch/odoo/modules/migration.py", line 18, in migrate_module
    MigrationManager.migrate_module._original_method(self, pkg, stage)
  File "/opt/odoo/odoo/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.10/dist-packages/openupgradelib/openupgrade.py", line 2297, in wrapped_function
    func(
  File "/opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py", line 257, in migrate
    _migrate_mail_templates(env)
  File "/opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py", line 230, in _migrate_mail_templates
    tmpl_lang.body_html = mako_html_to_qweb(tmpl_lang.body_html)
  File "/opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py", line 209, in mako_html_to_qweb
    string = _migrate_html_attributes(string)
  File "/opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py", line 190, in _migrate_html_attributes
    for element in root.iter():
```

The error is shown in the file **migration.py** and **post-migration.py** of the openupgrade module path: /opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py"

##Installed packages and libraries

Python 3.10.12
OS:  Ubuntu 22.04.4
Postgresql 14.13
Lxml 4.6.5 *

*I have tried updating to version 5.0.0 of lxml but the error persists

## To Reproduce
I run the update script as follows;
./odoo-bin --addons-path=/opt/odoo/odoo/addons,/opt/odoo/odoo/odoo/addons,/opt/odoo/odoo/openupgrade_15 --database=database_original --upgrade-path=/opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts --load=base,web,openupgrade_framework --update=all

I appreciate the help you can give me.

Regards.

**Comment by pedrobaeza** [comment]
The important part of the error is missing.

**Comment by specks-zz** [comment]
Hi.

I have added more information to the error trace:

2024-09-09 14:44:41,560 1172 ERROR database_original OpenUpgrade: mail: error in migration script /opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py: 'NoneType' object has no attribute 'iter'
2024-09-09 14:44:41,564 1172 ERROR database_original OpenUpgrade: 'NoneType' object has no attribute 'iter'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openupgradelib/openupgrade.py", line 2297, in wrapped_function
    func(
  File "/opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py", line 257, in migrate
    _migrate_mail_templates(env)
  File "/opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py", line 230, in _migrate_mail_templates
    tmpl_lang.body_html = mako_html_to_qweb(tmpl_lang.body_html)
  File "/opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py", line 209, in mako_html_to_qweb
    string = _migrate_html_attributes(string)
  File "/opt/odoo/odoo/openupgrade_15/openupgrade_scripts/scripts/mail/15.0.1.5/post-migration.py", line 190, in _migrate_html_attributes
    for element in root.iter():
AttributeError: 'NoneType' object has no attribute 'iter'
2024-09-09 14:44:41,596 1172 WARNING database_original odoo.modules.loading: Transient module states were reset
2024-09-09 14:44:41,605 1172 ERROR database_original odoo.modules.registry: Failed to load registry

Regards.

**Comment by pedrobaeza** [comment]
Well, it seems you have bad content in the body of a mail template that is being trying to be converted. Put a debug break before giving the error for knowing which model and record is the bad one, and empty it or fix it, or directly browse each of the templates and deduce which one is the corrupted.

Closing as no bug on the OpenUpgrade code itself.

**Comment by specks-zz** [comment]
Thank you for your response, your suggestion seems good to me, 
I am going to do the review you indicate.

Regards.
