### ISSUE TITLE
hr_holidays migration from OpenERP 7 to Odoo 8

### ISSUE THREAD

**Issue by cungureanu** [OCA/OpenUpgrade#465]
Hi guys,
Thank you for your hard work.

I have a problem upgrading hr_holidays module; here is the logcat:

```
2016-04-04 12:29:22,469 15350 ERROR openerp_test_migrated openerp.sql_db: bad query: ALTER TABLE "hr_holidays" ADD FOREIGN KEY ("user_id") REFERENCES "res_users" ON DELETE set null
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "hr_holidays" violates foreign key constraint "hr_holidays_user_id_fkey"
DETAIL:  Key (user_id)=(110) is not present in table "res_users".

2016-04-04 12:29:22,469 15350 CRITICAL openerp_test_migrated openerp.service.server: Failed to initialize database `openerp_test_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 179, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/module.py", line 293, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 2752, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "hr_holidays" violates foreign key constraint "hr_holidays_user_id_fkey"
DETAIL:  Key (user_id)=(110) is not present in table "res_users".
```

I can get past this removing from hr_holidays the inexistent fields but this way data is being dropped  
`DELETE FROM hr_holidays WHERE user_id NOT IN (SELECT id FROM res_users);`

Can this be fixed?

**Comment by hbrunn** [comment]
yes, by fixing your database. Either do what you propose, or create users with the appropriate ids, there's no other way to have referential integrity again.
