### ISSUE TITLE
[7.0] duplicates in ir_sequence_type

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#478]
After migrating from 6.04 to 6.1, I renamed the database and began a migration to 7.0. It stops with the following SQL query:

insert into "ir_sequence_type" (id,"code","name",create_uid,create_date,write_uid,write_date) values (45,'account.journal','Account Journal',1,(now() at time zone 'UTC'),1,(now() at time zone 'UTC'))

There is already a record with id 45, so migration stops.
2016-04-27 00:01:06,325 3803 INFO xxxx_61_migrated openerp.modules.module: module account_sequence: creating or updating database tables
2016-04-27 00:01:06,824 3803 INFO xxxx_61_migrated openerp.modules.loading: module account_sequence: loading account_sequence_data.xml
2016-04-27 00:01:06,879 3803 ERROR xxxx_61_migrated openerp.sql_db: bad query: insert into "ir_sequence_type" (id,"code","name",create_uid,create_date,write_uid,write_date) values (45,'account.journal','Account Journal',1,(now() at time zone 'UTC'),1,(now() at time zone 'UTC'))
Traceback (most recent call last):
  File "/var/tmp/openupgrade/7.0/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « ir_sequence_type_code_unique »
DÉTAIL : La clé « (code)=(account.journal) » existe déjà.

2016-04-27 00:01:06,933 3803 ERROR xxxx_61_migrated openerp.tools.convert: Parse error in /var/tmp/openupgrade/7.0/addons/account_sequence/account_sequence_data.xml:7: 
<record id="sequence_journal" model="ir.sequence.type">
        <field name="name">Account Journal</field>
        <field name="code">account.journal</field>
    </record>
Traceback (most recent call last):
  File "/var/tmp/openupgrade/7.0/server/openerp/tools/convert.py", line 855, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/var/tmp/openupgrade/7.0/server/openerp/tools/convert.py", line 822, in _tag_record
    id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/var/tmp/openupgrade/7.0/server/openerp/addons/base/ir/ir_model.py", line 1001, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/var/tmp/openupgrade/7.0/server/openerp/osv/orm.py", line 4592, in create
    cr.execute('insert into "'+self._table+'" (id'+upd0+") values ("+str(id_new)+upd1+')', tuple(upd2))
  File "/var/tmp/openupgrade/7.0/server/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/7.0/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « ir_sequence_type_code_unique »
DÉTAIL : La clé « (code)=(account.journal) » existe déjà.

2016-04-27 00:01:06,959 3803 ERROR xxxx_61_migrated openerp: Failed to initialize database `xxxx_61_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/7.0/server/openerp/cli/server.py", line 97, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname,update_module=update_module)
  File "/var/tmp/openupgrade/7.0/server/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/registry.py", line 203, in get
    update_module)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/loading.py", line 379, in load_modules
    registry)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/loading.py", line 282, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, registry=registry)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/loading.py", line 206, in load_module_graph
    load_data(module_name, idref, mode)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/loading.py", line 77, in <lambda>
    load_data = lambda _args: _load_data(cr, *args, kind='data')
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/loading.py", line 125, in _load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/7.0/server/openerp/tools/convert.py", line 962, in convert_xml_import
    obj.parse(doc.getroot())
  File "/var/tmp/openupgrade/7.0/server/openerp/tools/convert.py", line 855, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/var/tmp/openupgrade/7.0/server/openerp/tools/convert.py", line 822, in _tag_record
    id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/var/tmp/openupgrade/7.0/server/openerp/addons/base/ir/ir_model.py", line 1001, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/var/tmp/openupgrade/7.0/server/openerp/osv/orm.py", line 4592, in create
    cr.execute('insert into "'+self._table+'" (id'+upd0+") values ("+str(id_new)+upd1+')', tuple(upd2))
  File "/var/tmp/openupgrade/7.0/server/openerp/sql_db.py", line 161, in wrapper
    return f(self, *args, *_kwargs)
  File "/var/tmp/openupgrade/7.0/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « ir_sequence_type_code_unique »
DÉTAIL : La clé « (code)=(account.journal) » existe déjà.

**Comment by ghost** [comment]
I need to validate migration to 6.1 prior to moving to 7.0, so closing this now.
