### ISSUE TITLE
[6.1] to [7.0] Adding a foreign key to a table may stop migration if table is inconsistent

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#486]
Dear all,

When migrating from 6.1 to 7.0, an inconsistent table stopped the migration. Here is the log:
ALTER TABLE "ir_act_window" ADD FOREIGN KEY ("view_id") REFERENCES "ir_ui_view" ON DELETE cascade
Traceback (most recent call last):
  File "/var/tmp/openupgrade/7.0/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  une instruction insert ou update sur la table « ir_act_window » viole la contrainte de clé
étrangère « ir_act_window_view_id_fkey »
DÉTAIL : La clé (view_id)=(1196) n'est pas présente dans la table « ir_ui_view ».

Running the following query in the source 6.1 database removed/sanitized the offending record(s):
DELETE FROM ir_act_window
WHERE id=(SELECT ir_act_window.id
FROM ir_act_window
LEFT JOIN ir_ui_view
ON ir_act_window.view_id=ir_ui_view.id
WHERE ir_ui_view.id IS NULL
AND ir_act_window.view_id IS NOT NULL)

It is very neutral and **_could**_ be included in the migration script.

More generally, before adding a foreign key, it would be nice to remove any non-referenced record using the above script, otherwise, migration may stop.

**Comment by kellogs** [comment]
More generally, it would be nice to run a batch of SQL queries before migration to remove data which could stop migration because of lack of referential integrity.

I would like to do the same as database_clean, but using normal SQL queries, to make OpenUpgrade more liable.

Any idea where to start?

**Comment by ghost** [comment]
No this is not a workable solution.
2016-04-28 19:00:42,062 19474 ERROR xxxx_61_migrated openerp: Failed to initialize database `xxxx_61_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/7.0/server/openerp/cli/server.py", line 97, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname,update_module=update_module)
  File "/var/tmp/openupgrade/7.0/server/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/registry.py", line 203, in get
    update_module)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/loading.py", line 329, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, registry=registry)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/loading.py", line 183, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/7.0/server/openerp/modules/module.py", line 385, in init_module_models
    t[1](cr, *t[2])
  File "/var/tmp/openupgrade/7.0/server/openerp/osv/orm.py", line 2902, in _update_store
    res = f.get(cr, self, iids, k, SUPERUSER_ID, {})
  File "/var/tmp/openupgrade/7.0/server/openerp/osv/fields.py", line 1152, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/var/tmp/openupgrade/7.0/server/openerp/addons/base/ir/ir_ui_menu.py", line 289, in _get_needaction_enabled
    if menu.action and menu.action.type in ('ir.actions.act_window', 'ir.actions.client') and menu.action.res_model:
  File "/var/tmp/openupgrade/7.0/server/openerp/osv/orm.py", line 512, in __getattr__
    'id': self._id,
ValueError: Cannot fetch field "type" for "ir.actions.act_window" record with ID 762, that record does not exist or has been deleted

**Comment by ghost** [comment]
OK, I could recreate  the record, which comes from a module I removed (helpdesk):

761;"Helpdesk Categories";"ir.actions.act_window";"";1;"2011-02-03 02:51:03.81238";"";;535;"crm.case.categ";"form";"[('object_id.model', '=', 'crm.helpdesk')]";"Create and manage helpdesk categories to better manage and classify your support requests.";t;;0;"tree,form";f;"current";"";f;"";80;"{'object_id':'crm.helpdesk'}"

**Comment by ghost** [comment]
It would be a better solution to sanitize the database looking for modules "uninstalled" and then remove all information related to these modules. Is it possible in OpenERP? Probably not.

**Comment by ghost** [comment]
In fact, stopping migration is normal, this is a way to warn user. But tedious.

**Comment by StefanRijnhart** [comment]
OpenUpgrade assumes a consistent database indeed. I have never had a lot of problems with that apart from the occasional glitch that needed fixing manually, similar to the one you encountered here. Also, I think referential integrity improved over the last major releases of Odoo. Closing this issue now.

Sanitize your database with https://github.com/OCA/server-tools/tree/7.0/database_cleanup. Not available for 6.1 yet.
