### ISSUE TITLE
column "openupgrade_legacy_8_0_supply_method" does not exist

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#487]
During the post-migration of module "mrp" we're getting this error:

Traceback (most recent call last):
  File "/opt/odoo/v8/OpenUpgrade/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/odoo/v8/OpenUpgrade/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/v8/OpenUpgrade/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/opt/odoo/v8/OpenUpgrade/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/opt/odoo/v8/OpenUpgrade/openerp/modules/loading.py", line 208, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/odoo/v8/OpenUpgrade/openerp/modules/migration.py", line 179, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.1.1-py2.7.egg/openupgradelib/openupgrade.py", line 998, in wrapped_function
    func(cr, version)
  File "/opt/odoo/v8/OpenUpgrade/addons/mrp/migrations/8.0.1.1/post-migrate.py", line 228, in migrate
    migrate_product_supply_method(cr, pool)
  File "/opt/odoo/v8/OpenUpgrade/addons/mrp/migrations/8.0.1.1/post-migrate.py", line 159, in migrate_product_supply_method
    column=openupgrade.get_legacy_name('supply_method')), ('produce',))
  File "/opt/odoo/v8/OpenUpgrade/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/v8/OpenUpgrade/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "openupgrade_legacy_8_0_supply_method" does not exist
LINE 1: SELECT id FROM product_template WHERE openupgrade_legacy_8_0...

Any clue about this? @pedrobaeza @StefanRijnhart

**Comment by StefanRijnhart** [comment]
https://github.com/OCA/OpenUpgrade/blob/8.0/addons/procurement/migrations/8.0.1.0/pre-migration.py#L31 (applied in line 51) is supposed to rename product_template's supply_method to its legacy name.

**Comment by JordiBForgeFlow** [comment]
Thanks @StefanRijnhart. Not sure then why did the error appear. Will need to see the full log, to make sure that the pre-migration script for procurement was run correctly

**Comment by JordiBForgeFlow** [comment]
Finally resolved the problem. Not an issue anymore.
