### ISSUE TITLE
Error migrating from 7 to 8

### ISSUE THREAD

**Issue by dhecar** [OCA/OpenUpgrade#495]
Hello, i'm triying to migrate database with data (copy of production for testing the migration.

the conf for Openupgrade have the addons for Openupgrade and all the other addons i have in the original db, like: 

addons_path=/opt/odoo8/OpenUpgrade/addons,/opt/odoo8/custom8/MOTOSCOOT_V8,/opt/odoo8/custom8/l10n-spain,/opt/odoo8/custom8/odoomrp-wip,/opt/odoo8/custom8/odoomrp-utils,/opt/odoo8/custom8/web,/opt/odoo8/custom8/account-fiscal-rule,/opt/odoo8/custom8/account-financial-tools,/opt/odoo8/custom8/account-invoice-reporting,/opt/odoo8/custom8/account-invoicing,/opt/odoo8/custom8/account-payment,/opt/odoo8/custom8/bank-statement-import,/opt/odoo8/custom8/bank-statement-reconcile,/opt/odoo8/custom8/carrier-delivery,/opt/odoo8/custom8/connector,/opt/odoo8/custom8/connector-magento,/opt/odoo8/custom8/connector-ecommerce,/opt/odoo8/custom8/sale-workflow,/opt/odoo8/custom8/connector-telephony,/opt/odoo8/custom8/crm,/opt/odoo8/custom8/e-commerce,/opt/odoo8/custom8/hr,/opt/odoo8/custom8/partner-contact,/opt/odoo8/custom8/pos,/opt/odoo8/custom8/product-attribute,/opt/odoo8/custom8/purchase-workflow,/opt/odoo8/custom8/report-print-send,/opt/odoo8/custom8/rma,/opt/odoo8/custom8/sale-reporting,/opt/odoo8/custom8/server-tools,/opt/odoo8/custom8/stock-logistics-barcode,/opt/odoo8/custom8/stock-logistics-reporting,/opt/odoo8/custom8/stock-logistics-reporting,/opt/odoo8/custom8/stock-logistics-tracking,/opt/odoo8/custom8/stock-logistics-transport,/opt/odoo8/custom8/stock-logistics-warehouse,/opt/odoo8/custom8/stock-logistics-workflow,/opt/odoo8/custom8/webkit-tools,/opt/odoo8/custom8/extras

(I don't kbow If it's the correct way)

The migration stop with this error:

2016-05-02 17:33:55,471 12808 DEBUG MOTOSCOOT2015 OpenUpgrade: 100960 rows affected
2016-05-02 17:33:55,908 12808 WARNING MOTOSCOOT2015 OpenUpgrade: Module stock, table stock_move, column state: Reprocess 79782 stock moves in state done to fill stock.quant
2016-05-02 22:15:49,662 12808 ERROR MOTOSCOOT2015 openerp.sql_db: bad query: INSERT INTO "stock_move" ("id", "origin", "product_uos_qty", "product_uom", "price_unit", "product_uom_qty", "procure_method", "product_uos", "partner_id", "priority", "picking_type_id", "location_id", "company_id", "note", "state", "product_packaging", "date_expected", "procurement_id", "warehouse_id", "inventory_id", "partially_available", "propagate", "restrict_partner_id", "date", "restrict_lot_id", "group_id", "name", "rule_id", "product_id", "location_dest_id", "push_rule_id", "picking_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('stock_move_id_seq'), '/', '1.000', 1, 0.0, '1.000', 'make_to_stock', NULL, 1, '1', 3, 24, NULL, NULL, 'draft', NULL, '2016-03-22 14:33:05', NULL, 1, NULL, false, true, NULL, '2016-03-22 14:33:05', NULL, NULL, '[MS-Sticker] Pegatina Motoscoot.net', NULL, 2694, 19, 4, NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo8/OpenUpgrade/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "company_id" violates not-null constraint

2016-05-02 22:15:49,663 12808 ERROR MOTOSCOOT2015 OpenUpgrade: stock: error in migration script /opt/odoo8/OpenUpgrade/addons/stock/migrations/8.0.1.1/post-migration.py: null value in column "company_id" violates not-null constraint

2016-05-02 22:15:49,663 12808 ERROR MOTOSCOOT2015 OpenUpgrade: null value in column "company_id" violates not-null constraint
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.1.1-py2.7.egg/openupgradelib/openupgrade.py", line 948, in wrapped_function
    func(cr, version)
  File "/opt/odoo8/OpenUpgrade/addons/stock/migrations/8.0.1.1/post-migration.py", line 875, in migrate
    migrate_stock_qty(cr, registry)
  File "/opt/odoo8/OpenUpgrade/addons/stock/migrations/8.0.1.1/post-migration.py", line 743, in migrate_stock_qty
    move.action_done()
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/opt/odoo8/OpenUpgrade/addons/stock/stock.py", line 2437, in action_done
    ids = self.action_confirm(cr, uid, todo, context=context)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/addons/stock/stock.py", line 2270, in action_confirm
    self._push_apply(cr, uid, moves, context=context)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/addons/stock/stock.py", line 1970, in _push_apply
    push_obj._apply(cr, uid, rule, move, context=context)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/addons/stock/stock.py", line 3853, in _apply
    move_id = move_obj.copy(cr, uid, move.id, vals, context=context)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/openerp/models.py", line 4920, in copy
    new_id = self.create(cr, uid, data, context)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/addons/stock/stock.py", line 1991, in create
    res = super(stock_move, self).create(cr, uid, vals, context=context)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo8/custom8/connector/connector/producer.py", line 48, in create
    record_id = create_original(self, vals)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/openerp/models.py", line 4135, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/odoo8/OpenUpgrade/openerp/models.py", line 4273, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo8/OpenUpgrade/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo8/OpenUpgrade/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "company_id" violates not-null constraint

2016-05-02 22:15:49,664 12808 ERROR MOTOSCOOT2015 openerp.modules.loading: Error executing post migration script for module stock
`-> crm_rma_location
: null value in column "company_id" violates not-null constrain

The original db doesn't have crm_rma_location module but it seems thet  Openupgrade try to install the module, in fact all this modules have marked to install:

"crm_claim_code"
"crm_claim_type"
"sale_procurement_group_by_line"
"sale_payment_method_automatic_workflow"
"crm_claim_rma_code"
"stock_account"
"crm_rma_location"

Is this an error or aproblem with my configuration or steps ?

Thanks

**Comment by hbrunn** [comment]
the line numbers mentioned in the backtrace don't match https://github.com/OCA/OpenUpgrade/blob/8.0/addons/stock/migrations/8.0.1.1/post-migration.py, so you run outdated code. Update your code and reopen this issue if the problem persists.
