### ISSUE TITLE
Error migration openerp7 -> odoo8

### ISSUE THREAD

**Issue by mlpgmy** [OCA/OpenUpgrade#501]
I am trying use the project to migration odoo8.
But i get the following error:
2016-05-18 11:48:42,929 690 WARNING test_migrated OpenUpgrade: Module procurement, table procurement_order, column state: In this database, 4 procurements are in draft state. In Odoo 8.0, these procurements cannot be processed further.
2016-05-18 11:48:42,930 690 INFO test_migrated OpenUpgrade: procurement: loading migrations/8.0.1.0/noupdate_changes.xml
2016-05-18 11:48:43,043 690 INFO test_migrated openerp.modules.migration: module account: Running migration [>8.0.1.1] pre-migration
2016-05-18 11:48:43,043 690 INFO test_migrated openerp.modules.migration: module account: Running migration [>8.0.1.1] pre-migration
2016-05-18 11:48:43,044 690 INFO test_migrated OpenUpgrade: account: pre-migration script called with version 7.0.1.1
2016-05-18 11:48:43,046 690 INFO test_migrated OpenUpgrade: table account_bank_statement_line, column analytic_account_id: renaming to openupgrade_legacy_8_0_analytic_account_id
2016-05-18 11:48:43,046 690 INFO test_migrated OpenUpgrade: table account_bank_statement_line, column type: renaming to openupgrade_legacy_8_0_type
2016-05-18 11:48:43,047 690 INFO test_migrated OpenUpgrade: table account_bank_statement_line, column account_id: renaming to openupgrade_legacy_8_0_account_id
2016-05-18 11:48:43,047 690 INFO test_migrated OpenUpgrade: table account_bank_statement_line_move_rel: renaming to bak_account_bank_statement_line_move_rel
2016-05-18 11:48:43,057 690 DEBUG test_migrated OpenUpgrade: Running 
        UPDATE account_invoice_line ail
        SET partner_id=ai.partner_id
        FROM account_invoice ai
        WHERE
            ail.invoice_id = ai.id AND
            ail.partner_id != ai.partner_id;

2016-05-18 11:48:43,057 690 DEBUG test_migrated OpenUpgrade: 4 rows affected
2016-05-18 11:48:43,808 690 INFO test_migrated openerp.modules.module: module account: creating or updating database tables
2016-05-18 11:48:44,056 690 INFO test_migrated openerp.models: Moving XMLID for ir.model.fields record of res.company#expense_currency_exchange_account_id from account_voucher to account
2016-05-18 11:48:44,057 690 INFO test_migrated openerp.models: Moving XMLID for ir.model.fields record of res.company#income_currency_exchange_account_id from account_voucher to account
2016-05-18 11:48:47,132 690 INFO test_migrated openerp.models: Moving XMLID for ir.model.fields record of account.statement.from.invoice.lines#line_ids from account_voucher to account
2016-05-18 11:48:47,521 690 INFO test_migrated openerp.models: Moving XMLID for ir.model.fields record of account.config.settings#expense_currency_exchange_account_id from account_voucher to account
2016-05-18 11:48:47,522 690 INFO test_migrated openerp.models: Moving XMLID for ir.model.fields record of account.config.settings#income_currency_exchange_account_id from account_voucher to account
2016-05-18 11:48:47,606 690 ERROR test_migrated openerp.sql_db: bad query: ALTER TABLE "account_move" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner" ON DELETE set null
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "account_move" violates foreign key constraint "account_move_partner_id_fkey"
DETAIL:  Key (partner_id)=(672) is not present in table "res_partner".

2016-05-18 11:48:47,609 690 CRITICAL test_migrated openerp.service.server: Failed to initialize database `test_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 179, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/module.py", line 293, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 2751, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "account_move" violates foreign key constraint "account_move_partner_id_fkey"
DETAIL:  Key (partner_id)=(672) is not present in table "res_partner".

2016-05-18 11:48:47,611 690 INFO test_migrated openerp.service.server: Initiating shutdown
2016-05-18 11:48:47,611 690 INFO test_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by pedrobaeza** [comment]
This is something of your DB, that doesn't have the information consistent. You have to fix these inconsistencies by yourself.

**Comment by mlpgmy** [comment]
Means I need to fix these inconsistencies in odoo8 db?
Are the migration consider success?

**Comment by pedrobaeza** [comment]
No, you have to fixed them on v7. And no, the migration is not done, because it has been interrupted by the error.

**Comment by mlpgmy** [comment]
Sorry, I am new here. 
Do you have sample guide for me to fix these inconsistencies?

**Comment by pedrobaeza** [comment]
I'm afraid not. You are on your own there.

**Comment by mlpgmy** [comment]
Sorry as I am new. 
It must fix in the openerp7 or I can use the psql ?
If from psql, can let me know what the command I may use it?

**Comment by StefanRijnhart** [comment]
```
IntegrityError: insert or update on table "account_move" violates foreign key constraint "account_move_partner_id_fkey"
DETAIL: Key (partner_id)=(672) is not present in table "res_partner".
```

The error means that there are mentionings of a partner with id 672 in the account_move table, but there is no entry in res_partner with this id. You can simply wipe the value in the account_move table, but I would investigate further to check how this could have happened and if there are more inconsistencies like this.
