### ISSUE TITLE
Error on 9.0 migration account_cashbox_line

### ISSUE THREAD

**Issue by ToBeReplaced** [OCA/OpenUpgrade#543]
My migration from 8 to 9 is failing at:
https://github.com/OCA/OpenUpgrade/blob/9.0/addons/account/migrations/9.0.1.1/post-migration.py#L190

```
    # assign those to the cashbox lines they derive from
    cr.execute(
        'update account_cashbox_line l set cashbox_id='
        '(select id from account_bank_statement_cashbox where l.id='
        'any(%(cashbox_line_ids)s))' % {
            'cashbox_line_ids': openupgrade.get_legacy_name('cashbox_line_ids')
        }
    )
```

The error is:

```
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/service/server.py", line 885, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 389, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 404, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 296, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 189, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/migration.py", line 160, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 998, in wrapped_function
    func(cr, version)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 294, in migrate
    cashbox(cr)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 195, in cashbox
    'cashbox_line_ids': openupgrade.get_legacy_name('cashbox_line_ids')
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
ProgrammingError: more than one row returned by a subquery used as an expression
```

It's a little tricky for me to see what is going on because this is referencing tables in the post-migration step (so they don't exist after rollback). It looks like the whole query fails if there is more than one cashbox? Any recommendations?

**Comment by hbrunn** [comment]
in https://github.com/OCA/OpenUpgrade/blob/9.0/addons/account/migrations/9.0.1.1/post-migration.py#L176, replace `s.id` with `l.id` and file a PR with this change here
