### ISSUE TITLE
[9.0][sale] Fails to migrate during computation of invoice_qty

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#629]
During the migration of the sale module the following error stops the process:

2016-08-22 20:17:27,151 25807 CRITICAL ao_odoo_test openerp.service.server: Failed to initialize database `ao_odoo_test`.
Traceback (most recent call last):
  File "/opt/openupgrade9/parts/odoo9/openerp/service/server.py", line 892, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/loading.py", line 406, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/loading.py", line 297, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/loading.py", line 160, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/module.py", line 317, in init_module_models
    obj_list[0].recompute(cr, openerp.SUPERUSER_ID, {})
  File "/opt/openupgrade9/parts/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openupgrade9/parts/odoo9/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/openupgrade9/parts/odoo9/openerp/models.py", line 5907, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/opt/openupgrade9/parts/odoo9/openerp/models.py", line 5907, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/opt/openupgrade9/parts/odoo9/openerp/models.py", line 5794, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/openupgrade9/parts/odoo9/openerp/fields.py", line 830, in **get**
    self.determine_value(record)
  File "/opt/openupgrade9/parts/odoo9/openerp/fields.py", line 912, in determine_value
    self.compute_value(recs)
  File "/opt/openupgrade9/parts/odoo9/openerp/fields.py", line 892, in compute_value
    self._compute_value(records)
  File "/opt/openupgrade9/parts/odoo9/openerp/fields.py", line 882, in _compute_value
    getattr(records, self.compute)()
  File "/opt/openupgrade9/parts/odoo9/addons/sale/sale.py", line 538, in _get_invoice_qty
    qty_invoiced += self.env['product.uom']._compute_qty_obj(invoice_line.uom_id, invoice_line.quantity, line.product_uom)
  File "/opt/openupgrade9/parts/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openupgrade9/parts/odoo9/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/openupgrade9/parts/odoo9/addons/product/product.py", line 122, in _compute_qty_obj
    raise UserError(_('Conversion from Product UoM %s to Default UoM %s is not possible as they both belong to different Category!.') % (from_unit.name,to_unit.name))
UserError: (u'Conversion from Product UoM False to Default UoM PCE is not possible as they both belong to different Category!.', None)

The error is caused because an invoice line has a Null UoM, and it is trying to convert to the sales order line UoM that originated this invoice line.

Querying to the original v8 database, to table sale_order_line_invoice_rel, I can see no invoice line with empty UoM, linked to a sales order line with UoM.

The query:
SELECT *
FROM sale_order_line_invoice_rel as rel
inner join sale_order_line as sol
on sol.id = rel.order_line_id
inner join account_invoice_line ail
on ail.id = rel.invoice_id
where ail.uos_id is null
and sol.product_uom is not null;

, returns 0 records in the original v8 DB.

Running the equivalent query in the partially migrated DB:
SELECT count(*)
FROM sale_order_line_invoice_rel as rel
inner join sale_order_line as sol
on sol.id = rel.order_line_id
inner join account_invoice_line ail
on ail.id = rel.invoice_id
where ail.uom_id is null
and sol.product_uom is not null;

, returns 108190 records found.

I found that querying the partially migrated database, after the error terminated the migration process, running the following query:
select count(*) from account_invoice_line where uom_id is null
, results in 143988 records found

If I run the same query in the original v8 DB: 
select count(*) from account_invoice_line where uos_id is null
, results in 306 records found.

Seems as if the uos_id column in account_invoice_line was being nullified during the migration. Perhaps in the conversion to uom_id? I tried to map uos_id to uom_id during pre-migration in account module, with the same result.

**Comment by JordiBForgeFlow** [comment]
Now closing this issue. Was a bad update SQL query executed before starting the migration process.
