### ISSUE TITLE
[9.0] Error when trying to Purge obsolete modules

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#639]
Impacted versions: 9.0

Steps to reproduce:
Migrate a DB from 8.0 to 9.0 and, using module 'database_cleanup', start the menu "Purge obsolete modules'.

Current behavior:

```
Traceback (most recent call last):
  File "/opt/odoo9/parts/odoo9/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo9/parts/odoo9/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo9/parts/odoo9/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo9/parts/odoo9/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo9/parts/odoo9/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo9/parts/odoo9/addons/web/controllers/main.py", line 1157, in run
    [action_id], request.context)
  File "/opt/odoo9/parts/odoo9/openerp/http.py", line 1069, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/addons/base/ir/ir_actions.py", line 1084, in run
    res = func(cr, uid, action, eval_context=eval_context, context=run_context)
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/addons/base/ir/ir_actions.py", line 910, in run_action_code_multi
    eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo9/parts/odoo9/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo9/parts/server-tools9/database_cleanup/models/purge_wizard.py", line 56, in get_wizard_action
    wizard = self.create({})
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/parts/server-tools9/database_cleanup/models/purge_wizard.py", line 92, in create
    return super(PurgeWizard, self).create(values)
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/models.py", line 4137, in create
    vals = self._add_missing_default_values(vals)
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/models.py", line 1775, in _add_missing_default_values
    defaults = self.default_get(cr, uid, list(missing_defaults), context)
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo9/parts/server-tools9/database_cleanup/models/purge_wizard.py", line 42, in default_get
    res['purge_line_ids'] = self.find()
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/parts/server-tools9/database_cleanup/models/purge_modules.py", line 73, in find
    'name': module.name,
  File "/opt/odoo9/parts/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/parts/server-tools9/database_cleanup/models/purge_modules.py", line 55, in purge
    RegistryManager.new(self.env.cr.dbname, update_module=True)
  File "/opt/odoo9/parts/odoo9/openerp/modules/registry.py", line 389, in new
    del cls.registries[db_name]
  File "/opt/odoo9/parts/odoo9/openerp/tools/func.py", line 60, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo9/parts/odoo9/openerp/tools/lru.py", line 72, in __delitem__
    nobj = self.d[obj]
ValueError: "odoo" while evaluating
u'action = self.get_wizard_action(cr, uid, context=context)'
```

Expected behavior:
No error

**Comment by hbrunn** [comment]
this is a database_cleanup issue, not an openupgrade one. Please open your issue there. But pull first, I added a couple of fixes for this module lately which have been merged already
