### ISSUE TITLE
[9.0 ->10.0] Migrating from Odoo 9 to 10 fails with error msg: column "store" of relation "ir_model_fields" does not exist

### ISSUE THREAD

**Issue by balapal** [OCA/OpenUpgrade#662]
**Impacted versions:** 
When running https://github.com/OCA/OpenUpgrade/blob/10.0/scripts/migrate.py
(commit sha: 32c2dc2a1ee4dbf3d1811d64495b87e3e71a456d)

## Steps to reproduce:
Upgrading from Odoo 9.0c-20160620 to 10.0 when running:
`python migrate.py --config=/opt/bitnami/apps/odoo/conf/openerp-server.conf --run-migrations=10.0`

## Current behavior:

**Std output content:**
```
From git://github.com/OpenUpgrade/OpenUpgrade
 * branch            10.0       -> FETCH_HEAD
Already up-to-date.
git-remote-https: /opt/bitnami/common/lib/libldap_r-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
git-remote-https: /opt/bitnami/common/lib/liblber-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
From https://github.com/OCA/openupgradelib
 * branch            master     -> FETCH_HEAD
Already up-to-date.
copying database bitnami_openerp to bitnami_openerp_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
running migration for 10.0
/opt/bitnami/python/lib/python2.7/site-packages/setuptools-20.9.0-py2.7.egg/pkg_resources/__init__.py:1268: UserWarning: /opt/bitnami/.tmp is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Running as user 'root' is a security risk.
```

**Log file content:** /var/tmp/openupgrade/migration.log
```
2016-11-13 21:37:23,592 1617 INFO ? odoo: Odoo version 10.0
2016-11-13 21:37:23,592 1617 INFO ? odoo: Using configuration file at /var/tmp/openupgrade/10.0/server.cfg
2016-11-13 21:37:23,592 1617 INFO ? odoo: addons paths: ['/opt/bitnami/apps/odoo/data/addons/10.0', u'/var/tmp/openupgrade/10.0/server/odoo/addons', u'/var/tmp/openupgrade/10.0/addons']
2016-11-13 21:37:23,592 1617 INFO ? odoo: database: bn_openerp@127.0.0.1:5432
2016-11-13 21:37:23,650 1617 INFO bitnami_openerp_migrated odoo.modules.loading: loading 1 modules...
2016-11-13 21:37:23,887 1617 INFO bitnami_openerp_migrated odoo.modules.registry: module base: creating or updating database tables
2016-11-13 21:37:23,893 1617 INFO bitnami_openerp_migrated odoo.sql_db: bad query: INSERT INTO ir_model_fields (serialization_field_id,model_id,translate,name,index,required,related,relation_table,readonly,column2,relation,store,relation_field,ttype,model,copy,column1,selectable,field_description,help) VALUES (NULL,176,false,'display_name',false,false,NULL,NULL,true,NULL,NULL,false,NULL,'char','base',false,NULL,false,'Display Name',NULL) RETURNING id
2016-11-13 21:37:23,894 1617 ERROR bitnami_openerp_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 341, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 161, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 315, in init_models
    model._auto_init()
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 2358, in _auto_init
    self._field_create()
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 388, in _field_create
    cr.execute(query, vals)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "store" of relation "ir_model_fields" does not exist
LINE 1: ...,related,relation_table,readonly,column2,relation,store,rela...
                                                             ^

2016-11-13 21:37:23,898 1617 CRITICAL bitnami_openerp_migrated odoo.service.server: Failed to initialize database `bitnami_openerp_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/service/server.py", line 898, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 341, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 161, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 315, in init_models
    model._auto_init()
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 2358, in _auto_init
    self._field_create()
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 388, in _field_create
    cr.execute(query, vals)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "store" of relation "ir_model_fields" does not exist
LINE 1: ...,related,relation_table,readonly,column2,relation,store,rela...
                                                             ^

2016-11-13 21:37:23,899 1617 INFO bitnami_openerp_migrated odoo.service.server: Initiating shutdown
2016-11-13 21:37:23,899 1617 INFO bitnami_openerp_migrated odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```

## Expected behavior:
Migration from 9.0 to 10.0 successfully finishes.

**Comment by balapal** [comment]
1. By comparing the below two sql files I can see that the column called store has been added 10.0 
2. What I also noticed that the directory has been renamed from openerp to odoo. Not sure if it has anything to do with the failure, though.

https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/base.sql
vs
https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/base.sql

**Comment by balapal** [comment]
I can see 8.0->9.0 script on 9.0 branch to add columns to `ir_model_fields` table: https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/openupgrade/openupgrade_loading_90.py

For 10.0 at https://github.com/OCA/OpenUpgrade/tree/10.0/odoo/openupgrade I don't see such script.
I guess we need to create a script that adds the missing columns to `ir_model_fields`.

**Comment by pedrobaeza** [comment]
This migration is not yet available.

**Comment by daudakhtar** [comment]
Hey!!!! I have also the same issue, whenever i migrate 9 to 10. have any idea about that???

===========ERROR============
Failed, fallback on creating empty database + loading a dump
running migration for 10.0
Could not upgrade to version 10.0
===========ERROR============

**Comment by sebastienhasa** [comment]
@daudakhtar, @balapal, I added the column manually in the database with this:
``` sql
ALTER TABLE ir_model_fields
	ADD store BOOL;
```
