### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by vijaypatil091** [OCA/OpenUpgrade#665]
Impacted versions: 9.0

Steps to reproduce: run migrate.py file.

Current behavior: ValueError: need more than 1 value to unpack

Expected behavior: No Error

Video/Screenshot link (optional): 

I am trying to migrate from V8 to V9.

Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp-server", line 5, in <module>
    openerp.cli.main()
  File "/var/tmp/openupgrade/9.0/server/openerp/cli/command.py", line 64, in main
    o.run(args)
  File "/var/tmp/openupgrade/9.0/server/openerp/cli/server.py", line 168, in run
    main(args)
  File "/var/tmp/openupgrade/9.0/server/openerp/cli/server.py", line 120, in main
    openerp.tools.config.parse_config(args)
  File "/var/tmp/openupgrade/9.0/server/openerp/tools/config.py", line 307, in parse_config
    openerp.netsvc.init_logger()
  File "/var/tmp/openupgrade/9.0/server/openerp/netsvc.py", line 189, in init_logger
    loggername, level = logconfig_item.split(':')
ValueError: need more than 1 value to unpack

**Comment by vijaypatil091** [comment]
Hi Folks,

Issue sorted. Few parameters from configuration files were misplaced. Thanks.
