### ISSUE TITLE
[9.0] Mail module : "mail_channel_partner" is not present in the migrated table

### ISSUE THREAD

**Issue by E-HO** [OCA/OpenUpgrade#673]
Hi,

It seems to have an issue when upgrading from version 8 to 9 with mail addons. 
The problem is that the table "mail_channel_partner" is not present in the migrated table. Here is the error log.

> 2016-11-24 14:40:00,978 30817 INFO table_migrated OpenUpgrade: bus: pre-migration script called with version 8.0.1.0
2016-11-24 14:40:20,281 30817 INFO table_migrated OpenUpgrade: mail: pre-migration script called with version 8.0.1.0
2016-11-24 14:40:20,282 30817 INFO table_migrated OpenUpgrade: model mail.group: renaming to mail.channel
2016-11-24 14:40:20,587 30817 INFO table_migrated OpenUpgrade: model email.template: renaming to mail.template
2016-11-24 14:40:20,700 30817 INFO table_migrated OpenUpgrade: table mail_group: renaming to mail_channel
2016-11-24 14:40:20,701 30817 INFO table_migrated OpenUpgrade: table email_template: renaming to mail_template
2016-11-24 14:40:20,712 30817 INFO table_migrated OpenUpgrade: table mail_group_res_group_rel: renaming to mail_channel_res_group_rel
2016-11-24 14:40:20,712 30817 INFO table_migrated OpenUpgrade: table mail_group_id_seq: renaming to mail_channel_id_seq
2016-11-24 14:40:20,713 30817 INFO table_migrated OpenUpgrade: table email_template_id_seq: renaming to mail_template_id_seq
2016-11-24 14:40:20,713 30817 INFO table_migrated OpenUpgrade: table mail_channel_res_group_rel, column mail_group_id: renaming to mail_channel_id
2016-11-24 14:40:49,179 30817 INFO table_migrated OpenUpgrade: mail: post-migration script called with version 8.0.1.0
2016-11-24 14:40:49,181 30817 INFO table_migrated openerp.sql_db: bad query: 
    INSERT INTO mail_channel_partner (channel_id, partner_id)
    SELECT res_id, partner_id from mail_followers
    WHERE res_model = 'mail.channel'
    

> 2016-11-24 14:40:49,181 30817 ERROR table_migrated OpenUpgrade: mail: error in migration script /var/tmp/openupgrade/9.0/addons/mail/migrations/9.0.1.0/post-migration.py: insert or update on table "mail_channel_partner" violates foreign key constraint "mail_channel_partner_channel_id_fkey"
DETAIL:  Key (channel_id)=(3) is not present in table "mail_channel".

> 2016-11-24 14:40:49,181 30817 ERROR table_migrated OpenUpgrade: insert or update on table "mail_channel_partner" violates foreign key constraint "mail_channel_partner_channel_id_fkey"
DETAIL:  Key (channel_id)=(3) is not present in table "mail_channel".
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1087, in wrapped_function
    version)
  File "/var/tmp/openupgrade/9.0/addons/mail/migrations/9.0.1.0/post-migration.py", line 32, in migrate
    """)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "mail_channel_partner" violates foreign key constraint "mail_channel_partner_channel_id_fkey"
DETAIL:  Key (channel_id)=(3) is not present in table "mail_channel".

> 2016-11-24 14:40:49,204 30817 ERROR table_migrated openerp.modules.loading: Error executing post migration script for module mail
`-> analytic
   `-> account
      `-> account_accountant
      `-> account_bank_statement_import
      `-> account_cancel
      `-> account_full_reconcile
      `-> account_voucher
      `-> base_iban
      `-> base_vat
      `-> l10n_be_invoice_bba
      `-> l10n_multilang
         `-> l10n_be
      `-> payment
         `-> payment_transfer
         `-> portal_sale
`-> auth_signup
   `-> portal
`-> base_action_rule
   `-> calendar
      `-> crm
         `-> crm_partner_assign
         `-> sale_crm
`-> fetchmail
`-> im_odoo_support
`-> note
`-> product
   `-> procurement
      `-> sale
         `-> mrp_repair
      `-> stock
         `-> stock_account
            `-> mrp
            `-> purchase
            `-> sale_stock
               `-> delivery
               `-> point_of_sale
               `-> portal_stock
               `-> procurement_jit
               `-> sale_mrp
`-> sales_team
`-> share
: insert or update on table "mail_channel_partner" violates foreign key constraint "mail_channel_partner_channel_id_fkey"
DETAIL:  Key (channel_id)=(3) is not present in table "mail_channel".

@

**Comment by hbrunn** [comment]
sounds a lot like https://github.com/OCA/OpenUpgrade/issues/658, the solution should be the same

**Comment by E-HO** [comment]
In fact the script seems to go further by removing "mail.group'.

It is not a good idea to directly add a removing feature in the sources ?

**Comment by hbrunn** [comment]
first we need to know if this is actually your problem. is it?

and yes, it *renames* `mail.group` to `mail.channel`, because the's the best functional equivalent

**Comment by E-HO** [comment]
I mean adding a line to remove mail.group during the upgrade script to avoid this error with : 

> DELETE from mail_followers WHERE res_model = 'mail.group'

With that, it seems to work : before, the scripts was stopped, and now it continues with account upgrade (who sould take time).

**Comment by pedrobaeza** [comment]
Why not better to update the mail_followers table pointing to the new model name?

**Comment by hbrunn** [comment]
that's fixed by https://github.com/OCA/openupgradelib/pull/48 in the meantime
