### ISSUE TITLE
Crash in migration of vouchers to payments - I will try to provide fix

### ISSUE THREAD

**Issue by NL66278** [OCA/OpenUpgrade#707]
Impacted versions: 8.0 to 9.0

Steps to reproduce:

Run migration with large dataset containing vouchers. Not yet certain about what data causes crash.

Current behavior: Migration crashes

Expected behavior: migration runs without problems

Video/Screenshot link (optional):

2016-12-22 06:55:40,920 7461 INFO odottrtst90_migrated openerp.modules.migration: module account_voucher: Running migration [9.0.1.0>] post-migration
2016-12-22 06:55:40,921 7461 INFO odottrtst90_migrated OpenUpgrade: account_voucher: post-migration script called with version 8.0.1.0
2016-12-22 06:55:44,975 7461 INFO odottrtst90_migrated openerp.sql_db: Programming error: more than one row returned by a subquery used as an expression
, in query         UPDATE account_move_line aml
        SET payment_id = (
            SELECT av.id
            FROM account_voucher_line avl
            JOIN account_voucher av ON av.id = avl.voucher_id
            WHERE avl.move_line_id = aml.id
        )
        WHERE aml.id IN (
            SELECT avl.move_line_id
            FROM account_voucher_line avl
            JOIN account_voucher av ON av.id = avl.voucher_id
            WHERE av.voucher_type IN ('receipt', 'payment')
              AND NOT avl.move_line_id IS NULL
              AND NOT av.move_id IS NULL
        )
        
2016-12-22 06:55:44,975 7461 ERROR odottrtst90_migrated OpenUpgrade: account_voucher: error in migration script /var/tmp/openupgrade_nl66278/9.0/addons/account_voucher/migrations/9.0.1.0/post-migration.py: more than one row returned by a subquery used as an expression

2016-12-22 06:55:44,975 7461 ERROR odottrtst90_migrated OpenUpgrade: more than one row returned by a subquery used as an expression
Traceback (most recent call last):
  File "/var/tmp/openupgrade_nl66278/openupgradelib/openupgradelib/openupgrade.py", line 1087, in wrapped_function
    version)
  File "/var/tmp/openupgrade_nl66278/9.0/addons/account_voucher/migrations/9.0.1.0/post-migration.py", line 103, in migrate
    create_payments_from_vouchers(env)
  File "/var/tmp/openupgrade_nl66278/9.0/addons/account_voucher/migrations/9.0.1.0/post-migration.py", line 85, in create_payments_from_vouchers
    """
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: more than one row returned by a subquery used as an expression

2016-12-22 06:55:44,976 7461 ERROR odottrtst90_migrated openerp.modules.loading: Error executing post migration script for module account_voucher
: more than one row returned by a subquery used as an expression

2016-12-22 06:55:44,978 7461 ERROR odottrtst90_migrated openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/loading.py", line 406, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/loading.py", line 297, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/loading.py", line 189, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/migration.py", line 160, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade_nl66278/openupgradelib/openupgradelib/openupgrade.py", line 1087, in wrapped_function
    version)
  File "/var/tmp/openupgrade_nl66278/9.0/addons/account_voucher/migrations/9.0.1.0/post-migration.py", line 103, in migrate
    create_payments_from_vouchers(env)
  File "/var/tmp/openupgrade_nl66278/9.0/addons/account_voucher/migrations/9.0.1.0/post-migration.py", line 85, in create_payments_from_vouchers
    """
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: more than one row returned by a subquery used as an expression

2016-12-22 06:55:44,979 7461 CRITICAL odottrtst90_migrated openerp.service.server: Failed to initialize database `odottrtst90_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/service/server.py", line 892, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/loading.py", line 406, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/loading.py", line 297, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/loading.py", line 189, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/modules/migration.py", line 160, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade_nl66278/openupgradelib/openupgradelib/openupgrade.py", line 1087, in wrapped_function
    version)
  File "/var/tmp/openupgrade_nl66278/9.0/addons/account_voucher/migrations/9.0.1.0/post-migration.py", line 103, in migrate
    create_payments_from_vouchers(env)
  File "/var/tmp/openupgrade_nl66278/9.0/addons/account_voucher/migrations/9.0.1.0/post-migration.py", line 85, in create_payments_from_vouchers
    """
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade_nl66278/9.0/server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: more than one row returned by a subquery used as an expression

2016-12-22 06:55:44,979 7461 INFO odottrtst90_migrated openerp.service.server: Stopping gracefully

**Comment by NL66278** [comment]
Closing as invalid. I was working on older branch. Issue was solved by commit 4fae0fb7.
