### ISSUE TITLE
when installing account_tax_python, we should also patch the dependency graph to have sale and purchase depend on it

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#716]
Impacted versions: v8->v9

Current behavior:

When executing a migration from v8 to v9 I'm getting an error while the compute of the fields of sale.order.line is in progress. See log below. The error is probably due to bad data, but how can I trace the specific record that is wrong?
```
2016-12-27 22:55:47,711 23485 CRITICAL ao_odoo_20161219_9 openerp.service.server: Failed to initialize database `ao_odoo_20161219_9`.
Traceback (most recent call last):
  File "/opt/openupgrade9/parts/odoo9/openerp/service/server.py", line 892, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/loading.py", line 406, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/loading.py", line 297, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/loading.py", line 160, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/opt/openupgrade9/parts/odoo9/openerp/modules/module.py", line 317, in init_module_models
    obj_list[0].recompute(cr, openerp.SUPERUSER_ID, {})
  File "/opt/openupgrade9/parts/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/openupgrade9/parts/odoo9/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/openupgrade9/parts/odoo9/openerp/models.py", line 5907, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/opt/openupgrade9/parts/odoo9/openerp/models.py", line 5907, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/opt/openupgrade9/parts/odoo9/openerp/models.py", line 5794, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/openupgrade9/parts/odoo9/openerp/fields.py", line 830, in __get__
    self.determine_value(record)
  File "/opt/openupgrade9/parts/odoo9/openerp/fields.py", line 912, in determine_value
    self.compute_value(recs)
  File "/opt/openupgrade9/parts/odoo9/openerp/fields.py", line 892, in compute_value
    self._compute_value(records)
  File "/opt/openupgrade9/parts/odoo9/openerp/fields.py", line 882, in _compute_value
    getattr(records, self.compute)()
  File "/opt/openupgrade9/parts/odoo9/addons/sale/sale.py", line 498, in _compute_amount
    taxes = line.tax_id.compute_all(price, line.order_id.currency_id, line.product_uom_qty, product=line.product_id, partner=line.order_id.partner_id)
  File "/opt/openupgrade9/parts/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/openupgrade9/parts/odoo9/addons/account/models/account.py", line 685, in compute_all
    tax_amount = currency.round(tax_amount)
  File "/opt/openupgrade9/parts/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/openupgrade9/parts/odoo9/openerp/addons/base/res/res_currency.py", line 110, in round
    return float_round(amount, precision_rounding=self.rounding)
  File "/opt/openupgrade9/parts/odoo9/openerp/tools/float_utils.py", line 52, in float_round
    normalized_value = value / rounding_factor # normalize
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by JordiBForgeFlow** [comment]
@NL66278 @hbrunn Can you help me on this one?

**Comment by hbrunn** [comment]
a quick look on the backtrace lets me assume there's a NULL value in some sale_order_line.product_uom_qty, have you checked this?

**Comment by JordiBForgeFlow** [comment]
yes, I did run SELECT * FROM sale_order_line WHERE product_uom_qty IS NULL, and got 0 results.

**Comment by hbrunn** [comment]
hmmm. Then the only option for this to happen I see is https://github.com/OCA/OCB/blob/9.0/addons/account/models/account.py#L617 returning nothing. Given the conditions are not exhaustive, this seems possible to happen. Did you check all your taxes if one of them produces `None` here?

**Comment by JordiBForgeFlow** [comment]
I found that I have some sales order lines that use a tax code with amount_type = 'code'.

This type is not defined in accounting module (https://github.com/OCA/OCB/blob/9.0/addons/account/models/account.py#L518) but in account_tax_python (https://github.com/OCA/OCB/blob/9.0/addons/account_tax_python/account_tax_python.py#L9).

During the pre-migration of account module we're flagging the `account_tax_python` module to be installed:
https://github.com/OCA/OpenUpgrade/blob/9.0/addons/account/migrations/9.0.1.1/pre-migration.py#L136

But as I realize, by the time `sale` module is being installed, `account_tax_python` is still in status 'to install'.

So, if I could force the `account_tax_python` to be installed BEFORE `sale` module, that would resolve the issue. But how to do that?

**Comment by hbrunn** [comment]
if only somebody thought about this kind of situation and thought up a configuration key that allows us to force dependencies: https://doc.therp.nl/openupgrade/migration_details.html#configuration-options ;-)

**Comment by JordiBForgeFlow** [comment]
ahhhh. That's great! Using Buildout, can I add the parameter `force_deps` in the buildout.cfg file, in a format such as:
`options.force_deps = {'sale': ['account_tax_python'], 'purchase': ['account_tax_python']}`

**Comment by JordiBForgeFlow** [comment]
Answer to self:
With buildout, add `openupgrade.force_deps = {'sale': ['account_tax_python'], 'purchase': ['account_tax_python']}` in the buildout.cfg file.

**Comment by hbrunn** [comment]
nice to hear that helps. I think for correctness, we should inject those dependencies in the dependency graph at the same point where we mark account_tax_python for installation. Should be quite possible, so I'll keep this open for the real fix, this solution is a hack/workaround

**Comment by JordiBForgeFlow** [comment]
Thanks  @hbrunn. Now checking if this resolves the issue.

**Comment by pedrobaeza** [comment]
Is this still relevant?

**Comment by hbrunn** [comment]
yes

**Comment by pedrobaeza** [comment]
OK, waiting for a possible PR for cleaning up issues :wink:

**Comment by pedrobaeza** [comment]
No news with this?

**Comment by pedrobaeza** [comment]
Is this going to be solved?

**Comment by pedrobaeza** [comment]
Closing as no answer.
