### ISSUE TITLE
Upgrade 8 to 9 on debian

### ISSUE THREAD

**Issue by brivalland** [OCA/OpenUpgrade#770]
Dear,
I get a python error using migrate.py.
It looks like a problem with the database access, does anyone have a suggestion ?

Thank you :)

# python migrate.py --config=/etc/odoo/openerp-server.conf --database=mydb--run-migrations=9.0
From git://github.com/OpenUpgrade/OpenUpgrade
 * branch            9.0        -> FETCH_HEAD
Already up-to-date.
From https://github.com/OCA/openupgradelib
 * branch            master     -> FETCH_HEAD
Already up-to-date.
copying database emundus to emundus_migrated...
Traceback (most recent call last):
  File "migrate.py", line 361, in <module>
    db_name = copy_database(conn_parms)
  File "migrate.py", line 25, in copy_database
    conn = psycopg2.connect(**conn_parms)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 167, in connect
    if port is not None and int(port) > 0:
ValueError: invalid literal for int() with base 10: 'False'

**Comment by brivalland** [comment]
Yes, that was a problem with db connection.
I replace 
db_port = false 
to 
db_port = 5432
in /etc/odoo/openerp-server.conf

And now a new problem :

Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 10274; 0 0 COMMENT EXTENSION plpgsql
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension plpgsql
    Command was: COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
