### ISSUE TITLE
Missing "Exchange Rate Journal" (8 -> 9)

### ISSUE THREAD

**Issue by Jerther** [OCA/OpenUpgrade#791]
**Impacted versions**:
9.0

**Steps to reproduce**:
Migrate 8.0 database to 9.0 using this command
`python migrate.py --config=/home/jerther/code/openerp-server.conf --database=backup_2017_04_10 --run-migrations=9.0`

**Current behavior**:
After almost 4 hours, stops with error (see below)

**Expected behavior**:
Upgrade finishes without any error.

**Technical details**:
```
2017-04-11 16:32:48,048 17977 INFO backup_2017_04_10_migrated openerp.models: Actual recompute of field account.invoice.residual_signed for 1 recs.
2017-04-11 16:32:50,265 17977 ERROR backup_2017_04_10_migrated OpenUpgrade: account: error in migration script /var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py: (u"You should configure the 'Exchange Rate Journal' in the accounting settings, to manage automatically the booking of accounting entries related to differences between exchange rates.", None)
2017-04-11 16:32:50,266 17977 ERROR backup_2017_04_10_migrated OpenUpgrade: (u"You should configure the 'Exchange Rate Journal' in the accounting settings, to manage automatically the booking of accounting entries related to differences between exchange rates.", None)
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1112, in wrapped_function
    version)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 458, in migrate
    account_partial_reconcile(env)
  File "/var/tmp/openupgrade/9.0/addons/account/migrations/9.0.1.1/post-migration.py", line 315, in account_partial_reconcile
    move_lines.auto_reconcile_lines()
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 829, in auto_reconcile_lines
    'currency_id': currency,
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 1389, in create
    aml_id, partial_rec_id = partial_rec.create_exchange_rate_entry(aml_to_balance, total_debit - total_credit, total_amount_currency, currency, maxdate)
  File "/var/tmp/openupgrade/9.0/addons/account/models/account_move.py", line 1297, in create_exchange_rate_entry
    raise UserError(_("You should configure the 'Exchange Rate Journal' in the accounting settings, to manage automatically the booking of accounting entries related to differences between exchange rates."))
UserError: (u"You should configure the 'Exchange Rate Journal' in the accounting settings, to manage automatically the booking of accounting entries related to differences between exchange rates.", None)
2017-04-11 16:32:50,639 17977 ERROR backup_2017_04_10_migrated openerp.modules.loading: Error executing post migration script for module account
`-> account_accountant
   `-> account_asset
`-> account_bank_statement_import
`-> account_budget
`-> account_cancel
`-> account_full_reconcile
`-> account_voucher
   `-> account_check_printing
`-> payment
   `-> payment_transfer
   `-> portal_sale
```
It appears the migration is looking for a field named `company_id.currency_exchange_journal_id` but this field was introduced in 9.0 so I can't configure this before the upgrade.

**Comment by Jerther** [comment]
If I uncheck "Allow multiple currencies" in accounting settings, the migration goes all the way. Should I disable this feature before the upgrade and then re-enable it after?

(btw 4 hours was because I ran the upgrade on a remote database. It's 20 minutes when doing it local.)

**Comment by StefanRijnhart** [comment]
The real problem here of course is that you do not want the migration to create a new accounting entry.

I can't really explain how unchecking the multi currency option avoids the problem, because it only makes the currency fields visible on the various forms. But if it does avoid the problem, could you find out which move causes the problem, and then run the migration with the multicurrency option disabled and check the resulting reconcilation afterwards?

**Comment by Jerther** [comment]
We've ended up buying Odoo 10 Enterprise and we're using their upgrade system. I'm so sorry. I still plan on investing the problem though, just for the sake of it. Obviously my priorities have shifted, so it might take a little while before I retry the v9 migration...

**Comment by pedrobaeza** [comment]
As stated, I close this.
