### ISSUE TITLE
Issues migrating hr_evaluation 7.0->8.0

### ISSUE THREAD

**Issue by bwrsandman** [OCA/OpenUpgrade#812]
# Description
Duplicate of #214

# Impacted versions
7.0 -> 8.0

# Steps to reproduce
* Install `hr_evaluation` on a vanilla 7.0 database
* In Human Resources Create an Interview Request only filling `survey_id`

Issue is not present with only survey module installed

# Current behavior

Upgrade fails with:
```
2017-05-10 16:49:12,943 11081 CRITICAL survey7 openerp.service.server: Failed to initialize database `survey7`.
Traceback (most recent call last):
  File "/home/odoo/openupgrade/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/openupgrade/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/openupgrade/openerp/modules/loading.py", line 420, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/home/odoo/openupgrade/openerp/modules/loading.py", line 312, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/home/odoo/openupgrade/openerp/modules/loading.py", line 179, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/odoo/openupgrade/openerp/modules/module.py", line 293, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/home/odoo/openupgrade/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/openupgrade/openerp/models.py", line 2751, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/home/odoo/openupgrade/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/openupgrade/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "hr_evaluation_interview" violates foreign key constraint "hr_evaluation_interview_request_id_fkey"
DETAIL:  Key (request_id)=(1) is not present in table "survey_user_input".
```

# Expected behavior

Migration script should have created `request_id` in the same was as the `hr_evaluation_interview.create()`

OR

Migration script should have migrated `survey_request` to `survey_user_input`

**Comment by bwrsandman** [comment]
Same can be seen with `hr_applicant`

**Comment by pedrobaeza** [comment]
Hey, Sandy!! Have you come back to the Odoo old times?

**Comment by hbrunn** [comment]
wow, welcome back!

**Comment by hbrunn** [comment]
and the answer is simple: Nobody ever wrote a migrations script for this, cf https://github.com/OCA/OpenUpgrade/blame/8.0/openerp/openupgrade/doc/source/modules70-80.rst#L155, https://github.com/OCA/OpenUpgrade/tree/8.0/addons/hr_evaluation/migrations/8.0.0.1

**Comment by bwrsandman** [comment]
Hey guys! No I'm not back to Odoo dev. My company was on 7.0 and we decided to update to 9.0.

As for the migration scripts. We managed to upgrade with #813 and #814.

**Comment by pedrobaeza** [comment]
As there are PRs with the solution, I close the issue.
