### ISSUE TITLE
[9.0] Duplicate key error when generation records for OpenUpgrade Analysis

### ISSUE THREAD

**Issue by NL66278** [OCA/OpenUpgrade#860]
Impacted versions: in any case 9.0

Steps to reproduce: Install openupgrade_records module. Install all modules. Then generate records.

Current behavior: Duplicate key error

Expected behavior: All records are generated

Odoo Server Error

Traceback (most recent call last):
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/service/model.py", line 120, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/http.py", line 312, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/http.py", line 962, in __call__
    return self.method(*args, **kw)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/addons/openupgrade_records/model/generate_records_wizard.py", line 92, in generate
    _db, pool = pooler.restart_pool(cr.dbname, update_module=True)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/pooler.py", line 28, in restart_pool
    registry = RegistryManager.new(db_name, force_demo, status, update_module)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/modules/loading.py", line 410, in load_modules
    loaded_modules, update_module, upg_registry)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/modules/loading.py", line 297, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/modules/loading.py", line 100, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/tools/convert.py", line 848, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/openeyedev/var/projects/oe_oup_90/odoo/parts/odoo/openerp/tools/convert.py", line 916, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_nz failed: file l10n_nz/data/account.tax.template.csv could not be processed:
 Line 3 : duplicate key value violates unique constraint "account_tax_template_name_company_uniq"
DETAIL:  Key (name, company_id, type_tax_use)=(Zero (Export) Sale, 1, sale) already exists.

**Comment by NL66278** [comment]
The problem is when all localization modules are installed. They will tend to have the same kind of xml_id' s. It would probably be best to exclude the localization modules from the install all modules. This will make analysis also much faster.

**Comment by pedrobaeza** [comment]
Yeah, that is what I was about to say you.

**Comment by NL66278** [comment]
Here a PR for 9.0. Now have to do it for 10.0.

Just a remark: the already existing wizard takes care to also support 7.0 and before syntax. I did not change this. But maybe time to get rid of this?

**Comment by StefanRijnhart** [comment]
It's this error: https://github.com/odoo/odoo/issues/12600. I'm currently checking if it can be fixed by cherrypicking https://github.com/odoo/odoo/commit/5e7650204b0682072d1718400273560fa21f71f8

**Comment by StefanRijnhart** [comment]
The cherry-pick does fix this: https://github.com/OCA/OpenUpgrade/pull/872
