### ISSUE TITLE
[10.0]Module contacts duplicate ir_model_data

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#934]
Impacted versions:
Latest OpenUpgrade

Steps to reproduce:
migrate a 8.0 to 10.0 with 9.0,10.0 option. It failed on the module_contacts.

Current behavior:
```
IntegrityError: duplicate key value violates unique constraint "ir_model_data_module_name_uniq"
DÉTAIL : Key (name, module)=(module_contacts, base) already exists.
```

What is the proper way to debug this ?
regards

**Comment by hbrunn** [comment]
you've clipped the backtrace beyond recognition, without this, nobody can help you

**Comment by flotho** [comment]
Hi @hbrunn ,

Is it better like this ?

```

2017-06-25 20:59:58,148 1066 INFO mag_prod_migrated odoo.modules.loading: loading base/security/ir.model.access.csv
2017-06-25 20:59:59,499 1066 INFO mag_prod_migrated odoo.modules.migration: module base: Running migration [10.0.1.3>] post-migration
2017-06-25 20:59:59,499 1066 INFO mag_prod_migrated odoo.modules.migration: module base: Running migration [10.0.1.3>] post-migration
2017-06-25 20:59:59,500 1066 INFO mag_prod_migrated OpenUpgrade: base: post-migration script called with version 9.0.1.3
2017-06-25 20:59:59,501 1066 INFO mag_prod_migrated OpenUpgrade: base: loading migrations/10.0.1.3/noupdate_changes.xml
2017-06-25 20:59:59,527 1066 INFO mag_prod_migrated odoo.addons.base.ir.ir_translation: module base: loading translation file (fr) for language fr_FR
2017-06-25 20:59:59,527 1066 INFO mag_prod_migrated odoo.tools.translate: loading /var/tmp/openupgrade/10.0/server/odoo/addons/base/i18n/fr.po
2017-06-25 21:00:09,943 1066 INFO mag_prod_migrated odoo.modules.loading: 1 modules loaded in 24.76s, 0 queries
2017-06-25 21:00:09,966 1066 INFO mag_prod_migrated odoo.modules.loading: updating modules list
2017-06-25 21:00:10,535 1066 INFO mag_prod_migrated odoo.sql_db: bad query: INSERT INTO "ir_model_data" ("id", "noupdate", "name", "res_id", "date_update", "module", "model", "date_init", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('ir_model_data_id_seq'), true, 'module_contacts', 749, '2017-06-25 21:00:10', 'base', 'ir.module.module', '2017-06-25 21:00:10', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2017-06-25 21:00:10,535 1066 ERROR mag_prod_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 359, in load_modules
    Module.update_list()
  File "/var/tmp/openupgrade/10.0/server/odoo/addons/base/module/module.py", line 629, in update_list
    mod = self.create(dict(name=mod_name, state='uninstalled', **values))
  File "/var/tmp/openupgrade/10.0/server/odoo/addons/base/module/module.py", line 592, in create
    self.env['ir.model.data'].create(module_metadata)
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 3872, in create
    record = self.browse(self._create(old_vals))
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 3967, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_model_data_module_name_uniq"
DÉTAIL : Key (name, module)=(module_contacts, base) already exists.

2017-06-25 21:00:10,543 1066 CRITICAL mag_prod_migrated odoo.service.server: Failed to initialize database `mag_prod_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/service/server.py", line 902, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 359, in load_modules
    Module.update_list()
  File "/var/tmp/openupgrade/10.0/server/odoo/addons/base/module/module.py", line 629, in update_list
    mod = self.create(dict(name=mod_name, state='uninstalled', **values))
  File "/var/tmp/openupgrade/10.0/server/odoo/addons/base/module/module.py", line 592, in create
    self.env['ir.model.data'].create(module_metadata)
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 3872, in create
    record = self.browse(self._create(old_vals))
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 3967, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_model_data_module_name_uniq"
DÉTAIL : Key (name, module)=(module_contacts, base) already exists.

2017-06-25 21:00:10,543 1066 INFO mag_prod_migrated odoo.service.server: Initiating shutdown
2017-06-25 21:00:10,543 1066 INFO mag_prod_migrated odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2017-06-25 21:00:10,543 1066 DEBUG mag_prod_migrated odoo.service.server: current thread: <_MainThread(MainThread, started 140039225349888)>
2017-06-25 21:00:10,544 1066 DEBUG mag_prod_migrated odoo.service.server: process <_MainThread(MainThread, started 140039225349888)> (False)
2017-06-25 21:00:10,544 1066 DEBUG mag_prod_migrated odoo.service.server: --
```

**Comment by hbrunn** [comment]
a world of a difference. Running `delete from ir_model_data where name='module_contacts' and module='base'` before the migration should do the trick

**Comment by flotho** [comment]
@hbrunn , does this need to be implemented in OpenUgrade code because it could be reproductible in other env?
Or a simple SQL query would be enough ?
Regards

**Comment by hbrunn** [comment]
it seems that for whatever reason, your database has an xmlid for the 8.0 version of the contacts module, but no entry for it in the modules table.

That's probably caused by https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/addons/base/migrations/9.0.1.3/pre-migration.py#L60, looks a lot like we need to update/delete the xmlid in the `merge_modules` case too: https://github.com/OCA/openupgradelib/blame/master/openupgradelib/openupgrade.py#L730 - patch openupgradelib with this, and submit your patch there.

**Comment by pedrobaeza** [comment]
After migrating to one version, you should purge your non installed module list, and this won't happen.

**Comment by hbrunn** [comment]
i think in this case, we should do something anyways. Usually, cruft left in the database is only annoying, here, it breaks stuff

**Comment by flotho** [comment]
@pedrobaeza , you proposed to use a first migration to 9.0 from 8.0 for example. Then purge the uninstalled module, then rerun the 10.0 upgrade.
Am I right?
How do you purge the uninstalled module? Simple deletion in application list?
Regards

**Comment by pedrobaeza** [comment]
Yeah, but you don't need to do it interactively. I use Odoo shell and perform this:
```
modules = self.env['ir.module.module'].search([('state', '=', 'uninstalled')])
modules.unlink()
env['ir.module.module'].update_list()
env.cr.commit()
```

**Comment by flotho** [comment]
I'm not sure to understand, when do you do this? during the upgrade?

**Comment by pedrobaeza** [comment]
No, after migration to 9.0

**Comment by flotho** [comment]
Thanks @pedrobaeza , I'll try to do this by CLI, I'm not sure to succeed this way ;-)

**Comment by flotho** [comment]
@hbrunn , @pedrobaeza , 
Thanks for your support, deleting the wrong module name allow me to go further.
I'm now stucked with this king of issue :
```
17-06-27 20:27:09,701 17162 INFO mag_prod_migrated_migrated odoo.addons.base.ir.ir_translation: module hr: loading translation file (fr) for language fr_FR
2017-06-27 20:27:09,701 17162 INFO mag_prod_migrated_migrated odoo.tools.translate: loading /var/tmp/openupgrade/10.0/addons/hr/i18n/fr.po
2017-06-27 20:27:10,334 17162 DEBUG mag_prod_migrated_migrated odoo.modules.loading: loading module marketing_campaign (36/115)
2017-06-27 20:27:10,422 17162 INFO mag_prod_migrated_migrated odoo.modules.registry: module marketing_campaign: creating or updating database tables
2017-06-27 20:27:10,529 17162 DEBUG mag_prod_migrated_migrated odoo.models.schema: Table 'marketing_campaign_activity': column 'type': dropped NOT NULL constraint
2017-06-27 20:27:10,542 17162 DEBUG mag_prod_migrated_migrated odoo.models.schema: Table 'marketing_campaign_activity': renamed column 'type' to 'action_type'
2017-06-27 20:27:10,542 17162 DEBUG mag_prod_migrated_migrated odoo.models.schema: Table 'marketing_campaign_activity': column 'action_type': added NOT NULL constraint
2017-06-27 20:27:10,661 17162 INFO mag_prod_migrated_migrated odoo.modules.loading: loading marketing_campaign/security/marketing_campaign_security.xml
2017-06-27 20:27:10,666 17162 INFO mag_prod_migrated_migrated odoo.sql_db: bad query: INSERT INTO "res_groups" ("id", "category_id", "share", "name", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_groups_id_seq'), 88, false, 'User', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2017-06-27 20:27:10,666 17162 ERROR mag_prod_migrated_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/tmp/openupgrade/10.0/server/odoo/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/var/tmp/openupgrade/10.0/server/odoo/tools/convert.py", line 921, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/var/tmp/openupgrade/10.0/server/odoo/tools/convert.py", line 805, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/tmp/openupgrade/10.0/server/odoo/tools/convert.py", line 713, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/var/tmp/openupgrade/10.0/server/odoo/addons/base/ir/ir_model.py", line 1247, in _update
    record = record.create(values)
  File "/var/tmp/openupgrade/10.0/server/odoo/addons/base/res/res_users.py", line 676, in create
    user = super(GroupsView, self).create(values)
  File "/var/tmp/openupgrade/10.0/server/odoo/addons/base/res/res_users.py", line 609, in create
    group = super(GroupsImplied, self).create(values)
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 3872, in create
    record = self.browse(self._create(old_vals))
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 3967, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ParseError: "duplicate key value violates unique constraint "res_groups_name_uniq"
D\xc9TAIL : Key (category_id, name)=(88, User) already exists.
" while parsing /var/tmp/openupgrade/10.0/addons/marketing_campaign/security/marketing_campaign_security.xml:3, near
<record id="marketing_campaign.group_lead_automation_user" model="res.groups">
        <field name="name">User</field>
        <field name="category_id" ref="base.module_category_lead_automation"/>
    </record>
```
Is it the same kind of issue, the group is not correctly recognized?

**Comment by ghost** [comment]
Got same problem. i tried delete from ir_model_data where name='module_contacts' and module='base'  as per @hbrunn 

Traceback (most recent call last):
  File "/opt/odoo10/odoo/service/server.py", line 902, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo10/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo10/odoo/modules/loading.py", line 280, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/opt/odoo10/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo10/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo10/odoo/tools/convert.py", line 842, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/odoo10/odoo/tools/convert.py", line 898, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading base failed: file base/res/res.lang.csv could not be processed:
 duplicate key value violates unique constraint "res_lang_name_key"
DETAIL:  Key (name)=(Chinese (CN) / \u7b80\u4f53\u4e2d\u6587) already exists.

duplicate key value violates unique constraint "res_lang_name_key"
DETAIL:  Key (name)=(Chinese (TW) / \u6b63\u9ad4\u5b57) already exists.

duplicate key value violates unique constraint "res_lang_name_key"
DETAIL:  Key (name)=(Japanese / \u65e5\u672c\u8a9e) already exists.

duplicate key value violates unique constraint "res_lang_name_key"
DETAIL:  Key (name)=(Korean (KP) / \ud55c\uad6d\uc5b4 (KP)) already exists.

**Comment by flotho** [comment]
Hi @balvantramani 
I'm not sure that it's the same issue. Could you start another post. Do you work with multiple languages?
regards

**Comment by ghost** [comment]
Yes multiple language.

**Comment by ghost** [comment]
Now i got same, first i migrate 8 to 9 and then try 9 to 10 and this occur.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 359, in load_modules
    Module.update_list()
  File "/var/tmp/openupgrade/10.0/server/odoo/addons/base/module/module.py", line 629, in update_list
    mod = self.create(dict(name=mod_name, state='uninstalled', **values))
  File "/var/tmp/openupgrade/10.0/server/odoo/addons/base/module/module.py", line 592, in create
    self.env['ir.model.data'].create(module_metadata)
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 3881, in create
    record = self.browse(self._create(old_vals))
  File "/var/tmp/openupgrade/10.0/server/odoo/models.py", line 3976, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_model_data_module_name_uniq"
DETAIL:  Key (name, module)=(module_contacts, base) already exists.

**Comment by ghost** [comment]
I tried 
	delete from res_groups where category_id = 50

and it migrated , but i am facing other issue, when i tried loging using new database it can't load backend assets. i checked log and below 404 with all css or less.


2017-07-18 09:11:32,733 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:32] "GET /web_tree_hide_add_item/static/src/css/tree_hide_add_item.css HTTP/1.1" 404 -
2017-07-18 09:11:32,853 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:32] "GET /report/static/src/less/web.assets_backend/report_backend.less.css HTTP/1.1" 404 -
2017-07-18 09:11:33,237 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:33] "GET /sales_team/static/src/less/web.assets_backend/sales_team_dashboard.less.css HTTP/1.1" 404 -
2017-07-18 09:11:35,748 12945 WARNING db_migrated odoo.addons.base.ir.ir_cron: Model u'queue.worker' does not exist.
2017-07-18 09:11:45,082 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:45] "GET /mail/static/src/less/web.assets_backend/chatter.less.css HTTP/1.1" 404 -
2017-07-18 09:11:49,596 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:49] "GET /web_calendar/static/src/less/web.assets_backend/web_calendar.less.css HTTP/1.1" 404 -
2017-07-18 09:11:53,639 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:53] "GET /web_editor/static/src/less/web.assets_backend/web_editor.common.less.css HTTP/1.1" 404 -
2017-07-18 09:11:53,860 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:53] "GET /web_diagram/static/src/less/web.assets_backend/diagram_view.less.css HTTP/1.1" 404 -
2017-07-18 09:11:53,908 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:53] "GET /web_editor/static/src/less/web.assets_backend/web_editor.backend.less.css HTTP/1.1" 404 -
2017-07-18 09:11:54,058 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:54] "GET /web/content/14491-047ed7e/web_editor.summernote.0.css HTTP/1.1" 200 -
2017-07-18 09:11:54,115 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:54] "GET /web_kanban/static/src/less/web.assets_backend/kanban_dashboard.less.css HTTP/1.1" 404 -
2017-07-18 09:11:54,274 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:54] "GET /web/content/14492-967628d/web_editor.assets_editor.0.css HTTP/1.1" 200 -
2017-07-18 09:11:54,823 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:54] "GET /website_theme_install/static/src/less/web.assets_backend/website_theme_install.less.css HTTP/1.1" 404 -
2017-07-18 09:11:55,002 12945 INFO db_migrated werkzeug: 127.0.0.1 - - [18/Jul/2017 09:11:55] "GET /web_settings_dashboard/static/src/less/web.assets_backend/dashboard.less.css HTTP/1.1" 404 -
