### ISSUE TITLE
[10.0]Stock migration error

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#937]
Working on a db coming from 8.0 and trying to migrate it via 90 then 10.0.
Ir progressed by solving #934 and from now I have this issue :
```
6 rows affected
2017-06-27 21:11:41,749 19856 DEBUG mag_prod_migrated_migrated OpenUpgrade: Running ALTER TABLE procurement_rule ALTER COLUMN route_sequence TYPE integer
2017-06-27 21:11:41,750 19856 DEBUG mag_prod_migrated_migrated OpenUpgrade: -1 rows affected
2017-06-27 21:11:41,787 19856 DEBUG mag_prod_migrated_migrated OpenUpgrade: Running ALTER TABLE stock_location_path ALTER COLUMN route_sequence TYPE integer
2017-06-27 21:11:41,788 19856 DEBUG mag_prod_migrated_migrated OpenUpgrade: -1 rows affected
2017-06-27 21:11:41,788 19856 DEBUG mag_prod_migrated_migrated OpenUpgrade: Running UPDATE ir_model_data SET module = stock, name = group_stock_multi_locations WHERE module = stock and name = group_locations
2017-06-27 21:11:41,788 19856 DEBUG mag_prod_migrated_migrated OpenUpgrade: 1 rows affected
2017-06-27 21:11:41,792 19856 INFO mag_prod_migrated_migrated odoo.sql_db: bad query: 
        SELECT id
        FROM ir_model_fields
        WHERE model = 'res.partner' AND name in ARRAY['picking_warn', 'picking_warn_msg']
        
2017-06-27 21:11:41,793 19856 ERROR mag_prod_migrated_migrated OpenUpgrade: stock: error in migration script /var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py: syntax error at or near "ARRAY"
LIGNE 4 :         WHERE model = 'res.partner' AND name in ARRAY['picki...
                                                          ^

2017-06-27 21:11:41,793 19856 ERROR mag_prod_migrated_migrated OpenUpgrade: syntax error at or near "ARRAY"
LIGNE 4 :         WHERE model = 'res.partner' AND name in ARRAY['picki...
                                                          ^
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1194, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py", line 67, in migrate
    warning_update_module_names_partial(cr)
  File "/var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py", line 46, in warning_update_module_names_partial
    """, (moved_fields,))
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "ARRAY"
LIGNE 4 :         WHERE model = 'res.partner' AND name in ARRAY['picki...
                                                          ^

2017-06-27 21:11:41,793 19856 ERROR mag_prod_migrated_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1194, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py", line 67, in migrate
    warning_update_module_names_partial(cr)
  File "/var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py", line 46, in warning_update_module_names_partial
    """, (moved_fields,))
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "ARRAY"
LIGNE 4 :         WHERE model = 'res.partner' AND name in ARRAY['picki...
                                                          ^

2017-06-27 21:11:41,794 19856 CRITICAL mag_prod_migrated_migrated odoo.service.server: Failed to initialize database `mag_prod_migrated_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/service/server.py", line 902, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1194, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py", line 67, in migrate
    warning_update_module_names_partial(cr)
  File "/var/tmp/openupgrade/10.0/addons/stock/migrations/10.0.1.1/pre-migration.py", line 46, in warning_update_module_names_partial
    """, (moved_fields,))
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "ARRAY"
LIGNE 4 :         WHERE model = 'res.partner' AND name in ARRAY['picki...
                                                          ^
```

Does it looks like a bug for you ?
@pepetreshere , what's your point of view ?

Thanks in advance for your support. Regards

**Comment by JordiBForgeFlow** [comment]
Do you agree with the proposed fix?
