### ISSUE TITLE
Groups with misplaced module in ir_model_data table

### ISSUE THREAD

**Issue by PCatinean** [OCA/OpenUpgrade#951]
Impacted versions:

10

Steps to reproduce:

Create new database in V8 and install Sale, Purchase, Invoicing, Website

Run ./odoo.py -d DB -u all --stop-after-init on the v9 branch
Do the same on v10 branch

Current behavior:

Multiple groups have misplaced modules and generate duplicate key value error on migration to v10

Expected behavior:

Groups are not moved from base to the new modules

Environment:

Ubuntu 16.04 LTS
Fresh pull of openupgrade with openupgrade lib installed in virtualenv version 1.3.0

Traceback examples:

```
ParseError: "duplicate key value violates unique constraint "res_groups_name_uniq"
DETAIL:  Key (category_id, name)=(7, Editor and Designer) already exists.
" while parsing /opt/odoo/10.0/OpenUpgrade/addons/website/security/website_security.xml:7, near
<record id="group_website_designer" model="res.groups">
        <field name="name">Editor and Designer</field>
        <field name="users" eval="[(4, ref('base.user_root'))]"/>
        <field name="implied_ids" eval="[(4, ref('group_website_publisher'))]"/>
        <field name="category_id" ref="base.module_category_website"/>
    </record>
```
Query in db for this group revealed:
```
Test=> select module from ir_model_data where name = 'group_website_designer';
 module 
--------
 base
(1 row)
```

**Comment by PCatinean** [comment]
Apparently this happens if you attempt to do the migration in the same directory and just switch branches. Most probably the .pyc files mess things up so I'm leaving this as reference for someone trying to do the same stupid thing :)

**Comment by hbrunn** [comment]
hmmm, we'd have chatted for hours to find this. For what it's worth, maybe you'll have more success with my [migration buildout](https://github.com/hbrunn/OpenUpgrade/tree/buildout)? Didn't update this for a while, but I think it's obvious how to extend this to the later versions

**Comment by PCatinean** [comment]
@hbrunn indeed, I thought I would not depend on the buildout since I have to go to version 10 as well and that's not supported from what I know.

I only now noticed that doing pip install openupgradelib does not get the latest version even though it still shows 1.3.0. That's pretty bad and I also wasted quite some time until I noticed some outdated code

**Comment by pedrobaeza** [comment]
We use our Docker project https://github.com/Tecnativa/docker-odoo-base putting openupgrade as origin in the repo configuration, but you should know how to work with Docker.

**Comment by PCatinean** [comment]
@pedrobaeza the docker project is indeed very interesting and I will take a look at it soon. I may be missing something but at a quick glance through the Dockerfile shows it also installs openupgradelib with pip and even with the --no-cache parameter the library is out of date yet showing the same version number.

That ate up my entire day debugging like crazy :)

**Comment by pedrobaeza** [comment]
Well, if the library is not updated enough, you can always add a pip compatible syntax for taking from git following scaffolding (https://github.com/Tecnativa/docker-odoo-base/blob/scaffolding/odoo/custom/dependencies/pip.txt). It would be: `git+https://github.com/OCA/openupgradelib.git@master`

**Comment by hbrunn** [comment]
@PCatinean do [that](https://github.com/OCA/OpenUpgrade/blob/10.0/.travis.yml#L62) for installing openupgradelib (will change this in the buildout too the next time i've got to touch it), but the version number won't change because we only update this before a release: https://github.com/OCA/openupgradelib/blob/master/openupgradelib/__init__.py#L5 might make sense to add `-develop` or something as first commit after a release. But on the other hand that for devs, so not sure if it's worth the trouble

**Comment by PCatinean** [comment]
I understand, the only problem for a newcomer of openupgrade is that if he follows the instructions on the repo https://github.com/OCA/openupgradelib/blob/master/docs/installation.rst or does a pip install -r requirements.txt on any openupgrade version he can have an outdated version like in this scenario.

This translates into frustration for the user relating to problems that could already be solved. Then issues might be opened for those solved problems which translates into overhead for OCA maintainers and a bit of back and forth (including debugging) that can be avoided if the installation instructions specify how to get the latest version. That's at least how I see it from the perspective of the user that has been burned by this :)

**Comment by pedrobaeza** [comment]
Make a PR then changing the documentation for avoiding this frustration to others :wink:

**Comment by PCatinean** [comment]
I was thinking the same thing :D will do

**Comment by treviser** [comment]
I face exactly the same problem, same environment. I'm trying the second weekend now to migrate a customer database from 9.0 to 10.0, to no avail. I have updated to latest version according to the advices of @pedrobaeza and @hbrunn, it does not help. Is there anything I can do? I also have no idea on how to overcome https://github.com/OCA/OpenUpgrade/issues/2175
Both errors stop the migration process and I'm lost.
Any help is really appreciated.

**Comment by pedrobaeza** [comment]
Put your stack trace to judge the problem.

**Comment by treviser** [comment]
```
2020-02-02 17:24:01,550 1647 INFO MyDatabaseName odoo.sql_db: bad query: INSERT INTO "res_groups" ("id", "share", "category_id", "name", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_groups_id_seq'), false, 3, 'Editor and Designer', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2020-02-02 17:24:01,553 1647 WARNING MyDatabaseName odoo.modules.loading: Transient module states were reset
2020-02-02 17:24:01,555 1647 ERROR MyDatabaseName odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 441, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 326, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/odoo/odoo-server/odoo/modules/loading.py", line 201, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 99, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 850, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 920, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 804, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 712, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1276, in _update
    record = record.create(values)
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 733, in create
    user = super(GroupsView, self).create(values)
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 648, in create
    group = super(GroupsImplied, self).create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3927, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/odoo/models.py", line 4022, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ParseError: "duplicate key value violates unique constraint "res_groups_name_uniq"
DETAIL:  Key (category_id, name)=(3, Editor and Designer) already exists.
" while parsing /odoo/odoo-server/addons/website/security/website_security.xml:7, near
<record id="group_website_designer" model="res.groups">
        <field name="name">Editor and Designer</field>
        <field name="users" eval="[(4, ref('base.user_root'))]"/>
        <field name="implied_ids" eval="[(4, ref('group_website_publisher'))]"/>
        <field name="category_id" ref="base.module_category_website"/>
    </record>
2020-02-02 17:24:01,565 1647 CRITICAL MyDatabaseName odoo.service.server: Failed to initialize database `MyDatabaseName`.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/service/server.py", line 974, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 441, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 326, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/odoo/odoo-server/odoo/modules/loading.py", line 201, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 99, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 850, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 920, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 804, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 712, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1276, in _update
    record = record.create(values)
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 733, in create
    user = super(GroupsView, self).create(values)
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 648, in create
    group = super(GroupsImplied, self).create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3927, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/odoo/models.py", line 4022, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ParseError: "duplicate key value violates unique constraint "res_groups_name_uniq"
DETAIL:  Key (category_id, name)=(3, Editor and Designer) already exists.
" while parsing /odoo/odoo-server/addons/website/security/website_security.xml:7, near
<record id="group_website_designer" model="res.groups">
        <field name="name">Editor and Designer</field>
        <field name="users" eval="[(4, ref('base.user_root'))]"/>
        <field name="implied_ids" eval="[(4, ref('group_website_publisher'))]"/>
        <field name="category_id" ref="base.module_category_website"/>
    </record>
2020-02-02 17:24:01,567 1647 INFO MyDatabaseName odoo.service.server: Initiating shutdown
2020-02-02 17:24:01,567 1647 INFO MyDatabaseName odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```
