### ISSUE TITLE
[10.0]Sale migration error, tuple issue

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#956]
Hi,

I have a problem on sale migration like for stock #937:
```
Running UPDATE ir_translation SET module = sale WHERE module = product_visible_discount
2017-07-05 21:33:07,353 17660 DEBUG mag_prod_migrated_migrated OpenUpgrade: 0 rows affected
2017-07-05 21:33:07,354 17660 DEBUG mag_prod_migrated_migrated OpenUpgrade: Running DELETE FROM ir_module_module WHERE name = product_visible_discount
2017-07-05 21:33:07,354 17660 DEBUG mag_prod_migrated_migrated OpenUpgrade: 1 rows affected
2017-07-05 21:33:07,354 17660 INFO mag_prod_migrated_migrated odoo.sql_db: bad query: 
        SELECT id
        FROM ir_model_fields
        WHERE model IN ('res.partner', 'product.template') AND name in ARRAY['sale_line_warn', 'sale_line_warn_msg', 'sale_warn', 'sale_warn_msg']
    
2017-07-05 21:33:07,355 17660 ERROR mag_prod_migrated_migrated OpenUpgrade: sale: error in migration script /var/tmp/openupgrade/10.0/addons/sale/migrations/10.0.1.0/pre-migration.py: syntax error at or near "ARRAY"
LIGNE 4 : ...N ('res.partner', 'product.template') AND name in ARRAY['sal...
                                                               ^

2017-07-05 21:33:07,355 17660 ERROR mag_prod_migrated_migrated OpenUpgrade: syntax error at or near "ARRAY"
LIGNE 4 : ...N ('res.partner', 'product.template') AND name in ARRAY['sal...
                                                               ^
Traceback (most recent call last):
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1194, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/sale/migrations/10.0.1.0/pre-migration.py", line 166, in migrate
    warning_update_module_names_partial(env.cr)
  File "/var/tmp/openupgrade/10.0/addons/sale/migrations/10.0.1.0/pre-migration.py", line 95, in warning_update_module_names_partial
    """, (moved_fields,))
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "ARRAY"
LIGNE 4 : ...N ('res.partner', 'product.template') AND name in ARRAY['sal...

```

**Comment by pedrobaeza** [comment]
Closing as there's the PR #957.
