### ISSUE TITLE
Model has no attribute _columns

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#965]
2017-07-17 11:44:18,713 18500 ERROR db_migrated OpenUpgrade: crm: error in migration script /var/tmp/openupgrade/10.0/addons/crm/migrations/10.0.1.0/post-migration.py: 'crm.activity' object has no attribute '_columns'
2017-07-17 11:44:18,713 18500 ERROR db_migrated OpenUpgrade: 'crm.activity' object has no attribute '_columns'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1182, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/crm/migrations/10.0.1.0/post-migration.py", line 45, in migrate
    _convert_next_activities(env)
  File "/var/tmp/openupgrade/10.0/addons/crm/migrations/10.0.1.0/post-migration.py", line 17, in _convert_next_activities
    'recommended_activity_ids', openupgrade.get_legacy_name(column),
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 807, in m2o_to_x2m
    if not model._columns.get(field):
AttributeError: 'crm.activity' object has no attribute '_columns'
2017-07-17 11:44:18,714 18500 ERROR db_migrated odoo.modules.loading: Error executing post migration script for module crm
`-> sale_crm
: 'crm.activity' object has no attribute '_columns'

**Comment by mileo** [comment]
How you fix this problem?

**Comment by pedrobaeza** [comment]
Upgrade your openupgradelib library from source, not from pypi
