### ISSUE TITLE
[10.0]Syntax Error Sale(premigration.py)

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#966]
In sale_expense_update_module_names_partial method sql query use in operator, in postgres it should be tuple not array.

Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 409, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/migration.py", line 165, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.0-py2.7.egg/openupgradelib/openupgrade.py", line 1194, in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/10.0/addons/sale/migrations/10.0.1.0/pre-migration.py", line 167, in migrate
    sale_expense_update_module_names_partial(env.cr)
  File "/var/tmp/openupgrade/10.0/addons/sale/migrations/10.0.1.0/pre-migration.py", line 138, in sale_expense_update_module_names_partial
    new_name))
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.0-py2.7.egg/openupgradelib/openupgrade.py", line 700, in logged_query
    cr.execute(query, args)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "ARRAY"
LINE 1: ...sale' WHERE module = 'sale_expense' AND res_id IN ARRAY[8706...
                                                             ^

Please fix it. Same method 3 places used array.

**Comment by pedrobaeza** [comment]
Are you using latest version? It's supposed to be changed in https://github.com/OCA/OpenUpgrade/pull/957

> Please fix it. Same method 3 places used array.

This is not how it works. We can do the best for fixing it, but you can also propose a PR with the needed changes.

**Comment by ghost** [comment]
Ok got latest version.

Repo automatically download using migration.py script, might it dowload older version that is problem.
